### ISSUE TITLE
Combining my Node program with Express

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1005]
* **Node.js Version**: v8.2.1
* **OS**:  Sierra 10.12.6

Hi all, I am fairly new to Node and am building my first app with it.
I want to setup a user interface for a node program that I wrote. This programme is all finished and working. t searches the web and sends e-mails depending on what kind of information it retrieves... Here is what my file structure looks like: 
rootfolder: 
/Users/o.vanvelsen/Desktop/Nodesaves/nodetest/node-crawler-master
├── CHANGELOG.md
├── Dockerfile
├── LICENSE.txt
├── README.md
├── WPtest.js
├── crawl.js
├── crawlSave.js
├── crawler2test.js
├── dataAds.json
├── jsdomCrawl.js
├── lib
├── mailerTest3.js
├── myfile.txt
├── node_modules
├── package-lock.json
├── package.json
├── randomOffet.js
├── testArg.js
├── testFiles
├── tests
├── travis_scripts
└── vendor
All is well, however: I want to give my programme (which main action occurs in the file "crawl.js") a user interface, and change objects/variables depending on user input.
And so I've set up Express using the express app generator @ http://expressjs.com/en/starter/generator.html

I did this while being inside the root directory of my programme which I just mentioned, thus adding the myapp folder inside my file structure.
now this is what my index.pug file looks like:
```js
extends layout

block content
  h1= title
  p Welcome to #{title}
  p test
```
**Now I get how pug is a specific HTML markup, but at this point my brain still overloads:
- Is this even the correct file structure? Shouldn't I put my crawl.js file inside the myapp express folder instead of the other way around? 
- How do I create my HTML/pug input fields so that the filled in info changes my Javascript variables and objects? 
- my crawl.js file has the following structure: 
var X = 23;
function jack() { return X +23;}
etc.
I want to export this. Do I need to rewrite this into an object format before I can reuse/import this into an express file?
**
Many thanks in advance :)

**Comment by keksipurkki** [comment]
While your problem is not a NodeJS issue but a general question about how web applications work, this may not be the best forum to ask such questions. 

The best strategy is to solve your problem is to know how HTTP works and take it from there. Knowing HTTP allows you to always reason how to solve a particular problem, no matter what the programming language is. 

To answer your questions:

1. The generator app assumes that it creates the root folder for your entire app, so in a way you now have an app inside an app.

To fix your problem, you'd start with the generated Express *myapp*, and create a folder called `src` where you'd put your application code. 

Recognize however that the way your app appears to the internet does not depend directly on the organization of your source files. It is in the process of *routing* where you define what kind of resources are going to be served. It is merely a convention that we mark the `public` folder as the web root `/`, so that a GET request for `/cat.png` is routed to `public/cat.png`.
 
2. You'd designate the crawler as a *model* object in your app. You'd create a *view* for the crawler. The view is a pug template that includes a web form with input fields to modify the crawler. Upon submitting the web form, the data is routed to the crawler *controller* that requests the crawler to change with the data provided by the requests. After modification, the app responds with an updated view of the crawler. This is the MVC story; it is up to you to implement it and there are multiple ways to do it technically. 

3. You export code across modules in NodeJS using the commonJS module API. See https://darrenderidder.github.io/talks/ModulePatterns/.

**Comment by WAINGOR** [comment]
@keksipurkki thank you for this valuable information. Meanwhile I've fixed these issues by trial and error, but thanks for helping me reach a fundamental understanding. Greets

**Comment by gireeshpunathil** [comment]
closing as answered.
