### ISSUE TITLE
Uncaught reference error: require is not defined

### ISSUE THREAD

**Issue by ShaunodCIT** [nodejs/help#102]
Simply as the title says. I'm calling the require() function in my code and the error "Uncaught reference error: require is not define" is being displayed in the console.

Does anyone know what could possible cause this?
I'll include links to my code if needs be.

Thank you.

EDITS:
Node v5.5.0
OS: Windows 7 Ultimate
Language: Javascript

**Comment by joshmanders** [comment]
Include any relevant information such as what version of node, operating system, code, etc.

**Comment by ShaunodCIT** [comment]
Edits made. Thanks.

**Comment by joshmanders** [comment]
Can you please provide the code that is causing errors?

**Comment by joshmanders** [comment]
Aso is this in your terminal console or browser console you're getting this error?

**Comment by ShaunodCIT** [comment]
This is the one line that is causing it:
var klapi = require('./klapi.js');

This error is appearing in my browser console.

**Comment by joshmanders** [comment]
Node.js is for the server side. Browsers do not implement require. For that to work you need to bundle your code with either Browserify or Webpack.

**Comment by ShaunodCIT** [comment]
I have tried doing that and it has resulted in the same error. Is there any other way, other than require(), to do what I'm trying to do?

**Comment by joshmanders** [comment]
I really can't help with any more than that without code showing what you're trying to do. Browserify and Webpack are used by thousands of people a day, they work. I use require in the browser because of these tools.

**Comment by megastef** [comment]
Maybe this is helpful: 
- https://github.com/substack/node-browserify#external-requires
- https://truongtx.me/2014/03/20/browserify-bring-nodejs-modules-to-browser
Create the file with browserify. Load your script with <script src="..."> in HTML after loading the script require() should work.

**Comment by subfuzion** [comment]
@ShaunodCIT, @joshmanders is correct. Browsers don't implement `require` so the reference is undefined. As he explained, you need to use a tool like [browserify](https://github.com/substack/node-browserify) that provides this support if you want to do Node-style programming for the browser.

It probably seems a bit confusing because both browser and Node.js platforms use JavaScript. JavaScript historically did not have support for modules and no browsers today support modules natively, but Node.js (which is not a browser platform) does provide a module system. The browser and Node.js are two completely separate platforms that have different conventions for loading external code. However, a tool like Browserify mimics the Node.js convention, which can be useful for developers who would like to take advantage of modules in their browser code and leverage the rich Node.js module ecosystem.

Since you haven't replied in the past month, I'm going to go ahead and close the issue. Good luck and feel free to open another issue if you run into any other node-related issues.

**Comment by achyuth** [comment]
```
module.exports = function(grunt){
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		uglify: {
			/*options: {
		      	mangle: false
		    },*/
			my_target: {
				files: {
					'dest/output.min.js': ['src/js/app.js', 'src/js/site.js']
				}
			}
		},
		cssmin: {
			my_target:{
				files : [{
					expand: true,
					cwd: 'css/',
					src: ['*.css', '.min.css'],
					//src: '*.css',
					dest: 'css/',
					ext: '.min.css'
				}]
			}
		},
		obfuscator:{
			files: [
				'src/js/app.js',
				'src/js/*.js'
			],
			entry: 'src/js/app.js',
			out: 'obfuscated.js',
			strings: false,
			root: __dirname
		}
	});
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-cssmin');
	grunt.loadNpmTasks('grunt-obfuscator');
}
```

Above is sample code "obfuscator" generates obfuscated js file that is great, But throws "obfuscated.js:1 Uncaught ReferenceError: require is not defined" browser console. 



app.js code: 
```
var funt = function(){
	var test  = 213123;
	var test_a = "string";
	return test+test_a;
};
document.getElementByID('res').innerHTML = funt(); 
```

site.js code:
```
var text = "text Variable"; 
var test = "text Variable"; 
var string = "text Variable";
var array = [2,3,2432,23,23,2]; 
var boolean_var = false;
```
Please help me on this.

**Comment by joshmanders** [comment]
@achyuth looks like an issue with your obfuscated plugin.

**Comment by achyuth** [comment]
@joshmanders i have used "grunt-obfuscator" source: https://www.npmjs.com/package/grunt-obfuscator

**Comment by RitikaJain8818** [comment]
@ShaunodCIT 
Hey!
Hope your issue is resolved now, I am facing the same issue now.
Can you help?

**Comment by asadmanzoor099** [comment]
@RitikaJain8818 
Hey!
Can you please lemme know if got some solution because i'm also facing same issue?
