### ISSUE TITLE
Burdening the CPU

### ISSUE THREAD

**Issue by renanbastos93** [nodejs/help#1028]
Guys,

Node Version: 8.7.x

I'm testing the performance of the my applications, but it is burdening the CPU.
Help-me I want reduce much this %.

![image](https://user-images.githubusercontent.com/8202898/34131988-0d633480-e435-11e7-9c93-584f287f015f.png)

**Comment by gireeshpunathil** [comment]
@renanbastos93 : 
1. how is your application fairing in terms of transactions? i.e., what is a rough number of operations per second?
2. what the app is doing in terms of the transactions? i.e., what actions the client request handler performs?
3. what is your baseline data? i.e., are there node versions or app versions where the CPU consumption was observed to be much less?

**Comment by gireeshpunathil** [comment]
Because of high level of concurrency at the virtual machine layer due to non-blocking I/O, it is not very uncommon for node.js to exhibit high CPU consumption. Moreover, there is no standard way of telling what is the right number for a healthy CPU consumption, it is always an comprative inference based on the workload at hand, its throughput numbers and probably a history where the same workload was catered through lesser CPU consumption. So answers to the above questions will help making an assertion on the overconsumption.

**Comment by renanbastos93** [comment]
@gireeshpunathil ,

Good morning, 

So I'll awnser this questions below.

1. Is variable, because depends if have many clients connect. For update the we cache.
2. He takes many data of other API and generation a cache with this data treaties.
3. I'm used NodeJS v8.7.x

I got it optimizar the memory used, now I want optimizar the process this machine. We used one TM2 small of the Amazon.

**Comment by gireeshpunathil** [comment]
@renanbastos93 - thanks. So I understand your requirement as a need for general improvements (reduction) on CPU consumption.

I suggest to use a test environment and:
  - start with single, sequential transactions and measure CPU
 - gradually increase the number of concurrent clients

If CPU consumption is observed in proportion to the increase in concurrency, I assert that the application is doing good, and the main thread is leveraging its CPU to an efficient manner. If improvements is desired beyond this point, please consider using [Cluster](https://nodejs.org/dist/latest-v9.x/docs/api/cluster.html) module to de-centralize transactions and thereby reduce congestion as well as CPU monopoly.

If the CPU consumption is static regardless of concurrent clients, there may be elements in the code that is CPU savvy. Static analysis followed in conjunction with runtime profiling may be necessary to identify those elements.

**Comment by renanbastos93** [comment]
@gireeshpunathil ,

Perfect, but I want know if can I to use Cluster in machine of one core?

**Comment by gireeshpunathil** [comment]
@renanbastos93 : it does not help, other than that now you will `spread` the work among pluralities of processes whose cumulative CPU consumption will be similar to what you are observing now. Ideally Clusters are used to leverage the untapped computing power of a system to scale up the application in response to high demand.

**Comment by renanbastos93** [comment]
Of course, also I need know one form of monitoring only the process in NodeJS for I create a statistic and generate graphs. Later this I want create a article about performance.

**Comment by gireeshpunathil** [comment]
1. Profile with the in-built tool:

 - produce performance data
 `$ node --prof app.js // generates <isolate-0x...v8.log>`
 - post-proess the performance data
`$ node --prof-process <generated log>`

This provides the fine level of broken-up insight into where the CPU was spent within the virtual machine
https://nodejs.org/en/docs/guides/simple-profiling/

2. If you are in Linux, you can use `perf` that provides a best performance analysis experience - it leverages the PMU hardware for extracting performance data, so intereference with the node process is minimal.
http://www.brendangregg.com/blog/2014-09-17/node-flame-graphs-on-linux.html

3. third party tools that provide customized APM experience:
https://newrelic.com/nodejs
https://github.com/RuntimeTools/appmetrics
https://www.dynatrace.com/technologies/nodejs-monitoring/
https://www.appdynamics.com/nodejs/
https://www.ca.com/us/products/ca-application-performance-management.html

**Comment by renanbastos93** [comment]
Wow, thanks, how I should make to improment performance of the request at my applications?

**Comment by keksipurkki** [comment]
It is normal to experience high CPU usage when there are lots of concurrent connections. To establish what is too much, you'd need to record the CPU usage as a function of concurrent requests and observe where things start to go south. What is good enough ultimately depends on your use case; over in PHP land something like 1770 reqs/s with commodity hardware is excellent (http://phpfastcgi.github.io/general/2015/08/24/phpfastcgi-benchmarks-symfony-silex-slim.html).

But, after looking at the attachment you provided, here's what came to my mind: 

* Excessive memory allocation/deallocation and GC churn may tax your app's performance
* Modern cryptographic hash algorithms specifically include parts that increase CPU usage to guard against brute force attacks
* If your app is making tons of HTTP calls, you need to queue them so that only a given amount are outstanding at any given time.

**Comment by gireeshpunathil** [comment]
One of the natural (but complex and iterative) starting point in investigating and improving concurrency is to measure the loop latency. There are variations in the definitions of loop latency, but the core of it is `the time taken for a listener to be fired from the time its associated event has been ready`. This gives an estimate on how CPU-bound the transactions are, how much time the main thread takes to complete one iteration of event handling / re-visit the loop etc. If you find this unacceptably high, then trace / profile the body of the transaction(s) to see where time is spent.

**Comment by renanbastos93** [comment]
Thanks a lot.
