### ISSUE TITLE
child_process.execFile

### ISSUE THREAD

**Issue by tsrahm** [nodejs/help#1085]
* **Node.js Version**: v.6.9.2
* **OS**: macOS 10.12.6
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I used child_process.execFile to execute a JS file. The docs state this:
**child_process.execFile(file[, args][, options][, callback])**
* **file: The name or path of the executable file to run.**

This failed:
```js
execFile("node filename.js", { cwd: "path_to_file" })
```
This worked:
```js
execFile("node", ["filename.js"], { cwd: "path_to_file" })
```

Some clarification in the docs would have helped me a lot. In my case, the file that I needed to execute was not passed in as the **file** but as an **arg**. Thanks for your consideration.

Tory Rahm
-->

**Comment by ProfNandaa** [comment]
@tsrahm - you are right, I think the docs should read, `child_process.execFile(command, [file, args][, options][, callback])` instead?

**Comment by tsrahm** [comment]
Yes, @ProfNandaa. That looks perfect to me.

**Comment by gireeshpunathil** [comment]
while `filename.js` is the script file that needed to be executed, the binary image that was subjected to the `exec` system call (the routine that runs a new executable image) is that of the node executable in your case. the script file was parsed, read and interpreted by the node virtual machine.

So the document looks correct to me, though it can be confusing - not because of the wordings, but because pluralities of command-line execution styles exist; natively compiled executables with arguments, virtual machines and managed runtimes that takes programs as arguments, script files that appear to be executables but internally hosted by a shebang-driven interpreter etc.

examples:
`$ java Foo // invokes JVM interpreter with Foo.class as the argument`
`$ python Foo.py // invokes python interpreter with FOo.py as the argument`
`$ ls -lrt // invokes ls executable with -lrt as the argument`
`$ ./a.out 1 2 3 // invokes a.out with 1, 2, 3 as the arguments`
`$ foo.sh // invokes an appropriate interpreter that is specified inside the script, with the script as the argument`

**Comment by ProfNandaa** [comment]
@gireeshpunathil - I see, make sense. Thanks for the clarification! 👍

**Comment by tsrahm** [comment]
Thanks for the response, @gireeshpunathil. As you stated, it can be confusing. So while the document may be technically correct, any clarification which reduces the confusion for the user would be very welcome. I believe that @ProfNandaa 's suggestion, i.e. child_process.execFile(command, [file, args][, options][, callback] would accomplish that. However, I will accept your decision if you disagree.

Best regards

**Comment by gireeshpunathil** [comment]
@tsrahm - thanks, if you have willingness and bandwidth, a PR to that effect is much appreciated!

**Comment by gireeshpunathil** [comment]
closing, as answered.

**Comment by ProfNandaa** [comment]
I can go ahead and work on the PR if @tsrahm is not on it already 👍

**Comment by tsrahm** [comment]
Thank you gentlemen!
