### ISSUE TITLE
Nodejs segfaulting on arch Linux armv7

### ISSUE THREAD

**Issue by staymetal** [nodejs/help#1095]
Node version : 9.5.0.1 
OS : arch Linux
platform : Android (nexus 5)
arch : arm v7

Installation : pacman -S nodejs

when I type node on the bash terminal ,I get

segmentation fault.

**Comment by bnoordhuis** [comment]
You should report that to the maintainers of the arch package.  If it turns out to be an issue with node.js itself and not, say, the way it was built or linked, they'll forward the bug report to us.

If you can reproduce with the binaries from nodejs.org, please report back (and include the stack trace from gdb) and I'll reopen.
