### ISSUE TITLE
When writing C++ addons, how to know the order of destructors called by Garbage Collector?

### ISSUE THREAD

**Issue by JoshuaWise** [nodejs/help#110]
Hello,

I'm in the process of writing a C++ addon/package for Nodejs. I was wondering:

If two wrapped objects (subclasses of `node::ObjectWrap`) are detached from their only root node at the same time, then when the garbage collector comes to call their C++ destructors, how can I be sure which destructor is called first? Is the order arbitrary and indeterminable? Is there a way of making one class's destructor depend on another class's destructor being called first?

What if one class instance is a member of the other?
What if one instance's JavaScript object has a property which references the other?
Does the order of creation matter?

**Comment by kelthenoble** [comment]
cc @nodejs/addon-api

**Comment by rvagg** [comment]
I don't have an answer to the basic question but at a higher level, you shouldn't be relying on such semantics even if we were able to pin one down because it might change in the next version of V8. Basically, try and detach your logic as much as possible from the GC process and assume it's going to do something crazy wrt timing and ordering.

**Comment by JoshuaWise** [comment]
Can I at least be promised that the destructors will be called in the same thread? (i.e., not in parallel)

This is important as some destructors must change behavior based on what has or hasn't been destructed yet.

**Comment by kkoopa** [comment]
In the specific case of `ObjectWrap` and current V8, V8 is single threaded, so the destrcutors related to that should run on the same thread. However, what you are asking for seems like a design smell. Change it so that said assumption is unnecessary. You can use composition or inheritance to assure an order of destructor execution therein.

**Comment by bnoordhuis** [comment]
> f two wrapped objects (subclasses of node::ObjectWrap) are detached from their only root node at the same time, then when the garbage collector comes to call their C++ destructors, how can I be sure which destructor is called first?

You can't.

> Is the order arbitrary and indeterminable?

Yes.

> Is there a way of making one class's destructor depend on another class's destructor being called first?

Make A weakly persistent relative to B.  You can find an example in [src/node_contextify.cc](https://github.com/nodejs/node/blob/v5.8.0/src/node_contextify.cc) where we juggle reference counts on top of weakly persistent handles.

> What if one class instance is a member of the other?

Doesn't matter.

> What if one instance's JavaScript object has a property which references the other?

Also doesn't matter.

> Does the order of creation matter?

No.

**Comment by lordKnighton** [comment]
closing for now, reopen to pursue 

happy coding 👍
