### ISSUE TITLE
Merge sync with non-sync methods

### ISSUE THREAD

**Issue by rentalhost** [nodejs/help#1106]
* **Node.js Version**: next major maybe
* **OS**: any
* **Scope (install, code, runtime, meta, other?)**: meta
* **Module (and version) (if relevant)**: all appliable

Why Node.js have a lot of methods with "sync" and "non-sync", once that the unique difference is on signature that receives as last argument a callback.

I mean, it couldn't identify in runtime if it should be sync or not?

For instance: `fs.close(fd)` and `fs.closeSync(fd, callback)` is basically the same, with the difference in last parameter that accepts a callback.

Why not:

```js
fs.close(fd);           // Run sync.
fs.close(fd, callback); // Run non-sync.
```

For this example, the [code is that](https://github.com/nodejs/node/blob/b1c6ecb2c674f43290ad772bc464568aa42ef5d0/lib/fs.js#L733):

```js
fs.close = function(fd, callback) {
  validateUint32(fd, 'fd');
  const req = new FSReqWrap();
  req.oncomplete = makeCallback(callback);
  binding.close(fd, req);
};

fs.closeSync = function(fd) {
  validateUint32(fd, 'fd');

  const ctx = {};
  binding.close(fd, undefined, ctx);
  if (ctx.errno !== undefined) {
    throw errors.uvException(ctx);
  }
};
```

And a simplified version should be:

```js
fs.close = function(fd, callback) {
  validateUint32(fd, 'fd');

  if (callback) {
    const req = new FSReqWrap();
    req.oncomplete = makeCallback(callback);
    binding.close(fd, req);
    return;
  }

  const ctx = {};
  binding.close(fd, undefined, ctx);
  if (ctx.errno !== undefined) {
    throw errors.uvException(ctx);
  }
};
```

Of course, it is a breaking change, but it could be avoided by using alias until Node.js 13, for instace.

**Comment by bnoordhuis** [comment]
It's to make sync methods stand out and subtly discourage them.

It helps with code review too.  If, say, you see `fs.close(fd, cb)` then you might not notice it when `cb` is a variable that's set to `undefined`.  With overloaded methods, you now have a very subtle performance bug.

**Comment by seishun** [comment]
>It's to make sync methods stand out and subtly discourage them.

This argument doesn't work for CPU-bound functions like `zlib.deflateSync`. There is no need to discourage them since their use is perfectly fine in most cases.

**Comment by bnoordhuis** [comment]
Unless you know there is a fixed upper bound on CPU time - and know what it is - then no, it still applies to `deflateSync()` and friends.  The async methods wouldn't exist if it was inconsequential.  Contrast with `path.join()`.

**Comment by seishun** [comment]
>Unless you know there is a fixed upper bound on CPU time - and know what it is

There are plenty of usecases where you do. When you're implementing a message protocol that deflates some messages, for instance.

**Comment by bnoordhuis** [comment]
And plenty of cases where you don't.  Or think you do but don't.  Your example is one: an attacker can craft messages to maximize CPU utilization and degrade the responsiveness of your service.

**Comment by seishun** [comment]
`zlib.deflate` isn't a magic bullet in that case. The attacker would just send a sufficient number of such messages, causing many threads to be spawned and slowing your service to a crawl.

**Comment by bnoordhuis** [comment]
There's a qualitative difference in that the service stays responsive.  You don't have that when the main thread is tied up.

**Comment by ORESoftware** [comment]
In the unlikely event that static types, like TypeScript are introduced to Node.js core

having  xSync vs x, allows for adding static types, if it's all dynamic at runtime, harder to manage typing info.

Also, at some point there was talk that Node.js core was going to be promisified. 

if you have `fs.readFile().then()`, (with no "sync" paradigm) it wouldn't know whether to return synchronously or return a promise, given the idea in this thread.

The "Sync" paradigm adds information, and that information is useful. Great paradigm IMO.

**Comment by seishun** [comment]
>There's a qualitative difference in that the service stays responsive. You don't have that when the main thread is tied up.

You missed the point. If you expect such attacks, you'll use a proper defense mechanism rather than just offload the work to threads and ignore the problem. For example, have a message size limit (at which point `zlib.deflate` provides no value over `zlib.deflateSync`).

**Comment by bnoordhuis** [comment]
With all due respect @seishun, but I think it's you who is missing the point.  The first and perhaps only rule of Node.js is "never block the event loop."

> have a message size limit (at which point zlib.deflate provides no value over zlib.deflateSync)

Bad idea.  The size of the input has only a weak relation to the size and cost of the output.

> Also, at some point there was talk that Node.js core was going to be promisified:

@ORESoftware It happened!  `require('fs/promise')` - only in master so far but it will be in Node 10.

**Comment by seishun** [comment]
>With all due respect @seishun, but I think it's you who is missing the point. The first and perhaps only rule of Node.js is "never block the event loop."

I don't see how that rule of Node.js shows that I'm missing the point. It normally refers to I/O-bound functions. It's not as clear-cut with CPU-bound functions.

I'm saying that in your scenario where `deflate` helps you, you're kinda screwed either way (and you have a trivial way of mitigating it that works just fine with `deflateSync`).

>Bad idea. The size of the input has only a weak relation to the size and cost of the output.

Zlib functions are linear in the size of input according to Mark Adler ([link](https://stackoverflow.com/a/39662445/550110)). Can you provide some evidence to the contrary?

**Comment by ORESoftware** [comment]
@bnoordhuis  the paradigm of `require('fs/promise')` is smart, that is a good idea. Better than dynamically returning different types.

The idea of dynamically returning different types for the same function call in JS is a bad idea...this isn't Java where methods/functions can be overloaded with different signatures etc.

**Comment by bnoordhuis** [comment]
@ORESoftware Yeah, I agree.  I don't think it could've worked otherwise.

> Zlib functions are linear in the size of input according to Mark Adler (link). Can you provide some evidence to the contrary?

@seishun You're falling into the big-O trap.  `O(n)` doesn't mean the best case and worst case for a given input size can't be a factor ten or more apart.

Big-O notation is useful for talking about properties of algorithms and data structures as `n` grows towards infinity.  For everything else, you should be using WCET (Worst Case Execution Time.)

If you're old enough to remember MSN Messenger (which used zlib), it was for a long time susceptible to the exact same issue we're discussing here.  You could lock up the recipient's UI by drip-feeding it crafted messages.

**Comment by seishun** [comment]
Links, please. Your description doesn't prove that "size of the input has only a weak relation to the size and cost of the output" anyway, the Worst Case Execution Time can still grow linearly with input size.

**Comment by bnoordhuis** [comment]
Hey Nikolai, you can do the research yourself.  I've pointed you in the right direction but I don't get paid to tutor you.

**Comment by hackygolucky** [comment]
Wearing my education hat here, @bnoordhuis 

While you don't get paid to tutor anyone here, this is the /help repo. Please feel free to step away from responding further on this thread if you aren't feeling like you're making progress in helping, but we don't want to deter anyone in these this repo especially from learning. The folks who are contributing to this repo are teaching as a contribution.

**Comment by bnoordhuis** [comment]
@hackygolucky "teaching as a contribution" - yes, thanks, that's what I'm doing.  Look at the stats, I'm probably the most active contributor here.
<hr>

Okay, @seishun, let's generalize a bit to something that is applicable to most data-driven algorithms, not just deflate.

You're probably aware that modern CPUs rely heavily on L1 caches for good performance.  Observe that memory access is about 100x slower than a L1 cache hit.  Google it if you don't believe me.

That fact alone means the difference between the best case and the worst case is 100x but more practically, a good implementation of a data structure or algorithm usually hovers around 70-80% cache utilization; call it 75%.

It's almost always possible to craft cache-adverse input that lowers the cache rate significantly.  Manage to lower it to 25% and you've slowed down your victim's application by 3x at no cost to you.  You can often do this while still maintaining the same output, making it hard to observe by your befuddled victim.

The above is a bit of digression and I ignored L2 and L3 caches for the sake of simplicity (changes the numbers but not the principle) but I hope it helps you understand why "sync deflate is okay" is bad advice: there are simply too many ways for a clever attacker to exploit that naivety.

Coincidentally, that's why many hard real-time systems use cache-less or cache-disabled CPUs; it's too hard to reason about WCET otherwise.

**Comment by Trott** [comment]
I believe the original question here has been answered and we've moved off into a different topic at this point. I'm going to close this. Feel free to comment or re-open if I'm mistaken.
