### ISSUE TITLE
messed-up order of guides on nodejs website

### ISSUE THREAD

**Issue by priambodop** [nodejs/help#1122]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Hi i'm actually don't have any issue with codes, but i just wanted to tell you that your nodejs guides on your official web has been always not in order. It is very confusing because as a starter like me, i need to follow a guide to really understand the basic. So, hopefully the guides will soon to be fixed.
Thank you

**Comment by gireeshpunathil** [comment]
can you please be specific? which document(s) are in disorder?
do you have specific recommendations to make?
are you willing to contribute to improve it?

**Comment by priambodop** [comment]
@gireeshpunathil I’m sorry did not to be specific. I’m sending you a screen captured right away to see what i actually mean.

<img width="1274" alt="screen shot 2018-03-06 at 9 13 16 pm" src="https://user-images.githubusercontent.com/14269541/37037391-c6339504-2184-11e8-8bed-86e7b35a8e7a.png">

Pretty sure the order of the guides seems incorrect, so i’m a little bit confused.

**Comment by gireeshpunathil** [comment]
@nodejs/documentation - please review and advise: the order -starting with event loop, ending with file systems, and getting started somewhere in the middle - probably not natural for a first comer. Anything can be bettered here?

**Comment by richardlau** [comment]
cc @nodejs/website

**Comment by benjamingr** [comment]
Thank you for your feedback @priambodop it is appreciated. What sort of expectation did you have for the guides and how did we not meet it?

**Comment by glennschler** [comment]
I recall the guides have grown over the past two years. The [Docs/Guides](https://nodejs.org/en/docs/#guides) section describes them as _Long-form, in-depth articles about Node.js technical features and capabilities_. When I reference it is because I consider them as best practice guidelines created by experts in the community. Perhaps some categories are a start to organize better? For example:

- Getting Started
  - [Getting Started](https://nodejs.org/en/docs/guides/getting-started-guide/)
  - [The Node.js Event Loop, Timers, and process.nextTick()](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/)
  - [Anatomy of an HTTP Transaction](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/)
  - [Timers in Node.js and beyond](https://nodejs.org/en/docs/guides/timers-in-node/)
  - [Overview of Blocking vs Non-Blocking](https://nodejs.org/en/docs/guides/anatomy-of-an-http-transaction/)
  - [Debugging Guide](https://nodejs.org/en/docs/guides/debugging-getting-started/)
  - [Don't Block the Event Loop (or the Worker Pool)](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/)
- Advanced Topics
  - [Domain Module Postmortem (_deprecate?_)](https://nodejs.org/en/docs/guides/domain-postmortem/)
  - [Backpressuring in Streams](https://nodejs.org/en/docs/guides/backpressuring-in-streams/)
  - [Dockerizing a Node.js web app](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/)
  - [To publish N-API version of a package alongside a non-N-API version](https://nodejs.org/en/docs/guides/publishing-napi-modules/)
  - [Easy profiling for Node.js Applications](https://nodejs.org/en/docs/guides/simple-profiling/)
  - [Working with Different Filesystems](https://nodejs.org/en/docs/guides/working-with-different-filesystems/)

**Comment by Qard** [comment]
As I recall, it originally started in alphabetical order. It looks like it has deviated from that a bit. At this point there are enough guides that we should probably start grouping them. As @glennschler mentioned above, we could split into "getting started" and "advanced topics" but those are also getting to be large enough lists it might be worth splitting further. Perhaps we should also have a "deep dive" section for going over deeper details of things and abstract concepts, and a performance/debugging section.

**Comment by fhemberger** [comment]
Hello, Frederic here from the website team. Thanks for the feedback, I just filed a PR that will address this issue.

**Comment by fhemberger** [comment]
PR has been merged, issue resolved.

**Comment by priambodop** [comment]
@benjamingr @fhemberger huge thanks to you guys. it is so much easier now to exactly know where i need to begin with to learn node.js.
