### ISSUE TITLE
NodeJS on SPARC

### ISSUE THREAD

**Issue by MGuz-DXC** [nodejs/help#1127]
* **Node.js Version**: Any
* **OS**: Solaris 11
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**:

Is there a version of nodejs that can be installed and under Solaris 11 on SPARC hardware? 

```js
// I am an example of JS code
// please remove me too
```
-->

**Comment by shellberg** [comment]
The short answer is No.  Not that I'm aware of.

Technically, its likely not far away from executing because SmartOS was a derivative of the OpenSolaris family of OSes.  However, with Solaris 11 returning to its proprietary, closed roots there are potentially a range of recent SPARC-based hardware/servers that may well have differing drivers.  As far as I know, Oracle have not contributed to making a Node.js port and I don't believe the community have any Solaris 11 platforms as part of the build/CI infrastructure.

**Comment by gireeshpunathil** [comment]
closing as answered.
