### ISSUE TITLE
Is there a forum where I can ask questions?

### ISSUE THREAD

**Issue by markfilipak** [nodejs/help#1150]
[http://github.com/nodejs/help](http://github.com/nodejs/help) is for programmers, not for civilians asking questions.
And [http://nodeslackers.com](http://nodeslackers.com) is unresponsive. It appears to be some sort of invitation site for slack.zendesk.com. I don't know how it's supposed to work, but the folks at Slack are scratching their heads over it. I'm mystified.

I'm looking for discussion of nodejs, not creating a workspace. Do you know of any sites for nodejs discussion? -- I'm hoping that will eventually lead me to CJS.

**Comment by gireeshpunathil** [comment]
Can you please clarify the nature of `civilian` discussions?

Any programming problems emanating from node usage, that is not confirmed as bug this is the repo.
For direct chat / discussion on a specific topic: #node.js on https://webchat.freenode.net
Otherwise, if it is for general discussion on architecture, use cases etc. a blog that has discussion thread feature is nice.
Having said that, for discussions with themes that bring new use cases, creative ideas, usage pain points, field insights etc. this repo of nodejs/node repo is always open!

Hope this helps.

**Comment by markfilipak** [comment]
@gireeshpunathil wrote: "Can you please clarify the nature of civilian discussions? Any programming problems emanating from node usage ..."

It is like this, Mr. Data,

It is an allusion to the difference between the military and the civilian realms in which the military is like developers and civilians are like users. Each group has their own concerns. And any war (project) that addresses only the concerns of developers (the military) and doesn't provide a forum for users (the civilians) will not succeed.

Let me put it another way. You are mecha. We are orga. ...
:-)

**Comment by gireeshpunathil** [comment]
sorry, I fear we don't have any such forums. Closing.

**Comment by markfilipak** [comment]
Please don't close this thread.

I seek a place for discussion of nodejs... **anywhere, anywhere at all**. If no one here knows where nodejs can be discussed, then there's a problem, isn't there?
