### ISSUE TITLE
Handling socket (close/destroy/end) events, when streaming data to them

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1167]
This regards Node.js versions > 6

I have this code:

```js
import net = require('net');
import {ObservableOplog} from 'oplog.rx';
import JSONStdio = require('json-stdio');

export const clientMap = new Map();
const oplog = new ObservableOplog();

const transform2JSON = JSONStdio.transformObject2JSON();
const t = oplog.getFilteredStream({}).pipe(transform2JSON);

export const s = net.createServer(function (socket) {
  
  console.log('client connected.');
  
  clientMap.set(socket, socket);
  t.pipe(socket);
  
  socket.once('close', function () {
    clientMap.delete(socket);
  })
  
});

s.listen(6969);
```

my concern is - if the socket disconnects, what will happen with the 

`  t.pipe(socket);`

call?

What do I need to do to prevent a runtime error and/or memory leaks?

Should I do something like this?

```js
 t.pipe(socket).once('error', function(){
    t.unpipe(socket);
});
```

should I retry / reuse the same socket, or wait for a new connection?

**Comment by gireeshpunathil** [comment]
@ORESoftware : 
re: how to catch errors - as the sockets are prone to close, end and destroy (there is no disconnect event or API, it boils down to one of these three forms), and we are not sure which one can happen, and from which end point, the safe thing is to install 'close', 'end' and 'error' handlers and perform unpiping to detach the readable streams.

re: memory leak: as it is evident in this [highlighted code](https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L732-L745), unpiping twice or more does not break anything, it simply returns if it was not piped earlier. Also the same shows detaching the  `pipee` so that they are now unreferenced from the pipe.

re: retry / reuse the same socket : that is a general problem outside of the current scenario I guess. If we don't know the reason for the socket `disconnect` it is not safe to attempt a re-use.

Hope this helps!

**Comment by ORESoftware** [comment]
wait so there is 'end' / 'close' / 'destroy' events but there is no 'disconnect' event, so by "disconnect" I guess you mean one of the first 3 events, right?

**Comment by gireeshpunathil** [comment]
@ORESoftware - you used the `disconnect` term first, not me. :) But yes, right. As the sockets abstract a number of parties behind it (buffers, HTTP / TCP layers, the network, and the remote endpoint) , plurality of events that can happen anywhere in the path that leads to the breakage of the connection - makes sense to cover it under disconnect, while the actual reason could be one or more more events represented by `end`, `destroy` and `close`.

**Comment by the1mills** [comment]
Thanks @giresh do you think you could describe your approach with a few lines of code?

**Comment by gireeshpunathil** [comment]
sure, here:
#cat 1167.js 
```js
const net = require('net')
const stream = require('stream')
const CHAR = 'G'
class Readable extends stream.Readable {
  constructor() {
    super()
  }
  pump(hz) {
    this.t1 = setInterval(() => {
      this.push(Buffer.from([(97 + Math.round((Math.random() * 26)))]))
    }, hz)
    this.t2 = setInterval(() => {
      this.push(Buffer.from(CHAR))
    }, hz * 10)
  }
  unpump() {
    clearInterval(this.t1)
    clearInterval(this.t2)
  }
  _read(size) {}
}

var r = new Readable()
r.pump(100)


const s = net.createServer((f) => {
setTimeout(() => {
   // unlock this as needed.
   // f.destroy()
}, 2000)
f.on('error', (r) => {
  console.log('error!')
  r.unpipe(f)
})
f.on('end', (v) => {
  console.log('end!')
  r.unpipe(f)
})
f.on('close', (h) => {
  console.log('close!')
  r.unpipe(f)
})
r.pipe(f)
})
s.listen(6969, () => {
  var c = net.createConnection(6969)
  setTimeout(() => {
    c.destroy()
  }, 1000)
  c.on('data', (d) => {
      console.log(d.toString())
  })
})
```

#node 1167.js 

```trace
{
k
s
m
j
p
t
y
g
G
end!
close!
^C
```

**Comment by gireeshpunathil** [comment]
ping @ORESoftware

**Comment by ORESoftware** [comment]
thanks I am going to use your code, that works for me, will reopen if I have questions about it.
