### ISSUE TITLE
Using multiple child processes

### ISSUE THREAD

**Issue by Wodki** [nodejs/help#1168]
* **Node.js Version**: v8.10.0
* **OS**: CentOS7 / Win32
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

I have a function that while it is not async it does some taxing calculations, let's say 500ms. 
While that is not necessarily a problem right now, it will be upon scaling.
I decided therefore to use child processes and every time it is needed to create one, call the function with it and return the result when is done.

My questions are the following;
**i)** Is it a bad practice to creating many child processes for the same function eg: 10, 1000, or 10k?
**ii)** Considering the above problem and my solution was there a better alternate to go about this?
**iii)** If my CPU has 1 thread (eg: VSP server) or for the arguments sake 2, will it have any performance improvement spawning more than 2 child processes aside from the fact that the main process won't be blocked.
**iv)** Should I keep the childs instead of killing them every time since I will need them again?

_Thank you for giving me some of your time and helping me out I honestly appreciate it!_

**Comment by gireeshpunathil** [comment]
- If concurrency is the main goal, the parent node process itself will give great performance at low and moderate scale.
 - if the workload is computation intensive,  it makes sense to offload them into child processes.
 - consider using [cluster](https://nodejs.org/dist/latest-v9.x/docs/api/cluster.html) module that is designed to distribute the load by taking advantage of the multi-core. It is a marvelous abstraction around child processes and distribution of work.
 - if your system is single-CPU, there is no perceived performance advantage of doing any of the above, other than clean isolation and modularity between work items. This is because, when one of the cluster member or a child process picks up its work, the main process stalls execution and vice versa.
- keeping the children process vs. terminating then after the work is done is a tradeoff between space and time. If you can afford the resources held up but concerned about latency, you keep them. On the other hand, if you are worried about memory footprint, open descriptors etc., you recycle them.

Hope this helps.

**Comment by ORESoftware** [comment]
@Wodki  you don't really need more than 100 processes running for your server, if they are in high utilization. Most high performance systems use a process pool or thread pool, sometimes capped around 10 or 15 in size.

**Comment by Wodki** [comment]
Thank you both for your responses. 

First of all due to some reasons and they way my node is structured I cant really use cluster (create another instance of the whole app), but I now understand better about the child processes. I will try adding first a single child process since right now my CPU is a dual-core and see how it goes.

Have a nice day.

**Comment by gireeshpunathil** [comment]
closing then, cheers!

**Comment by ORESoftware** [comment]
@Wodki sure keep in mind that under the hood node.js is multithreaded - but since your machine is just a dual core, you don't need to spawn that many processes to take full advantage of the hardware.

You can experiment with the following env variable to change the threadpool size in node:

`UV_THREADPOOL_SIZE=16 node your-script.js`
