### ISSUE TITLE
Install specific version of NodeJS

### ISSUE THREAD

**Issue by gpstmp** [nodejs/help#118]
I need NodeJS v4.2.3 and i'm using this instructions https://github.com/nodesource/distributions#installation-instructions. Everything is ok but i got 4.0.0 version and cannot find a way to install 4.2.3 (or any other 4.x version).
I have tried to specify version but with no success: 

    apt-get install nodejs=4.2.3
    apt-get install nodejs=4.2.3-1nodesource1~trusty1

`apt-cache madison nodejs` command gives me this:

    nodejs | 4.4.0-1nodesource1~trusty1 | https://deb.nodesource.com/node_4.x/ trusty/main amd64 Packages
    nodejs | 4.4.0-1nodesource1~trusty1 | https://deb.nodesource.com/node_4.x/ trusty/main Sources

Thanks for any help!

**Comment by lordKnighton** [comment]
Here, I'd like you to try here. [~click-me~](https://nodejs.org/download/release/v4.2.3/)

**Comment by williamkapke** [comment]
I'm not sure if you're dedicated to using apt-get or not...

But if you're looking for some flexibility in swapping versions as needed, I've had great success with https://npmjs.com/package/n.
```
npm install -g  n
n 4.2.3
```

If you do not have ANY version of node installed (therefor no NPM) you can use:
https://github.com/mklement0/n-install

```
curl -L http://git.io/n-install | bash
```

**Comment by lordKnighton** [comment]
did you get this fixed? :hammer:

**Comment by gpstmp** [comment]
@williamkapke i know about `n` or `nvm` BUT i want to install with apt-get. It is a kind of a strange problem for me: official guide suggest straight forward way but i cannot get required version. Also, why official guide does not suggest using `n` or `nvm`?
@lordKnighton thanks for the link, but i cannot understand how to install v4.2.3 (for example) via `apt-get install` from that list of packages. 
Maybe i should download required deb here https://deb.nodesource.com/node_4.x/pool/main/n/nodejs/ and than use `dpkg -i`?

**Comment by TheAlphaNerd** [comment]
@gpstmp if you are having problems with the nodecourse debs you might get better support posting over at https://github.com/nodesource/distributions

**Comment by gpstmp** [comment]
@TheAlphaNerd thanks, will do that! It is a bit strange for me again: is that a big problem to install a specific nodejs version?

**Comment by TheAlphaNerd** [comment]
personally I use nvm and never have problems aside from testing rc's

**Comment by subfuzion** [comment]
@gpstmp, What is your particular use case here? Are you switching back and forth between different versions frequently? Are you trying to apt-get a specific version for CI builds? Or you just want to ensure you can install a specific version for a particular reason, but you can then stay on that version for a while?

I used to use `nvm` for switching back and forth frequently (I agree with @TheAlphaNerd assessment), but these days I use Docker and just mount the directory:

    docker run --rm -it -v $PWD:/usr/src/app node:4.2.3-onbuild node app.js

or just run container with default `npm start` command:

    docker run --rm -it -v $PWD:/usr/src/app node:4.2.3-onbuild

**Comment by gpstmp** [comment]
@subfuzion thanks for Docker example!
As for your questions: 
+ i am using nvm myself
+ i cannot find any practical sense in https://github.com/nodesource/distributions#installation-instructions. This is why i asked this question. Maybe i am missing something, but why not just tell `use nvm or n` (this is what i hear from anyone).

**Comment by subfuzion** [comment]
@gpstmp NodeSource is a third party firm focused on providing enterprise-grade Node support. They contribute to the community and employ several Node core maintainers. One of the things NodeSource does is provide convenient hosting of Node packages and they [hired Chris Lea](https://nodesource.com/blog/chris-lea-joins-forces-with-nodesource/) who originally maintained the Node PPA (personal package archive) for Ubuntu.

However, as convenient as it is, that is not an official Node page and anyone no one is going to dictate to you to use either `nvm` or `n` since they solve the problem of switching versions of node in two very distinctly different ways. If you want to be able to switch versions of node frequently, you'll have to make the choice yourself. If you want guidance, well, I agree with @TheAlphaNerd  and happen to prefer `nvm`. But you really should make that choice on your own after doing some homework. Both are just convenient utilities created by separate developers to make switching between versions convenient. It is not a core feature of the node platform itself.

As far as guidance for choosing any particular node version, if you work for an enterprise where long term stability is important, then choose the latest Node v4 LTS version. Otherwise, just go with the latest v5 version.

If you don't want to use `nvm` or `n`, and you can't get the specific version you want via `apt-get`, then go ahead and clone the node repo, checkout the tag for the version of node you want, and [build from source](https://github.com/nodejs/node/blob/master/BUILDING.md).

Good luck.

**Comment by subfuzion** [comment]
@gpstmp I ran `apt-get policy nodejs` and see that `4.4.2-1nodesource1~wily1` is the version that is available.

```sh
$ curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
...
$ apt-cache policy nodejs
nodejs:
  Installed: (none)
  Candidate: 4.4.2-1nodesource1~wily1
  Version table:
     4.4.2-1nodesource1~wily1 0
        500 https://deb.nodesource.com/node_4.x/ wily/main amd64 Packages
     0.10.25~dfsg2-2ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ wily/universe amd64 Packages
```

`4.4.2` is in fact the latest version of Node v4.x LTS.

I think you really ought to save a lot of trouble for yourself and just install `nvm`...

**Comment by gpstmp** [comment]
@subfuzion thanks again! I think the issue must be closed now.

**Comment by singhIshu** [comment]
I was struggling in downgrading my node version from 11.11.1 to 11.10.1
These were the few commands I ran that helped me
If you don't have node install first install node by running 
```
brew install node
```
for those who already have it installed just install package call "n" . 
This n package helps you to  Interactively Manage Your Node.js Versions

```
npm install -g  n
```
After installing it you just run 

```
sudo n <node-version-you-want>
e.g sudo n 11.10.1
``` 
and your node version will get changed you can check the node version by running

```
node --version
```
I hope it will be helpful :)
