### ISSUE TITLE
Looking for unit tests for internal/process/stdio.js

### ISSUE THREAD

**Issue by reggi** [nodejs/help#1182]
I am curious if there's unit tests for this internal module, and if so can someone point me to them? https://github.com/nodejs/node/blob/master/lib/internal/process/stdio.js

**Comment by gireeshpunathil** [comment]
@reggi - 
 - as the name suggests, this is an internal module that does not expose itself to the user programs.
 - having said that, no harm in having unit tests. AFAIK, there is none.
 - Copying @Trott who can provide better information on this.
 - If you are interested in developing test cases, most welcome!

**Comment by Trott** [comment]
It looks like that module's only exported property is `setup()`.

Since it's an internal module, any direct unit-testing will have to be done with a test that has `--expose-internals`.

So, grepping first for that flag, and then grepping for `setup`:

```console
$ grep -lr -- --expose-internals test | xargs grep -l setup
test/parallel/test-buffer-bindingobj-no-zerofill.js
test/parallel/test-inspect-async-hook-setup-at-inspect.js
test/sequential/test-inspector-async-hook-setup-at-signal.js
test/sequential/test-inspector-break-when-eval.js
$
```

One buffer test and three inspector tests. So it looks like there are no direct unit tests.

If this is about writing a unit test to check the `default` cases of the `switch` statements, that would be great. There's quite possibly no way to trigger that from userland as that would be an error in Node.js's internal code.

I'm going to close this because I *think* I've answered the question, but feel free to post additional comments/questions. For questions about Node.js core tests, you can also try the #node-dev channel on Freenode IRC.
