### ISSUE TITLE
how the Api res.writeHead to do that only used once

### ISSUE THREAD

**Issue by xukaijie** [nodejs/help#1188]
* **Node.js Version**:8.0.0
* **OS**:mac 
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I know ths api  res.writeHead can be used only once for every http request. i saw the node source code. but i can not understand how to complete the limit. i add print info at the writeHead start below(API is in file _http_server.js):

ServerResponse.prototype.writeHead = writeHead;
function writeHead(statusCode, reason, obj) {
  console.log("starting writing header");
 .........................
}

and i use the API as follow:

res.writeHead(200,{test:1});
res.writeHead(200,{test2:1});

the results is : the writeHead only use once  i see only once print info .and ths process is pending . i do not know why the function is not be used. how to complete the limit .

thanks for you!

**Comment by gireeshpunathil** [comment]
can you please clarify `how to complete the limit .`  part? what you are trying to achieve? are you not able to complete the response? or are you not able to see the changes you made being taken into effect?

```js
var h = require('http')
var n = require('net')

var v = h.createServer((q, s) => {
  s.writeHead(200,{test:1});
  s.writeHead(200,{test:2});
  s.writeHead(200,{test:3});
  s.writeHead(200,{test:4});
  s.writeHead(200,{test:5});
  s.end('hello')
}).listen(12000, () => {
  const c = n.createConnection(12000, () => {})
  c.on('data', (d) => {
    console.log(d.toString())
  })
  c.end('GET / HTTP/1.1\r\nHost: localhost:12000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\n\r\n')
})
```
#node 1188.js
```trace
#node 1188.js
HTTP/1.1 200 OK
test: 5
Date: Wed, 28 Mar 2018 15:51:29 GMT
Connection: keep-alive
Transfer-Encoding: chunked

5
hello
0


```

As you can see, the last data that was passed to the `writeHead` took effect. This is because of the logic covered [here](https://github.com/nodejs/node/blob/4de78219711dcfdc24290520b20dce1fff01e164/lib/_http_server.js#L215-L220). This is to make sure the server sends a valid protocol message which the client understands.

If you are not able to finish with the response, you will need to `end` it: in my case, `s.end()` call.

On the other hand, if you are not able to see your changes (debug prints) not being reflected, you need build from source - `./configure && make`

Hope this helps, if your question is different, let me know.

**Comment by gireeshpunathil** [comment]
ping @xukaijie

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if you have anything outstanding on this.
