### ISSUE TITLE
Detecting if a child process spawned successfully

### ISSUE THREAD

**Issue by pushkin-** [nodejs/help#1191]
* **Node.js Version**: 7.9.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**: `child_process`

Is there anyway to detect if a process has successfully spawned? There's an `error` event that I can listen to, but no `success` event, so it seems that I have no guarantee that the process successfully spawned until I start actually writing to its streams and get errors.

I have found that I can check `proc.pid` right after `spawn`ing, and if I pass in a faulty path, it's `undefined.` If I pass in the correct path, it's set to a number, which seems promising. However, someone on [SO](https://stackoverflow.com/questions/49577641/synchronously-checking-if-a-child-process-failed-to-spawn-in-node) said that the spawning might still fail after the OS gives back a pid.

What exactly is guaranteed after the `spawn` function returns? At what point in the spawning process are we? And can I rely on this `proc.pid === undefined` technique? If not, how can I at least asynchronously know if the process successfully spawned? Why is there no `success` callback?

**Comment by ORESoftware** [comment]
One thing you could do, is in the child process, write to stdout "spawned successfully", read from stdout in the parent process, and then wait for that message.

**Comment by addaleax** [comment]
I’m pretty sure there was some very similar issue here a while ago, but I can’t seem to find it … anyway:

> Is there anyway to detect if a process has successfully spawned?

Sadly, no, not in the general case.

> I have no guarantee that the process successfully spawned until I start actually writing to its streams and get errors.

Yup, that’s correct. libuv does a best-effort thing here, but it’s impossible to get a guaranteed result without resorting to e.g. polling techniques that look up the process pid and what that process is currently doing.

> I have found that I can check `proc.pid` right after `spawn`ing, and if I pass in a faulty path, it's `undefined.` If I pass in the correct path, it's set to a number, which seems promising. However, someone on [SO](https://stackoverflow.com/questions/49577641/synchronously-checking-if-a-child-process-failed-to-spawn-in-node) said that the spawning might still fail after the OS gives back a pid.

Part of the problem here is that there is no clear line for determining what a “failed” spawn attempt means – at what point do you consider a process spawned successfully? There can be errors at any point during process setup.

> What exactly is guaranteed after the `spawn` function returns?

On Unix, that the [`execve()`](https://linux.die.net/man/2/execve) system call was entered in the child process, and it succeeded in loading the relevant parts of the target executable into memory.

On Windows, a similar thing goes for [`CreateProcess()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx).

Either way, there are still plenty of reasons why starting a process might fail – missing DLLs/shared libraries, memory exhaustion while running setup code, etc.

> At what point in the spawning process are we?

If the `spawn()` call succeeds, all you know that it’s up to the OS and the spawned process. No code from Node.js/libuv will be executed anymore inside the child.

> And can I rely on this `proc.pid === undefined` technique?

For checking whether the executable could be found, yes, that’s reliable.

> If not, how can I at least asynchronously know if the process successfully spawned?

The only thing that comes to my mind would be polling the OS’s way of providing information about the process tree in general.

> Why is there no `success` callback?

When, and most importantly, from where would that callback be called? `spawn()` finishing means that the OS and the target executable’s code are in charge now, so Node.js can’t make the process do something like saying “I’m good to go”.

> Node.js Version: 7.9.0

(Side note: Node 7 has been unmaintained for ~ 9 months, you might want to consider upgrading to an actively maintained version. [Here](https://github.com/nodejs/Release#release-schedule)’s the schedule. :))

**Comment by pushkin-** [comment]
@addaleax Thanks for all the info. I'm running an outdated Node, because I'm running an older [Electron](https://electronjs.org/releases#1.7.13) which uses that Node version.

**Comment by ORESoftware** [comment]
@pushkin-  no problem

**Comment by arashmad** [comment]
> One thing you could do, is in the child process, write to stdout "spawned successfully", read from stdout in the parent process, and then wait for that message.
> 
> ```js
> const k = cp.spawn('bash');
> let stdout = '';
> 
> k.on('data', function(d){
>   stdout+= String(d);
>  if(stdout.match(/spawned successfully/)){
>      // do your thing
>   }
> });
> ```

Thank you so much @ORESoftware - simple and handy
