### ISSUE TITLE
When can I assume the data pointer of Buffer/arrayBuffer/typedarray remain constant ?

### ISSUE THREAD

**Issue by yw662** [nodejs/help#1194]
* **Node.js Version**: 9.10.1
* **OS**: linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: N-API/Addon

```js
    double *buf;
    napi_value ab;
    napi_value ta;
    napi_create_arraybuffer(env, size, &buf, &ab);
    napi_create_typedarray(env, napi_float64_array, size, ab, 0, &ta);
```

When can I assume the `double* buf` still points to the the right place ?
If I return the typedarray to javascript, can I keep the `double* buf` for future use ?

**Comment by addaleax** [comment]
> When can I assume the `double* buf` still points to the the right place ?

Always, until the `Buffer` object is garbage collected. Node explicitly disables moving around typed arrays in memory so that addons can rely on this. :)

> If I return the typedarray to javascript, can I keep the `double* buf` for future use ?

Yes, and in fact it’s something that Node.js itself does a lot because it’s one of the fastest ways to transfer data between JS and C++/C.

One gotcha is that this doesn’t play well with ChakraCore’s time-travel debugging, but those workarounds are engine-specific and not exposed through N-API. For practical purposes, I guess you can ignore that, but it might be something to keep in mind in the long run.

**Comment by yw662** [comment]
@addaleax Thanks a lot. I think there is no need to worry about chakra for now. I am glad to here that.
