### ISSUE TITLE
net: why net.Socket's property without pid info

### ISSUE THREAD

**Issue by MrTreasure** [nodejs/help#1213]
* **Node.js Version**: v8.9.3
* **OS**: win10 64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: net

Why net create a IPC server, the coming socket without pid info. Under this condition I can't define which socket it is.Then I must send a message to tell server it's pid info. Code beblow here
```javascript
const clientList: IClient[] = []
enum MSG_TYPE {
  INIT,
  DATA,
  COMMUNICATE
}

interface IClient {
  id: number | string
  socket: net.Socket
}

const handleClientMsg = (msg, current) => {
  switch (msg.type) {
    case MSG_TYPE.INIT:
      let client = clientList.find(item => item.socket === current)
      if (client) {
        client.id = msg.id
      }
      break
    
    case MSG_TYPE.COMMUNICATE: {
      let client = clientList.find(item => item.id === msg.id)
      if (client) {
        client.socket.write(msg.data)
      } 
    }
      break
    default:
      break
  }
}

server.on('connection', socket => {

  clientList.push({ id: undefined, socket })

  socket.on('data', function (msg) {
    let message = JSON.parse(msg.toString())
    handleClientMsg(message, this)
    console.log(this, this === socket)
    log(chalk.green(clientList.map(item => item.id).toString()))
  })
})
```
If soeckt has pid info, I can store it's pid info during connection event

**Comment by gireeshpunathil** [comment]
what if you do this:

```js
socket.on('data', function (msg) {
    let message = JSON.parse(msg.toString())
    socket.write(message)
  })
})
```

the socket object you receive each time when a connection is established itself uniquely identify the client socket, eliminating the need of a key.

Can you try and let me know?

**Comment by gireeshpunathil** [comment]
ok - because you are using a shared pipe by multiple clients, it is reasonable that you need to pass your identifier to be distinguishable from other processes.

as to your question on why socket does not have PID info: 
 - the most common use case have a socket uniquely identifying a single end point so another identifier is not required
 - in less common scenarios, sockets can be shuttled between processes, so associating a PID with socket does not make meaning too.

In your use case, what you are doing seem to be right and reasonable to me.

Hope this helps.

**Comment by gireeshpunathil** [comment]
closing as answered, @MrTreasure feel let me know if you have anything outstanding on this.
