### ISSUE TITLE
Interpreting profiler output

### ISSUE THREAD

**Issue by elimence** [nodejs/help#1221]
* **Node v9.11.1**:
* **macOS High Sierra Version 10.13.4**:
* **Profilling**:

I run the nodejs inbuilt profiler and got the following output:
```
Summary]:
   ticks  total  nonlib   name
    438   13.5%   13.5%  JavaScript
   2243   68.9%   69.3%  C++
    475   14.6%   14.7%  GC
     21    0.6%          Shared libraries
    554   17.0%          Unaccounted
```
```
[C++ entry points]:
   ticks    cpp   total   name
   1178   67.7%   36.2%  T v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
    111    6.4%    3.4%  T v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*)
     64    3.7%    2.0%  T ___sandbox_mm
     61    3.5%    1.9%  T v8::internal::Builtin_FunctionConstructor(int, v8::internal::Object**, v8::internal::Isolate*)
```

Seems like this guy v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) is the candidate for optimisation (?) but I'm not sure what that is.

Here's the entire output: https://pastebin.com/G8vURNkX

**Comment by devsnek** [comment]
Builtin_HandleApiCall is used by v8 to translate calls from js to any builtin implementations that are implemented in not-javascript. basically any time you call most javascript builtins (Array.prototype.slice as an example) you will see this show up in your traces. it shows up a lot because js builtins are used a lot
