### ISSUE TITLE
Simple question on mongodb

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1226]
Hi all, 

I am currently using Mongo DB for the first time for a project. I would like to know what the right way is to handle my DB connections, and if I should close them at the end of my mongo.connect callbacks? Currently I am not as can be seen in the code below...

Greets and many thanks

```javascript
if (advertisorFound) {
	
	var hasCurrentAd = advertisorFound.some(function(title){
		return title == titlePlat;
	});
	if (!hasCurrentAd) {
		
		mongo.connect(url, async (err, client) => {
										
			var db = client.db('nodeads');
			
			// searched is oude testmeuk
			const searchedAdsCollection = db.collection("searchedAds");  
			
			searchedAdsCollection.insertOne({ 'advertisor': currentAdvertisor, 'ads' : searched } );							
	
		
		});	
		
	}
}

else {
	mongo.connect(url, async (err, client) => {
		
		var db = client.db('nodeads');
		// searched is oude testmeuk
		const searchedAdsCollection = db.collection("searchedAds");  
		searchedAdsCollection.insertOne(currentAd, function(err, res){
			assert.equal(null,err);
			}
			
		});

		
		const userqueriesCollection = db.collection("falco");  
		const cursorQ = userqueriesCollection.find();
		
		console.log(searched);
		console.log(this.mainCrawl);				
		this.mainCrawl.options.searched = searched;
	
		this.checkQueries(queries);
	
		
	});	
}
```

**Comment by ryzokuken** [comment]
Hi, @WAINGOR! This question issue seems off-topic as it is not related to Node.js in any way, but rather to MongoDB.

Evidently, you would find better help resources and assistance in one of the Mongo support communities.

Try visiting https://support.mongodb.com/ or #mongodb on freenode.
Basically, anywhere in https://docs.mongodb.com/manual/support/#community-support works.

Closing this as off-topic, but feel free to reopen if you feel otherwise or if you have any other issues.
