### ISSUE TITLE
Catching thrown errors inside a Promise

### ISSUE THREAD

**Issue by ddimitrioglo** [nodejs/help#1239]
* **Node.js Version**: v6.11.4
* **OS**: MacOS
* **Scope**: Promises

I have some misunderstanding about how to catch `throw new Error()` inside promises:

1. In this example I can catch error as expected:

```js
function p1() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({ name: 'p1' });
    }, 1000);
  });
}

function p2() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({ name: 'p2' });
    }, 1000);
  });
}

p1().then(res => {
  throw new Error('Failed A2'); // <= throw is here
  return p2();
}).then(res => {
  console.log(res);
}).catch(err => {
  console.warn(err.message);
});
```

2. In this case I'm getting `Uncaught Error` exception:

```js
function p1() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({ name: 'p1' });
    }, 1000);
  });
}

function p2() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      throw new Error('Failed A2'); // <= throw is here
    }, 1000);
  });
}

p1().then(res => {
  return p2();
}).then(res => {
  console.log(res);
}).catch(err => {
  console.warn(err.message);
});
```

Thanks.

**Comment by ORESoftware** [comment]
You might need to use domains. But for now, try this:

```js
process.on('unhandledRejection', function(e,p){
    p.reject('foo');
});
```

can you capture the promise that way?

**Comment by ddimitrioglo** [comment]
That's the tricky... 
As I understand we are getting `unhandledRejection` when `reject()` something but never `catch()`, but in my case it just throws the error and stops execution, so your listener won't catch it.
Is my understanding wrong?

**Comment by ddimitrioglo** [comment]
@ORESoftware thank you, but as I see in Node.js documentation - [this is not a good idea:](https://nodejs.org/api/domain.html):

```js
// XXX WARNING! BAD IDEA!

const d = require('domain').create();
d.on('error', (er) => {
  // The error won't crash the process, but what it does is worse!
  // Though we've prevented abrupt process restarting, we are leaking
  // resources like crazy if this ever happens.
  // This is no better than process.on('uncaughtException')!
  console.log(`error, but oh well ${er.message}`);
});
d.run(() => {
  require('http').createServer((req, res) => {
    handleRequest(req, res);
  }).listen(PORT);
});
```

**Comment by addaleax** [comment]
Yea, it really depends on what exactly you want. If you want an error inside the `setTimeout` callback to reject the Promise – then `domain`s or `unhandledRejection` definitely are not the right thing for you.

Ultimately, the issue here is that Promises and other async primitives don’t play along well without interaction – the easiest way to address this is to use something like `const delay = util.promisify(setTimeout);`, so that you can use `delay(400)` and get a `Promise` as the return value, instead of having to provide a callback.

Otherwise, if you have to mix callback-style `setTimeout` code and Promises, then you’re best approach is probably to use explicit `try { … } catch (e) { reject(e); }` blocks inside the callback.

**Comment by ddimitrioglo** [comment]
@addaleax I did not know this, thank you!
