### ISSUE TITLE
determine if symlinked file or dir

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1258]
If we use:

```js
fs.stat(p, function(err, stats){
   if(stats.isSymbolicLink()){
      // *what now?
  }
});
```

* I assume we can't immediately determine if the file is a folder or not.
What is the recommended way to determine if the symlinked item is a folder or file?

I assume it's `fs.readlink`?

**Comment by addaleax** [comment]
If you’re using `fs.stat`, `.isSymbolicLink()` won’t return true – instead, `.isDirectory()` will return true, because `stat` looks at the link *target*. If you want to inspect a link by itself, `fs.lstat` is what you might want. (You could still use `fs.stat` to check whether the target is a directory or not in that case.)

**Comment by ORESoftware** [comment]
ahh ok so isSymbolicLink should never return true when using `fs.stat`...?

**Comment by addaleax** [comment]
Yes – from https://linux.die.net/man/2/stat:

> `lstat()` is identical to `stat()`, except that if path is a symbolic link, then the link itself is stat-ed, not the file that it refers to.

**Comment by ORESoftware** [comment]
nice thank you, gonna have to investigate more, a little confusing
