### ISSUE TITLE
Charter?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/help#130]
Is there a Charter in the works for this Working Group?
Is this targeted to be a Top-Level Working Group?

**Comment by jasnell** [comment]
The help repository really isn't a WG. It's largely just a forum for asking and answering general questions that should not go to the main repository.

**Comment by jasnell** [comment]
In other words... it's more a team of dedicated collaborators who quite helpfully take the time to answer questions that come in than a formal WG. That said, if those collaborators wanted to make it a WG, I certainly wouldn't object ;-)

**Comment by williamkapke** [comment]
I kinda thought so- but it says it is a WG with members in the README so I thought I'd ask.

**Comment by subfuzion** [comment]
@williamkapke The working group consists of the same members of the [Evangelism WG](https://github.com/nodejs/evangelism). If anyone is interested in becoming a member, by all means please participate and make contributions. If you have been making contributions and think perhaps you might not have been noticed in all the activity goes on, please go ahead and reach out to any of us. You can DM on Twitter. I see you've made several helpful comments so far, including in #118 (other than the fact you recommended `n` instead of `nvm` ... kidding)!  :)

Any more questions, or can I close this?

**Comment by williamkapke** [comment]
I'm working to get organizational things in order around the repos to make them easier to find & understand. Can you please add that info to the README? It would clear up questions/confusion for others that don't see this thread.

Also: We can battle out the `n` vs `nvm` when I see you next Wednesday night- oh wait, we got in to that @ the last Node Night! ;)

**Comment by Fishrock123** [comment]
This is a "wg" in the loose sense. There's no significant decisions this group would ever be making outside of this repo that doesn't already belong to another team, like docs or website. I don't think chartering is necessary, and the group probably won't even have meetings, so there really isn't a point.

**Comment by williamkapke** [comment]
@Fishrock123 Sounds right to me! I do think it should link over to Evangelism for posterity though.

**Comment by SomeoneWeird** [comment]
I'd love to join either this WG (if it is one haha) or the evangelism WG, keen to keep helping folks who are new like I do over with nodeschool :)

**Comment by Fishrock123** [comment]
Perhaps the list in the repo should be "who to mention", "helpers" or something?

**Comment by williamkapke** [comment]
This has been resolved via #400
