### ISSUE TITLE
Unclear behavior of process.memoryUsage

### ISSUE THREAD

**Issue by itaysabato** [nodejs/help#1315]
* **Node.js Version**: 8.11.2
* **OS**: Linux, Mac
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: process

There's something I couldn't figure out from the docs or googling so far, regarding [process.memoryUsage](https://nodejs.org/api/process.html#process_process_memoryusage):

1. Is it ever possible that `heapTotal > rss`? If so, how? Supposedly, the latter should always contain the former, but it seems like it does happen sometimes.
2. Also not sure about how `external` intersects with `rss` and `heapTotal`.
3. In general, what are the guarantees and caveats regarding these sizes?
4. How does one determine the total memory consumed by the Node process using these correctly (for any OS).

Thanks.

**Comment by addaleax** [comment]
> 1. Is it ever possible that `heapTotal > rss`? If so, how? Supposedly, the latter should always contain the former, but it seems like it does happen sometimes.

I think so, yes. At the very least, I see no reason why `heapTotal` can’t include memory pages that are on swap rather than in physical memory – and I think the JS engine doesn’t keep track of that.

> 2. Also not sure about how `external` intersects with `rss` and `heapTotal`.

It doesn’t intersect with `heapTotal` (i.e. no memory is shared between the two). The same caveat as above applies to RSS – not all memory that is externally allocated also has to reside in physical memory.

> 3. In general, what are the guarantees and caveats regarding these sizes?

One other big caveat is (imo) that `external` is really just an estimate, and there’s just a lot of things that Node.js doesn’t necessarily keep track of. All major memory allocations should be contained in this, though.

> 4. How does one determine the total memory consumed by the Node process using these correctly (for any OS).

I mean, that depends on what you mean by “total memory”? Either way, I don’t know the answer. `rss` is probably close to what you want.

**Comment by itaysabato** [comment]
Thanks @addaleax for the detailed answer!

Let me see if I got this straight:
1. The `rss` property counts the total amount of bytes occupied in the process's **_physical memory_**, including the stack, heap and external c++ objects.
2. However, it does **_not necessarily include_** everything allocated on the heap nor the external objects since they may be swapped to disk by the OS.
3. There is no way to use only these properties (even if they were accurate) to determine the total amount of memory **_allocated_** by the process since, e.g., stack variables are only counted as `rss` and cannot be isolated by simply subtracting `external` and `heapTotal`.
4. If, at a given moment, all allocated memory resides in physical memory, then it is true that
```rss - heapTotal - external = stack + codeSegment + untrackedExternal```
where the right-hand side properties don't really exist but self explanatory.

Did I miss anything or is this an accurate description?

**Comment by addaleax** [comment]
@itaysabato Yes, I think you’re correct.

One thing to add to point 4 would be that virtual memory may be allocated, but not yet in use; e.g. allocating a buffer of 64 kB but only writing to its first few bytes would typically increase the RSS by only 4 kB, the size of a single page.

**Comment by itaysabato** [comment]
@addaleax Awesome, thanks!
