### ISSUE TITLE
NodeJS REPL crashes after creating and using variable called 'Date'

### ISSUE THREAD

**Issue by rdmello** [nodejs/help#1341]
* **Node.js Version**: 10.4.1
* **OS**: macOS High Sierra 10.13.5
* **Scope (install, code, runtime, meta, other?)**: REPL (?)
* **Module (and version) (if relevant)**: 

Hello, I'm not sure if this is legal JS, but the node REPL seems to shut down with an error after I create a variable called Date: 

```
> var Date = 3;

> Date
```

this throws the following error and shuts the REPL down: 

```
> readline.js:1032
            throw err;
            ^

TypeError: Date.now is not a function
    at REPLServer.Interface._ttyWrite (readline.js:918:34)
    at REPLServer.self._ttyWrite (repl.js:688:7)
    at ReadStream.onkeypress (readline.js:168:10)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.EventEmitter.emit (domain.js:442:20)
    at emitKeys (internal/readline.js:422:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1022:36)
    at ReadStream.emit (events.js:182:13)
    at ReadStream.EventEmitter.emit (domain.js:442:20)
```

**Comment by trvsapjiac** [comment]
Creating a variable using `var` in the global scope creates (overrides) property of the global object with the same name. Therefore `var Date = 3` is equivalent to `global.Date = 3`, but `Date` is used by Node.js REPL script.

I don't know if this is intended or not, The only way to safely execute scripts in repl is to run them in a separate realm, which Node.js doesn't currently do. Otherwise, user scripts may override any of the useful global properties.

It is not hard to break REPL. For example, `String.prototype.replace = null` will also terminate the process.

**Comment by vp93** [comment]
Date is a global object in the Node environment , and is used to get date/time information in milliseconds. 
As such, when you declare a variable with the same name 'Date' , it is referring to that global object and not the variable that you just created by default and by order of precedence ( global variable names are resolved first, and then local variable names ). 

`var date = new Date ()` is the correct usage for the global Date object.

A solution to your problem would be just to use any other name for the variable, so that it does not conflict with any global objects' names.
It is in no way good practice to think of any other workaround like running them in a separate environment when the alternative is simply renaming the local variable. 
Global variable names should be familiarized with and never used unless you are referring to them explicitly.

**Comment by trvsapjiac** [comment]
> global variable names are resolved first, and then local variable names

That's not true. When you reference a variable by name, local variables are resolved firstly, and only if there is no local variable with such name, javascript engine searches for it in the global object.

**Comment by vp93** [comment]
`local variables are resolved firstly, and only if there is no local variable with such name, javascript engine searches for it in the global object.`

Not if the local variables are declared within a global scope, which seems to be the case here.

**Comment by trvsapjiac** [comment]
That's what I've explained in my first comment. But the point is that there are no two variables, it's just one variable which overlaps with a propery of the global object.

**Comment by vp93** [comment]
I read somewhere that Node REPL treats all input by default as top-level input, for access and control to all available Node core globals , so that means conflicts like this will always happen if using reserved variable names like 'Date' . 
It is a known good practice to familiarize yourself with at least the most common global objects' names so as to avoid any conflicts ( these are usually common words like Date, Math etc ). 

> Close: #1341

**Comment by gireeshpunathil** [comment]
problem is understood, and the question is answered. Further discussion seem to be drifting a bit, so let us close this. thanks all for providing the insights!
