### ISSUE TITLE
array is undefined after array.push

### ISSUE THREAD

**Issue by phaitonican** [nodejs/help#1347]
It is returning undefined.
```js
function getMembers() {
  var result = [];
  mongodb.MongoClient.connect(uri, function(err, client) {

    if(err) throw err;
    let db2 = client.db('members');

    let members2 = db2.collection('members');

    members2.find({}).forEach(function(row) {
       result.push(row.member);
    }, function(err) {
      console.log(result); <-- works
    });
  });
  return result; <-- is undefined
}
```
-->

**Comment by gireeshpunathil** [comment]
`mongodb.MongoClient.connect` is asynchronous which means the call does not complete when the execution reaches the next line, which is `return result` and at that time, result will be an empty array.

When calling an async method such as this, the best practice is to pass a callback function too and call back the function with the result, rather than returning it.

**Comment by phaitonican** [comment]
thanks gireeshpunathil. this async stuff is throwing me away, gotta take a look at it. thanks for the help!
