### ISSUE TITLE
get file icon

### ISSUE THREAD

**Issue by cat998** [nodejs/help#1360]
how nodejs get file icon and show it in html?

**Comment by lordKnighton** [comment]
Like how do you mean?
like inserting the png logo with the <img> element

**Comment by cat998** [comment]
I want to show the file icon that is dragged into the HTML page. I know that the fs module can get some information about the file, such as file size, file path, file modification date, etc., but can't get the file icon information.

**Comment by trvsapjiac** [comment]
It is very unclear what you're asking for. What does HTML have to do with this problem? Are you using Node.js (server-side script) or client-side script? How is your HTML related to Node.js?

I assume you want to do it from Node.js (I don't see how HTML is relevant here). Obtaining icon of a file is not well-defined. What do you mean by extracting icon? The icon that is shown in file explorer (I'm talking about Windows, since you haven't say which OS you're using) depends on the file type, associated programs and possibly some custom cases like media files or shortcuts (links).

In case of executable files (.exe, .msi, ...) you need to parse the file in order to find some specific sections and then obtain information about icons. If it contains an icon, then you need to extract it and possibly decode it or convert to image format you like. If the file has no icons, you can use default icon for executable files, which is stored in some system directory.

In case of associated extensions, you need to determine to which program the file is associated and then use corresponding icon of that program intended for associated files (it may differ from the icon of the program itself).

For images, you need to read the image data and generate a thumbnail. Similarly for videos. For shortcuts, you need to resolve the path and extract relevant data from the linked file (and you may also want to add little shortcut arrow icon on the resulting image in order to indicate that the file is a shortcut).

These are some general advices, but it really depends on your operating system and the environment you're running your application in. Your requirements are unclear to me. If you explain more briefly what you want, I may provide more detailed advices.

**Comment by cat998** [comment]
Thank you very much. What I want is to get the icon of the uploaded file and display it on the webpage. From your description I realized that Nodejs cannot directly get file icon. So ,for general files，I can detect the file type and prepare the corresponding default icon. for executable files (.exe, .msi, ...) I need to parse the file(with c++,... help) to get icon.

**Comment by trvsapjiac** [comment]
If you are on Windows, you can use [ExtractIconEx](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776417(v=vs.85).aspx) to obtain icon information and [LoadImageA](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-loadimagea) to extract image data from the icon. Then you can use [FFmpeg](https://www.ffmpeg.org/) to convert it to PNG or JPG format and send it as a buffer to the client-side script, which then can render it on the HTML page. For media files, you can still use FFmpeg to extract thumbnail and resize it to desired dimensions.

**Comment by cat998** [comment]
Thank you very much.
