### ISSUE TITLE
Need help on node js

### ISSUE THREAD

**Issue by chanlkcc** [nodejs/help#1373]
Dear Sir/Madam,

I would like to seek help from you.

Background, :

we ask a software developer to build an communication and collaboration app that could work in all platform (Web, Android, and IOS). He was saying that is app is a cloud-based app which park at S3 amazon. He uses tokbox service for the communication and create his own web based whiteboard collaboration in S3 amazon and uses node js.

Problem : 
In the collaboration features, we have a feature to use a pen tool that can annotate across the space of the whiteboard. Next we also wanted a feature that can partially erase the element. 

For example : 
The user draw 1 line. With this partial erase feature, I am able to erase at the middle of the line so that it becomes 2 line.
Note that, if we are annotating a document, we don’t want the original document to be erase
Therefore, this partial erase only erase the annotation , not the background

Our developer encounter difficulties to have this partial erase feature.
Any recommendation and help you can give to produce this features?

Thanks for your help

**Comment by trvsapjiac** [comment]
Your question is very abstract. It is highly unlikely that you'll get useful help here.

Since you're asking for an algorithm which is not strictly related to Node.js, I would recomment you to try the [Stack Overflow](https://stackoverflow.com/) or maybe [PPCG](https://codegolf.stackexchange.com/).

Of course, if you provide the source code of your application, I will try to help you, Otherwise, the stack overflow is probably the best option for you.

**Comment by gireeshpunathil** [comment]
closing as answered in the best possible way. As @ghost already articulated, a Node.js usage related help is something which is best addressed here, while the question here is application specific one.
