### ISSUE TITLE
Npm version error

### ISSUE THREAD

**Issue by rhovell** [nodejs/help#1382]
* **Node.js Version**: 8.1.3
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: npm

I have installed node.js and checked the version fine, but checking npm --version throws the below error. I have tried uninstalling and reinstalling node.js

$ npm --version
module.js:549
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (C:\Users\rhove\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

Any ideas please?

**Comment by zedzorander** [comment]
I don't know if this is a separate issue but I am also having problems with npm. My node version is 8.11.3 and my OS is also Windows 10. The problem I have is that any time I run any npm command, it opens up a file called `npm.js` in one of my IDE's and then the command prompt just does this:

`[main 5:00:17 PM] update#setState idle`
`[main 5:00:47 PM] update#setState checking for updates`
`[main 5:00:47 PM] update#setState idle`

In my environment variables, there was one pointing to `C:\Users\Cole\AppData\Roaming...` so I added one to `C:\Program Files\nodejs\node_modules` before it and still has the same problem. I don't think I can uninstall the old global `npm` version because I can't run any `npm` commands. Let me know if I should make a new issue for this. Thanks.

**Comment by gireeshpunathil** [comment]
ping @rhovell

**Comment by gireeshpunathil** [comment]
closing as answered
