### ISSUE TITLE
pipe inside a pipe

### ISSUE THREAD

**Issue by ramiel** [nodejs/help#1395]
* **Node.js Version**: 10.7.0
* **OS**: Ubuntu
* **Scope (install, code, runtime, meta, other?)**: runtime 
* **Module (and version) (if relevant)**: Stream

I want to pipe a stream to a stream which is the result of a pipe
In the code below transformX are Transform tream, so duplex.
I expect all the transformation to happen and instead only t2 and t3 are applied
```js
const piped = transform1.pipe(transform2);
const rs = stream.pipe(piped).pipe(transform3);
```

**Comment by addaleax** [comment]
I think this is happening because `a.pipe(b)` always returns `b`; so in your case, `piped === transform2`, and `transform1` gets lost. Can you maybe explain a bit about your use case?

That being said – If you are looking for a way to turn 2 Duplex streams into 1 Duplex stream by chaining them: I don’t think there’s a built-in primitive that lets you solve this. However, you can work around that by using something like https://www.npmjs.com/package/duplexpair (yes, this is a bit of a shameless advertisement for my own package :smile:):

```js
const DuplexPair = require('duplexpair');
 
function chainDuplexes(duplex1, duplex2) {
  const { socket1, socket2 } = new DuplexPair();
  socket2.pipe(duplex1).pipe(duplex2).pipe(socket2);
  return socket1;
}

const piped = chainDuplexes(transform1, transform2);
```

**Comment by ramiel** [comment]
Thank you for your quick response. My use case is that I want to provide a pipe operation as a block to use in other pipes. I don't think your package is good for this use case

**Comment by gireeshpunathil** [comment]
@ramiel - is this still outstanding?

**Comment by ramiel** [comment]
@gireeshpunathil yes I solved. I needed this for a library I was writing, [streamfp](https://github.com/ramiel/streamfp) and you can find the implementation in the [`pipeline`](https://github.com/ramiel/streamfp#pipeline) method

**Comment by gireeshpunathil** [comment]
thanks, I will close this out then!
