### ISSUE TITLE
When development a node add-on program, Could I create a context with v8::Context::New?

### ISSUE THREAD

**Issue by magicfish2007** [nodejs/help#140]
When development a node add-on program, Could I create a context with v8::Context::New in native? Within this Context, how could I get a global object in node global context?

**Comment by bnoordhuis** [comment]
> Could I create a context with v8::Context::New in native? 

Yes.

> how could I get a global object in node global context?

I'm not sure what you mean.  Is your question how to install a `process` object in the new context?

**Comment by lordKnighton** [comment]
👍

**Comment by magicfish2007** [comment]
@bnoordhuis In a word, how can I get  the context which is used in node::CreateEnvironment?  For that I want to install a object in this context.

**Comment by bnoordhuis** [comment]
If you call `node:CreateEnvironment()` yourself, you pass in a context explicitly.  If you're dealing with an existing environment, you don't have access (because `node::Environment` is an opaque type) unless you include `src/env.h` and `src/env-inl.h` and call `env->context()` - but note that those files are implementation details and don't fall under the API/ABI stability guarantees of `src/node.h`.

If you have access to an object from the context you're interested in, you can retrieve its context with `object->CreationContext()`.  If code from the context ends up calling one of your C++ callbacks, you can retrieve it with `args.GetIsolate()->GetCallingContext()`, although that's slated to be removed.

**Comment by magicfish2007** [comment]
Actually,  there are some situations that programmer have to get the node context with an existing environment, and programmer didn't want to include src/env.h. Programmer  want to make sure the context is the same one with node. Is there any necessary for NodeJS to expose an api in node.h? Just as what Environment::context() do.

**Comment by bnoordhuis** [comment]
It wouldn't be hard to add a public function but when exactly would that come up?  You can file an issue or a pull request but you'll be asked to come up with plausible use cases.

**Comment by magicfish2007** [comment]
Well, I agree with you. Thanks for your explain in details!
