### ISSUE TITLE
 Error during program execution.

### ISSUE THREAD

**Issue by abhishakskilrock** [nodejs/help#1406]
By doing debugging it seems that it runs last line(console.log("purchase_payload2", ticket);) initially and execute functions later. can anyone help me to resolve this issue.

```js
var axios = require("axios");
function sendDataWithHeaders(url, payload, cb) {
  console.log(url);
  console.log(payload);
  axios({
    method: "POST",
    url: url,
    data: payload,
    headers: {'Content-Type':'application/json','username': 'xxxxxxxxxxxxxxxx', 'password': 'xxxxxxxx'}
    })
    .then(response => {
      cb(response);
      console.log("asd",response);
    })
    .catch(error => {
      console.error(error);
      cb(error);
    }); 
}
function ticket_purchase(purchase_payload) {
  sendDataWithHeaders(
    "http://192.ip.address",
    purchase_payload,
    function(body) {
      console.log("Purchase ticket resp body", body);
      return body;
      // use body here; ******
    }
  );
}
var purchase_payload = {
 _some json data_
};
let ticket = ticket_purchase(purchase_payload);
console.log("purchase_payload2", ticket);
```

I am attaching my  debugging result here:

> http://192.ip. address2
> a.js:5
> Object {merchantCode: "xxxx", noOfDraws: 1, noOfPanel: "3", gameCode: "xxxxx", …}
> a.js:6
> purchase_payload2 undefined
> a.js:71
> Purchase ticket resp body
> a.js:27
> Object {status: 200, statusText: "OK", headers: Object, config: Object, request: ClientRequest, …}
> a.js:27
> asd
> a.js:15
> Object {status: 200, statusText: "OK", headers: Object, config: Object, request: ClientRequest, …}
> a.js:15

**Comment by ankur-anand** [comment]
```
axios({
    method: "POST",
    url: url,
    data: payload,
    headers: {'Content-Type':'application/json','username': 'xxxxxxxxxxxxxxxx', 'password': 'xxxxxxxx'}
    })
    .then(response => {
      cb(response);
      console.log("asd",response);
    })
    .catch(error => {
      console.error(error);
      cb(error);
    }); 
```
Is a promise which first gets resolved and then calls the callback you have passed. This is no error rather the desired result :)

I would suggest learning more about callback and promise in JavaScript, and asychronous nature of the JavaScript.

**Comment by abhishakskilrock** [comment]
@ankur-anand  Can you give me some suggestion what is correct code?

**Comment by gireeshpunathil** [comment]
code looks ok, except your expectation on the `console.log` to be printed first. As `ticket_purchase` invokes asynchronous code, the control flow will immediately return back to the point where the call was made, and the associated callback methods called at later point in time, when the asynchronous work is completed.

If you are wanting to do the console.log after the `ticket_purchase` is completed, you should place it along with `console.log("Purchase ticket resp body", body);` because that is where the completion handler for `ticket_purchase` executes.

**Comment by abhishakskilrock** [comment]
@gireeshpunathil I want to use value of ticket somewhere else but it is showing undefined it means ticket variable has no value. How can I resolve this?

**Comment by gireeshpunathil** [comment]
It is not a good idea to return values from a callback. It is not a good idea to store return values from asynchronous calls either.

this is because, callbacks are not called from the calling context. Look at this example:

```js
foo() {
  bar(a, b, function cb()  {
    // some code
  })
}
```

Here this is how the call flows:
`foo() -> bar() -> cb()`

if cb() returns a value, it does not reach foo or its caller. Instead it reaches bar(). And in most cases, caller of callbacks neither care about the return values, nor cannot meaningfully use it, as they are not in the context of the callback and its actual beneficiary.

**Comment by gireeshpunathil** [comment]
ping @abhishakskilrock - does this help you?

**Comment by abhishakskilrock** [comment]
Yeah It helped me.
