### ISSUE TITLE
Help with basics NodeJS question

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#1413]
Dear all, I have some basic questions on NodeJS:
- first of all, I have this piece of code:
```js
          mongo.connect(url, async (err, client) => {

              var ErrorObject = {};
              ErrorObject.test = 'BLABAL2A:A';

              var db = client.db('nodeads');
              const bodiesTest = db.collection("testLoadError");
              bodiesTest.insertOne( ErrorObject , function(err, res){
                  assert.equal(null,err);
              });
          })
```
Somehow, if I don't define ErrorObject within the .insertOne function, it doesnt get inserted into my Mongo db... How can this be? I mean the mongo.connect method is async, and I believe that the insertOne method inside of mongo.connect is also async. But cant I rely on the fact that let ErrorObject is defined lexically **before** the invocation of .insertOne, and is therefore available **within** .insertOne? This is very confusing to me. 

Might anybody have recommendations as to which courses/articles I should read/do in order to fully understand async/await stuff?

1 more question: I am using mongo to store crawled data. The collected data consists of objects that each have about 6 strings maximum (each string max 80 characters) . I want to store about 13.000 objects per day as a maximum, most of which get deleted after two days. Currently I am creating 1 single records for each object in my db. Is this the right choice or can I just store them all in 1 record?

Greets and thanks

**Comment by bounc3-paradise-on-e** [comment]
After reading your question several times, it's not clear to me what you're asking.

---

> If I don't define ErrorObject within the .insertOne function, it doesnt get inserted into my Mongo db

What do you mean by "defining an object *within* a function"? The `insertOne` is a method of `bodiesTest`'s prototype. It is mongodb's native function and you can't "define an object" inside it. In your code, you are passing a reference to the `ErrorObject` as the first argument to the `insertOne` method.

If that is what you mean by defining an object *within* a function `insertOne`, then why it surprises you if it doesn't work when you don't pass the object? How can it insert something if you don't tell it what to insert? Or maybe I don't understand what you're aksing...

> I mean the mongo.connect method is async

First of all, what is the `mongo` actually? I suppose it is the `MongoClient` constructor, but I can't tell for sure by looking at your code.

In case it is `MongoClient`, the static method `connect` is asynchronous in the sense that it takes a callback as an argument, but it is not *async* in the case that it returns a `Promise`. What do you mean by "mongo.connect method is *async*"? Also, what is the reason for defining the callback as an *async* function, while you're not awaiting anything in there?

> I believe that the insertOne method inside of mongo.connect is also async

Just to make it clear, `insertOne` is not inside the `mongo.connect` function. It syntactically appear in your callback function of the `connect` method, but it's semantically unrelated to the `connect` method. Also, similarly to `connect`, method `insertOne` is not *async* in the sense of *async* functions, but it is asynchronous, since it takes a callback as an argument.

> Cant I rely on the fact that let ErrorObject is defined lexically before the invocation of .insertOne, and is therefore available within .insertOne?

It's really not clear to me what you want to ask. This is how I understood your question: *"Since the object `ErrorObject` is defined before the call of the `insertOne` method, is it guaranteed that we can pass it as an argument to that method, without risking of getting a ReferenceError?"* If that is your question, then the answer is: yes. Function arguments are evaluated synchronously, independently of the function type you're calling. It means, if you call an asynchronous function with some arguments, they will be evaluated synchronously in the scope where the call is performed. In this particular case, `ErrorObject` is defined before the call of `insertOne` and therefore is available as the function argument.

> Might anybody have recommendations as to which courses/articles I should read/do in order to fully understand async/await stuff?

In my opinion, the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) article is enough to understand any JavaScript concept (including async function) to an advanced level. If you want to to go further, you can read the ES specification, but it is not recommended for people that are trying to *learn* a concept. Therefore, the MDN article provided (and similar linked articles from there) should be enough.

But I can't see what *async* functions have to do with this particular piece of code you've provided. None of the mongodb functions/methods are *async*. They are asynchronous only because some of them take a callback as an argument, but none of them you've posted here return a Promise.

---

Your second question is more related to the mongodb API than to the JavaScript syntax or abstract concepts. The answer can probably be found in their [docs](https://docs.mongodb.com/).

**Comment by WAINGOR** [comment]
First of all thank you so much for taking your time in elaborating. Im sorry that my question was unclear. 
Meanwhile I have solved my issue also thanks to your help, and your reasoning was quite clear so many thanks. By the way, what I meant what defining an object within the callback of .connect... We do agree that its possible to define an object within a callback function right? Greets :)

**Comment by bounc3-paradise-on-e** [comment]
> We do agree that its possible to define an object within a callback function right?

Yes. Callback functions, like all other functions, may have local variables in their scopes.

**Comment by gireeshpunathil** [comment]
closing as answered, cheers.
