### ISSUE TITLE
Allow for control chars with util.inspect or console.log

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1414]
I am on Node.js version 10+

https://stackoverflow.com/questions/51689540/allow-for-control-chars-with-util-inspect-console-log

The above SO question explains it pretty well. Basically what I am looking to do is:

```js
const chalk = require('chalk');
console.log({message: `Here is the highlighted message ${chalk.bold('foo bar baz')}`});
```

the problem is that looks like this:

```
{ message:
   'Here is the highlighted message \u001b[1mfoo bar baz\u001b[22m' }
```

**Comment by devsnek** [comment]
that's the correct behaviour. the escape codes are part of the string content, not the stylistic output of util.inspect.

**Comment by bounc3-paradise-on-e** [comment]
@devsnek 

I hope you're aware this is the *help* repo and not the main repo. The user is asking for help rather than submitting an issue report or a feature request.

@ORESoftware 

The answer from user *estus* on your SO question doesn't work for all cases. It breaks if the string contains new lines (which is true in your case) and it doesn't work for some special unicode escape sequences. For example, it breaks with the following object:

```js
{[Symbol('\\"\\`')]: 1}
```

One solution to your problem is to override `console.log` (and probably `console.info` and similar functions too) like this:

```js
const util = require('util');

console.log = (log =>
  (...args) => log(
    args.length === 0 && typeof args[0] === 'string' ?
      args[0] :
      Function(`return\`${
        args.map(arg => util.inspect(arg)).join(' ')
          .replace(/[`\$\\]/g, a => `\\${a}`)
      }\``)()
  )
)(console.log);
```

Then you can log your object properly:

```js
var obj = {
  message: 'Here is the highlighted message \u001b[1mfoo bar baz\u001b[22m',
};

console.log(obj);
```

![](https://user-images.githubusercontent.com/41899356/43683417-8bd8cb4e-988b-11e8-9d2e-aba57169d8da.png)

Hope it helps.
