### ISSUE TITLE
TLS_EMPTY_RENEGOTIATION_INFO_SCSV Cipher

### ISSUE THREAD

**Issue by cyphercodes** [nodejs/help#1443]
* **Node.js Version**:  v9.9.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: request@2.81.0

I am trying to send a request using specific ciphers.

However, I think NodeJS adds `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` cipher automatically at the end of the ciphers list to protect itself from POODLE attack.

I have a requirement where I have to send the request without it, is it possible somehow in the options / request agentOptions / or any other setting I can tweak? 

Or is the only way adjusting & recompiling NodeJS? 

Please advise!

**Comment by gireeshpunathil** [comment]
ping @nodejs/crypto

**Comment by indutny** [comment]
I'm afraid that there is no control over it. `SSL_set_mode` is not exposed in JS APIs. Sorry.

**Comment by sam-github** [comment]
In node 11.x and 12.x, the openssl.cnf is read by default, I suggest you investigate where that file is under Windows (sorry, I don't know), and whether any configuration you can do in it is capable of controlling this behaviour. You'd have to move from node 9.x, but since that version is no longer supported (it won't get security updates, for example), you might want to do that anyhow.

Out of curiousity, why is it so important to remove this cipher?

**Comment by gireeshpunathil** [comment]
ping @cyphercodes

**Comment by gireeshpunathil** [comment]
inactive, closing. pls reopen if there is anything outstanding
