### ISSUE TITLE
need function, which can keep the image on the original size.

### ISSUE THREAD

**Issue by Schindar** [nodejs/help#1451]
is there any trick, so that i can keep the images on the original size or at least control the width and height of the images before sending into the Microsoft bot-framework? my problem is that when the user tries to send an image through bot-Framework, the size of his image is changed automatically . the pixels also is combined. so i need any function with Node/java script, which can solve my problem.

**Comment by djmangoo** [comment]
So, you keep repeatedly asking questions about your closed-source bot framework and expecting from Node.js developers and other volunteering people to take their free time and help you develop something that nobody except you will ever be able to use. Aren't these expectations a bit unfair?

Your questions are unrelated to Node.js API/CLI/REPL. They are more related to Microsoft Bot Framework, which is neither open-source, nor free. In order to answer your questions, one must install the framework and do the testing locally, which is impossible without purchasing the license.

Why don't you try to move your questions to [Stack Overflow](https://stackoverflow.com/)? They even have a [tag for this framework](https://stackoverflow.com/questions/tagged/botframework?page=265&sort=votes&pagesize=15), they are very experienced with it, fast on answering and objective in their voting decisions. That is also the place where you can expect your questions to be answered faster than anywhere else.
