### ISSUE TITLE
How do I get the module's imported parent from an ESM module?

### ISSUE THREAD

**Issue by isiahmeadows** [nodejs/help#1476]
[In the docs](https://nodejs.org/api/esm.html), it makes no mention of the parent URL. I would like this, for the sake of resolving a module name from a query parameter. (It would make my module much easier to use.) Is it possible to retrieve the parent URL from the child, and if so, how?

Also, while I'm at it, how are URLs tested for equivalence WRT caching? Are hashes included, or only queries?

**Comment by devsnek** [comment]
> Is it possible to retrieve the parent URL from the child, and if so, how?

This doesn't really make sense, a module can have multiple parents.

> how are URLs tested for equivalence WRT caching?

At the moment we use the full resolved URL, but there's no guarantee that things will stay this way. /cc @bmeck on that

**Comment by isiahmeadows** [comment]
> This doesn't really make sense, a module can have multiple parents.

In CommonJS modules, `module.parent` is the first parent to request the module. I'd like to maybe do similar for the module.

Maybe, a better question is how to write an uncached ESM module with that constraint. (May require an es-discuss proposal instead...)

**Comment by bmeck** [comment]
@isiahmeadows both in browsers and in node's current implementation caches are done including fragments. However, node uses the fully resolved Response URL in browser terms. Browsers use the Request URL, so there is some mismatch. https://github.com/nodejs/modules/issues/62 has some details on differences.

> In CommonJS modules, module.parent is the first parent to request the module. I'd like to maybe do similar for the module.

In CJS there is the possibility of reliable parents because evaluation is done inline.

In ESM you can get into cases where the parent differs based upon timing:

```mjs
// main.mjs
import('a');
import('b');
```

```mjs
// a
import 'c';
```

```mjs
// b
import 'c';
```

Could have either `b` or `a` evaluate first depending on speed of loading the files.

**Comment by isiahmeadows** [comment]
This answers my question well enough.
