### ISSUE TITLE
How to use C# dll with nodejs

### ISSUE THREAD

**Issue by natatatata** [nodejs/help#1501]
Can I include a C# dll with nodejs and consume its classes/functions? If yes, is there any existing samples or guides with this? Thanks!

**Comment by addaleax** [comment]
I don’t know about any standard solutions, but https://stackoverflow.com/questions/778590/calling-c-sharp-code-from-c has some ideas about how to call C# from C++ in general; and since you can write [C++ addons](https://github.com/nodejs/node-addon-api) for Node.js, it’s definitely possible to write glue code that would do this.

**Comment by LiamKarlMitchell** [comment]
@natatatata Could this be of use?
https://github.com/tjanczuk/edge#how-to-specify-additional-clr-assembly-references-in-c-code

**Comment by gireeshpunathil** [comment]
ping @natatatata - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing
