### ISSUE TITLE
Sqlite3 module issue

### ISSUE THREAD

**Issue by XDimensioN0** [nodejs/help#1525]
* **Node.js Version**: v8.11.1
* **OS**: Windows 7
* **Scope (install, code, runtime, meta, other?)**: MSYS2
* **Module (and version) (if relevant)**: sqlite3 v4.0.2

Hi

When I include the sqlite3 in my code cause node to terminate without any error.
I tried also this code in node interactive mode:

```js
const db = require('sqlite3').verbose();
```
Did somebody encounter the same issue. How can I resolve this.
Thanks in advance

**Comment by lordKnighton** [comment]
@XDimensioN0 Could you show more code?
------------------
most other SQLite code has something like:
```js
const sqlite3 = require('sqlite3').verbose();
let db = new sqlite3.Database('users.db');
```

or something like: 

```js
const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('path/to/mydb.sqlite');
 ```

I know that a variable name is just that, in your code you go straight for the `db variable` instead of creating an instance of sqlite3 then composing a `db variable` of a sqlite3 varible. which is fine if you have another variable holding the Database connect code `example: sqlite3.Database(':memory:');`. Is this by intention? Or did you fix your issue already

**Comment by gireeshpunathil** [comment]
ping @XDimensioN0

**Comment by gireeshpunathil** [comment]
inactive, closing
