### ISSUE TITLE
--max_old_space_size not affecting

### ISSUE THREAD

**Issue by vowave** [nodejs/help#1548]
Hello,
I'm trying to increase max old space size but its not working even when I tried to decrease the memory size so my physical memory is not a problem my server has 48 GB ram.

```
[root@server waveform]# node --max_old_space_size=19191818 memory.js
Total heap size (bytes) 20463838747424, (GB ~19058.43)
[root@server waveform]# node memory.js
Total heap size (bytes) 1520884512, (GB ~1.42)
[root@server waveform]# node --max_old_space_size=128 memory.js
Total heap size (bytes) 164551456, (GB ~0.15)
[root@server waveform]# node memory.js
Total heap size (bytes) 1520884512, (GB ~1.42)
```

I searched a lot and couldn't find any solutions for this.

<sub>_(edited by @vsemozhetbyt: changed backticks for the code block)_</sub>

**Comment by gireeshpunathil** [comment]
please share your `memory.js`

**Comment by yathamravali** [comment]
@vowave 
```
$ node --v8-options | grep max-old-space-size
  --max-old-space-size (max size of the old space (in Mbytes))
```
In the first command u have given 19191818(Mbytes) means 20124079751168 bytes. In the output it is 20463838747424 bytes, the extra bytes are due to native memory consumption(required for VM's).

Similarly, 128(Mbytes) means 134217728 bytes. In the output it is 1520884512 bytes where extra bytes are due to native memory consumption.

The output that are generated for u are correct.

If u think that I didn't addressed your issue please let me know and share your code(memory.js).

**Comment by gireeshpunathil** [comment]
ping @vowave

**Comment by gireeshpunathil** [comment]
answered, closing
