### ISSUE TITLE
Node.js fails to install/uninstall - "is not a valid short file name"

### ISSUE THREAD

**Issue by smaunsell** [nodejs/help#1553]
* **8.11.3 64-bit**:
* **Windows 10 64-bit 15063.674**:
* **Installer**:
* **Module (and version) (if relevant)**:

I'm a network admin. One of our web developers has reported an issue trying to install Node.js. Or rather uninstall it. Somehow they managed to get it installed but I don't know how as when I try to install it on my PC I get the same error and it won't install. They get the same error when trying to uninstall.

The error displayed is "Win10Appdata is not a valid short file name". Win10Appdata is the name of a network location that is used for AppData redirection which is done by Group Policy. The PCs are on a Windows 2012R2 domain and the user accounts are also domain users. The %AppData% variable is redirected using Group Policy so that various things are stored in a central location and allow users to move PCs and retain that information. The full path to the redirection of the Windows %AppData% variable is \\mydomain.com\Appdata\Win10Appdata\{username}\AppData\

All other applications and features within Windows work perfectly fine. Node.js is the only one that has presented any issue.

Usually we use Microsoft's SCCM to deploy software but these users got local administrator access so they could install what they want :( I just tested deploying with SCCM and it successfully installed (using the SYSTEM account_ but I am now unable to uninstall it and get the same error.

Why doesn't it like the AppData redirection? And how can this be resolved?

**Comment by smaunsell** [comment]
UPDATE: user is logged in to PC as a non-admin account, when they run a .exe it prompts for their admin credentials but the MSI doesn't do that and it fails. Installing via SCCM works but when uninstalling from Add/Remove Programs it doesn't prompt for admin credentials like ALL other applications do and this is why they can't uninstall. There appears to be an issue with the MSI and the way it works with Windows to not prompt for admin credentials. In our case we have a work around as the installation via SCCM as well as the uninstallation via SCCM both work.

**Comment by gireeshpunathil** [comment]
@smaunsell - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to reopen if this is still outstanding

**Comment by DJAG95** [comment]
in my case, the error comes because a secondary hard drive broke (I use windows at work) and node.js was installed on it

since you can't access the program's path, you can't install or uninstall the program, making it inaccessible, it's frustrating

![Captura](https://user-images.githubusercontent.com/22800159/86001170-ce335300-ba0e-11ea-8253-171b287e35ad.PNG)

**Comment by johankotze72** [comment]
I had this issue trying to uninstall a program, which was installed on an external drive, and changed the drive letter since the installation. The solution for me was to change the drive letter back to what it was before (using the Computer Management software) and then uninstall it. 

Another way might be to open the registry and find and change the "InstallPath" variable for the software:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\

**Comment by water007melon** [comment]
> 

https://github.com/nodejs/help/issues/3122#issuecomment-1034619200
