### ISSUE TITLE
Caught exception: Error: read ECONNRESET

### ISSUE THREAD

**Issue by zdying** [nodejs/help#1564]
* **Node.js Version**: v10.9.0
* **OS**: MacOS
* **Scope**: runtime

hi, i have an Node.js app that will use http.request and https.request. some times it print some log:
```
Caught exception:  Error: read ECONNRESET
    at TCP.onread (net.js:660:25)
```

but no detail error stack printed. so i don't know where the error has been emitted and which domain request failed.

I want to catch the error myself and get the full error.stack , what can i do?

**Comment by gireeshpunathil** [comment]
have you installed an error handler on the request object? such as:
```js
request.on('error', (e) => {
   console.log(e)
})
```
and does it improve the situation any better?

**Comment by gireeshpunathil** [comment]
ping @zdying

**Comment by zdying** [comment]
Yes, i have error handler. my code is:

```javascript
proxy.on('error', function (e) {
      if (e.code === 'ENOTFOUND') {
        res.statusCode = 404;
      } else {
        res.statusCode = 500;
      }
      res.end(e.stack);
      next();
    });
```

I think if not add `error` handler, it will throw `UncaughtException`, NOT `Caught exception`.

**Comment by gireeshpunathil** [comment]
@zdying - I did not follow your last statement, can you please clarify?

**Comment by gireeshpunathil** [comment]
ping @zdying

**Comment by zdying** [comment]
I mean that I Have error handler. I think If no error handler provided, it SHOULD tell me I have an uncaught error, and should NOT tell me it’s a caught error.

I don’t know what does the “caught exception” mean

**Comment by gireeshpunathil** [comment]
probably related: https://github.com/nodejs/node/issues/14102

@zdying - without a program to reproduce the issue it is really difficult to pin point the root cause. At high level, the module that issues the request (plain tcp socket / http request api / request module or any other middleware component) should install an error handler, which gets invoked on a low level event such as network read error. In your case, I would recommend:
 - figure out which object is issuing the network request
 - install an error handler and see if it catches the error
 - if not, identify the network primitive that the module / object is abstracting
 - install an error handler for that and see if it catches at that point
 - iterate this approach until you get the callback or find the root cause

**Comment by zdying** [comment]
@gireeshpunathil OK, i will try it. thanks.
