### ISSUE TITLE
Can I use assert on production env?

### ISSUE THREAD

**Issue by chs97** [nodejs/help#1574]
such as I use assert check type.
 ```
assert.strictEqual(typeof pass, 'string', new TypeError('pass should be a string'))
```

**Comment by gireeshpunathil** [comment]
It actually depends on your scenario. If the business logic cannot meaningfully proceed when `pass` is not a string, then assert is the best thing to do so that the error is transmitted and consumed with clarity.

On the other hand, if your logic is part of a webapp, and if the encompassing block / function is part of a client-service transaction, then I would return an error which then is translated into an error code to the client, hiding the low level details.

Hope this helps.

**Comment by gireeshpunathil** [comment]
answered, closing
