### ISSUE TITLE
Issue to install Node.js V11 on AIX 7.1

### ISSUE THREAD

**Issue by LeoMXIBM** [nodejs/help#1595]
Issues to run Node.JS on AIX 7.1

* **Node.js Version**: node-v11.0.0-aix-ppc64
* **OS**: AIX 7100-05-02-1810
* **Scope (install, code, runtime, meta, other?)**: Install Node.JS
* **Module (and version) (if relevant)**: N/A

Hello, 

I'm new in this Node.js world and I try to install Node.JS on one of AIX server.
our server is an AIX 7.1 and I try to install node J.S V11.

I Download the package from https://nodejs.org/en/download/current/   (node-v11.0.0-aix-ppc64.tar.gz)
after dad I uncompressed the content on /opt/node/node-v11.0.0-aix-ppc64,

Follow the instructions here: https://www.ibm.com/developerworks/community/blogs/55382396-b19a-4819-8618-6522a02f2d99/entry/run_nodered_on_aix?lang=en_us

but when I try to check the version: node --version 

I have this error:

./node --version
exec(): 0509-036 Cannot load program ./node because of the following errors:
        0509-150   Dependent module libstdc++.a(libstdc++.so.6) could not be loaded.
        0509-103   The module has an invalid magic number.

Can you help me? please.
Thank you

**Comment by gireeshpunathil** [comment]
what is the `GLIBC` version in your system? `rpm -qa | grep -i glibc`

**Comment by LeoMXIBM** [comment]
Hi, 

I don't have output for that command, What version I need to install and where I can download?

**Comment by shellberg** [comment]
I'm afraid the instructions you're following from Node-RED are too old (2015).  They relate to use of Node v0.10, whereas, you are trying to install the latest greatest Node v11!  Back then, you could use the  glibc levels that were distributed with AIX 7.1 base; however, the rate of change with the v8 component means that you have to add later levels of GCC and GNU C++ support to your AIX 7.1 environment to meet the current compilation dependency levels.  And, it can be a bit tricky to get them to co-exist!

@gireeshpunathil was trying to determine the last level of GLIBC support you might have added in your environment.  Almost all the sources of GNU tooling for AIX add this in the `/opt/freeware/lib/gcc/...` directory tree.  Even getting the RPM repository data synchronised between base AIX packages and any additions can prove unreliable.  So, perhaps you could tell us if you have any contents at:

`$ ls /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/`

As for where to download, you need to try and keep consistent in your sources of freeware packages (because of the dependence they typically place on the GNU toolchain) to maintain a coherent set of packages.  We should determine if you have any such additions first!  (Do you have any content in `/opt/freeware/`?) Then you need to choose a good complrehensive source such as the [AIX Toolbox](https://www.ibm.com/developerworks/aix/library/aix-toolbox/index.html), or [Bull Freeware](http://www.bullfreeware.com/).  Once chosen, you need to commit to that choice and not try and mix-n-match packages, IMHO.  Otherwise, a wide variety of problems can present...

**Comment by LeoMXIBM** [comment]
Hi, 

Yes I have content in my. /opt/freeware:

ls /opt/freeware
64/                bin/               etc/               info/              lib64/             man/               sbin/              src/
Director_instNLS/  doc/               include/           lib/               libexec/           packages/          share/             var/
also, for the /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/

I have this output:

ls /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/
4.8.2/  4.9.4/

**Comment by LeoMXIBM** [comment]
Hi, 

so, @shellberg what level of GLIBC I need to install?

As I recall, AIX Toolbox was used for other libraries.

**Comment by LeoMXIBM** [comment]
hi @gireeshpunathil 

I tried, but the same result:

**pwd**
/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.9.4
**ls -ltr libstdc++.a**
-rwxr-xr-x    1 root     system     11562081 Aug 04 2016  libstdc++.a*
**ls -ltr libstdc++.so.6**
ls: 0653-341 The file libstdc++.so.6 does not exist.

**export LIBPATH=$LIBPATH:/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.9.4**

**cd /opt/node/node-v11.0.0-aix-ppc64/bin**

**pwd**
/opt/node/node-v11.0.0-aix-ppc64/bin

**./node --version**
exec(): 0509-036 Cannot load program ./node because of the following errors:
        0509-150   Dependent module /opt/freeware/lib/libstdc++.a(libstdc++.so.6) could not be loaded.
        0509-103   The module has an invalid magic number.
**echo $LIBPATH**
/opt/freeware/lib:/opt/freeware/lib64:/usr/lib:/usr/lib64:.:/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/4.9.4

Do I need to install another GLIBC version?

**Comment by gireeshpunathil** [comment]
apologies; did not give enough attention last time - node 11 needs gcc 6.3. Once that is installed, you can set the LIBPATH appropriately based on the installation path.

**Comment by shellberg** [comment]
@LeoMXIBM : Sorry, @gireeshpunathil and myself are in different timezones... possibly from you too!  So, you have GCC v4.8.2 and v4.9.4 GCC (and associated support?) installed, but as Gireesh mentioned, we will need a minimum of GCC v6.3 installed.  You should install both GCC and C++ support at this compatible level...  In terms of RPMs, you need this set (compatible with v6.33):

```bash
gcc-6.3.3
gcc-c++-6.3.3
gettext
gmp
info
libgcc
libiconv
libmpc
libstdc++-6.3.3
libstdc++-devel-6.3.3
mpfr
zlib
```
From memory, this set of RPMs (in the same directory) will install with `rpm -Uvh *.rpm`, with the exception of the latest `gettext` package; that almost always needs to be installed with `-nodeps` (that should occur first).

AIX Toolbox can be a source of packages, including the compiler toolchains.  You should not treat it as only a source of individual libraries, because its a bad idea to try and treat this as _a la carte_ (as I mentioned) and attempt to mix-n-match content.
