### ISSUE TITLE
scrypt password verify

### ISSUE THREAD

**Issue by ddwwcruz** [nodejs/help#1626]
* **Node.js Version**: 10.13.0
* **OS**: Ubuntu 16.04

The document outlines how to use crypto's scrypt to create hashed passwords. How do we verify these passwords? PHP has password_verify for example. How to recreate this in Node?

**Comment by Hakerh400** [comment]
Something like this?

```js
const crypto = require('crypto');
const realPassword = 'Pa$$w0rd';
const salt = Buffer.from(Array(512).fill().map(() => Math.random() * 256));
const key = crypto.scryptSync(realPassword, salt, 64);

function verifyPassword(password){
  return crypto.scryptSync(password, salt, 64).equals(key);
}
```

**Comment by ddwwcruz** [comment]
does that mean that if i change the cost and block size the derived key would be different?

**Comment by Hakerh400** [comment]
Yes.

**Comment by gireeshpunathil** [comment]
answered, closing

**Comment by sergioadorna** [comment]
I think the way @hackerh400 suggested to verify a derived key is not totally correct, at least is a misleading example. The crypto.scrypt call returns a string formated per the standard scrypt specification that contains the salt used to generate the hash https://github.com/Tarsnap/scrypt/blob/master/FORMAT

To verify a derived hash you don't need to explicitly declare the salt used to generate the hash, as the hash already contains the salt. 

From the previous example someone could think the salt needs to be stored together with the key to have it available for verification, but the thing is you can extract the salt from a derived key.

To those familiar with JWT the signature is contained in the token, in this case the salt is contained in the key string.

**Comment by ddwwcruz** [comment]
@sergioadorna what's your suggestion?

**Comment by sergioadorna** [comment]
When the hash is created it contains the salt and the params used to generate the hash. So a better example would illustrate the process of extracting those from the generated hash instead of reusing the variables used for hashing.

This package verify function is a better example on how to use crypto.scrypt to verify hashes: https://github.com/chrisveness/scrypt-kdf/blob/master/scrypt.js#L125

Here is how the information of the params and the salt is contained in the generated hash:
format https://github.com/Tarsnap/scrypt/blob/master/FORMAT

**Comment by alanhamlett** [comment]
Use [crypto.timingSafeEqual](https://nodejs.org/api/crypto.html#cryptotimingsafeequala-b) instead. [KeyObject.equals](https://nodejs.org/api/crypto.html#keyobjectequalsotherkeyobject) isn't constant time.
