### ISSUE TITLE
"Segmentation fault (core dumped)" ERROR

### ISSUE THREAD

**Issue by carloverhamme** [nodejs/help#1636]
So, every time I try to run my node.js app (express), I keep getting this error:
"Segmentation fault (core dumped)".
And then It creates a file to.

How can I fix this?

**Comment by contacreast** [comment]
Please share all relevant code.

**Comment by carloverhamme** [comment]
I know what the problem is, it is with "enmap" ( a npm module database ). Now need to know what the problem is with enmap!

**Comment by gireeshpunathil** [comment]
ping @carloverhamme - is this still an issue?

**Comment by tniessen** [comment]
This sounds like a problem with a third-party package. If the problem persists and is assumed to be a problem within Node.js and not within a third-party package, we would consider it a bug. In that case, please post a detailed issue in the [nodejs/node repository](https://github.com/nodejs/node) providing information as described in the issue template.

**Comment by trecktom** [comment]
it happened to me , my code simply was processing an array of 7 millions elements
Each Element is an 10 length array ...
At First It Said `Javascript heap out of memory` So I Used => `--max-old-space-size=4096`
Then This `core dumped` Error Happened so ...
i reduced the array to 70 element ( each element is 10 length array ) Guess what ... !
IT WORKED without any Errors or Exits For 3 Hours !!!
so I Think that's some kind of overloading ? i really don't know
my solution was to optimize my code and upgrading my RAM and Processor

**Comment by SamuelHenry367** [comment]
Due to conflict of both npm and nodejs
so remove nodejs by below commands, (Don't worry it does not affect anything badly)

sudo apt-get remove nodejs
sudo apt autoremove

This worked for me

**Comment by KingLiLi** [comment]
I also encountered this problem. However, it is through libraries such as Koffi or FFI-NAPI that third-party SO files are called.
When executing certain functions. Low version nodes, such as versions 12-14, can execute correctly. Any higher version will have a segmentation fault. This is very troubling

**Comment by renown93** [comment]
If anyone is still struggling with this — I feel you. It’s a super vague error and it took me days to figure out.

**My stack: Node.js + PrismaORM + PostgreSQL.**

For me, the issue started randomly with segmentation fault (core dumped) errors once a week. It wasn’t too annoying at first, so I ignored it.

But later, while integrating with a new client, it started happening constantly — always triggered by one specific function call, which was sending audit logs to the database.

The problem:

I was passing a JavaScript object directly into a PostgreSQL JSON field using Prisma. Prisma normally handles parsing automatically, but depending on the object’s content, it would throw this crazy error.

I still don’t know exactly why — maybe a Prisma bug, maybe Postgres not liking some structure.

**The fix:**

Instead of passing a JS object, I now manually stringify the object before sending it to the database. Since doing that, the problem completely disappeared.

Hope this helps someone!
