### ISSUE TITLE
Puppeteer mocha. Timeout error occuring. 

### ISSUE THREAD

**Issue by adrianmcg85** [nodejs/help#1642]
Getting issues with a timeout error when running puppeteer with a mocha framework.

* **Node.js Version**: 8.11.1
* **OS**:Windows
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: 
    "i": "^0.3.6",
    "mocha": "^5.2.0",
    "node": "^8.7.0",
    "npm": "^6.4.1",
    "puppeteer": "^1.10.0"

```js
require('./bootstrap.js')
const puppeteer = require('puppeteer')

describe('sample test', async () => {
  before(async () => {
    page = await browser.newPage()
  })
  after(async () => {
     await page.close()
  })
  it('a test1',async  () => {
    await page.goto('https://www.bbc.co.uk')
      await  console.log('test')
  })
})
```

**Comment by gireeshpunathil** [comment]
@adrianmcg85 - is this still an issue?

I stripped off all the modules and asnc semantics from the picture, and wrote a simple program to fetch the page (because the intent of the code is to actually get the page), and got this - 

#cat 1642.js 
```js
var h = require('https')
h.get('https://www.bbc.co.uk', (r) => {
  let count = 0
  r.on('data', (d) => { count +=d.length })
  r.on('end', () => { console.log(`got ${count} bytes.`)})
})
```
#curl -s https://www.bbc.co.uk | wc -c
  321708
#node 1642.js
got 321729 bytes.
#

So basically there is no issue with the base API, I am not sure what are the logic implemented in `bootstrap` and `puppetteer`. May be worthwhile to raise this on those project areas?

**Comment by gireeshpunathil** [comment]
ping @adrianmcg85

**Comment by gireeshpunathil** [comment]
inactive, closing
