### ISSUE TITLE
crypto.createDecipheriv won't decrypt my old keys

### ISSUE THREAD

**Issue by writemonkey** [nodejs/help#1673]
Hi,

In the past I was creating license keys for my application using code below:

~~~javascript
function cr(string, key) {
	var c = crypto.createCipher('aes-256-ctr', key);
	var cr = c.update(string, 'utf8', 'hex');
	cr += c.final('hex');
	return cr;
}
~~~

and for decryption:

~~~javascript
function dcr(string, key) {
	var d = crypto.createDecipher('aes-256-ctr', key);
	var de = d.update(string, 'hex', 'utf8');
	de += d.final('utf8');
	return de;
}
~~~

Now that `crypto.createCipher` and `crypto.createDecipher` are deprecated and won't work with newer versions of node, I need to update my code with: `crypto.createDecipheriv` and `crypto.createCipheriv`.

But: with these new methods initialization vector (iv) parameter is mandatory:

`crypto.createCipheriv(algorithm, key, iv[, options])`

Since my keys (that are already in the wild distributed to users) were created with `crypto.createCipher` without iv, can I decrypt those keys using new methods. If not, is there a way to decrypt those keys without `crypto.createDecipheriv` (some other way)?

BTW: I am aware that old method without iv was not secure, but it was good enough for my needs.

Thanks,
Iztok

**Comment by gireeshpunathil** [comment]
ping @nodejs/crypto

**Comment by sam-github** [comment]
Try a zero-length Buffer for the IV.

**Comment by tniessen** [comment]
> Try a zero-length Buffer for the IV.

That won't work since `aes-128-ctr` needs an IV. The problem here is that `createCipher` derives the key and IV automatically based on the given passphrase. I wrote this snippet to generate key and IV from a legacy password a while ago:

```javascript
// Parameters for aes-128-ctr.
const keySize = 16;
const ivSize = 16;

// Simulate EVP_BytesToKey.
const bytes = Buffer.alloc(keySize + ivSize);
let lastHash = null, nBytes = 0;
while (nBytes < keySize + ivSize) {
  const hash = crypto.createHash('md5');
  if (lastHash)
    hash.update(lastHash);
  hash.update(password);
  lastHash = hash.digest();
  lastHash.copy(bytes, nBytes);
  nBytes += lastHash.length;
}

// Use these for decryption.
const key = bytes.slice(0, keySize);
const iv = bytes.slice(keySize, keySize + ivSize);
```

This should decrypt all existing keys, but make sure to use a more secure method in the future.

**Comment by sam-github** [comment]
@tniessen The code above looks like a good candidate to add the deprecation notice, isn't it?

@writemonkey would you have time to update the docs so people coming after you know what to do?

**Comment by tniessen** [comment]
> The code above looks like a good candidate to add the deprecation notice, isn't it?

We could do that, but it will probably result in people copying this to fix their code instead of writing proper and secure code themselves. It's perfectly valid to decrypt contents that were encrypted using `createCipher`, but no new contents should be encrypted using these keys and IVs. Anyway, @bnoordhuis had a more sophisticated script IIRC.

**Comment by tniessen** [comment]
Closing as answered.
