### ISSUE TITLE
Is using currently-unsupported features in the best-interest of future-proofing?

### ISSUE THREAD

**Issue by harrysolovay** [nodejs/help#1675]
I'm about to begin work on a tool that does fun things like monkey-patching and adding loader hooks. I'm not yet sure of the full scope of Node features that I'll want to use... but I know that I want to be on the cutting-edge as much as possible. I'd love to––a year from now––look back on my code and not have the realization that its implementation is (too) stale. Maybe this is a difficult question to answer... but do you have any advice on what to make use of / avoid?

**Comment by Qix-** [comment]
Not _really_ a Node.js question but I'll attempt to answer.

Using as much "Vanilla Node" as possible is generally your best bet. Adopting Babel early on is a good start, but these days you can do just about anything you need to with modern ES6 that is already natively supported by Node - the only exception being `import` and `export`.

Avoid "all in one" frameworks. They tend to "rot" and cause massive headaches when trying to move away from them, and aren't considered good practice in Node.js anyway.

If you're worried about keeping the language as "fresh" as possible, that's a pipe dream. The ecmascript specification (the specification upon which Javascript is based) changes _frequently_, and Babel supports any [TC39 proposals](https://github.com/tc39/proposals) that are [beyond stage 0](https://github.com/babel/proposals), which means your code won't be "cutting edge" for long, no matter how hard you try.

And this is okay. I maintain a few packages on npm that still use ES5 syntax (`var` instead of `const`/`let`, for example). More recently, I updated [`debug`](https://www.npmjs.com/package/debug) to ES2015 (ES6) without much issue aside from a few users misusing version ranges and breaking their own applications.

The point is, as long as you're not trying to do anything _overly_ clever, following best practices and reducing the amount of dependencies you have (not necessarily npm dependencies, but also dependencies on things like specific environment, a user having certain files in a certain place, pre-requisites, etc.) generally makes for code that stands up to the test of time.

Obviously this is a large subject to write about but hopefully that helps a little.

**Comment by harrysolovay** [comment]
@Qix- thank you so much for taking the time to respond to my vague question. This is actually incredibly helpful & will absolutely guide my project! THANK YOU!
