### ISSUE TITLE
Writing JS to cache –– calling it doesn't work

### ISSUE THREAD

**Issue by harrysolovay** [nodejs/help#1678]
Hi NodeJS help. Here's what I'm attempting (it might seem like a strange implementation... but I'm really hoping to get it working)... I'm thinking my current failure to do so might have to do with the fact that it's cyclical... but I'll let you diagnose (and thank you in advance!):

`index.js`

```js
require('./some-file.js')()
return 

console.log('Hi NodeJS Help')
```

`some-file.js`

```js
const {readFile} = require('fs')

module.exports = () => {
  const {id} = module.parent // the already-resolved `index.js`
  readFile(id, 'utf8', (error, data) => {
    if (data) {
      const codeAfterReturn = data.split('return')[1]
      require.cache[id] = codeAfterReturn
      console.log(require.cache[id]) // properly logs out the file's contents post-`return`
      require(id) // nothing happens––'Hi NodeJS Help' is not logged to the console
    }
  })
}
```

Why is it that `require(id)` doesn't trigger the `console.log` call?

Any help would be really, really appreciated! Thank you so much!!!

Kind regards,

Harry

**Comment by Eomm** [comment]
Hi, your doubt is explained here:
https://nodejs.org/api/modules.html#modules_cycles

You are right, `require` is sync but in your case, the `return` statement will never let execute the `console.log` in index.js, consider your file like a function to run, and you are returning without exporting nothing. 
You can find more (well written) information here: https://nodejs.org/api/modules.html#modules_the_module_wrapper

Turning back to your code, here a simplified example:
`index`

```js
const test = require('./some-file')
module.exports = () => {
  console.log('index exported')
}
test()
// return // <------- if you return without doing any export, nothing will happen
console.log('index')
setTimeout(test, 500)
```

`some-file`
```js
module.exports = () => {
  require('./index')
  console.log('some-file', module.parent.loaded)
}
```

This will print out:
```
index exported
some-file false
index
index exported
some-file true
```

Consider also the `module.parent.loaded` parameter to understand if a module is fully or partially loaded.

I hope to has been helpful 😄

**Comment by Hakerh400** [comment]
There are several problems here:

 - `module.id` doesn't always represent script file name. For `index.js` it is `.` and `fs.readFile` fails with error `EISDIR` and `if(data){...}` never gets executed. Use `module.filename` instead
- `require.cache[id] = codeAfterReturn` - this line doesn't make sense. Properties of `require.cache` are instances of `Module`, but you're assigning a string (code of the module). You need to construct a new `Module`, or use existing module. Again, use `filename` instead of `id`
- `require(id)` - If you want `Hi NodeJS Help` message to be logged from this exact line, then it's impossible. When called, `require` reads the script from disk, or in case the script is cached, it returns the cached exported value. It doesn't re-execute module script. For example, if you have `example.js` with content `module.exports = Math.random()`, every time you call `require('./example.js')` it will return the same value

However, you can achieve something similar to what you are asking for.
The following code prints `Hi NodeJS Help` message:

`index.js`

```js
require('./some-file.js')();
return;

console.log('Hi NodeJS Help');
```

`some-file.js`

```js
const {readFile} = require('fs');
var first = true;

module.exports = () => {
  if(!first) return;
  first = false;
  const {filename} = module.parent;
  readFile(filename, 'utf8', (error, data) => {
    if(data){
      const codeAfterReturn = data.split('return')[1];
      const module = require.cache[filename];
      const func = new Function('module', 'exports', codeAfterReturn);
      module.exports = {};
      func(module, module.exports);
      require(filename);
    }
  });
};
```

**Comment by harrysolovay** [comment]
@Hakerh400 thank you!!! This is exactly what I'm looking for 💯
