### ISSUE TITLE
Issue installing truffle via npm

### ISSUE THREAD

**Issue by alecgarza96** [nodejs/help#1685]
Trying to install truffle but this is what i'm being prompted:

<img width="952" alt="screen shot 2018-12-20 at 11 05 26 am" src="https://user-images.githubusercontent.com/43724421/50315224-832e9c00-0477-11e9-8b9b-c9fc6c442643.png">
<img width="634" alt="screen shot 2018-12-20 at 11 05 47 am" src="https://user-images.githubusercontent.com/43724421/50315245-9a6d8980-0477-11e9-9255-d35a3caa92a5.png">

When i use `truffle init` I'm prompted `bash: command not found`

**Comment by nameszian** [comment]
If I'm not mistaken, that's just Warnings when compiling a program in c / c ++, in this case with node-gyp, I do not think you'll miss anything with that package, I always get Warning and nothing fails me.

On the other hand, `command not found` indicates that you have a problem in your global node_module `e.g. /Users/Alects/node_module`, (someone would have to confirm the exact route, since I use `nvm` and it is different) you should check that your `PATH` points to your node_modules, I recommend you use [nvm](https://github.com/creationix/nvm)

**Comment by gireeshpunathil** [comment]
ping @alecgarza96 - is this still an issue for you?

**Comment by tniessen** [comment]
Title changed.

**Comment by gireeshpunathil** [comment]
inactive, closing
