### ISSUE TITLE
Question about socket.write callback and drain event.

### ISSUE THREAD

**Issue by bgnx** [nodejs/help#1687]
How to know when data written to socket is reached to other side? I need to know this to send remaining part of some buffered data (data buffers in case when connections is closed due to bad network and new connection is made until it is ready).
And the question came up - is callback of socket.write method or "drain" event fires only when data is flushed to kernel buffer (as documentations says) or when tcp acknowledgments of sent data was received ? If it indicates only flushing so how can I setup a callback to know when tcp acknowledgement packets of my sent data was received? If this possible with node? If no why such api haven't been added for years?

**Comment by Qix-** [comment]
> How to know when data written to socket is reached to other side

There are two questions here:

1. How do I know that **data I've sent** has reached **the other computer**?
2. How do I know that **a message I've sent** has been read and acknowledged by **the other application**?

The answer to the first question is **it depends**. If you're using TCP, you can guarantee that, so long as the connection is intact and the other side is actively waiting for data, that the data will arrive in order and in full.

If you're using UDP, the answer is **you don't** - which is also the answer for question 2.

If you want some sort of acknowledgement that the other side has received your data successfully, they will need to send back some sort of message that indicates this. There is nothing specified to you by either TCP or UDP that will tell you this with any amount of certainty (at least, not anything exposed to you at the application level).

> I need to know this to send remaining part of some buffered data

Don't do this. Just send it. The underlying network stack will handle it for you.

If you were using blocking ("synchronous") I/O and TCP, the call to `write()` or (`send()` on windows) will block, meaning that your program won't continue running until the other side has picked up the data. This is sometimes referred to as "backpressure", and there's a wonderful article about it [here](https://nodejs.org/en/docs/guides/backpressuring-in-streams/).

In non-blocking mode, the call to `write()` or `send()` will return an error code indicating that the same call should happen again at a later time. There are also ways to wait for a socket to become writable.

That's what Node.js does - you can keep writing to a socket, and if Node can't _actually_ send it, it will buffer the data until it can be sent.

> is callback of socket.write method or "drain" event fires only when data is flushed to kernel buffer (as documentations says) or when tcp acknowledgments of sent data was received

Seeing as how applications don't _generally_ look for the ACK signal from TCP, and I don't believe Node exposes this (easily) to the user, it's safe to assume it means that the kernel buffers have been flushed.

Further, from a performance standpoint, it wouldn't make sense to wait for the other end to receive data before sending more. There can be a large amount of data in-flight at any given time. This would slow socket applications to a grinding halt, and generally applications aren't written to wait for ACK.

More on ACK here: https://stackoverflow.com/a/1506911/510036

> If it indicates only flushing so how can I setup a callback to know when tcp acknowledgement packets of my sent data was received?

Don't do this. You're trying to solve a problem that doesn't exist.

>  If no why such api haven't been added for years?

Because that's not how you write socket applications 😅 What **exactly** is the problem you're trying to solve?

**Comment by bgnx** [comment]
@Qix- , thanks for your answer. I just want to be sure that the data is not lost by underlying network and was hoping that I can setup some sort of callback for tcp acknowledgments of sent data. I understand that this is not indicating that data was received by application, but excluding network from possibilities of data loss is a big step because other possibilities is very rare and I don't want to reimplement this  of acknowledgments in application level (e.g sending back message indicating of received data and retrying on the other side if this acknowledgment wasn't received)

**Comment by Qix-** [comment]
> I just want to be sure that the data is not lost by underlying network 

This is a guarantee that is put in place by the TCP/IP protocol so long as a connection is valid. However, data that has been passed to the kernel buffer but is unsent when a socket dies is indeed lost - it's up to you, as the application maintainer, to set up application-specific checks to make sure data has been received as you'd expect.

> I don't want to reimplement this of acknowledgments in application level 

You have no other choice. Anything else would be a hack and thus you'd make life very hard for the next person who has to maintain your code.

Most applications operate under the assumption the data will reach the other side and that all state data can be re-produced if necessary in the event the connection gets dropped. That's just how socket applications are designed.

---

What you're ultimately asking is "how do I write _fault tolerant_ applications". That's a very Google-able term with a mountain of excellent prose behind it. [Here's the first result for `writing fault tolerant socket applications` from Google.](https://doc.akka.io/docs/akka/1.3.1/scala/tutorial-chat-server.html)

It's not a simple solution, and writing fault-tolerant applications is a game of trade-offs. I definitely recommend researching that, as it will answer all of your questions :)

**Comment by gireeshpunathil** [comment]
ping @bgnx - is this outstanding?

**Comment by gireeshpunathil** [comment]
inactive, closing
