### ISSUE TITLE
Async function execute in different version got different output about async function itself

### ISSUE THREAD

**Issue by Jiasm** [nodejs/help#1733]
* **Node.js Version**: 11.7.0 & 10.15.0
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**: runtime

I found an interesting things,
Simple test code:

```javascript
async function test () {
  await 1
}

console.log(test.constructor.name, test.prototype)

test()

console.log(test.constructor.name, test.prototype)
```

When I use the `10.15.0` version, I got two different outputs.
This does not appear on the `11.7.0` version.

![image](https://user-images.githubusercontent.com/9568094/51590564-5f062500-1f25-11e9-8505-ea77fe6e10fc.png)

I did not find the relevant modification record on the [ChangeLog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md).
I'm not sure if it is a bug fix, or an implementation change. Can you provide the corresponding information?
I'm more interested in this, thank you.

**Comment by vsemozhetbyt** [comment]
On Windows 7 x64:
```
>node.08.15.0.v8-6.2.exe test.js
AsyncFunction undefined
AsyncFunction {}

>node.10.15.0.v8-6.8.exe test.js
AsyncFunction undefined
AsyncFunction Object [Generator] {}

>node.11.7.0.v8-7.0.exe test.js
AsyncFunction undefined
AsyncFunction undefined
```

**Comment by vsemozhetbyt** [comment]
cc @nodejs/v8

**Comment by Hakerh400** [comment]
Seems like it was a bug in old V8.

```js
async function test(){await 1}
test()
console.log('prototype' in test)    // false
console.log(test.prototype)         // Object [Generator] {}
console.log(test['prototype'])      // Object [Generator] {}
console.log(test['prototype' + '']) // undefined
```

There's no semantical difference between the last two lines, but they give different results.

**Comment by yathamravali** [comment]
I did bisect and landed with this PR:
https://github.com/nodejs/node/pull/22390
I'm not sure whether this is a bug or Enhancement. Copying the author to get more insight. 
cc @TimothyGu

**Comment by TimothyGu** [comment]
@yathamravali The referenced PR was later reverted: https://github.com/nodejs/node/pull/22911. So it couldn’t have been that.

**Comment by TimothyGu** [comment]
@Hakerh400’s analysis seems correct though.

**Comment by gireeshpunathil** [comment]
closing as answered, let me know if there is anything outstanding here

**Comment by Hakerh400** [comment]
I did more research on this. This bisects to https://github.com/nodejs/node/commit/0e7ddbd3d7e9439c67573b854c49cf82c398ae82 (brought by PR https://github.com/nodejs/node/pull/22754). Further bisecting V8 revealed that the bug is fixed in https://github.com/v8/v8/commit/4ef4deae6eb3277b0ce63908661bac9f64eea386, as a special case of [v8/v8#5085](https://bugs.chromium.org/p/v8/issues/detail?id=5085). The relevant test, which is basically the same script from the OP, that was added in that commit is [test-regress-5085](https://github.com/v8/v8/blob/4ef4deae6eb3277b0ce63908661bac9f64eea386/test/mjsunit/regress/regress-5085.js).
