### ISSUE TITLE
V8 commit to version mapping

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#180]
Say, I'm interested in a particular commit:

https://github.com/v8/v8/commit/e39ba01420733cf5fa7a16f9c91dcc8b8b044a47
https://chromium.googlesource.com/v8/v8/+/e39ba01420733cf5fa7a16f9c91dcc8b8b044a47

How can I identify the V8 release (version) from which this commit is available? So I can know when I can use it in the Node.js.

**Comment by bnoordhuis** [comment]
The answer is 'not easily' due to the way V8 does release management.

If you have the V8 repository checked out, you'll find that `git tag --contains e39ba01` points to 5.1.298 as the first release containing that commit.

That's misleading however, because if you look at the tip of the 5.1 release branch (`git log branch-heads/5.1`), you won't find it anywhere - neither with that commit hash or with another.

The first release branch to contain it is 5.2 (`branch-heads/5.2`) at commit v8/v8@e39ba01420733cf5fa7a16f9c91dcc8b8b044a47.

**Comment by vsemozhetbyt** [comment]
Well, in the 5.1.298 sourse code there are files added in this commit: `test\mjsunit\harmony\regexp-property-binary.js` and `test\mjsunit\harmony\regexp-property-enumerated.js`. Is this indicator somehow misleading too?

**Comment by bnoordhuis** [comment]
Yes, at least, the version number suggests 5.1.298 is part of the 5.1 series.  But it's not, it's one of the development snapshots leading up to the 5.2 release branch.

**Comment by vsemozhetbyt** [comment]
Ooh. Thank you)
