### ISSUE TITLE
zlib.createUnzip: unexpected Z_DATA_ERROR

### ISSUE THREAD

**Issue by bigslycat** [nodejs/help#1826]
* **Node.js Version**: v10.15.3
* **OS**: Ubuntu 19.10 amd64
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: zlib

I tried to download and unzip the zip archive, but I received this error and no further information:

```
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -3, code: 'Z_DATA_ERROR' }
```
My code:
```js
const { get } = require('https');
const { createUnzip } = require('zlib');

get(
  'https://download.geonames.org/export/dump/hierarchy.zip',
  response =>
    response
      .pipe(createUnzip())
      .on('data', console.log)
      .on('error', console.error),
);
```

**Comment by addaleax** [comment]
Thank you for the easy reproduction!

The issue is that `createUnzip()` doesn’t actually handle `.zip` files, the naming is a bit unfortunate here – what it does is dynamically choose to either use `createInflate()` or `createGunzip()` depending on the recognized data format. Generally, all built-in `zlib` streams only recognize a single stream of data, and can’t deal with formats such as `.zip` or `.tar` that contain multiple files.

For reading `.zip` files, there are ecosystem utilities on npm such as [`yauzl`](https://www.npmjs.com/package/yauzl), or a variety of alternatives: https://www.npmjs.com/search?q=zip

**Comment by gireeshpunathil** [comment]
ping @bigslycat

**Comment by bigslycat** [comment]
@gireeshpunathil still relevant.

* **Node.js Version:** v12.5.0
* **OS:** Ubuntu 19.04 amd64

**Comment by bigslycat** [comment]
@addaleax thanks for explanation.

**Comment by tylerssn** [comment]
Still an issue on Node 14
