### ISSUE TITLE
Is Node 8.15.1 FIPS 140-2 certified?

### ISSUE THREAD

**Issue by devanshah2** [nodejs/help#1844]
* **Node.js Version**: 8.15.1
* **OS**: Docker image: node:8.15.1-alpine
* **Scope (install, code, runtime, meta, other?)**: question
* **Module (and version) (if relevant)**:

Is the base code from Node v8.15.1 FIPS 140-2 certified for both the crypto libraries as well as the https libraries used with in Node's base code.

I did come across: https://github.com/nodejs/node/blob/v8.15.1/BUILDING.md#building-nodejs-with-fips-compliant-openssl which states it is not and we need to re-build node according to the steps outlined to pull in the openssl lib that is FIPS compliant. Is this still true?

**Comment by gireeshpunathil** [comment]
@mhdawson

**Comment by mhdawson** [comment]
The binaries shipped by the Node.js project have **NOT** been built following the processes need to make them FIPS compatible (note compatible because you still need extra steps to be compliant).

You would need to build node your self and follow the additional requirements for getting the FIPS canister code through a trusted path etc.

**Comment by mhdawson** [comment]
@devanshah2 I see you are from IBM.  If you'd like to set up a time to discuss in more detail you can email me (michael_dawson@ca.ibm.com) or set up a time through notes.  I would be interested in hearing about your requirement/need.

**Comment by gireeshpunathil** [comment]
@devanshah2 - is this resolved?

**Comment by gireeshpunathil** [comment]
answered, closing

**Comment by tommymarshall** [comment]
How was this resolved? Running into a similar situation.
