### ISSUE TITLE
node-gyp with no sources / library only?

### ISSUE THREAD

**Issue by rreed** [nodejs/help#1845]
* **Node.js Version**: 10.14.1
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)** node-gyp build/runtime:

I'm trying to build a library using *just* a dll, with no sources, and running into the following: 
```
Uncaught Exception:
Error: Cannot open (path)/build/Release/foo.node: Error: Module did not self-register
```

My bindings file is as follows (I have also tried this with `bar.dll`, no dice, same error):
```
{
    "targets": [
        {
            "target_name": "foo",
            "sources": [ "src/native/bar.lib" ]
        }
    ]
}
```

`src/native` is a directory which just contains `foo.dll`, `foo.lib`, and `foo.h`.

Configure looks reasonable to my untrained eye:
```
C:\Users\RR\workspace\>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.14.1 | win32 | x64
...
gyp info ok
```

Build looks reasonable...I think?:
```
C:\Users\RR\workspace\>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.14.1 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  foo.vcxproj -> C:\Users\RR\workspace\build\Release\\foo.node
gyp info ok
```

However, when I load this, I get the error above. So now I'm asking either "what am I doing wrong?" or "how do I debug this?" depending on whether or not what I'm doing wrong is obvious. :) Thanks!

**Comment by Hakerh400** [comment]
What you're trying to do is, in general, not possible. Node.js addons must provide a valid JavaScript interface (so that JavaScript functions can access methods of your addon). Libraries like .lib and .dll contain functions that are supposed to be called from C++, not from JavaScript. That's what "registering an addon" means - you need to register the main function that will be called during requiring your addon, then you export JavaScript-adapted interface that calls functions from your library. It may be possible to load only a library though, but you need to register the entry function (that will be called by Node.js) in the library itself. Easier way is to write some C++ code that will do it instead.

How does your library look like? What functionalities does it provide? What exactly are you trying to achieve? Can you give an example of how your addon will be used in JavaScript?

**Comment by rreed** [comment]
Without getting too much into the NDA-violating specifics, it's an authentication library provided to us by a vendor. This is for an Electron app, which needs to call this C library to do auth-related things that I'll handwave. :p

But your answer gave me what I basically needed to know: that the answer is probably just "write some C that loads this DLL and calls the right functions in `main()`, call that from Electron". My initial mental model of this was that I'd need to do the equivalent of `const foo = require('foo.dll'); foo.bar()`, and I wasn't anywhere near getting that to work.

**Comment by bnoordhuis** [comment]
You can do that with [node-ffi](https://www.npmjs.com/package/ffi) but if your requirements involve good performance then you should probably look elsewhere, it has a lot of overhead.

If you're going to write your own add-on, take a look at [n-api](https://nodejs.org/api/n-api.html).

**Comment by gireeshpunathil** [comment]
ping @rreed

**Comment by gireeshpunathil** [comment]
answered, closing
