### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by jeffrson** [nodejs/help#1867]
* **Node.js Version**: 10.15.3
* **OS**: Linux, Docker
* **Scope (install, code, runtime, meta, other?)**: runtime, memory
* **Module (and version) (if relevant)**:

We have a project that start's with about 170MB RSS memory where, according to chrome://inspect, heap is 35MB of 70MB used. Memory usage grows at some point (I cannot tell yet when and how exactly), while heap usage stays approximately the same.
The overall memory usage even grows up until 2.5GB and beyond (we've seen 4.5GB) - heap stays moderately at 40MB used/80MB total.

We haven't increased the max_old_space_size. The program does not crash so far (maybe we hadn't waited long enough...).

What memory might that be? How can we analyse this? Needless to say, this only happens in production...

AFAICT, there's no native code responsible (though we use websockets package, with native buffer).

**Comment by yathamravali** [comment]
@jeffrson 

This might be because  when we run an empty node app inside container the static rss usage with an empty node will be around 20MB(for Node.js v10.x) and there are other memory regions in the heap pertinent (such as new_space, code_space etc.) account for another 20 MB assuming their default configurations. If the defaults are adjusted these assumptions will change.
 
The other item that take memory (unaccounted in `--max-old-space` is the native memory - such as buffer, array etc.) Only a small portion of those sit in the javascript heap, the rest in the native space, so cannot be seen in `max-old-space`

Actually the application will be killed by OOM-KILLER when the `rss` memory limit exceeds the container memory limit.

Check the container limit by issuing `cat /sys/fs/cgroup/memory/memory.limit_in_bytes`. As your program might not have crossed the container limit so it’s not crashed yet.

**Comment by gireeshpunathil** [comment]
ping @jeffrson

**Comment by gireeshpunathil** [comment]
answered, closing
