### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by yeguixin** [nodejs/help#1870]
* **Node.js Version**:  v10.12.0
* **OS**:  Ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**:  runtime

* **Testcase**: 
```js
var a = function(values, stride, order) {
    var nValues = values.length;
    var result = new values.constructor(nValues);
    for (var i = 0, dstOffset = 0; dstOffset !== nValues; ++i) {
        var srcOffset = order[i] * stride;
        for (var j = 0; j !== stride; ++j) {
            result[dstOffset++] = values[srcOffset + j];
        }
    }
    return result;
};
a(6227569859725143, null, function() {
    var a = h$r1.d1;
    h$bh();
    h$l3(17191, h$$b, a);
    return h$ap_1_2_fast();
});
```

When I run the above testcase using node, a bug was triggered following this error information:

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1d4282d5be1d]
    1: StubFrame [pc: 0x1d4282d89042]
Security context: 0x2ef7fe01e6e1 <JSObject>
    2: a [0xf3654d368e1] [/home/nisl/gxye/program/fuzzing/testcases/nodejs_v4.2.6/crash/1/testcase.js:8] [bytecode=0x12cfa9f33339 offset=99](this=0x04fce469ad49 <JSGlobal Object>,values=0x12cfa9f32691 <Number 6.22757e+15>,stride=0x240a879022b1 <null>,order=0x0f3654d36921 <JSFunction (sfi = 0x12cfa9f32601)>)
    3: /* ano...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x8daaa0 node::Abort() [node]
 2: 0x8daaec  [node]
 3: 0xad79ae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad7be4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xece9e2  [node]
 6: 0xede2df v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
 7: 0xea71d6 v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [node]
 8: 0xea7a5a v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [node]
 9: 0xea8017 v8::internal::Factory::NewUninitializedFixedArray(int, v8::internal::PretenureFlag) [node]
10: 0xe692f0  [node]
11: 0xe694cf  [node]
12: 0xfe1dce v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::ShouldThrow) [node]
13: 0xffb5a2 v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::ShouldThrow, v8::internal::Object::StoreFromKeyed) [node]
14: 0x101615d v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode, v8::internal::Object::StoreFromKeyed) [node]
15: 0x1175fc5 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [node]
16: 0x11772d0 v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [node]
17: 0x1d4282d5be1d

**Comment by Hakerh400** [comment]
What exactly is your question?

Argument `values` is of type `number`, so `values.length` is `undefined` and `nValues` is also `undefined`. Variable `result` is an instance of the `Number` class. The outer loop is infinite, because `dstOffset !== nValues` will always be false (`dstOffset` is number and `nValues` is `undefined`). In the inner loop you're constantly creating new properties of the `result` object and assigning `undefined` to each of them. This will eventually cause out-of-memory error, as you experienced. That is expected behavior.

It seems that you're trying to debug/understand someone other's code. Giving a bit more info about what you're trying to do and where you have found these functions would be useful if you want more detailed help. As written, the function `a` is probably intended to take arguments of type typed array for `values` and `order` and integer for `stride`, but you're calling it with integer, null and a function respectively, which doesn't make sense.

If you're just wondering why this causes fatal error and not a regular catchable error, the answer is: that's how JavaScript's V8 engine works. Out-of-memory errors can't be handled and they force the program to crash. Simpler example that causes this error is

```js
let a = {}, i = 0;
while(a[i] = ++i);
```

**Comment by yeguixin** [comment]
Thanks for your detailed answer @Hakerh400 . Now I want to learn to fuzze Node.js. Could you give me some advices on how to fuzzing or how to debug the Node.js. Thanks again.

**Comment by gireeshpunathil** [comment]
ping @yeguixin - is there anything pending in this issue?

**Comment by gireeshpunathil** [comment]
answered, closing
