### ISSUE TITLE
How to initialise and start node in c++? 

### ISSUE THREAD

**Issue by niks3089** [nodejs/help#1890]
* **11.14.0:**:
* **Ubuntu 18.04**:
* **Runtime**:

I have a c++ application where I build node from source and link its static libraries to my application. I would want my application to read a javascript file, initialise node and run the js file as a node application. However, I am not finding the right c++ node APIs to call to achieve this.  Any idea how this can be done?

The end-result I am looking for is ```myapp -f test.js```  Runs as a node app

**Comment by gireeshpunathil** [comment]
@niks3089 - https://github.com/nodejs/node/blob/8dae89b396df64e6a9e44cb94efe27809a5a3d89/src/node.cc#L873-L877 is the function you should be calling.

You can follow instructions in https://github.com/nodejs/node/blob/master/BUILDING.md on how to build Node from source, with `./configure --shared` option instead of `./configure` to get a shared library (that contain the said `start` method in it) which you can link you app against.

Hope this helps!

**Comment by niks3089** [comment]
Thanks @gireeshpunathil
I guess I need to read the code to figure out what argv needs to be passed. I will find that out and update it here.

**Comment by gireeshpunathil** [comment]
@niks3089 - welcome. the `argc` and the `argv` are the one you get from your (the C++ app's) command line. To source that in, your main should be defined as:

`int main(int argc, char *argv[]) {
...
 return node::Start(argc, argv); // node's start method
}

for reference, have a look at Node's own entry point, here:

https://github.com/nodejs/node/blob/8dae89b396df64e6a9e44cb94efe27809a5a3d89/src/node_main.cc#L96

**Comment by gireeshpunathil** [comment]
ping @niks3089

**Comment by gireeshpunathil** [comment]
answered, closing
