### ISSUE TITLE
Reduce code size of node

### ISSUE THREAD

**Issue by cuttlfish** [nodejs/help#19]
Hi,

Is there any way to reduce the code size of nodejs. On a cross compile platform it comes to be about 9 MB. 

Also is there a way to reduce initial heap allocated by V8

Thanks
David

**Comment by mikeal** [comment]
pinging @trevnorris since he likely knows the answer.

**Comment by trevnorris** [comment]
By code size do you mean the built binary? As for v8, there are ways to constrain how much maximum memory it can use, but don't know of a way to limit memory consumption at startup.

**Comment by cuttlfish** [comment]
Hi Trevor,

Yes I mean the built binary. I tried changing the v8 gcc flag to -Os, that
did succeed in making it smaller, but starts up slower I guess due to less
optimization

David

**Comment by trevnorris** [comment]
I'm not really sure. you could compile w/o openssl if you don't need crypto.

**Comment by srl295** [comment]
@cuttlfish what operating system and platform?

**Comment by cuttlfish** [comment]
This is linux running on a ARM platform that is similar to raspberry pi

**Comment by amulpatel** [comment]
I am also looking to reduce node memory size around 20 MB in openwrt. currently it is consuming around 50 MB.

is there any way to reduce memory consumption ? even i am ready to change code to reduce memory i.e v8, uv or other deps.

Thanks,
Amul Patel

**Comment by bnoordhuis** [comment]
There is an `--optimize_for_size` flag in newer versions of node and you can limit the size of the heap with `--max_old_space_size=...` (and `--max_semi_space_size` and `--max_executable_size`) in all versions.

You can also tweak common.gypi to build at -Os instead of -O3.  The smaller binary, besides using less memory, also tends to run faster on systems with small L1 code caches.
