### ISSUE TITLE
Why does the function setTimeout() return the different value between nodejs and chrome console?

### ISSUE THREAD

**Issue by bahuwang** [nodejs/help#1903]
* **Node.js Version**: 10.15.3
* **OS**: windows 10 1809
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: Timers

```js
    var a = setTimeout(function () {
        console.log('time')
    },1000 )
    console.log(a)
```
I want to know why the return value of nodejs is Timeout and chrome console is a timeoutID.

**Comment by gireeshpunathil** [comment]
as per docs: https://nodejs.org/dist/latest-v12.x/docs/api/timers.html

`The timer functions within Node.js implement a similar API as the timers API provided by Web Browsers but use a different internal implementation that is built around the Node.js Event Loop.`

According to me, the `timer` functions in Node are implemented using the same type of abstraction that other asynchronous APIs are designed with, leveraging the `register- poll / check - trigger` mechanism that the event loop uses. The major difference is that instead of polling the OS, it detects the scheduled intervals with the help of an internal counter that the loop maintains. Otherwise, more or less the same abstractions - native bindings, request registration, triggering callbacks etc. remain more or less same.

Having said that, the scheduling (set..) and de-scheduling (clear..) semantics do not impose any difference at the API level, to the user - between browsers and node, so!

Hope this explanation helps?

**Comment by bahuwang** [comment]
Thanks @gireeshpunathil. Maybe based on different considerations, there are some inconsistent.
