### ISSUE TITLE
Event loop execution order changes based on code part that didn't executed

### ISSUE THREAD

**Issue by davNazaryan** [nodejs/help#1912]
* **Node.js Version**: v10.14.1
* **OS**: Windows10x64

No need to init new project. Only the built-in `fs` module used there.

I have a code that works as designed in Unix based OS, but in windows, it gives the "strange" result.
Code 
```js
const fs = require('fs');

function someAsyncOperation(callback) {
  fs.readFile('/path/to/file', callback);
}

const timeoutScheduled = Date.now();

setTimeout(() => {
  const delay = Date.now() - timeoutScheduled;

  console.log(`${delay}ms have passed since I was scheduled`);
}, 1000);

someAsyncOperation(() => {
  console.log('BEFORE WHILE');
  const startCallback = Date.now();

  while (Date.now() - startCallback < 1000) {
    // do nothing
  }

  // setImmediate(() => { console.log('IMMEDIATE'); });

  console.log('AFTER WHILE');
});
```
The output is
```cmd
BEFORE WHILE
AFTER WHILE
2007ms have passed since I was scheduled
```
The output is the same independently of how many timers are present. ( it's always 2000+ )

Which is weird. I guess that such a result is possible if the `setTimeout` ( I mean the `setTimeout` itself, not the`setTimeout`'s callback ) registered AFTER `while` loop work. 

Pay attention at `// setImmediate(() => { console.log('IMMEDIATE'); });` line.
If I uncomment it the output will be 
```cmd
BEFORE WHILE
AFTER WHILE
IMMEDIATE
1005ms have passed since I was scheduled
```
In Unix based system the output always {1000+}ms, and doesn't depend on `setImmediate` existence.

Can someone explain why it happens, and give event loop execution order. 

It's maybe a BUG, but I'm not sure.

Thanks in advance.

**Comment by gireeshpunathil** [comment]
@davNazaryan - when you say `which is weird` , can you please explain what is the expected behavior?

I ran this code, and see similar results as you posted, but does not find anything unusual. 

If I make a guess about your concern, you expect the the timer callback to be fired exactly (or at least cnsistently) around 1 second, but the actual is not matching that, instead much more, accounting the time taken for `someAsyncOperation` too. If you increase the while loop iteration, you can prove that point.

If that is your concern, then the answer is: `someAsyncOperation` is not an async operation! other than the name it carries, everything inside the function is executed synchronously, which means the single thread is blocked (mostly on the while loop) so there is no one to dispatch the timer call back that was readied in between.

Hope this helps!

**Comment by gireeshpunathil** [comment]
@davNazaryan - sorry, please ignore my previous comment. I am able to see your point now. Looking further on to this.

**Comment by yathamravali** [comment]
@davNazaryan - Yeah!! I can see the same difference when running on windows. 

In https://nodejs.org/de/docs/guides/event-loop-timers-and-nexttick/#poll blog I can see a Note mentioning there is a slight discrepancy between the Windows and the Unix/Linux implementation.

So I hope the weird behaviour is because of that implementation difference.

**Comment by davNazaryan** [comment]
@yathamravali The code is a modified version of the example code from https://nodejs.org/de/docs/guides/event-loop-timers-and-nexttick/#poll
And yes they are mention that windows and Unix based versions have differences. The nodeJS poll is based on epoll (for Unix version), also js is an *event-driven* and a lot of things in Unix version based on Unix sockets. As I know windows didn't even have sockets.

```
There are actually seven or eight steps, but the ones we care about — ones that Node.js actually uses - are those above.
```
The lack of a clear explanation for this line especially infuriates me :)

All I want to know is an exact discrepancy between the Windows and the Unix/Linux implementation.
Also, such behavior may be a nodeJs core BUG.

**Comment by nairihar** [comment]
I don't think it's a bug. Most probably something related to EventLoop phases. I think it's mostly related to IO Polling phase, that's why commenting setImmediate affects on the result. Also, the implementation of different environments sometimes can show different results.

**Comment by nairihar** [comment]
I don't think it's a bug. Most probably something related to EventLoop phases. I think it's mostly related to **Idle**, **Prepare** phase, that's why commenting setImmediate affects on the result. The implementation, for different environments sometimes can show different results.

**Comment by davNazaryan** [comment]
I'm closing this issue, as It's the confirmed bug. If you are interested, You can track issue here => https://github.com/nodejs/node/issues/27747
