### ISSUE TITLE
incorrect decryption on >=8.0.0 compared to <=7.10.0

### ISSUE THREAD

**Issue by IRoninCoder** [nodejs/help#1913]
Referring to [CHANGELOG.log][1] shows a few changes around the crypto module and i think one of those broke my decryption mechanism when upgrading from 6.10 to 8.10. It turns out that the breakage happens when going from nodejs <=7.10.0 to >=8.0.0. I've created a github repository with a sample code to demonstrate the issue [here][2]. To test side-by-side, simply download two docker containers for nodejs 7.10.0 and 8.0.0, then run the source code in both containers. The containers have the same version of openssl installed (OpenSSL 1.0.1t  3 May 2016), but they do produce two different outcomes!! which i believe is the issue and i'm trying to resolve this inconsistency as it's currently breaking the decryption by producing incorrect results.

Any hint on how to resolve this is appreciated.

Version: 7.10.0 and 8.0.0
Platform: docker images and MacOS

PS: AWS Lambda is terminating support for nodejs 6.10 by the end of May 2019. Upgrading to 8.10 lambda version revealed this issue.

  [1]: https://github.com/nodejs/node/blob/e006a8545e6ed45a4e1ba231e9abde794c033d02/doc/changelogs/CHANGELOG_V8.md#8.0.0
  [2]: https://github.com/IRoninCoder/nodejs-sha256-inconsistent-dec

**Comment by addaleax** [comment]
(Moving to nodejs/help because this isn’t a Node.js bug.)

```js
var key = Buffer.from(item.key.data).toString()
var sha256 = crypto.createHash('sha256', options).update(key, 'binary');
```

Those lines should almost surely be 

```js
var key = Buffer.from(item.key.data);
var sha256 = crypto.createHash('sha256', options).update(key);
```

By using `.toString()` on the key buffer, and passing it to `.update()` using `'binary'` (aka `'latin1'`), you are telling Node to first decode the key buffer as UTF-8 and then re-encode it as ISO-8859-1, but neither of these operations make sense when dealing with binary data (because binary data buffers, like the keys, don’t correspond to sequences of characters).

In particular, from Node 7 to Node 8 the V8 engine underlying Node has changed its UTF-8 decoding behaviour to be more consistent, and emits a different number of replacement characters (`�`) for invalid input. You can verify that by logging the contents of the `key` variable in your example.

There is no way to recreate the behaviour from Node 7 in Node 8 using Node’s built-ins only, and vice versa. If you are locked into the Node 7 behaviour because your database contains that particular kind of invalid data and you cannot update its contents, you may have to use old versions of the https://www.npmjs.com/package/string_decoder module in order to achieve the old UTF-8 decoder behaviour. If you’re not locked into that data format, fixing your code by not converting binary data into strings should be enough.

**Comment by IRoninCoder** [comment]
Modified the example to test and all of the data is decrypted incorrectly. As for database, yes there's a database containing these values and from reading your post it seems there was a backward incompatible change from nodejs 7 to 8 that i don't see stated in change logs explicitly (as in "things will not work").

So if this is true, then I'll have to use the old decoder. Crypto imports its own modules, so can you provide an example of how to use the older string decode when using crypto?

**Comment by addaleax** [comment]
> Modified the example to test and all of the data is decrypted incorrectly.

Yes, because now the keys are not “scrambled” through UTF-8 decoding + ISO-8859-1 encoding… the example was just my attempt to explain where the bug is, not to fix it for already existing data.

> a backward incompatible change from nodejs 7 to 8 that i don't see stated in change logs explicitly (as in "things will not work").

Yeah, that’s a bit unfortunate … we haven’t listed notable changes from the JS engine itself in the past, mostly because the language itself doesn’t allow for breaking changes to begin with.

> So if this is true, then I'll have to use the old decoder. Crypto imports its own modules, so can you provide an example of how to use the older string decode when using crypto?

This really has nothing to do with crypto at all.

If you want the pre-Node-8 behaviour, you can use something like this, when installing `string_decoder@1.0.3` (no higher version, not even `1.1.0` – they didn’t follow semver on this).

```js
var string_decoder = require('./node_modules/string_decoder');

...

  var decoder = new string_decoder.StringDecoder('utf8');
  var keyBuffer = Buffer.from(item.key.data);
  var key = '';
  for (var j = 0; j < keyBuffer.length; j++)
    key += decoder.write(keyBuffer.slice(j, j + 1));
  key += decoder.end();

...
```

**Comment by IRoninCoder** [comment]
> ```js
> var string_decoder = require('./node_modules/string_decoder');
> 
> ...
> 
>   var decoder = new string_decoder.StringDecoder('utf8');
>   var keyBuffer = Buffer.from(item.key.data);
>   var key = '';
>   for (var j = 0; j < keyBuffer.length; j++)
>     key += decoder.write(keyBuffer.slice(j, j + 1));
>   key += decoder.end();
> 
> ...
> ```
Tried this code as well with no success. Any other ideas that may resolve this?

**Comment by addaleax** [comment]
@IRoninCoder In your repo, the `require` call points to `string_decoder`, not `./node_modules/string_decoder` as in the example, and thus loads the builtin module with the changed behaviour, rather than the old `string_decoder` module from the disk.

You also want to keep the `'binary'` parameter to `.update()`, because the ISO-8859-1 encoding is part of recreating the broken behaviour.
