### ISSUE TITLE
How to read file descriptor or filepath using fs

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1932]
Regarding latest Node.js versions. I posted this question on unix.stackexchange

https://unix.stackexchange.com/questions/521817/implement-file-read-option-from-command-line-anonymous-file/521818#521818

so it looks like `cat` can read from a file, or file descriptor:

```bash
cat /dev/fd/63
```

or 

```bash
cat /Users/me/my_file.json
```

how does cat do that, and how can I do that with Node.js? With node.js I have to do:

```js
fs.createReadStream(file)
```
or

```js
fs.createReadStream(null, {fd});
```

how does cat know whether it's a file descriptor or a file?

**Comment by wide4head** [comment]
@ORESoftware May be this link contains some clue https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options

**Comment by addaleax** [comment]
> how does cat know whether it's a file descriptor or a file?

It doesn’t! :slightly_smiling_face: At least on Linux, `/dev/fd` is a symlink to `/proc/self/fd`, and `/proc/self` itself is a symlink to `/proc/${pid}`. And then each “file” in `/proc/${pid}/fd/` is special, in that it can be opened by a process (at least for all types of streams typically used for stdio) and get a copy of that file descriptor.

So, the magic is happening in the OS, not the application; you could also open `/dev/fd/${fd}` with a Node.js application, although Node.js does not have a great story when dealing with arbitrary file types (because of its distinction between fs streams and non-blocking streams).

**Comment by gireeshpunathil** [comment]
ping @ORESoftware - is this resolved?

**Comment by ORESoftware** [comment]
yep thanks
