### ISSUE TITLE
You are using Node v13.0.0-pre, but this version of ... requires Node >=8.9

### ISSUE THREAD

**Issue by dagelf** [nodejs/help#1934]
Is there a standard Node version check? Why does it think that v13 < v8.9 ? Is this something that needs to be fixed in the version check, or in every single package or dependency?

**Comment by gireeshpunathil** [comment]
@dagelf - is this still outstanding? could you pls provide minimal steps to reproduce? thnx

**Comment by tniessen** [comment]
If we publish prereleases, they are usually meant for testing only, and not for production purposes. The semver package intentionally does not recognize them as a newer version since they are not guaranteed to follow semantic versioning.

If you want to test your own module against our prereleases, I would suggest to temporarily patch your module or the semver dependency to recognize it as a newer release.

**Comment by gireeshpunathil** [comment]
closing as answered; pls re-open if necessary
