### ISSUE TITLE
32bit update

### ISSUE THREAD

**Issue by Folorunsho-Yusuf** [nodejs/help#1938]
Good Day,
I need help i cant get to install the latest update of Nodejs on my 32bit linux operating system

**Comment by refack** [comment]
Hello @Folorunsho-Yusuf 

I'm transferred this issue to our help repo, as this seemed to me as more of a [usage question](https://github.com/nodejs/node/blob/master/.github/SUPPORT.md), and not specifically a bug report.

Since Node.js version 10 we stopped creating official binaries for 32bit Linux. But we have recently started helping promote https://unofficial-builds.nodejs.org/download/release/ as a repository for well built binaries for some of the platform we don't officially support.

For how to use the new download source with package managers, please refer their support channels.

Hope this helps.

**Comment by gireeshpunathil** [comment]
answered, closing
