### ISSUE TITLE
python not working correctly when called from child-process

### ISSUE THREAD

**Issue by lxknvlk** [nodejs/help#1968]
Im not sure where to ask, there https://github.com/yahoo/open_nsfw
or here, so i asked there and here.

So theres a script that loads the deep learning model and then classifes the image.

The script stops at this line

    # Pre-load caffe model.
    nsfw_net = caffe.Net(model_def, pretrained_model, caffe.TEST)

Everything else in python works fine. And the script run directly works fine too. Why it is not working when called from child-process?

When i run it from a node app like this

            const cp = require("child_process")
	        const spawn = cp.spawn;
		const pythonProcess = spawn('python',['/home/ubuntu/classify.py']);

		pythonProcess.stdin.write(req.body.image, function(err){
			pythonProcess.stdin.end();
		});

		pythonProcess.stdout.on('data', (data) => {
		    	console.log("message from python:" + data)
			});

		pythonProcess.stdout.on("end", (data) => {
  			console.log("end received data: " + data);
			res.status(200);
		    res.end(); 
		});

**Comment by addaleax** [comment]
Can you give a full example, or a reproduction? What is the result you see vs the output you expect?

**Comment by lxknvlk** [comment]
The code stops on the line specified. I have added log lines before and after that line, and i see the before log but not the after line log. There are no errors, the code just hangs on that line.

**Comment by addaleax** [comment]
Wild guess: Does that line provide output when run as a standalone python script? What happens when you add `pythonProcess.stderr.pipe(process.stderr);` to the Node.js script?

If that doesn’t help, is there any chance you could get a stack trace of where the python program is stuck? (e.g.: figure out the process id, run `gdb -p [pid]`, and run `bt` inside gdb to get a stack trace)

**Comment by lxknvlk** [comment]
Yes, it has output (lots of info logging) when run as stantalone python script. 

@addaleax thanks, i have added the line `pythonProcess.stderr.pipe(process.stderr);` and did see errors from python, there were some errors in the python script, i fixed them and now it works.

**Comment by thrinath925** [comment]
The issue you're encountering is likely due to the output not being flushed to the standard output immediately. Python buffers the output by default, so you won't see it in your Node.js script until the buffer is flushed. You can force the output to be unbuffered by setting the PYTHONUNBUFFERED environment variable before running the Python script. Here's how you can do it:
#test.py
import time

while True:
    print("Printing every 10 seconds...")
    time.sleep(5)




const { spawn } = require('child_process');
const path = require('path');

const pythonScriptPath = path.join(__dirname, 'test.py');

// Set PYTHONUNBUFFERED environment variable to force unbuffered output
const pythonProcess = spawn('python', ['-u', pythonScriptPath]);  **//if you remove -u arg you will not log in node observe** 

// Log any output from the Python script
pythonProcess.stdout.on('data', (data) => {
  console.log(`stdout from Python: ${data}`);
});

pythonProcess.stderr.on('data', (data) => {
  console.error(`stderr from Python: ${data}`);
});

pythonProcess.on('close', (code) => {
  console.log(`Python process exited with code ${code}`);
});

**Comment by briancullinan2** [comment]
I am having issues with this, did anybody find a solution? I'm getting `ImportError: Failed to load PyTorch C extensions:` after dropping into the python script.
