### ISSUE TITLE
Stream 'readable' event oddness

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#198]
* **Version**: 6.2.2
* **Platform**: Windows 7 x64

> The 'readable' event is emitted when there is data available to be read from the stream... The 'readable' event will also be emitted once the end of the stream data has been reached but before the 'end' event is emitted.

Why in this script (saved in UTF-8 with BOM) the handler is called no more and no less than twice?

```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fs = require('fs');

const readStream = fs.createReadStream(__filename, { encoding: 'utf8' });

readStream.on('readable', () => {
  console.log(readStream.read(3));
});
```
The output:
```
 ﻿/*
***
```

**Comment by vsemozhetbyt** [comment]
Call stacks for both event firing. Is the second emitting taken into account by the documentation?

![1](https://cloud.githubusercontent.com/assets/10393198/16212568/450230cc-3751-11e6-9b1f-49ef954f2c4b.png)

![2](https://cloud.githubusercontent.com/assets/10393198/16212567/44fe6ab4-3751-11e6-9087-a35620e33750.png)

**Comment by addaleax** [comment]
I think the `end of stream data` part of `The 'readable' event will also be emitted once the end of the stream data has been reached but before the 'end' event is emitted.` line refers to the `onEofChunk`, so yeah, I think the docs are correct.

I don’t know the specific reasons for this, though.

**Comment by vsemozhetbyt** [comment]
@addaleax Does `onEofChunk` means `end of Chunk` or `EOF Chunk`? If the first, is end of chunk (in the function) == end of the stream data (in the doc)? It seems not obvious. If the second, why does it fire if I does not read all the data, only some bytes? Is data read to the end anyway on the exit?

**Comment by addaleax** [comment]
`onEofChunk` means `EOF`, i.e. after all data from the source has been read into the `Readable`.

I’m not entirely sure I understand the question, but maybe the source of confusion is the fact that `Readable` streams actually buffer data to a certain degree, to have more data available for reading when the stream becomes readable.

The size of that buffer is configurable through the `highWaterMark` option, and if you set that low enough, the stream will not read then entire file:

```js
/******************************************************************************/
'use strict';
/******************************************************************************/
const fs = require('fs');

const readStream = fs.createReadStream(__filename, {
  encoding: 'utf8',
  highWaterMark: 5
});

readStream.on('readable', () => {
  console.log(readStream.read(3));
});
```

Here the `'readable'` listener only fires once, because only 5 bytes are read from the source into the stream’s internal buffer, of which only 3 bytes are used. After the `.read()` call, there will be 2 more bytes in the streams internal buffer; the stream will remain paused until these have been extracted using `.read()`, too (e.g. try setting the `3` to `5` and see what happens).

**Comment by vsemozhetbyt** [comment]
O, I think I see now. So `once the end of the stream data has been reached` also means `including being exhausted by internal buffer`?

**Comment by addaleax** [comment]
It is rather fired “as soon as it is clear that no more data will be added to the internal buffer, because the data *source* (i.e. the file itself) contains no more content”. After the last `readable` event (the onEofChunk one), the user can call `.read()` a few times to get the rest of the buffered data.

The event that is fired when all data has been read and the internal buffer has fully been cleared is the `end` event.

**Comment by vsemozhetbyt** [comment]
Phew)  Thank you for all your time and explanations!

**Comment by addaleax** [comment]
Glad if it helped, and of course feel free to ask more questions here!

**Comment by PacoHuerta** [comment]
@addaleax could you please tell me what the expected behavior is when we read a chunk size that is greater than the highWaterMark?

When executing the following: 
`
const fs = require('fs');
const rr = fs.createReadStream('foo.txt', {highWaterMark: 10});
rr.setEncoding('utf-8');
rr.on('readable', () => {
    console.log('readable event received');
    console.log('read 1:', rr.read(11));
});

rr.on('end', () => {
  console.log('end');
});
`

Where foo.txt contains (on Windows, so has carriage return):
`
12345678
abcdefgh
ijklmnop
qrstuvwx
12345678
abcdefgh
ijklmnop
qrstuvwx
`

I get the following output:
`
readable event received 1
read 1: null
readable event received 2
read 1: 12345678
a
readable event received 2
read 1: bcdefgh
ij
`
I'm sure the first read there is null because we are attempting to read more than what is available (11 > 10); however, I don't know why the program stops there. If I change the 'readable' callback to have the following two reads as opposed to the original read, the file is printed out completely:

`
...
    console.log('readable event received');
    console.log('read 1:', rr.read(6));
    console.log('read 2:', rr.read(5));
...
`
Output:
`
readable event received
read 1: 123456
read 2: null
readable event received
read 1: 78
ab
read 2: cdefg
readable event received
read 1: h
ijk
read 2: lmnop
readable event received
read 1:
qrst
read 2: uvwx
readable event received
read 1:
12345
read 2: 678

readable event received
read 1: abcdef
read 2: null
readable event received
read 1: gh
ij
read 2: klmno
readable event received
read 1: p
qrs
read 2: tuvwx
readable event received
read 1: null
read 2: null
readable event received
read 1:


read 2: null
end
`
Again, the first "read 2" line here is probably null because we want 5 bytes but only 4 are available. I don't understand why only a bit of the file is read when the chunk size is greater than the highWaterMark. Why is this the case? Are we not depleting the internal buffer on each readable event in both of the above cases? Apologies for the massive post.

**Comment by saharshjain** [comment]
@addaleax   I have a csv file and it contains 6K records and I am using streams to read and csv-parse package only.
I could see the readable event getting fired after few chunks of rows. Shall I understand that as soon as it starts reading the chunk and no more could be buffered it emits 'readable' event and when it start reading next chunk and end of chunk is reached it is fired again and so on. 

So practically 

> no. of readable events will be equal to  = start event + no. of chunks read at a time(in buffer) + end of file
