### ISSUE TITLE
Is nodejs 10.15.3 affected by CVE-2018-16065?

### ISSUE THREAD

**Issue by tom-shan** [nodejs/help#2000]
Is nodejs 10.15.3(V8 version: **6.8.275.32**) affected by [CVE-2018-16065](https://nvd.nist.gov/vuln/detail/CVE-2018-16065)?

The V8 version in Chrome 69.0.3497.81 is **6.9.427.19** according to these two links below and is great than **6.8.275.32**. So it seems that the answer is yes.

https://chromium.googlesource.com/chromium/src/+/refs/tags/69.0.3497.81/DEPS#113
https://chromium.googlesource.com/v8/v8/+/aae279118869ad4ae1f31513a8b66a17ff2f0dd4

* **Node.js Version**: 10.15.3
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: V8 6.8.275.32

**Comment by gireeshpunathil** [comment]
ping @nodejs/security

**Comment by cjihrig** [comment]
Assuming I'm running their reproduction correctly, I can't reproduce the issue on 10.15.3. Also, @ofrobots labeled https://bugs.chromium.org/p/chromium/issues/detail?id=867776#c38 as `NodeJS-Backport-Rejected` - maybe Ali can confirm.

**Comment by mcollina** [comment]
I don’t think that vulnerability is in the threat model of Node.js.

**Comment by sam-github** [comment]
In that `process.kill(0, 'SIGKILL')` is an easier way to kill the current process?

**Comment by ChALkeR** [comment]
@tom-shan Not unless you run untrusted JS code from user input inside a Node.js process, which is something one shouldn't do. It is [documented](https://nodejs.org/api/vm.html#vm_vm_executing_javascript) that VM module is not a security mechanism, for example. If you have to run js code from user input -- it has to be done inside at least an isolated and sandboxed process or a container / virtual machine.

That is what is meant by that this vuln is not in the threat model of Node.js -- to exploit this vuln (even if it affects Node.js), the attacker has at least to obtain prior access to running arbitrary untrusted JS code in the Node.js process, which is already bad enough so that this vuln won't be needed.

**Comment by ofrobots** [comment]
Apart from the trust model making the fix not a security issue for Node.js, the fix is, in fact, already in Node 10. It was merged to the V8 6.8 branch in version 6.8.275.25 ([branch history](https://chromium.googlesource.com/v8/v8.git/+log/branch-heads/6.8)) as https://github.com/v8/v8/commit/ddbaf97.
