### ISSUE TITLE
http request - how to handle 413 error from server

### ISSUE THREAD

**Issue by RidgeA** [nodejs/help#2034]
* **Node.js Version**: v11.15.0
* **OS**: Fedora Linux 5.1.15-300.fc30.x86_64
* **Scope (install, code, runtime, meta, other?)**: code?
* **Module (and version) (if relevant)**: n/a

I have the following code snippet:

I created a server that listens to incoming requests and returns body size.
And I added limitation - I don't want to handle body greater than 2^15 (this number comes from default `highWaterMark` value which is 2^14, I just want to handle `data` event several times).
In a real-world use case, this is an HTTP handler that handles files upload.
Also, I have a client-side code (in my case client - is an integration test, but it could be another NodeJS application as well), that sends some data to the server.
When I the client sends data to the server more than the server is going to handle I want to get just a regular HTTP response with 413 status, but instead of that I got and error:

```
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:71:16)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at ClientRequest.onerror (_stream_readable.js:729:7)
    at ClientRequest.emit (events.js:193:13)
    at Socket.socketErrorListener (_http_client.js:397:9)
    at Socket.emit (events.js:193:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:621:3)
```

Here is code snippet:
```js
// server
const { createServer } = require('http');
const server = createServer((req, res) => {
  console.log("Got request");

  let bodySize = 0;

  req.on('data', chunk => {
    bodySize += chunk.length;
    console.log('Got chunk ' + bodySize);

    if (bodySize > 1 << 15) {
      console.log("Body to large");
      res.statusCode = 413;
      res.setHeader('Connection', 'close')
      res.end();
      req.removeAllListeners('data');
    }
  });

  req.on('end', () => {
    res.end(bodySize.toString());
  });
});

server.listen(3000);

// client
const { Readable } = require('stream');
const { randomBytes } = require('crypto');
const { request } = require('http');
const req = request("http://localhost:3000", {method:"POST"});

req.on('response', res => {
  console.log('response: ', res.statusCode);
})

const inputData = new Readable({
  read(size) {
    this.push(randomBytes(size));
    return;
  }
});
inputData.pipe(req);
```

To my understandig, this is happening because the stream, that produces data, tries to write to stream that already closed

So here are my questions:

1. Does this expected behavior?
2. Is there another way to handle this case and read a response from the server other than handle `error` and `response` events (with built-in modules)?
3. Maybe the server's code could be modified to handle this case properly?

**Comment by wide4head** [comment]
@RidgeA  see if you can use https://expressjs.com/en/resources/middleware/body-parser.html

**Comment by RidgeA** [comment]
@wide4head how it would help?

Moreover, as I can see now, there is `resueme` method used.

I suppose It is intended to overcome this issue and reads *entire* body before send 413 error.

But if I add this to my example, this will lead to endless streaming. 
Obviously, this is not a common use-case to have infinity incoming stream, however, it is possible to transfer huge amount of data and then get an error that body to large. I would prefer to get this error as early as possible.

**Comment by Hakerh400** [comment]
Running your code on v11.15.0 and v12.0.0 I get ECONNRESET rather than EPIPE.

**Comment by RidgeA** [comment]
>  ECONNRESET rather than EPIPE
Which OS?

> I still don't get any errors on the server script.
The error happens on client-side

**Comment by Hakerh400** [comment]
It seems that the behavior is different between Windows and Linux. On windows [it throws ECONNRESET](https://travis-ci.org/Hakerh400/test/builds/556412553), while on Linux [it throws EPIPE](https://travis-ci.org/Hakerh400/test/builds/556410739), but that is probably working as intended.

After looking more closely to your sample script, it is unclear to me what your goal here is. Do you want to adapt server script to the client script, or vice versa? Or do you want to modify both server and client scripts to avoid the error? In case of latter, the example is still unclear: you're writing endless stream of data from the client to the server socket and you want to receive the server's response while still sending data. That doesn't make much sense.

Node's HTTP request object is a high-level abstraction wrapper around net socket. Writing data to closed socket throws error. Even if you modify `inputData` stream to check if `req.socket` is closed and then stop streaming random bytes, it would still not work, since the server may split chunks at different locations and some data from the previous chunk may remain in the internal buffer, leading to `EPIPE` or `ECONNRESET` error.

If I understood your question properly (please correct me if I'm wrong), you want to stream random bytes from the client side until the server closes the connection, then you want to obtain the status code, right? It can probably be achieved using `net.Server`, but it may not be trivial.

**Comment by RidgeA** [comment]
@Hakerh400 thank you for the detailed response

First of all my intention was to understand is it a bug or it is expected behavior. 
My first thought was that it is a bug and piping should hangle this case internally, and do not throw `EPIPE` error (or `ECONNRESET`).
However, after some reflection and your answers, I came up to the idea that most likely it is the proper behavior.
`http.ClientRequest` emits `response` event where I can get a response from a server with status code and body, and at the same time, it emits `error` event as well to indicate that something went wrong with streaming (maybe it should be handled somehow, according to an application logic). In this case - the reader was closed before the writer ends. 
The code snippet was intended to reproduce the case.
Obviously, an endless stream has no sense, this is was just an emulation of sending body much bigger than server accepts, for instance, the server expects to get file not bigger than 10Mb, but a client sends 10Gb.

> Even if you modify inputData stream to check if req.socket is closed and then stop streaming random bytes, it would still not work, since the server may split chunks at different locations and some data from the previous chunk may remain in the internal buffer, leading to EPIPE or ECONNRESET error.

I thought to add a transform stream between the reader stream and writer stream to check if the writer not closed yet.
But I agree with you that it wouldn't work and there is a chance to get `EPIPE`/`ECONNRESET` anyway. 

Since the answer is clear for me, I think this issue could be closed.
