### ISSUE TITLE
Can't use import.meta even with type: module set

### ISSUE THREAD

**Issue by PassTheMayo** [nodejs/help#2058]
* **Version**: `v12.6.0`
* **Platform**: `Windows 10 1903 18362.239`
* **Subsystem**: None

I have created a new folder, with my `package.json` at the root. The property `type` is set to `module` and the `main` property is pointed to my `src/index.js` file. Upon trying to use `node .` at the root of my folder, I am still faced with the problem where I can't use `import.meta` outside of a module. The full error is posted below.
```js
SyntaxError: Cannot use 'import.meta' outside a module
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

![image](https://user-images.githubusercontent.com/16949253/61417785-0bfea080-a8be-11e9-9d2d-efd4fb8fc8c3.png)
![image](https://user-images.githubusercontent.com/16949253/61417808-19b42600-a8be-11e9-9c1b-a3d8f6c10919.png)

I'm just experimenting with how this works in context, I don't actually know if the code I posted would be functional or not.

Is this something that I'm doing wrong, or is this just a partially implemented support for the new `type` property in the package?

**Comment by guybedford** [comment]
The problem here is that the ES module resolution system does not resolve the main of local files. Instead you need to specify the file directly - `node src/index.js`.

The problem you are hitting here is that `node .` is actually resolving to `/path/to/app` where say your package.json is located at `/path/to/app/package.json`. The ES module resolver sees `/path/to/app` and doesn't recognize that as a module (no mjs extension, or package.json type module), and thus defers to the CommonJS resolver.

Usually the ESM resolver only defers to the CommonJS resolver when there is a .js file extension, but for the main entry into Node.js it will support no file extension due to the need to support package bin file use cases.

One thing we could do to fix this error is to do a stat on the resolved file and if it is a directory, to not support deferring to the CommonJS resolver.

**Comment by PassTheMayo** [comment]
@guybedford I tried what you said and I'm still experiencing this issue
![image](https://user-images.githubusercontent.com/16949253/61418347-d9ee3e00-a8bf-11e9-9c30-39770e8271a1.png)

Additionally, if I do it the correct way and use the `--experimental-modules` flag, then now if I attempted to use `import { Website } from './Website'` in my file, then it doesn't correctly resolve to `Website.js` in the same directory, and it also doesn't work if I rename it to `Website.mjs`. I just think the whole file resolving system is pretty broken, and could be improved.

**Comment by guybedford** [comment]
You must use `--experimental-modules`. If the first case wasn't happening with `--experimental-modules`, then my entire thesis is gibberish :P

**Comment by PassTheMayo** [comment]
@guybedford Even with `--experimental-modules` enabled, it's still not able to find `Website.js` using `import './Website'`
![image](https://user-images.githubusercontent.com/16949253/61418863-a14f6400-a8c1-11e9-8739-b408cf4d067a.png)

**Comment by devsnek** [comment]
you need to include the extension or use `--es-module-specifier-resolution=node`

**Comment by PassTheMayo** [comment]
@devsnek Thanks, that was able to solve it.
