### ISSUE TITLE
there is stderr about  "dos2unix"

### ISSUE THREAD

**Issue by hwbeauty** [nodejs/help#206]
test.js:
  childProcess.exec('sh test.sh',function(error,stdout,stderr) {
}
test.sh:
# !/bin/bash

dos2unix /home/ins.sh

![image](https://cloud.githubusercontent.com/assets/19684476/16367470/5f13488e-3c56-11e6-9a9e-a07ecd6095db.png)

I do not know why this error ...

**Comment by CodeMan99** [comment]
Pretty sure that isn't an error, rather the author of `dos2unix` uses stderr for normal output so that piping doesn't break.

For example, if you do `cat somedosfile | dos2unix | less`, then `less` will receive the converted file, and the text _dos2unix: converting file somedosfile to UNIX format ..._ will be written to stderr.
