### ISSUE TITLE
ESM loader cannot find a module detected by rollup

### ISSUE THREAD

**Issue by pravi** [nodejs/help#2081]
* **Version**: v12.7
* **Platform**: linux
* **Subsystem**:

With the following test code (test.mjs),

```
import { encode } from 'sourcemap-codec';
 console.log(encode);
```
And rollup.config.js

```
import resolve from 'rollup-plugin-node-resolve';
const plugins = [ resolve(), ];
export default [                                        /* umd */                                       
{                                                       input: 'test.mjs',                              
plugins,                                        
output: {                                               
file: 'bundle.js',                              
format: 'umd',                                  
name: 'Test',                                   
sourcemap: true                         
}
        
}
];
```

Run `npm install sourcemap-codec`

Then `rollup -c`
```
test.mjs → bundle.js...

created bundle.js in 41ms
```
There are no warnings and 

```
$ node bundle.js
[Function: encode]
$
```
But 
```
$ node --experimental-modules test.mjs                   
(node:26761) ExperimentalWarning: The ESM module loader is experimental.
file:///home/praveen/forge/test-rollup/test.mjs:1

import { encode } from 'sourcemap-codec';
         ^^^^^^                                 SyntaxError: 
The requested module 'sourcemap-codec' 
does not provide an export named 'encode'
 
   at ModuleJob._instantiate 
(internal/modules/esm/module_job.js:93:21)                          
  at async ModuleJob.run 
(internal/modules/esm/module_job.js:108:20)                             
 at async Loader.import 
(internal/modules/esm/loader.js:134:24)
```

**Comment by devsnek** [comment]
once could make a loader hook for node which duplicates whatever the behaviour of rollup is, but node core itself isn't trying to match any specific bundlers.

**Comment by pravi** [comment]
@devsnek aren't both rollup and node implementing the same standard? Do you think rollup implementation is wrong?

**Comment by devsnek** [comment]
@pravi i don't know quite how rollup's works, but there are a few things to note here. Firstly, esm doesn't specify how implementations perform resolution at all, so node and rollup can have completely different ways of deciding if a file is an es module and still be standards compliant. Looking at the `sourcemap-codec` package, it is likely that rollup is using the `"module"` field of sourcemap-codec's package.json. However, many usages of the `"module"` field in package.json have been found to be incompatible with spec compliant esm (there's a long story here about babel handling graph validation incorrectly, but not very relevant at this point). Because of this, node does not use the `"module"` field at all, so it will end up resolving the umd bundle that sourcemap-codec ships, which is decidedly not esm.

**Comment by pravi** [comment]
@devsnek thanks for the clarification, I have opened an issue with sourcemap-codec.

**Comment by devsnek** [comment]
@pravi i would recommend against asking random packages to make themselves work with node's esm system until it is stable. we might change everything about it, and then the packages will still be incompatible.

**Comment by pravi** [comment]
@devsnek OK, I will stop with this issue for now. Is there a list of blockers or a roadmap for this to be declared stable?

**Comment by devsnek** [comment]
more or less https://github.com/nodejs/modules/issues

**Comment by pravi** [comment]
But if they add "module": " es6-entry.mjs", and other modules explicitly calling "module/es6-entry.mjs", won't it work for both loaders?

**Comment by PoojaDurgad** [comment]
@Pravi , is this still an issue ?

**Comment by gireeshpunathil** [comment]
inactive, closing
