### ISSUE TITLE
What is shared internal memory pool?

### ISSUE THREAD

**Issue by LvChengbin** [nodejs/help#2086]
I saw the following paragraph in the documentation of [Buffer](https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe).

> Buffer instances returned by Buffer.allocUnsafe() may be allocated off a shared internal memory pool if size is less than or equal to half Buffer.poolSize. Instances returned by Buffer.allocUnsafeSlow() never use the shared internal memory pool.

I want to know what the "shared internal memory pool" is and the pros and cons of using it.
I know it may be a stupid question, and I'll appreciate it if some one can help me.

**Comment by tniessen** [comment]
> I want to know what the "shared internal memory pool" is and the pros and cons of using it

Allocating heap memory can be slow, and allocating small amounts can lead to fragmentation. That is why node keeps an internal "memory pool", which is essentially a large segment of preallocated memory. When you create small buffers, Node.js can give you a slice of that large segment instead of having to allocate additional heap memory, leading to faster allocation and less memory fragmentation. There are very few downsides, and most applications should not have to worry about it.

**Comment by LvChengbin** [comment]
@tniessen thank you for your explanation.
