### ISSUE TITLE
Creating Directory and Adding Multiple Sub-Directories. (NOT NESTED)

### ISSUE THREAD

**Issue by Lowmana69** [nodejs/help#2093]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I would like some assistance if possible. I would like to create a directory and add multiple subdirectories (NOT NESTED). I have tried 

* make-dir
* fs-extra
* mkdir

None of these can give me the right results. Here is an example of what I would like.

Ex. 

Directory
   - Subdirectory
   - Subdirectory
   - Subdirectory

Is this possible? Please help me.

Thank you

**Comment by Hakerh400** [comment]
```js
(async () => {
  const fs = require('fs').promises;
  await fs.mkdir('main-directory');
  await fs.mkdir('main-directory/sub-directory-1');
  await fs.mkdir('main-directory/sub-directory-2');
  await fs.mkdir('main-directory/sub-directory-3');
})().catch(console.error);
```

It will create the following structure:

```
main-directory
├───sub-directory-1
├───sub-directory-2
└───sub-directory-3
```

If you need more complex directory structure, see https://github.com/nodejs/help/issues/1840#issuecomment-478124633

**Comment by gtkpr** [comment]
> ```js
> (async () => {
>   const fs = require('fs').promises;
>   await fs.mkdir('main-directory/sub-directory-1');
>   await fs.mkdir('main-directory/sub-directory-2');
>   await fs.mkdir('main-directory/sub-directory-3');
> })().catch(console.error);

Can't you remove `await fs.mkdir('main-directory')` since any of the following statements will also create `main-directory` if it does not already exist?

Also, isn't `mkdir` inherently asynchronous already? What is the purpose of adding the additional asynchronous stuff?

**Comment by Hakerh400** [comment]
> Can't you remove await fs.mkdir('main-directory') since any of the following statements will also create main-directory if it does not already exist?

No, it doesn't create `main-directory` implicitly, unless you provide `recursive` flag. See [this](https://travis-ci.org/Hakerh400/test/jobs/593856016) and [this](https://travis-ci.org/Hakerh400/test/jobs/593856017).

> Also, isn't mkdir inherently asynchronous already? What is the purpose of adding the additional asynchronous stuff?

I really don't know what you mean. CJS modules are synchronous functions, so we need to define an async IIFE in order to use `await` keyword. And `await` is used to ensure that all directories are created when the function returns.

**Comment by gtkpr** [comment]
> No, it doesn't create `main-directory` implicitly, unless you provide `recursive` flag. See [this](https://travis-ci.org/Hakerh400/test/jobs/593856016) and [this](https://travis-ci.org/Hakerh400/test/jobs/593856017).

Whoops. You're right. I forgot I've been using the `recursive` option.

> > Also, isn't mkdir inherently asynchronous already? What is the purpose of adding the additional asynchronous stuff?
> 
> I really don't know what you mean. CJS modules are synchronous functions, so we need to define an async IIFE in order to use `await` keyword. And `await` is used to ensure that all directories are created when the promise resolves.

[`fs.mkdir`](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback)
Literally the very first thing the documentation mentions is, **"Asynchronously creates a directory."**

[`fs.mkdirSync`](https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options)
Also the very first thing the documentation mentions, **"Synchronously creates a directory."**

That is what I mean...

**Comment by Hakerh400** [comment]
@gtkpr Then you misunderstand how async stuff work and what the purpose for it actually is. I'll try to make it clear.

By default, there is only one thread in a Node.js application that executes JavaScript code (other threads are hidden from user interface). Any thread can be in two states: executing code or waiting for an I/O operation to finish (read from disk, create a file, download from URL, etc). If a thread is waiting for an I/O operation, it cannot execute code until the operation is finished. That being said, the goal is to delegate I/O operations to other threads (which run in parallel) and leave the main thread to continue running JS code, while other threads are waiting for I/O. Once the I/O operation finishes, a new event is scheduled in the event loop and will be performed in the next tick on the JS thread.

Because of that, Node.js provides two types of functions: synchronous and asynchronous. Synchronous functions block the main JS thread and are generally discouraged. They wait for the operation to finish and prevent the rest of the code to execute. On the other hand, asynchronous methods, which are generally recommended, do not perform the operation immediately, but delegate the operation to another thread and continue running JS code.

`fs.mkdir` is asynchronous, while `fs.mkdirSync` is its synchronous conuterpart. Any asynchronous function that takes a callback as the last argument can be promisified using `util.promisify` function, making the new function return a promise and the callback argument is replaced by the promise `then` or `catch` branch. In my example above, I use `fs.promises`, which contain inherently promisified versions of all `fs` asynchronous functions.

To summarize:

* `fs.mkdirSync` - Synchronous
* `fs.mkdir` - Asynchronous, takes a callback
* `fs.promises.mkdir` - Asynchronous, does not take a callback, but returns a promise

The reason we use another level of encapsulation inside async IIFE is to achieve synchronization. We want to make sure that the main directory is created before we create a subdirectory. Also, we want to somehow know when all directories are successfully created.

If we did not use `async` stuff, it might throw an error:

```js
const fs = require('fs');        // No promises
fs.mkdir('main');                // Schedule directory creation
fs.mkdir('main/sub');            // Main dir may not be created at this point in time,
                                 // which would throw an error
```

That is the reason we need to use `await` - to make sure one operation finished before we start another one. The difference between awaiting an async operation and executing a synchronous operation is because async operation allows other JS code to run (except in the current async function).

**Comment by gtkpr** [comment]
> That is the reason we need to use `await` - to make sure one operation finished before we start another one. The difference between awaiting an async operation and executing a synchronous operation is because async operation allows other JS code to run (except in the current async function).

It was the whole promise thing that I didn't understand.

It just seems redundant to me to use asynchronous methods in a synchronous manner, and then encapsulate it all in an extra layer of asynchronization in order to achieve asynchronization.

Wouldn't something like the following code be less contradictory and redundant, much cleaner, and easier to understand?

```js
const
  fs = require('fs'),
  dirs = [
    'main-directory/sub-directory-1',
    'main-directory/sub-directory-2,
    'main-directory/sub-directory-3' ]

dirs.forEach((v)=>{
  fs.mkdir(v, {recursive:true}, (err)=>{
    throw(err)
  })
})

**Comment by Hakerh400** [comment]
> Wouldn't something like the following code be much cleaner, easier to understand, and less complex, contradictory, and redundant?

Your code makes sense if that is the only code in your application. However, usually creating a directory is a part of a more complex workflow, so we need make the rest of the code to wait for the directories to be created.

Here is an example: imagine you have a function `f` which takes (as the only argument) a path to an existing directory, which contains three existing subdirectories, and extracts the content of some archive into the directory and subdirectories. So, in order to use `f`, you need to create the main directory and three subdirectories first, In other words, you need to make sure not to call `f` before the directories are created. How would you achieve that using your example? You could try

```js
const
  fs = require('fs'),
  dirs = [
    'main-directory/sub-directory-1',
    'main-directory/sub-directory-2',
    'main-directory/sub-directory-3' ]

dirs.forEach((dir)=>{
  fs.mkdir(dir, {recursive:true}, (err)=>{
    throw(err)
  })
})

f('main-directory') // Error: directory does not exist
```

but it would throw an error, because the main directory is not created yet. You could also call `f` inside the callback of a subdirectory creation, but you'll end up calling `f` three times, which is not what you want. You'll need to use some counter and call `f` if the counter becomes 3, which makes the code less intuitive to work with. Even worse, if you have more complex directory structure, or even unknown before the runtime, you would need to implement a lot of complex callback conditions in order to call `f` at the right time.

The async/await provides synchronous syntax (no callbacks), but asynchronous execution (no blocking event loop).

```js
(async () => {
  const fs = require('fs').promises;
  await fs.mkdir('main-directory');
  await fs.mkdir('main-directory/sub-directory-1');
  await fs.mkdir('main-directory/sub-directory-2');
  await fs.mkdir('main-directory/sub-directory-3');
  f('main-directory'); // Works fine, all directories are created before this point
})().catch(console.error);
```

I really don't know what I am supposed to say more about it. That is how the things work. You can find a lot of blogs/tutorials/discussions about this topic, so feel free to explore.

**Comment by gtkpr** [comment]
> In other words, you need to make sure not to call `f` before the directories are created. How would you achieve that using your example? You could try
> 
> ```js
> const
>   fs = require('fs'),
>   dirs = [
>     'main-directory/sub-directory-1',
>     'main-directory/sub-directory-2',
>     'main-directory/sub-directory-3' ]
> 
> dirs.forEach((dir)=>{
>   fs.mkdir(dir, {recursive:true}, (err)=>{
>     throw(err)
>   })
> })
> 
> f('main-directory') // Error: directory does not exist
> ```
> 
> but it would throw an error, because the main directory is not created yet.

You're simply wrong, unless I'm misunderstanding your premise. The directory would be created if it did not already exist since the `recursive` flag is set to `true`. You pointed this out yourself earlier.

**Comment by gtkpr** [comment]
@Hakerh400 I understand what you're saying, and, yes, the promise is perfect for that scenario. However, the OP was simply asking how to create three directories, so the rest of it is unnecessary unless you find yourself in a situation like the one you described in your last message. That is all I was saying.

**Comment by gireeshpunathil** [comment]
@Lowmana69 - is this still outstanding?

**Comment by PoojaDurgad** [comment]
@Lowmana69 , is this still an issue? were you able to follow @Hakerh400 's suggestion?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
