### ISSUE TITLE
fs.writeFileSync not writing but doesn't give any errors.

### ISSUE THREAD

**Issue by naenaeMaster69** [nodejs/help#2116]
I try using this to write the values of my money file, but when I write it it doesn't save but it also doesn't give out an error. It worked on other projects that are running the same versions and on the same OS, but for some reason this doesn't work.

```js
// Other requires that aren't related

const fs = require("fs");

// Other code that isn't related

money[message.author.id] = {

            bank: 1000,
            cash: 0

 };

fs.writeFileSync("../money.json", JSON.stringify(money), (err) => {

       if (err) console.log(err)

});
```

The money.json file currently looks like this

```js
{}
```

**Comment by Hakerh400** [comment]
Unable to reproduce the issue. The following code:

```js
const fs = require('fs');
const money = {};
const message = {author: {id: 0}};
money[message.author.id] = {
  bank: 1000,
  cash: 0,
};
fs.writeFileSync('../money.json', JSON.stringify(money));
```

properly creates `money.json` file in the parent directory and writes the following content to it:

```json
{"0":{"bank":1000,"cash":0}}
```

There is not enough information in your code snippet to reliably tell what the problem is, but the problem could be among these:

- `fs.writeFileSync` does not take a callback. If an error occurs, it will throw the error immediately, since it is synchronous. Either change it to `fs.writeFile`, or remove the callback.
- Where is `money` defined and how exactly the definition of that variable look like?
- Are you sure the assignment `money[message.author.id] = ...` happens synchronously, or at least before `fs.writeFileSync` call?
- Note that `'../money.json'` resolves relatively to the current working directory `process.cwd()`, rather to the current script directory `__dirname`. Are you sure you're looking at the correct file?

---

One possible mistake that you may be doing is this:

```js
const fs = require('fs');
const money = {};
const someAsyncStuff = f => setTimeout(f);
someAsyncStuff(() => {
  const message = {author: {id: 0}};
  money[message.author.id] = {
    bank: 1000,
    cash: 0,
  };
});
fs.writeFileSync('../money.json', JSON.stringify(money));
```

where `someAsyncStuff` can be any function that performs some asynchronous actions and then calls the provided callback (it can be selecting from a database, reading from a file, fetching remote URL, etc).

If you share the whole code, the problem will be revealed more easily.

**Comment by naenaeMaster69** [comment]
@Hakerh400 I tried fs.writeFile and it fixed it. Thank you.
