### ISSUE TITLE
dns.resolve{4,6} can not handle "localhost" in docker

### ISSUE THREAD

**Issue by murgatroid99** [nodejs/help#2163]
* **Version**: 12.9.0
* **Platform**: Docker image `node:12` from Docker Hub
* **Subsystem**: dns

Test cases:

```js
const dns = require('dns');
dns.resolve4('localhost', console.log);
dns.resolve6('localhost', console.log);
```

Expected result:

```
null ['127.0.0.1']
null ['::1']
```

Actual result:

```
Error: queryA ENOTFOUND localhost
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:202:19) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'queryA',
  hostname: 'localhost'
}
Error: queryAaaa ENOTFOUND localhost
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:202:19) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'queryAaaa',
  hostname: 'localhost'
}
```

When running this code in the host machine (Linux, Node 12.9.0), I get the expected result.

The contents of `/etc/hosts`:

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.9.2	73514428cae4
```

**Comment by murgatroid99** [comment]
It looks like it never tries to read from `/etc/hosts`, even though it does read from `/etc/nsswitch.conf`, which contains the line `hosts:          files dns`.

**Comment by murgatroid99** [comment]
For completeness, the full strace output is here: https://gist.github.com/murgatroid99/6b0b1d72f60b83f4481c12546bbaf305

**Comment by murgatroid99** [comment]
For contrast, when the `grpc` library uses cares to perform DNS name resolution, it does open `/etc/hosts` and it does successfully resolve `localhost` within an identical docker image. This implies that there is something about the way that node is invoking cares that causes it to skip `/etc/hosts`. This appears to be caused by using `ares_query` instead of `ares_gethostbyname` in the implementation of `resolve4` and `resolve6`. I believe that unnecessarily limits the functionality of those functions, and that it is therefore a bug and should be moved back to the main node repository.

**Comment by bnoordhuis** [comment]
I think I know what's causing this and I don't think it's a bug - at least not in Node.js.

c-ares pulls the nameserver to query from `/etc/resolv.conf` and it's up to that nameserver to return a result for `localhost`. Compare:
```
$ nslookup localhost 4.2.2.1 | tail -n+4
Non-authoritative answer:
Name:   localhost
Address: 127.0.0.1

$ nslookup localhost 8.8.8.8 | tail -n+4
** server can't find localhost: NXDOMAIN
```
Your docker image is using 8.8.8.8 as the nameserver, ergo, that's why it doesn't work:
```
connect(17, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
# ...
sendto(17, "@z\1\0\0\1\0\0\0\0\0\0\tlocalhost\0\0\1\0\1", 27, MSG_NOSIGNAL, NULL, 0) = 27
```

**Comment by murgatroid99** [comment]
There are two separate things happening here that are together causing this problem:

 1. Node is using `ares_query` instead of `ares_gethostbyname` to do DNS lookups. Because of that, it is directly sending requests to DNS servers, bypassing the setting in `/etc/nsswitch.conf` that indicates that DNS lookups should check `/etc/hosts` before making requests to DNS servers.

 2. Some name servers have entries for `localhost` and some don't, so the behavior varies depending on the configured name servers.

I would say that number 1 is a bug even though that bug is sometimes mitigated by number 2.

**Comment by nicolasnoble** [comment]
> c-ares pulls the nameserver to query from `/etc/resolv.conf` and it's up to that nameserver to return a result for `localhost`. Compare:

This statement is false. localhost is supposed to be an /etc/hosts plaintext file entry, mainly because it needs to work even if you don't have any network. The fact some nameservers provide it is simply a courtesy, not the intended mechanism.

Consider a machine that is isolated from any network whatsoever, which needs to do any sort of airgapped work. Resolving "localhost" still works, because it's present in /etc/hosts. And localhost needs to work because the only network interface available on an airgapped machine is the loopback interface with 127.0.0.1.

What you're currently saying is that nodejs can't do localhost networking on an airgapped machine.

**Comment by bnoordhuis** [comment]
If you want gethostbyname-like behavior, use `dns.lookup()`. That calls out to the platform's `getaddrinfo(3)` and provides a superset of `gethostbyname(3)` functionality.

c-ares's `ares_gethostbyname()` is not a substitute for either `getaddrinfo(3)` or `ares_query()` because it's too limited. It doesn't support mDNS, for example.

c-ares parses `/etc/resolv.conf` and `/etc/nsswitch.conf` to find out what sources to consult and in what order. Your issue is almost certainly a configuration issue, not a c-ares bug.

Example: if you don't have an `/etc/resolv.conf` and your `/etc/nsswitch.conf` contains a `hosts: dns [!UNAVAIL=return] files` stanza (pretty standard), then it's always going to use DNS unless the resolver is down.

And caveat emptor, malformed conf files will subtly break c-ares. I just filed https://github.com/c-ares/c-ares/pull/274 to fix one such issue.

**Comment by murgatroid99** [comment]
As I said in a previous comment, my `/etc/nsswitch.conf` contains the line `hosts: files dns` which means that it should be using local files before dns. And I already said that in an identical environment, Node does not attempt to open `/etc/hosts` but a different program also using c-ares does, which implies that the difference is not in the machine configuration but in Node's behavior.

That being said, after looking at the documentation again I think I can actually use `dns.lookup` where I am currently using `dns.resolve`.

**Comment by bnoordhuis** [comment]
I looked into what parts of c-ares do and don't support file-based lookup and `ares_query()` falls in the "don't" category.

Ergo, https://github.com/nodejs/help/issues/2163#issuecomment-528766734 is the final answer w.r.t. `dns.resolve()`. Use `dns.lookup()` instead.

**Comment by murgatroid99** [comment]
But `dns.resolve` doesn't need to be implemented in terms of `ares_query`. Isn't it worth considering that maybe it should be implemented differently so that it can support file-based lookup?

**Comment by bnoordhuis** [comment]
The reason `dns.resolve()` exists is because it's much faster than `dns.lookup()`. Doing bulk DNS lookups in Node.js is a thing.

Introducing a `/etc/hosts` check would slow that down and people are sure to take notice of that (and file issues and complain about it - it's happened before.)

It's possible to add an opt-in flag that inserts an `ares_gethostbyname_file()` call but it would only be meaningful for variants of `dns.resolve()` that do A or AAAA lookups.

It doesn't seem that useful to me when `dns.lookup()` exists but you could open a PR and see how it's received.
