### ISSUE TITLE
Failing deconstruction does not throw exception

### ISSUE THREAD

**Issue by haraldrudell** [nodejs/help#2182]
Should the below program not throw an exception? it does exit 0

Secondly, would it not be better if ECMAScript just assigned undefined to everything when deconstruction fails on function invocation? like change ES2020

Version: v12.9.1
Platform: Darwin c87m1.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

```// © 2019-present Harald Rudell <harald.rudell@gmail.com> (http://www.haraldrudell.com)
// Node.js v12.9.1
// node --experimental-modules --no-warnings src/test.js
class X {
  async run({value}) {}
}
f()
async function f() {
  return new Promise((resolve, reject) => {
    const x = new X()
    return x.run()
  })
}
```

**Comment by addaleax** [comment]
The failing deconstruction *does* throw an exception here.

However, because that ends up as a rejected Promise in your code, it is reported as an `UnhandledPromiseRejectionWarning` rather than crashing the process. Since you explicitly specified `--no-warnings`, nothing gets printed to stderr.

It’s a point of debate of whether not crashing the process is the right thing to do, but that’s the default behaviour right now. You can pass `--unhandled-rejections=strict` to Node.js to change this behaviour so that the unhandled rejection *is* treated like an uncaught exception and always generates output + a non-zero exit code.

**Comment by haraldrudell** [comment]
No more **--no-warnings** or Node.js will be forever mysterious
