### ISSUE TITLE
How to simulate http request using buffer?

### ISSUE THREAD

**Issue by bzmlxos** [nodejs/help#2208]
* **Node.js Version**: v12.10.0
* **OS**: windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http & stream

I want to create an http server which does not listen any port and I want to inject this specific request to the server:

```
GET /docs/index.html HTTP/1.1
Host: www.example.com
Accept: image/gif, image/jpeg, */*
Accept-Language: en-us
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)

Mike
```

and I want to get this response:

```
HTTP/1.1 200 OK

Hello, Mike!
```

I have written the below code:

```js
var http = require("http");
var stream = require("stream");

var server = http.createServer((req, res) => {
  var buffers = [];

  req.on("data", buf => buffers.push(data));

  req.on("end", () => {
    res.end(`Hello, ${Buffer.concat(buffers)}!`);
  });
});

server.on("clientError", e => {
  console.log(e.stack);
});

server.emit("connection", new class extends stream.Duplex{
  #buffers = [];
  server = server;

  _read(){
    this.push(Buffer.from(
      "GET /docs/index.html HTTP/1.1\n" +
      "Host: www.example.com\n" +
      "Accept: image/gif, image/jpeg, */*\n" +
      "Accept-Language: en-us\n" +
      "Accept-Encoding: gzip, deflate\n" +
      "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)\n\n" +
      "Mike"
    ));
    this.push(null);
  }
  
  _write(buf, enc, cb){
    this.#buffers.push(buf);
    cb();
  }

  _final(){
    process.stdout.write(Buffer.concat(this.#buffers));
    server.close();
  }
});
```

but it does not work, I get an error when I run the program:

```
Error: Parse Error: Invalid method encountered
    at socketOnData (_http_server.js:523:22)
    at Object.emit (events.js:209:13)
    at Object.Readable.read (_stream_readable.js:520:10)
    at flow (_stream_readable.js:994:34)
    at resume_ (_stream_readable.js:975:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Please tell me what I am doing wrong and what should I change in my code to make it work.. Thanks

**Comment by bnoordhuis** [comment]
You need to use `\r\n` for line endings in HTTP requests if nothing else.

That aside, the problem is that your request doesn't have a Transfer-Encoding or Content-Length header.

That means the server assumes it's a body-less request and interprets "Mike" as the start of a new request. And that's not a valid request method, of course.

**Comment by bzmlxos** [comment]
> You need to use \r\n

Yeah, correct. Thanks, but

> That aside, the problem is that your request doesn't have a Transfer-Encoding or Content-Length header.

It says [here](https://www.ntu.edu.sg/home/ehchua/programming/webprogramming/HTTP_Basics.html) that a request doesn't need to have any of those two headers, even in the example of a valid request they didn't include any of those headers. `Content-Length` should not be mandatory, since some websites don't include it (like google drive). Regarding `Transfer-Encoding`, on MDN docs it says that "identity" is default encoding if the header is not specified...

But I tried your suggestion, added `Transfer-Encoding` (and also fixed typo `buf => buffers.push(data)`), but I still get parse error:

```js
var server = http.createServer((req, res) => {
  var bufs = [];

  req.on("data", buf => bufs.push(buf));

  req.on("end", () => {
    res.end(`Hello, ${Buffer.concat(bufs)}!`);
  });
});

server.on("clientError", e => {
  console.log(e.stack);
});

server.emit("connection", new class extends stream.Duplex{
  #bufs = [];
  server = server;

  _read(){
    this.push(Buffer.from(
      "GET /docs/index.html HTTP/1.1\r\n" +
      "Host: www.example.com\r\n" +
      "Accept: image/gif, image/jpeg, */*\r\n" +
      "Accept-Language: en-us\r\n" +
      "Transfer-Encoding: identity\r\n" +
      "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)\r\n\r\n" +
      "Mike"
    ));
    this.push(null);
  }
  
  _write(buf, enc, cb){
    this.#bufs.push(buf);
    cb();
  }

  _final(){
    process.stdout.write(Buffer.concat(this.#bufs));
    server.close();
  }
});
```

**Comment by addaleax** [comment]
@bzmlxos If you want to have a body for a `GET` request, you need to use `Transfer-Encoding: chunked` (and implement that correctly by sending `"4\r\nMike\r\n0\r\n\r\n"` as the body), or provide `Content-Length: 4` in advance; otherwise, there is no way for an HTTP server (for any HTTP server, not just Node.js) to tell whether `Mike` is the start of a new request or the body of the current request, and it will assume the former.

In your example, you also need to set `server.httpAllowHalfOpen = true;` because you close the connection (by using `.push(null)`) before the response is written. That option is, sadly, undocumented, and I don’t understand why it’s there in the first place.

**Comment by bzmlxos** [comment]
Great, that works! Thanks @addaleax and also thanks to @bnoordhuis
