### ISSUE TITLE
npm is not recognized as command

### ISSUE THREAD

**Issue by alex-jss** [nodejs/help#2211]
`c:\>npm -v & node -v v10.16.3`
`npm` is not recognized as command
windows 10 v. 1903 (18362.387)
In "environment variables" it's ok
I installed nodejs v.12.11.0, but not without result
How is can correct the error and why `npm` is not working?

**Comment by Hakerh400** [comment]
Can you post the output of the following commands:

* `set path`
* `where npm`
* `where node`

**Comment by alex-jss** [comment]
> * `set path`

`Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Acronis\CommandLineTool\;C:\openssl;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\user\AppData\Roaming\npm;C:\Users\user\AppData\Local\Microsoft\WindowsApps
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`

> * `where npm`

`C:\Program Files\nodejs\npm`
`C:\Program Files\nodejs\npm.cmd`

> * `where node`

`C:\Program Files\nodejs\node.exe`

**Comment by Hakerh400** [comment]
What is the exact output of `npm -v` ?

**Comment by alex-jss** [comment]
displays nothing

**Comment by Hakerh400** [comment]
Literally nothing? You previously said it prints `npm is not recognized as command`, what do you mean by that? What does `node -v` print? What is the output of command `echo %errorlevel%` if you execute it immediately after `npm -v` ?

**Comment by alex-jss** [comment]
![npm_err](https://user-images.githubusercontent.com/44188728/65832391-d9b4ea80-e2d3-11e9-8b5a-30453fd05b92.png)

**Comment by Hakerh400** [comment]
`-1073741819` means segfault. There are three possible causes: 1) there is a bug in NPM, 2) there is a bug in Node.js, or 3) your Node.js binary is corrupted. Please post the output of

```
certutil -hashfile "C:\Program Files\nodejs\node.exe" sha256
```

Also, can you compress `C:\Program Files\nodejs` folder into a RAR or ZIP archive and share it here?

**Comment by alex-jss** [comment]
`c:\>certutil -hashfile "C:\Program Files\nodejs\node.exe" sha256`
`Хэш SHA256 C:\Program Files\nodejs\node.exe:
cb8f5c1981e11a3d438b6867df5fb8e4f77cd29ddc0856d99b62060ef991c649`

[nodejs.zip](https://github.com/nodejs/help/files/3667344/nodejs.zip)

**Comment by Hakerh400** [comment]
Thanks. Using the files from your `nodejs.zip`, I cannot reproduce the issue. It properly prints `6.9.0` for me wher running `npm -v`. It would be helpful if you can share:

* The output of `node -p process.env`
* Run `start %appdata%`, then compress and share folder `npm` from there

It would also be useful if you can open `C:\Program Files\nodejs\npm.cmd` in a text editor and replace line

```
"%NODE_EXE%" "%NPM_CLI_JS%" %*
```

with

```
"%NODE_EXE%" --inspect-brk "%NPM_CLI_JS%" %*
```

and then run `npm -v`. Does it output `Debugger listening on...`? If yes, then open Chrome devtools and click on the Node.js icon from there. Then click step-in (F11) until it crashes. What is the last line (and the stack trace) before it crashes?

**Comment by alex-jss** [comment]
[inf.zip](https://github.com/nodejs/help/files/3667467/inf.zip)
Debugging through F-11 I can’t finish it, the process lasted more than 30 minutes and it never stopped. How much time should she take?

**Comment by Hakerh400** [comment]
I'm still unable to reproduce the crash. It may be something in your system configuration or registry that is causing the problem. It would be interesting to find out what is causing the issue, since Node.js v10.16.3 is still LTS. Please try the following:

* If debugging using step-in takes too long, then you can use step-over (F10). Keep doing step-over until it crashes, but remember the place where it crashed. Then start the process again, keep pressing step-over until you reach the place where it crashed, and then click step-in instead of step-over (because step-over would crash there). After that keep doing step-over until it crashes again. Then start process again and repeat: simply use step-over everywhere, except if it crashed at that place in the previous iteration. Eventually, you will end up seeing a crash when you press step-in. Please share the stack trace at that place (one step before it crashes).

* The easiest way to debug segfaults is using [segfault-handler](https://www.npmjs.com/package/segfault-handler), but it requires [node-gyp](https://www.npmjs.com/package/node-gyp) and you cannot install node-gyp if NPM does not work for you. So, I compiled `segfault-handler` for you: download [the archive](https://github.com/nodejs/help/files/3667635/2211.zip) and extract it into `C:\` directory, then add line `require('C:/1.js')` at the beginning of `C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js` (but after the line `#!/usr/bin/env node`). Remove the `--inspect-brk` from the `npm.cmd` and run command `npm -v`. It should generate file `C:\segfault.log`. Upload that file here.

* Replace `require('C:/1.js')` with `require('C:/2.js')` in `npm-cli.js`. Remove the `--inspect-brk` from the `npm.cmd`. Start [WinDbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools) and keep it open. Run `npm -v` from command prompt, it will ask you to click enter to continue. Before that, in WinDbg choose `File -> Attach to a process` and pick `node.exe`, then click `Debug -> Go`. Now, from the command prompt click enter. WinDbg should display some log and stack trace. Share it here.

**Comment by alex-jss** [comment]
I will send you the information you requested today.
Tell me, on which version (assembly) of `Windows` did you reproduce the crash?
I installed `Node v10.16.3` on a clean `Windows` after installing all the programs and drivers.
I can assume that the accident can occur in two possible causes for me: 1) the latest version of `Windows 10 Enterprise`, 2) due to some driver or program

**Comment by alex-jss** [comment]
Debugging using `step-in` unfortunately I did not succeed. I can not catch the desired line before the accident.
Unfortunately, there was no `node.exe` process in` WinDbg`, I had to manually load it to get some result.
[segfault.log](https://github.com/nodejs/help/files/3672159/segfault.log)
[winDbg.txt](https://github.com/nodejs/help/files/3672161/winDbg.txt)

**Comment by alex-jss** [comment]
I found the cause of the `npm` crash. It was due to `openssl`, which supports the Russian GOST encryption algorithm. And this is very strange, because on another version of `Windows 10`, it works fine with` npm` and there is no crash.
If you're interested, I share my `openssl`. Sources for its assembly: `https://update.cryptopro.ru/support/nginx-gost/bin/185515/win64/gostengy.dll`
`https://github.com/deemru/openssl/releases/download/openssl-1.1.1b-gost-0.24/bin64.zip`
[openssl.zip](https://github.com/nodejs/help/files/3672286/openssl.zip)
