### ISSUE TITLE
How to make Node.js exit regardless of a native module async call pending?

### ISSUE THREAD

**Issue by o2genum** [nodejs/help#2218]
* **Node.js Version**: 10.11.0
* **OS**: Windows 10
* **Scope**: native modules

I'm writing a native module [node-winapi](https://github.com/o2genum/node-winapi/blob/master/src/addon.cc). I'm trying to implement an asynchronous function `WaitForProcessToExit(pid)`, which infinitely waits for a certain process to terminate. I'm using `Napi::AsyncWorker`.

Everything works as intended, with a caveat: this async call prevents Node.js from exiting. I want Node.js to exit when it has nothing else to do, like it does with `child_process.unref()`. How do I do that?

**Comment by o2genum** [comment]
I saw lots of cool native modules by @addaleax 
Sorry for annoyance, maybe you know if such thing is possible?

**Comment by addaleax** [comment]
@o2genum `Napi::AsyncWorker` doesn’t really support this – it’s built more with CPU-bound functions that eventually come to an end in mind.

I’m afraid you might have to use libuv directly here; calling `uv_unref()` on an `uv_async_t` would do the same thing as `child_process.unref()`, and you may have to create a separate thread for calling `WaitForProcessToExit()` manually. In order to cancel the call when Node.js exits, I think you could then register a N-API cleanup hook that stops the thread manually (which iirc works well for Windows).

I hope this helps, but feel free to follow up :)

**Comment by o2genum** [comment]
@addaleax  I'm rather scared of libuv though 😨. And its interactions with APIs of various abstraction levels (`Napi`, `node.h`). Well, I hope I find some examples in the `node` repo.

One more confusing thing that I stumbled upon: [napi_unref_threadsafe_function](https://nodejs.org/api/n-api.html#n_api_napi_unref_threadsafe_function) - does it have anything to do with the "unref from event loop" that I need? Or if it's not, maybe `uv_async_t` is obtainable from some higher-level API like `Napi` or `node.h`?

In any case, thank you!

**Comment by o2genum** [comment]
Looks like I've found a pure Napi solution. I have used `napi_threadsafe_function`. Unless I call `napi_ref_threadsafe_function()` it stays "unreffed" and doesn't keep the event loop alive. It calls `uv_async_t` stuff under the hood, indeed, and also does some async resource registrations for Node async hooks.

The only issue is that `napi_ref_threadsafe_function` is not exposed via C++ API, and mixing C/C++ doesn't always work well: https://github.com/nodejs/node-addon-api/issues/556

**Comment by o2genum** [comment]
Ok, I'm posting the link to my solution. Hope it helps someone.
https://stackoverflow.com/a/58356953/633969
