### ISSUE TITLE
Multi core usage by node js

### ISSUE THREAD

**Issue by RahulS1994** [nodejs/help#2222]
Node version - All
OS - all
Scope - single threaded execution and muticore usage of processor 

  I read lots of articles and from node doc,  I have seen that for get full strength of multi core of processors, we must have clustering or child processos modules. So as node js run on single thread it's use only single core. So multi threaded process can use multiple cores of processor. But even in libuv it's using thread pool for concurrent execution. Then why node js won't use multi cores as like any other multi threaded process, as in the background it's using multithreading.

**Comment by addaleax** [comment]
> I read lots of articles and from node doc, I have seen that for get full strength of multi core of processors, we must have clustering or child processos modules.

You would either use child processes or [Workers](https://nodejs.org/api/worker_threads.html), yes. Cluster is a framework for using child processes for certain types of parallel processing.

> So as node js run on single thread it's use only single core. So multi threaded process can use multiple cores of processor. But even in libuv it's using thread pool for concurrent execution.

The JS engine uses threads to run certain tasks in parallel (e.g. garbage collection), and libuv also uses threads, partially for I/O that does not otherwise work well with an event loop model and partially for CPU-heavy work.

> Then why node js won't use multi cores as like any other multi threaded process, as in the background it's using multithreading.

Even if Node.js does use multiple threads for some operations, what people say when they say that Node.js is single-threaded is that *JavaScript* code inside Node.js will only run in a single-threaded fashion.

Only if you want to run JS code in parallel do you need child processes or Workers.

**Comment by RahulS1994** [comment]
thank you for replay Anna Henningsen ,
