### ISSUE TITLE
A way to get a Timezone offset from IANA?

### ISSUE THREAD

**Issue by danm** [nodejs/help#2225]
I want to be able to find out a UTC timezone offset by passing a State/territory (Australia/Sydney) into `Intl` and for it to return the offset.

At the moment, I can do this.

```
const tz = new Intl.DateTimeFormat('en-GB', {
  timeZone: 'Australia/Sydney',
  timeZoneName: 'short',
}).format(new Date());

const diff = tz.split('GMT')[1];
const offset = parseInt(diff, 10);
const offsetMins = offset * 60;
```

Which gets me to where I want to be, but not particularly elegant. I'd love to be able to access the database a little easier, maybe something like.

`Intl.DateTimeFormat.getOffset('Australia/Sydney');`
returns `660`

Is there a way to do this that I don't know about. (I think this is the first time I have used the `Itnl` class)

**Comment by tniessen** [comment]
You can write a small helper function youself. We cannot add such a feature to `Intl`, since we did not design the API. The `Intl` object is part of the [ECMAScript 2020 Internationalization API Specification](https://tc39.es/ecma402/). You can try to discuss this addition with the [relevant authority](https://github.com/tc39/ecma402).

**Comment by liangchr** [comment]
Does this work with daylight savings time though?
