### ISSUE TITLE
Send RSA encrypted messages from website to nodejs server

### ISSUE THREAD

**Issue by markg85** [nodejs/help#2254]
Hi,

I'm working on a little side project to send messages from a website (pure static html/css/javascript, no server for the site itself). This is a typical client site, no server and an API server from where data is fetched to view on the client site.

So far so good.

Now i wanted to play with encryption and signing. To make sure that the API side only allows handling calls from specific clients. To do this, i first made 2 RSA pairs (one for the client, one for the API) using code like:
```js
    crypto.generateKeyPair('rsa', {
        modulusLength: 2048,
        publicKeyEncoding: {
            type: 'spki',
            format: 'pem'
        },
        privateKeyEncoding: {
            type: 'pkcs8',
            format: 'pem'
        }
    }, (err, publicKey, privateKey) => {
        console.log(publicKey);
        console.log(privateKey);
    });
```
To make it clear right here at this point. **Yes**, i used the node.js code to generate the keys for **both** the client and the API. In this case they were both running locally anyhow so it's quite safe ;) But this little detail might be important later on as the key i generate here is what i will load into the browser.

I generated the keys in Node.js because it seemed easier to me. No other particular reason.

Next, in the client side i'm loading the API public key with the following snippet:
```js
function importRsaKey(pem) {
  // fetch the part of the PEM string between header and footer
  const pemHeader = "-----BEGIN PUBLIC KEY-----";
  const pemFooter = "-----END PUBLIC KEY-----";
  const pemContents = pem.substring(pemHeader.length, pem.length - pemFooter.length);
  // base64 decode the string to get the binary data
  const binaryDerString = window.atob(pemContents);
  // convert from a binary string to an ArrayBuffer
  const binaryDer = str2ab(binaryDerString);

  return window.crypto.subtle.importKey(
    "spki",
    binaryDer,
    {
      name: "RSA-OAEP",
      hash: "SHA-256"
    },
    true,
    ["encrypt"]
  );
}

let publicKey = await importRsaKey( ... );
```
And i'm loading the **client private key** with this snippet:
```js
function importPrivateKey(pem) {
  // fetch the part of the PEM string between header and footer
  const pemHeader = "-----BEGIN PRIVATE KEY-----";
  const pemFooter = "-----END PRIVATE KEY-----";
  const pemContents = pem.substring(pemHeader.length, pem.length - pemFooter.length);
  // base64 decode the string to get the binary data
  const binaryDerString = window.atob(pemContents);
  // convert from a binary string to an ArrayBuffer
  const binaryDer = str2ab(binaryDerString);

  return window.crypto.subtle.importKey(
    "pkcs8",
    binaryDer,
    {
      name: "RSA-PSS",
      // Consider using a 4096-bit key for systems that require long-term security
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["sign"]
  );
}

let privateKey = await importPrivateKey( ... );
```
**Note** that these import functions are a direct copy/paste from the mozilla documentation for importing keys. See: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey

Now when i want to send some encrypted data from the site to the API i do:
```js
    let privateKey = await importPrivateKey(myPrivateKey);
    let publicKey = await importRsaKey(remotePubKey);

    let signature = await window.crypto.subtle.sign(
      {
        name: "RSA-PSS",
        saltLength: 32,
      },
      privateKey,
      encodedData
    );

    let signatureBuffer = bufferToBase64(signature);

    let inputBlob = enc.encode(JSON.stringify({sign: signatureBuffer, data: "some test value"}))
    const encryptedData = await crypto.subtle.encrypt({name: 'RSA-OAEP'}, publicKey, inputBlob);

    var oReq = new XMLHttpRequest();
    oReq.open("POST", "http://localhost:3000/", true);
    oReq.setRequestHeader("Content-Type", "application/x-binary");
    oReq.onload = function (oEvent) {
      console.log('Uploaded!')
    };
    
    oReq.send(new Buffer(encryptedData, 'binary'));
```
Here i have a couple of questions already.

1. Is this the correct approach to encrypt the data?
2. Is this the right way to send encrypted data?
The information regarding those seems to be _really_ sparse so i'm just taking a lot of assumptions with all of this.

Anyhow, the data does arrive at the API side
In the API side i'm loading the private key from the API like so (**we're in node.js here again**):
```js
        fs.readFile(`private`, (err, data) => {
            privateKey = crypto.createPrivateKey(data);
        })
```
And then i'm using it to decrypt the incoming data as follows:
```js
    let blob = request.body;
    let buf = new Buffer.from(blob, 'binary');
    console.log(buf)
    let decrypted = crypto.privateDecrypt({key: privateKey, oaepHash: 'sha256', padding: crypto.constants.RSA_PKCS1_PADDING}, buf);
    console.log(decrypted)
```

But this fails with ERR_OSSL_RSA_INVALID_PADDING_MODE. Now i tried different padding settings. Like i did RSA_PKCS1_OAEP_PADDING too, but it gives the same error. I tried RSA_NO_PADDING too, that doesn't give errors but seems wrong. As i'm very clearly giving SHA-256 on the client javascript side.

Here too i have a couple of questions (continuing the numbering).

3. As you can see in the client side, i'm merely posting a very simple json blob in the form of: { sign: "...", data: "..."}. Is the way i'm encrypting and signing it the right way? If not, how should that be done?
4. As binary data flows in on the node.js side, how am i supposed to get the data back? This is besides the decryption. Somehow that binary buffer needs to be turned back into a string which then needs to be turned back into a json object. I know the latte (JSON.parse(...)), but how do i turn that binary data back to a string?
5. Are Crypto (Node.js) and SubtleCrypto (bowsers) even compatible?
6. Is what i'm doing even possible in todays tech stack? Or am i waaaaaay too ahead of my time and should i wait a couple of years till this encryption becomes more common place?

I'm looking forward to your replies :)

Cheers,
Mark

**Comment by tniessen** [comment]
Hey Mark,

> 1. Is this the correct approach to encrypt the data?

It is a valid approach. RSA-PSS is generally a good schema for signing data, and RSA-OAEP is okay for encrypting small amounts of data. For a more secure variant that can handle larger messages and that provides forward secrecy, use an EC/ECDH key exchange, sign the ECDH public key with the RSA key, and then encrypt the message using AES with the key that you exchanged using EC/ECDH.

> 2. Is this the right way to send encrypted data?

It appears to be okay for small messages as long as you somehow manage the keys securely. However, if you are just looking for authentication and confidentiality, you might be better off using TLS. Also, your encryption scheme does not seem to protect against replay attacks (that is, an attacker could record the signed and encrypted message and send it to the server himself, and the server would not notice any difference).

> 3. As you can see in the client side, i'm merely posting a very simple json blob in the form of: { sign: "...", data: "..."}. Is the way i'm encrypting and signing it the right way? If not, how should that be done?

It is okay, it is not particularly efficient, but it does not compromise the security. A more efficient way would be to just concatenate the binary signature and the binary data, and to encrypt the resulting binary data. The server can derive the length of the signature from the client's public key, and can thus split the decrypted message into signature and data.

> 4. As binary data flows in on the node.js side, how am i supposed to get the data back? This is besides the decryption. Somehow that binary buffer needs to be turned back into a string which then needs to be turned back into a json object. I know the latte (JSON.parse(...)), but how do i turn that binary data back to a string?

Due to the nature of RSA, `privateDecrypt` does not support streaming. The function returns a buffer, which you can convert to a string using `buffer.toString('utf8')`, and you can then decode the string using `JSON.parse`. (Again, not particularly efficient, but it should work.)

> 5. Are Crypto (Node.js) and SubtleCrypto (bowsers) even compatible?

In general, yes. There are many features that SubtleCrypto does not support, and there are a few features that Node.js does not support, but we are working on it. RSA-PSS and RSA-OAEP should work in the most recent releases. (Setting `padding` to `RSA_PKCS1_OAEP_PADDING` and `oaepHash` to the desired hash should work.)

Please let me know if the problem persists.

> 6. Is what i'm doing even possible in todays tech stack? Or am i waaaaaay too ahead of my time and should i wait a couple of years till this encryption becomes more common place?

It has been possible for many years, even though you are using newer standards (e.g., WebCrypto) than those available back then. (Also, RSA is not particularly future-proof, it is not well-suited for large messages, it relies on unproven assumptions, and does not provide forward secrecy.) Luckily, HTTPS/TLS has become omnipresent, which is why most websites don't need to implement their own cryptographic mechanisms. One of the most important rules in cryptography is: Never roll your own crypto. However, I would encourage everyone to learn about and experiment with cryptography!

**Comment by markg85** [comment]
Hi @tniessen 

Sorry for this quite late response.
And thanks a lot for your elaborate response! :)

From your response it looks like the only thing i was missing was `buffer.toString('utf8')` :)
Will test that out later.

> It is okay, it is not particularly efficient, but it does not compromise the security. A more efficient way would be to just concatenate the binary signature and the binary data, and to encrypt the resulting binary data. The server can derive the length of the signature from the client's public key, and can thus split the decrypted message into signature and data.

So if i just concatenate the two in that particular order (so: <signature><data blob>) then the decryption and verify steps just automagically know what to do? I don't quite get that...

Also, you said HTTPS and TLS. I've seen that being suggested on other places too, but how can i make use of that in my earlier approach? So to only allow specific clients to send messages?

Or in a very different way. Imagine an authentication system where i upload a file/whatever and _only_ want to share it with 1 or n people. (this is the classical PGP multiple recipients approach) How do i do that in just HTTPS/TLS? As far as i can tell, i _need_ to do my own key management, right? I might be very wrong here and just don't know about other techniques that might make this a no-brainer.

Lastly, i'm wondering if there is a library out there that can do this stuff for me. What i'm trying to do isn't a new concept at all. It's been done for decades in mail (for those that use PGP that is). Yet in the browser world, this stuff seems really tedious to get right with lots of high tech crypto details quite quickly that are obviously important! But having a library that makes it easier to use would be really nice to have! I haven't found it yet, but then again, i might just be missing it. (note: i'm looking for a library that wraps SubtleCrypto, not for one that re-implements cryptography).

**Comment by tniessen** [comment]
> So if i just concatenate the two in that particular order (so: ) then the decryption and verify steps just automagically know what to do?

No, sadly, neither WebCrypto nor Node.js will be particularly helpful in doing this "automagically", you will need to separate the two components manually.

> Also, you said HTTPS and TLS. I've seen that being suggested on other places too, but how can i make use of that in my earlier approach? So to only allow specific clients to send messages?

Well, TLS/SSL was designed to allow client authentication using client certificates, which would theoretically allow to identify clients. Sadly, this concept has found very little adoption. So in theory, you can use that to securely communicate with a selected set of clients, but in practice, UX will likely suffer from browser support for client certificates.

> Lastly, i'm wondering if there is a library out there that can do this stuff for me.

I don't know any, sorry.

**Comment by markg85** [comment]
Oke, i'm stuck again.
Ignore my first post as i started from scratch.

I get the concepts of cryptography  (or i think i do). I get the difference between asymmetric and symmetric. What i don't get is the sane way to use them.

Here's what i'm trying to do.
I'm making a website that needs to have secure communication from trusted users to a server. Overall the data that needs to be exchanged is fairly small, but lets for the sake of this argument say that it must be able to handle bigger files too. Just so that symmetric encryption makes sense.
The server has a public and private key.
Each user have a public and private key too.
All have them generated with a generateKey command like this:
```
    window.crypto.subtle.generateKey(
        {
            name: "RSA-PSS",
            modulusLength: 2048, //can be 1024, 2048, or 4096
            publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
            hash: {name: "SHA-256"}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
        },
        true, //whether the key is extractable (i.e. can be used in exportKey)
        ["sign", "verify"] //can be any combination of "sign" and "verify"
    )
```
But that is to sign and verify.
I can now do just that too. I kinda miss the whole encrypt and decrypt step here. Kinda important!

Now it's my understanding that i **should** be using **RSA-PSS**, not RSA-OAEP. Also because of what you said. It works for encrypting small data but is not the way to go for larger files.

So i need more keys. symmetric keys to perform the encryption.
Lets say "AES-CTR". Making them is no problem.
But... How do i **securely** communicate those keys? As anything i encrypt with it will need to be decrypted with the same key on the other side. I cannot encrypt this key using "RSA-PSS" as that simply doesn't allow encryption. I cannot blindly send it as it might be intercepted and used by a malicious party every time i send or receive encrypted data.

Or do i need to go back to RSA-OAEP yet again for this? ... This different key logic is sooooo freaking confusing! Really, whoever made this logic up should've made some examples to go along with it.

This all seems so much simpler in plain vanilla openssl: https://gist.github.com/dreikanter/c7e85598664901afae03fedff308736b

Hope you can help just a little more :)

**Comment by tniessen** [comment]
> I get the difference between asymmetric and symmetric. What i don't get is the sane way to use them.

That might be because neither asymmetric nor symmetric encryption are a perfect fit for your scenario. While you can use asymmetric encryption such as RSA-OAEP to transmit keys securely, it is generally preferable to use ECDH instead. ECDH is often counted towards asymmetric encryption, but it does not encrypt data. It is a key exchange mechanism, meaning that you can use it to securely exchange (symmetric) keys, but you cannot use ECDH to encrypt data. This is how you initiate encryption using ECDH:

1. Client and server each generate a private and a public key.
2. They exchange their public keys.
3. Both derive a key from their own private key and the other side's public key. (This is the beauty of ECDH, both sides will always derive the same key, even though they each only know one private key.)
4. Use the derived key for AES (or any other encryption scheme).

Now, that works perfectly well in Node.js and WebCrypto, but it does not involve authentication: You want the client to sign messages, and you suggested to use RSA-PSS for that. You can change the above steps like this (changes highlighted):

1. Client and server each generate a private and a public key. **The client also needs a RSA-PSS key pair.**
2. They exchange their public keys. **The client signs its ECDH public key with its own RSA-PSS private key before transmitting it to the server. The server uses the client's public RSA-PSS key to verify the signature.**
3. Both derive a key from their own private key and the other side's public key. (This is the beauty of ECDH, both sides will always derive the same key, even though they each only know one private key.)
4. Use the derived key for AES (or any other encryption scheme).

If you are using WebCrypto, the relevant API for step 3 is [deriveKey](https://github.com/diafygi/webcrypto-examples#ecdh---derivekey).

**Comment by markg85** [comment]
Hi @tniessen 

Thank you so much for this!
That's really clear and very helpful to know!

Now i am still confused about the fact that  this kind of security apparently is not a public and a private key for each party anymore. It is:
- Public key (RSA-PSS)
- Private key (RSA-PPS)
- Public key (ECDH)
- Private key (ECDH)
- AES key

For a simple hobby play experiment, this is going waaaaay too far.
But still, i like to have it really secure just to see how well it would work. I'm going to stick with it, for now.

Another thing in this hobby experiment is that i intent to make a library out of it for web and node.js just so that others can use it without going through the mountain of trouble that i'm going through to figure this stuff out.

However, i might consider kicking out signing/verification if it bites me much more then it has already.

Thanks again and Merry Christmas :)

**Comment by tniessen** [comment]
> Now i am still confused about the fact that this kind of security apparently is not a public and a private key for each party anymore. It is:

You are right, the client needs a persistent RSA-PSS key pair for signatures, and for ECDH, each side has an ephemeral key pair. Those ephemeral keys are used to exchange the AES key, and not stored beyond the current transmission. (This is how most HTTPS / TLS connections work internally.)

> Thanks again and Merry Christmas :)

No problem, and Merry Christmas to you, too!

**Comment by markg85** [comment]
I'm not quite sure if I follow you correctly. Am I right that the two RSA-PSS keys and the two ECDH keys are long lived. The AES one is session based.

As I can also interpret your reply as the ECDH keys being session based. In that case I wonder why there would even be a need to have them session based. As far as I can see it this far, that only adds in a handshake connection setup where you first need to exchange the keys (every time) before you can start the communication. That seems wasteful.

**Comment by tniessen** [comment]
> Am I right that the two RSA-PSS keys and the two ECDH keys are long lived.

ECDH keys are usually only used once, and not long-lived. ECDH is a Diffie-Hellman key exchange mechanism and works completely different from RSA etc. If you reuse the same ECDH keys, you will produce the same AES key every time, so you really need to use new ECDH keys every time you need a new AES key. The good thing is that, unlike RSA keys, ECDH keys are relatively cheap to generate. Since you use a new key pair every time, you need a persistent key pair (e.g., RSA) to sign the ECDH public key so the other party can authenticate the ECDH key exchange.

(I am not entirely sure why you are referring to two RSA-PSS keys. If I understand your scenario correctly, only the client needs one to authenticate itself, and the server is already authenticated using TLS. But you will need two ECDH key pairs for each session.)

> As far as I can see it this far, that only adds in a handshake connection setup where you first need to exchange the keys (every time) before you can start the communication. That seems wasteful.

You could just use RSA-PSS and RSA-OAEP to sign and exchange session keys (and that's similar to what old TLS implementations did), but
- that does not provide forward secrecy.
- you will either need two RSA key pairs, or you will have to use the same RSA key pair for both RSA-PSS and RSA-OAEP. While that won't necessarily compromise your security, it is generally considered a bad idea to use the same key with multiple algorithms.

**Comment by markg85** [comment]
> (I am not entirely sure why you are referring to two RSA-PSS keys. If I understand your scenario correctly, only the client needs one to authenticate itself, and the server is already authenticated using TLS. But you will need two ECDH key pairs for each session.)

Ignore TLS. As you said before, i can't easily hook into TLS and web security as the interfaces for that simply are non existent. Assume i'm building up a connection between two parties over a very open totally insecure line (i'm not, but it makes the discussion simpler :P)

So the logic is as follows, please verify.
Server and client, both generate a RSA-PSS key. This is persistent, they only do this once.
Both server and client generate an ECDH key. This is per session.
They then shake hands. The client sends it's signed public ECDH key to the server, the server sends his signed public ECDH key to the client. The receiving end receives a singed key verifiable by the senders persistent RSA-PSS public key.

Their session handshake is now completed.

If the client sends data to the server, the client generates a AES key based on his own ECDH private key and the server's ECDH public key. The data the client sends is encrypted by that resulting AES key.

The server, the receiving end of the data, generates the AES key (his private ECDH key + the client's public ECDH key) and decrypts the message.

That's one full cycle.

Now, if the client were to send another message, or the server were to send an ACK message, would they in that case re-use the keys? Or would they for **every** message generate a new key (and thus a new handshake)? If it's the former then there is some form of "key lifecycle duration"... and if that's the case, how do i do that in either Node.js or SubtleCrypto? If it's the latter then it's clear to me.

**Comment by tniessen** [comment]
> That's one full cycle.

Yes, all of that sounds correct. Note, however, that you will need to implement some kind of authentication if you don't want to rely on TLS, since the client needs to be able to verify that the server's public RSA key is indeed its public key and not that of an attacker.

> Now, if the client were to send another message, or the server were to send an ACK message, would they in that case re-use the keys? Or would they for every message generate a new key (and thus a new handshake)?

That's up to you, you can implement it either way. In practice, we try to minimize the number of handshakes / key exchanges for performance reasons, but if you just want a proof of concept, you can do the handshake every time. It gets a bit trickier if you want to make it more efficient...

If all your messages were to be sent over the same bidirectional network stream, you could easily encrypt the stream using AES-CTR for up to 5×10<sup>30</sup> GB of data without having to exchange a new session key.

In your case, you are likely using HTTP requests, which do not allow stream encryption. (Also, WebCrypto has no support for streams whatsoever.) So you want to encrypt each individual messages in a secure way. That opens up new problems. Usually, you could use the same key with different IVs, but depending on which AES mode you use, it might be difficult to determine which IVs can be used and which would cause security problems, and WebCrypto does not make it any easier.

So it appears safer to use a new key for each message, and thus we have arrived at the classic problem of deriving multiple secret keys from a single shared secret. If your messages had a guaranteed order and if WebCrypto had support for streams, that would be easy. But you can still create some scheme in WebCrypto:

1. Assign a unique identifier to each message, and encode it as a 16 byte `ArrayBuffer`. This identifier must be sent to the receiver.
2. Encrypt a 32 byte `ArrayBuffer` with static contents (e.g., all bits set to zero) using AES-CTR using the key that you derived using ECDH and the previously generated `ArrayBuffer` as the initialization vector (nonce).
3. The result will be a 32 byte `ArrayBuffer`, which you can use to encrypt/decrypt the message.

That is only one possibility, there are infinitely many others :)

**Comment by gireeshpunathil** [comment]
resolution provided, closing as inactive.
