### ISSUE TITLE
sending emails inside nodejs without using third-party libraries

### ISSUE THREAD

**Issue by frodoe7** [nodejs/help#2274]
**Is your feature request related to a problem? Please describe.**
Yes , I remember in PHP , I send emails without using libraries
`mail("someone@example.com","My subject",$msg);` , no configurations needed
[reference](https://www.w3schools.com/php/func_mail_mail.asp) : 
why NodeJS does not setup it's own SMTP server like the other languages

**Describe the solution you'd like**
I found [this package](https://www.npmjs.com/package/sendmail) , but did not help well

**Comment by thekemkid** [comment]
Hey. The Node.js core runtime libraries are intentionally kept slim as it's possible to manage many of these needs in userland modules. You can either try put together an SMTP tool yourself, or look at [nodemailer](https://nodemailer.com/about/) if you want the de-facto tool used across the ecosystem.

**Comment by tniessen** [comment]
PHP is a very old framework, and when it was first released in 1995, people didn't have access to modern package managers, so the developers had to integrate all kinds of features into the built-in libraries.

>  why NodeJS does not setup it's own SMTP server like the other languages

Because it isn't 1995 anymore. It is much more efficient to use a modern package manager and third-party modules instead of shipping every possible feature at once.

However, if you insist on implementing SMTP without third-party libraries, you are in luck: SMTP is a surprisingly simple protocol, which you can easily implement on top of the TCP implementation that Node.js ships.

**Comment by tniessen** [comment]
This question appears to be answered, but feel free to reopen the issue.
