### ISSUE TITLE
N-API: The arraybuffer returned from napi_get_typedarray_info() for Buffer objects doesn't point to the buffer data

### ISSUE THREAD

**Issue by jhanssen** [nodejs/help#2291]
* **Version**: 12.13.0
* **Platform**: Linux dev-linux 5.3.0-19-generic x86_64 x86_64 x86_64 GNU/Linux

The issue happens when passing a `Buffer` object down to a native module and one calls `napi_get_typedarray_info()` getting the `arraybuffer` object and then in turn calls `napi_get_arraybuffer_info()` on this. The size returned seems to be 8192 (even though the actual buffer here is significantly smaller) and the data pointer certainly doesn't point to the buffer data. 

However, if getting the size and data directly from `napi_get_typedarray_info()` then everything seems to be ok.

**Comment by addaleax** [comment]
Hi @jhanssen!

This is not specific to N-API:

```js
> Buffer.from('hello').buffer
ArrayBuffer {
  [Uint8Contents]: <68 65 6c 6c 6f 56 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 56 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 56 00 00 68 65 6c 6c 6f 00 00 00 68 65 6c 6c 6f 56 00 00 68 65 6c 6c ... 8092 more bytes>,
  byteLength: 8192
}
```

This is happening because `Buffer`s use an underlying `ArrayBuffer` pool for faster creation 

Quoting the [API docs](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_allocunsafe_size):

> The `Buffer` module pre-allocates an internal `Buffer` instance of
size `Buffer.poolSize` that is used as a pool for the fast allocation of new
`Buffer` instances created using `Buffer.allocUnsafe()` and the deprecated
`new Buffer(size)` constructor only when `size` is less than or equal to
`Buffer.poolSize >> 1` (floor of `Buffer.poolSize` divided by two).

> Use of this pre-allocated internal memory pool is a key difference between
calling `Buffer.alloc(size, fill)` vs. `Buffer.allocUnsafe(size).fill(fill)`.
Specifically, `Buffer.alloc(size, fill)` will *never* use the internal `Buffer`
pool, while `Buffer.allocUnsafe(size).fill(fill)` *will* use the internal
`Buffer` pool if `size` is less than or equal to half `Buffer.poolSize`. The
difference is subtle but can be important when an application requires the
additional performance that `Buffer.allocUnsafe()` provides.

---

> However, if getting the size and data directly from `napi_get_typedarray_info()` then everything seems to be ok.

This is indeed the right thing to do :+1:

**Comment by jhanssen** [comment]
Aha, I didn't realize that Buffer could be an offset'ed Uint8Array, I didn't handle the offset/length from the typedarray at all. Consider this pebkac.
