### ISSUE TITLE
On-premise Dev/Stage/Prod Environment for internal corporate apps.

### ISSUE THREAD

**Issue by jamesdruhan** [nodejs/help#2294]
**Node.js Version**: Latest
**OS**: Windows 2016 Server
**Scope (install, code, runtime, meta, other?)**: Install/Tools/Best Practices
**Module (and version) (if relevant)**: N/A

I am looking to introduce NodeJS as a development platform for our company developers (we currently have Java and SharePoint platforms that we develop on). I am looking for advice regarding the setup of a NodeJS development, staging and production environments for that will allow developers to build and launch internal corporate applications. Our network infrastructure allows us to spin up VM's (normally Win 2016 server) with as much memory, HD size and processor cores as we wish - no limitations.

All tools, services, servers must be on-prem - We are not allowed to use cloud or online services.

Some questions I have:

- Should we be spinning up a server per Node application?
- Should we be using Node for creating daily/hourly cron jobs?
- Should we be creating some sort of Node cluster of servers?
- Is Windows 2016 server a terrible idea for a Node OS production env?
- Are there tools that we should be using the manages the apps (like PM2 or better)?
- Are there any solutions out there for on-prem professional Node environment management?

Any articles, or help you can provide would be great! If possible we'd like to avoid hiring consultants/company for this stage of setup but we will if we have to.

**Comment by gireeshpunathil** [comment]
@jamesdruhan - is this still outstanding? I can attempt to answer a few, but want to make sure you are still interested in those (given some time has passed and workload characteristics and deployment strategies might have changed since then). let me know!

**Comment by jamesdruhan** [comment]
@gireeshpunathil it is indeed still relevant. I’m still in the process of converting teams to NodeJS. However the focus is more so on production now. Dev and Staging environments are easy enough. However most guides and advice I find mention “good for developing but don’t use in production”. 

It’s difficult to find sound production stable techniques and server configuration.

**Comment by gireeshpunathil** [comment]
there are several ifs and buts, so let us go over it as a top down approach, rather than addressing each question eparately.

> All tools, services, servers must be on-prem - We are not allowed to use cloud or online services.

there are cloud platforms that can be configured on-prem. I would be recommending that over anything else, due to:

 - current cloud technology addresses most of the known enterprise grade production life cycle issues of the past
 - Node.js being highly scalable and high performant, gives very good production experience if hosted in cloud
 - containerized application is much more manageable than its non-containerized counterpart
 - Node.js org provides stable docker builds.

I will not be recommending a specific on-prem Cloud offering, as it can potentially cause conflict of interest between my employment and the role in my community. However, kubernetes (https://kubernetes.io) is the most popular, stable and open container platform at the moment AFAIK, and I can vouch for that, as I have worked with it and enjoyed it cool features.

If we go this route, most of your questions gets auto-answered. For example:

> Should we be spinning up a server per Node application?

k8s handles this automatically as part of its load balancing, so we just don't need to.

> Should we be using Node for creating daily/hourly cron jobs?

yes, and again, deploy it as a k8s service, and forget about how it is being managed internally.

> Should we be creating some sort of Node cluster of servers?

no, if we are going with k8s, its primary workflow contains clusters, so we don't need to use Node.js cluster module

> Is Windows 2016 server a terrible idea for a Node OS production env?

It depends. If you are using a individual, self-managed instances for your production win 2016 is fair and good. But if we go cloud route, Linux is the defacto standard there, in terms of production efficiency, tools, frameworks, community support and many more.


> Are there tools that we should be using the manages the apps (like PM2 or better)?

for self-managed instances - yes, process management tools will help reduce the downtime, but in k8s environment, this is all automatic.

> Are there any solutions out there for on-prem professional Node environment management?

I don't know, but I will ping @mhdawson , @mcollina , @mmarchini  to see if they have more insights to add - on this questions as well as everything else.

**Comment by mhdawson** [comment]
+1 on the Kubernetes recommendation and I agree with the other points that @gireeshpunathil has mentioned.

In terms of `Are there any solutions out there for on-prem professional Node environment management?`.  I don't know of one that is Node.js only, but there are on-prem offerings that will support Node.js deployment along with other runtimes.  In order to avoid the potential conflict of interest @gireeshpunathil mentioned earlier I won't recommend one here but you can reach out to me at my email listed on https://github.com/nodejs/node#tsc-technical-steering-committee if you want my biased suggestion :)

**Comment by gireeshpunathil** [comment]
> However, unfortunately at my company we have very strict policies surrounding servers, data storage, user management, etc. The solution we deploy has to be 100% internal and on-premise. Zero cloud. The applications running on this Node environment are also 100% internal, corporate apps requiring VPN or onsite network access. None of this infrastructure is for external use or will be accessible via the Internet.

@jamesdruhan - fair, I understand that, and we call it [air-gapped environment](https://en.wikipedia.org/wiki/Air_gap_(networking)) , and the above recommendation(s) can be natively configured to meet your all requirement(s). That is:
 - function in a completely isolated and customized network with 0 public access
 - still enjoy the full benefit of being first class cloud topology

Hope this helps. Feel free to ask if you have questions, or connect over a call as @mhdawson suggested.

**Comment by jamesdruhan** [comment]
Great!!! I will most definitely look into this!

**Comment by gireeshpunathil** [comment]
@jamesdruhan - is there anything outstanding here?

**Comment by jamesdruhan** [comment]
Nothing outstanding. Thanks.
