### ISSUE TITLE
Destructering class instance methods, not bound to this by default

### ISSUE THREAD

**Issue by pimlie** [nodejs/help#2314]
* **Node.js Version**: v13.2.0
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

Given the following code, I was wondering whether this is the expected behaviour when destructering class instance methods. I find it a little bit confusing that `this` isnt strictly bound to the class instance. I understand why this happens (the logged message actually already explains it, instance var vs prototype var), but maybe it would make sense that the `this` context would be preserved when destructering?

Probably I should've ask this in the ECMAScript repo btw ;)

```js
class myClass {
  constructor() {
    this.bound = this.bound.bind(this)
  }

  bound() {
    console.log('bound this:', this)
  }

  unbound() {
    console.log('unbound this:', this)
  }
}

const classInstance = new myClass()

classInstance.bound() // -> bound this: myClass { bound: [Function: bound bound] }
classInstance.unbound() // -> unbound this: myClass { bound: [Function: bound bound] }

const { bound, unbound } = classInstance

bound() // -> bound this: myClass { bound: [Function: bound bound] }
unbound() // -> unbound this: undefined
```

**Comment by Hakerh400** [comment]
> I was wondering whether this is the expected behaviour

Yes, it is the expected behavior.

> But maybe it would make sense that the `this` context would be preserved when destructering?

From the logical point of view, it does not make any sense. Destructuring is nothing but accessing a property. `const {a} = b` is basically `const a = b.a`. Class instance is just an object whose prototype is a reference to the `prototype` property of the class function. And class methods are properties of the prototype reference, they are not inherently bound to anything. Calling a class method of a class instance is a syntactical thing - not a semantical manifestation of the logic behind the relation between the class instance and its prototype.

On the other hand, if you consider destructuring as a syntactically specific case of property access (like `a.b()` is a specific case of a function call), then it would make sense, but it is very likely that the ECMAScript committee would reject it, since the current behavior has been present for a long time and many libraries adapted to it already.

**Comment by pimlie** [comment]
Thanks for the in-depth response. 

> Calling a class method of a class instance is a syntactical thing

This is what I meant with the confusing part. You have to know how ecmascript is structured internally (ie prototypes) to understand the difference between _bound_ and _unbound_ in my example.

But reading the specifications again I think I do understand it a bit more knowing that `classInstance.bound` is actually an exotic function object and not eg a clone of the bound function.

Just wondering if there is a better way to do the above. Or maybe its just a bad example of using destructuring?
