### ISSUE TITLE
How is CC coverage generated?

### ISSUE THREAD

**Issue by juanarbol** [nodejs/help#2327]
* **Node.js Version**: current
* **OS**: macOS
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

How can I help with CC coverage? I just see few files on `cctest` folder, the documentation is quite simple, where could I learn how to test, or learn/understand how node internals are tested?

**Comment by Trott** [comment]
I don't know a whole lot about the C++ tests, but if you do make progress on this, a PR to add some documentation would be great.

**Comment by addaleax** [comment]
`cctest`s are only used when testing C++ APIs or C++ internals.

Mostly, C++ coverage is provided through the JS test suite, as most Node.js C++ code is reachable from there.

**Comment by joyeecheung** [comment]
re: how is cc coverage generated, it is generated with [gcovr](https://github.com/gcovr/gcovr)

https://github.com/nodejs/node/blob/487177954201ee098ecbf5027473b238187cee22/Makefile#L225-L234

https://github.com/nodejs/node/blob/487177954201ee098ecbf5027473b238187cee22/Makefile#L252-L255

> How can I help with CC coverage?

From a glance of https://coverage.nodejs.org/ to me it seems most of the missing coverage are false positives that are not covered because the CI machine running the coverage is not configured to  cover them all. But in general I think you'd want to find out when those branches get hit first and hit it somehow, it does not need to come from cctests, as @addaleax said.

**Comment by juanarbol** [comment]
So, is C++ coverage actually improved with js tests?

can you give me some example, like this test, is gonna test C++ more than js stuff, or both js and C++? I could drive myself by at least one example. And probably send a PR to docs.
