### ISSUE TITLE
process.versions.modules is not for N-API ?

### ISSUE THREAD

**Issue by linxiaowu66** [nodejs/help#2328]
* **Node.js Version**: 13.2.0
* **OS**: Mac
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: N-API
Hi guys, I have a problem about the global variable : `process.versions.modules`.

In the docs of nodejs, it describe the `process.versions.modules` as follow:

    process.versions.modules indicates the current ABI version, which is increased whenever a C++ API changes. Node.js will refuse to load modules that were compiled against a different module ABI version.

  So with this description, I think if I have a C++ addon with N-API build in the node v8(modules: '57'), and then use it the node v13(modules: '79'), it will throw error. But actually it does not.

And I read the nodejs source code, in the `DLOpen` function , I find this `if` statements:

```
// -1 is used for N-API modules
    if ((mp->nm_version != -1) && (mp->nm_version != NODE_MODULE_VERSION)) {}
```

as the comments, if this module is not N-API, so nodejs will compare the module version to current module version, if these two version is not the same, it will report error.

Now I am confusing with this code. `versions.modules` is not for N-API ?

Can anyone help me ?

Thanks.

**Comment by gireeshpunathil** [comment]
cc @nodejs/n-api

**Comment by NickNaso** [comment]
Hi @linxiaowu66,
if your native add-on is implemented using N-API you don't care of `NODE_MODULE_VERSION`, because your module will continue to work if you switch the Node.js version. What is important for N-API module is the N-API version. You can get the N-API version using `process.versions` (see: https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_process_versions) or you can use the `napi_build_version` (see: https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_process_config) in the `binding.gyp`. 
N-API is an additive API and is versioned independently from Node.js  so for example if you implement a native add-on with N-API v3 your module will work on all Node.js version that have N-API v3 or above. You can find information of wht N-API version is supported by different version of Node.js here https://nodejs.org/dist/latest-v12.x/docs/api/n-api.html#n_api_n_api_version_matrix
I

**Comment by linxiaowu66** [comment]
@NickNaso Firstly thanks for your answer.

Then I am still confusing.  N-API is based on ABI version, and the ABI version can be found in the `process.versions.modules`, is it right ? If this is wrong, the description for `process.versions.modules` maybe misleading(https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_process_versions):

    process.versions.modules indicates the current ABI version, which is increased whenever a C++ API changes. Node.js will refuse to load modules that were compiled against a different module ABI version.

Secondly, I am testing a N-API module, when i compile using v13.2.0(napi: v5),  and run this module in the v8.12.0(napi: v3), But it still can run and nothing error, is it normal?

**Comment by legendecas** [comment]
-API and Node.js C++ API offer different sets of API which have different ABI stabilities guarantees across Node.js versions.

N-API have its own ABI guarantees on N-API versions and is expected to be not related to Node.js versions. Its highest supported version in the Node.js could be retrieved by `process.versions.napi`. N-API offers merely __C APIs__ which could be used in C++ too, and we have a nice C++ wrapper [node-addon-api](https://github.com/nodejs/node-addon-api) around it.

`process.versions.modules` indicates Node.js C++ Addon API versions, which doesn't offer guarantees on ABI stabilities across Node.js versions.

So for your questions:
> Then I am still confusing. N-API is based on ABI version, and the ABI version can be found in the process.versions.modules, is it right ? If this is wrong, the description for process.versions.modules maybe misleading(https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_process_versions):

No, N-API version should be referred to `process.versions.napi`. `process.versions.modules` is for Node.js C++ API.

> Secondly, I am testing a N-API module, when i compile using v13.2.0(napi: v5), and run this module in the v8.12.0(napi: v3), But it still can run and nothing error, is it normal?

Yes, it is expected behavior. And this is what nice things N-API offer 🎉.

**Comment by legendecas** [comment]
> Secondly, I am testing a N-API module, when i compile using v13.2.0(napi: v5), and run this module in the v8.12.0(napi: v3), But it still can run and nothing error, is it normal?

Note that this would work only if you write your addon with N-API v3 and lower APIs, not higher.

**Comment by linxiaowu66** [comment]
@legendecas @NickNaso Thanks a lot.
