### ISSUE TITLE
require returns undefined

### ISSUE THREAD

**Issue by aprilmintacpineda** [nodejs/help#2340]
* **Version**: `v13.2.0`
* **Platform**: `Darwin Aprils-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64`
* **Subsystem**:

**a.js**

```js
const { c } = require('./c');
const { b } = require('./b');

const outputOfC = c();
const outputOfB = b();
```

**b.js**
```js
const { c } = require('./c');
const b = c(b);
module.exports = { b };
```

**c.js**
```js
function c () {
  // ...
};

module.exports = c;
```

The problem is, if `A` requires `B` and `C` and `B` requires `C` as well, `C` becomes undefined when required in `B`.

It's actually undefined because `module.exports` becomes an empty object.

**Comment by BobKerns** [comment]
It will be undefined in a.js as well!j You just hit your error while loading b, before you try to invoke c.c()

c.js is exporting the function c. That's it, the entire export, not `{c: c}`, the way b.js does.

But both a.js ans b.js are trying to import c as if it exported` {c: c}`.

Either change c.js to be consistent with its imports (and with b.js), i.e.:
```javascript
module.exports = {c};
```
or change a.js and b.js to import c.js correctly as it's written:
```javascript
const c = require('./c');`
```
Just to give you a parallel perspective on the difference, and to how it relates to the future:

The way you are exporting c is roughly equivalent to writing in ECMAscript modules:
```javascript
export default function c() {
  // ...
 }
```
and b.cjs would look like:
```javascript
import c from './c';
export const b = c;
```
or even:
```javascript
import c as b from './c';
 ```
and a.cjs:
```javascript
import {b} from './b';
import c from './c';
```

So there's no bug here. You can think of `require('./c')` as returning whatever you set `module.exports` to, in this case,the function `c`, and so don't destructure it. But that model doesn't quite work with ECMA modules, because they become shared, live bindings and ECMA modules are not objects to be destructured, but rather a set of named bindings and an optional default  (unnamed) binding. So the concepts are parallel but not equivalent. It would be better to think of this in terms of "the old equivalent of ECMA default exports".

You can have both named and unnamed exports. In this old world, that looks like this:
```javascript
function c(d) {}
c.b = c;
c.data = "Hi, I am Data!";
module.exports = c;
```
and
```javascript
const c = require('./c');
const {b, data} = c;
c(b(data));
```

**Comment by PoojaDurgad** [comment]
@aprilmintacpineda - did @BobKerns 's suggestion help you to resolve the issue? or is this still  outstanding?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding

**Comment by minhquan1313** [comment]
For someone who sillies as me :)), check if your imported file has the same name but different ext, example:

> ~/Province.ts
> ~/province.json

even correct imported with 
`import { Province } from "@/.../Province";` and `console.log({ Province });` still give undefined, because in the Location folder, I have province.json

**Comment by zekrom-vale** [comment]
I had a similar issue with electron, it appeared that require was not working for no reason when I required the file.
```js
const {app, BrowserWindow} = require('electron')
// app == undefined
// BrowserWindow == undefined
```

Turns out running your code with `node file.js` in the command line will fail.  You need to use `electron file.js` or all electron imports will be `undefined`.  (And not an issue with a required file requiring a dependency).
[electron-quick-start b58e398](https://github.com/zekrom-vale/electron-quick-start/commit/b58e3988f483d5ae4745e3ac5d7de429d215152b)
