### ISSUE TITLE
Can we use dynamicInstantiate to import non-JS files like `.jpg`, `.png`, etc?

### ISSUE THREAD

**Issue by trusktr** [nodejs/help#2353]
I'm curious about the new `dynamicInstantiate` feature.

Can I use `dynamicInstantiate` to allow my application code to do things like

```js
import imageBuffer from './path/to/image.jpg'

// imageBuffer is a Buffer containing image data

import MyWorker from './path/to/MyWorker.worker.js' // contains worker code, this code does not export a MyWorker class.

let worker = new MyWorker()
worker.postMessage(...)

import Foo from './path/to/Foo.ts' // TypeScript file

new Foo
```

or similar?

If so, how would I go about doing these things? The docs didn't mention much about dynamicInstantiate.

**Comment by jkrems** [comment]
The good news first: Yes. This should be possible once we have loaders. And it's possible using the current `dynamicInstantiate` hook.

The bad news: It's very unlikely that `dynamicInstantiate` in its current form will survive. While we unflagged modules overall, this doesn't include loader hooks. Those are still bound to change - possibly a lot. Part of the reason for `dynamicInstantiate` doesn't get much coverage in docs is that it, specifically, will likely go away.

You can implement loading of a jpg file using a resolve hook today:

1. Check the file extension and/or type.
2. Generate ES module source text and resolve to it.
3. ...
4. Profit!

Step 2 could mean putting the source text into a data URL and returning that URL. The generated ES module source could then "just" read file from the resolved URL and return the Buffer. There shouldn't be any need to use `dynamicInstantiate`.

But with all this I should note that all loader hooks are unstable right now. There's no guarantee that your `.jpg` loader would work with the "real" loaders once they are finalized. At least not without rewriting against the new hook APIs.

**Comment by jkrems** [comment]
I'd also like to second the gotcha by @guybedford who pointed out on Twitter that while you *can* there's a very real question if you *should*:

> The dynamic instantiate hook can run any code to create the module exports, including parsing an image yes. Whether this is a good idea is another question though. **Have to be careful to ensure module portability. Universal meaning of an image import isn’t necessarily clear.**
>
> -- [Twitter](https://twitter.com/guybedford/status/1205244226851786753)

**Comment by trusktr** [comment]
Ah, thank you! This may be an alright thing to do in application code, but probably not in generic library code (or that library code should be well documented, like "hey, import this file first so that loader hooks are available").

**Comment by joeyhub** [comment]
@jkrems I implemented something that works like that several months ago.

If you want portability you'd probably have to transpile it with your implementation for that though things like webpack already do it so for a lot of people it's just a way to make backend more consistent for testing or shared resources between front/back. In my situation I generally reciprocated my rollup resolve and load with the equivalent node custom loader. The might be some libraries that just want to load other types of things on the backend and be done with it.

I've stuck to mostly using resolve because I can't get dynamicInstantiate to work well. There's also not much in the way of documentation with some confusing aspects to it (I think you'll want to look at the experimental VM module to achieve some things the right way).

The main gotcha I think with using only resolve is that it won't do singleton logic properly. If you import your image from two different places then you're loading it twice, not the most efficient.

You can achieve this yourself though it's a bit of an extra effort.
