### ISSUE TITLE
npm Syntax Issue - Node.js

### ISSUE THREAD

**Issue by jimmschlo89** [nodejs/help#2373]
* **Node.js Version**: 8.16.1
* **OS**: UNIX on z/OS 2.2
* **Scope (install, code, runtime, meta, other?)**: Other
* **Module (and version) (if relevant)**: npm

![image](https://user-images.githubusercontent.com/49279914/71527825-ae29a800-28a2-11ea-8ead-5ae407a56b80.png)

I get this error when I try to run "npm --version".
No idea why but I can run "node --verison" no problem.

Any help would be awesome!

Thank you,

James

**Comment by gireeshpunathil** [comment]
what does cat \`which npm\` show?

cc @nodejs/platform-s390 in case if there is a prior art

**Comment by richardlau** [comment]
Perhaps try the environment variables listed in https://github.com/ibmruntimes/node/issues/138#issuecomment-547931428?

**Comment by the-blackpirate** [comment]
### @jimmschlo89 you have to set environment variables to your system.
**First try to run command for check node verison**

> npm -v  
this generate output with the installed node version.

if you got reply with the version details when you're using npm command then there will be no problem it means you have already have a path set in you're environment. try to update node version
from https://nodejs.org 

otherwise please check bash_profile in home folder in linux and if you have mac(unix) than please check your terminal which you're using like bash, zsh, fishshell. 

> export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

for mac if you have brew in it (homebrew missing package manager) 
then install npm from brew formula. 

> brew install node

**Comment by PoojaDurgad** [comment]
@jimmschlo89 - were you able to follow suggestions that are mentioned in the comment section? or still is it an issue?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
