### ISSUE TITLE
Need help with fs.writefile()

### ISSUE THREAD

**Issue by Adaptabil** [nodejs/help#2383]
Basically the problem i'm having is, i have a discord bot made, when i try write into a json file which is on the same repository and branch, it writes and reads the data correctly. However, when i apply a change to the main file and the bot gets redeployed on heroku, the json file resets itself and everyone's data is set to the default "10".

Everyone starts out on 10 currency as the default value when you first join etc. as a result of the json file resetting each time a update is made, the currency is pointless and i'm not too sure how to go about fixing this, if anyone has any help with this. please let me know. Thank you

**Comment by Hakerh400** [comment]
If you are using the Heroku [free plan](https://www.heroku.com/pricing), it does not provide a way for permanent file storage. From their docs:

> Heroku has an “ephemeral” hard drive, this means that you can write files to disk, but those files will not persist after the application is restarted.

They suggest either upgrading to the professional plan, or using external file storage, like amazon. In any case, this question would be more appropriate for their community forum, since it is not really related to Node.js.

**Comment by PoojaDurgad** [comment]
@Adaptabil - is this still outstanding?

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
