### ISSUE TITLE
Stream Transform, Write + Read

### ISSUE THREAD

**Issue by mStirner** [nodejs/help#2407]
* **Node.js Version**: 11.15.0
* **OS**: Ubuntu 16.04 LTS

Im trying to get a better understanding of streams in node.

What im doing is to transform a duplex stream in both directions:

```
Upstream  |     | Transform  |       | Stream (PassThrough)
------------------------------------------------------------
[device]  | --> |  [decode]  |  -->  |  [output]
[device]  | <-- |  [encode]  |  <--  |  [input]
```

```js
    const { Transform, PassThrough, Duplex } = require("stream");

    function Adapter(upstream){

            const stream = new PassThrough();
         

            const encode = new Transform({
                transform: (data, encoding, done) => {

                    // feedback
                    console.log("[encode] called");

                    done(null, data);

                }
            });


            const decode = new Transform({
                transform: (data, encoding, done) => {

                    // feedback
                    console.log("[decode] called");

                    done(null, data);

                }
            });


            upstream.pipe(decode).pipe(stream);
            stream.pipe(encode).pipe(upstream);
           
            return stream;

    }
```

The problem with the code snippet above is that i write to my own PassThrough stream, what results not in an output, but in an encoding again.

I need something like a transform method on the duplex upstream for the `_readable` & `_writable` stream.

Found something about a `_transform` method here: https://stackoverflow.com/questions/20317759/implementing-a-buffered-transform-stream but not in the nodejs docs neither im sure its still supported

Also im trying to avoid a own implementation of a Duplex stream until it is really necessary.

Is something like this possible ?

Pseudo code:

```js

function Adapter(upstream){

    const wrapper = new Duplex();

    wrapper._readableState = decode;
    wrapper._writableState = encode;

    upstream.pipe(decode);
    wrapper.pipe(encode);

    return wrapper;

}

```

**Comment by Hakerh400** [comment]
> What im doing is to transform a duplex stream in both directions

That exact requirement is logically impossible. To better understand why, here is a brief explanation. In Node.js there are three types of streams:

1. `Readable` - some external resource generates data and sends it to Node.js application.
2. `Writable` - Node.js application generates data and outputs to some external receiver.
3. `Duplex` - Node.js application both writes and reads data from it.

`Transform` is a special case of `Duplex`, and `PassThrough` is a special case of `Transform`. Knowing all that, you're asking whether it is possible to create a wrapper around a duplex stream so that it encodes data before sending it to the stream and decodes the data after receiving from the stream. But, as said, `Duplex` is a type of stream where Node.js application itself is responsible both for reading and writing the data to it. So, if you encode the data, who is going to read it? If another function from the same process is reading the data, then the data will be decoded automatically (because of the wrapper) and it doesn't make any sense (encoding and decoding cancel out, so you cannot detect that data is ever encoded or decoded - and the stream itself doesn't know who is reading/writing data). If an external receiver is going to read the encoded data (another process, for example), then you should use `Writable` instead. If you can construct a test which demonstrates how the stream should be used (including both ends), I can write the wrapper function you're looking for, but the problem is that your propositions are logically impossible.

You can't achieve it using a single duplex stream, but you can do it using a pair of duplex streams (one for both direction of data flow). Suppose you have a device that produces random strings consisting of uppercase letters and it also can receive any string, but it must consist of uppercase letters. Then suppose you have some code that expects lowercase letters, so you want to create an adapter to read uppercase string from the device, then convert it to lowercase and pass it to your application. Similarly, when application produces a string, the adapter converts it to uppercase and passes it to the device. I assume this use case is what you're trying to achieve, but you simply need a pair of duplex streams (here we are using transform streams for simplicity):

```js
'use strict';

const stream = require('stream');

class DoubleTransform{
  constructor(){
    this.stream1 = new stream.Transform({
      transform: this.transform1.bind(this),
    });

    this.stream2 = new stream.Transform({
      transform: this.transform2.bind(this),
    });
  }
}

class Upstream extends DoubleTransform{
  transform1(buf, enc, cb){ cb(null, buf); }
  transform2(buf, enc, cb){ cb(null, buf); }
}

class Adapter extends DoubleTransform{
  constructor(upstream, encode, decode){
    super();

    this.upstream = upstream;
    this.encode = encode;
    this.decode = decode;

    upstream.stream1.pipe(this.stream1);
    this.stream2.pipe(upstream.stream2);
  }

  transform1(buf, enc, cb){
    cb(null, this.decode(String(buf)));
  }

  transform2(buf, enc, cb){
    cb(null, this.encode(String(buf)));
  }
}

// Simple encode and decode functions
const encode = a => a.toUpperCase();
const decode = a => a.toLowerCase();

// Upstream and adapter
const upstream = new Upstream();
const adapter = new Adapter(upstream, encode, decode);

// Device
setInterval(() => {
  let s = '';
  for(let i = 0; i !== 10; i++)
    s += String.fromCharCode(65 + Math.random() * 26 | 0);
  console.log(`Device wrote: ${s}`);
  upstream.stream1.write(s);
}, 1e3);
upstream.stream2.on('data', a => {
  console.log(`Device received: ${a}`);
});

// Wait half second
const t = Date.now();
while(Date.now() - t < 500);

// Application
setInterval(() => {
  let s = '';
  for(let i = 0; i !== 10; i++)
    s += String.fromCharCode(97 + Math.random() * 26 | 0);
  console.log(`Application wrote: ${s}`);
  adapter.stream2.write(s);
}, 1e3);
adapter.stream1.on('data', a => {
  console.log(`Application received: ${a}`);
});
```

The above code generates output like this:

```
Device wrote: DTRPFPBDLO
Application received: dtrpfpbdlo
Application wrote: dxzghrchgn
Device received: DXZGHRCHGN
Device wrote: RNFBRSFZCF
Application received: rnfbrsfzcf
Application wrote: vdfjuymdyx
Device received: VDFJUYMDYX
Device wrote: ZQTGRHLMKO
Application received: zqtgrhlmko
Application wrote: gwmplvbhmr
Device received: GWMPLVBHMR
Device wrote: RKBVBCRNJZ
Application received: rkbvbcrnjz
Application wrote: pfbfgbioxn
Device received: PFBFGBIOXN
Device wrote: ICBXARKGRY
Application received: icbxarkgry
```

**Comment by mStirner** [comment]
I played a litle around and figured something similar like you out.

```js
function Adapter(upstream){

        // passthrough wrapper
        const transmit = new PassThrough();
        const receive = new PassThrough();

        const encode = new Transform({
            transform: (chunk, encoding, cb) => {

                console.log("[encode] called", encoding);
                cb(null, chunk);

            }
        });


        const decode = new Transform({
            transform: (chunk, encoding, cb) => {

                console.log("[decode] called", encoding);
                cb(null, chunk);

            }
        });


        transmit.pipe(encode).pipe(upstream);
        upstream.pipe(decode).pipe(receive);

        return {
            transmit,
            receive,
            encode,
            decode
        };

}
```
My main mistake was i thought that a duplex stream is something like your `DoupleTransform`.
Did you think mine is good solution or there any "side-effects"?

**Comment by Hakerh400** [comment]
> Did you think mine is a good solution or there any "side-effects"?

I can't see how you are going to use the adapted streams (4 streams returned from your function `Adapter` (which 2 of them are clearly redundant)). If `upstream` is a duplex stream, then it doesn't really do what you would expect. But if it works for whatever your use-case is, then go ahead with it, maybe I don't understand your requirements.

**Comment by PoojaDurgad** [comment]
@mStirner - is this still outstanding? looks like this can be closed now. please let me know if that is not the case

**Comment by mStirner** [comment]
@PoojaDurgad can be closed, thank you :)
