### ISSUE TITLE
Unable to download node js on Mac

### ISSUE THREAD

**Issue by henrycas123** [nodejs/help#2446]
I am unable to download node js on my mac, I keep having a pop up that says unable to download because apple is unable to check it for malicious software. 

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by Hakerh400** [comment]
See https://github.com/nodejs/node/issues/29216

**Comment by the-blackpirate** [comment]
You can install it from homebrew its works for me. just go to developer.apple.com then search for the downloads and download command line tools latest build or all the missing packages are installed on the darwin mac because mac has some packages missing which is used by Linux. go to https://brew.sh/ and run commands then you can install node js with brew formula which just a line of code and nodejs will be installed to your Mac.

https://formulae.brew.sh/formula/node@12

Run below command after install Homebrew

> brew install node

**Comment by ArkinSolomon** [comment]
This guide shows how to install it. Obviously, only do this if you install from nodejs.org.  It is only a temporary fix.

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by PoojaDurgad** [comment]
@henrycas123 - is this still an issue? were you able to follow the suggestions mentioned in the comments section.

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
