### ISSUE TITLE
Syslog without external modules?

### ISSUE THREAD

**Issue by Andreyooo** [nodejs/help#2474]
Is there a way to use syslog without external logging modules?

**Comment by bnoordhuis** [comment]
No, because there's no way to open `/dev/log` in AF_UNIX+SOCK_DGRAM mode.

Really old versions of node supported that as `dgram.createSocket('unix_dgram')` but that was removed when node was ported to Windows (and hence why I wrote [node-unix-dgram](https://github.com/bnoordhuis/node-unix-dgram).)

You can use [socat(1)](https://linux.die.net/man/1/socat) to create the socket, then pass the file descriptor to Node.js and use it with `dgram.createSocket('udp4').bind({ fd: 3 })`.

**Comment by Andreyooo** [comment]
Decided to use the modern-syslog module :)
