### ISSUE TITLE
await in while get difference value

### ISSUE THREAD

**Issue by lbj2014** [nodejs/help#2478]
* **Version**: v12.15.0
* **Platform**: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
* **Subsystem**:

I want to implement Compare-and-swap in js, but the code  **while(obj.lock && await obj.lock !== obj.v) {}** is ok
but other expression，**while(obj.lock && obj.v !== await obj.lock)**  or **while(obj.lock && obj.v !== await obj.lock){}** and **while(obj.lock && await obj.lock !== obj.v)** is not expected
Can anyone tell my why? thank you

here is code
```
'use strict'
let data = { "a": 1, "b": 100 }
function read(readUseTime) {
	return new Promise(resolve => {
		setTimeout(() => {
			resolve({...data})
		}, readUseTime)
	})
}

function write(value, writeUseTime) {
	return new Promise(resolve => {
		setTimeout(() => {
			data = value
			resolve()
		}, writeUseTime)
	})
}

async function synchronized(obj, func) {
	// problem is here
	// while(obj.lock && obj.v !== await obj.lock) // has problem, result: { a: 2, b: 102 }
	// while(obj.lock && obj.v !== await obj.lock){} // has problem, result: { a: 2, b: 102 }
	while(obj.lock && await obj.lock !== obj.v) {} // no problem, result: { a: 3, b: 102 }
	// while(obj.lock && await obj.lock !== obj.v)  // has problem, result: { a: 2, b: 102 }
	
	obj.v = (obj.v || 0) + 1
	obj.lock = new Promise(async (resolve) => {
		await func()
		resolve(obj.v)
	})
}

function readAndWrite3(key, value, readUseTime = 0, writeUseTime = 0) {
	synchronized(readAndWrite3, async () => {
		let d = await read(readUseTime)
		d[key] = value
		await write(d, writeUseTime)
	})
}

;(() => {
	setTimeout(readAndWrite3, 0, 'a', 2)
	setTimeout(readAndWrite3, 0, 'b', 101)
	setTimeout(readAndWrite3, 0, 'a', 3)
	setTimeout(readAndWrite3, 0, 'b', 102)
	setTimeout(() => {
		// result
		console.log(data) // expected： { a: 3, b: 102 }
	}, 1000)
})()
```

**Comment by Hakerh400** [comment]
That is not how promises are intended to be used. Algorithms related to synchronization and mutual exclusion make sense only in multi-threading application. Promises do not run in separate threads. They all run in the thread that created them.

First, the following code:

```js
setTimeout(readAndWrite3, 0, 'a', 2)
setTimeout(readAndWrite3, 0, 'b', 101)
setTimeout(readAndWrite3, 0, 'a', 3)
setTimeout(readAndWrite3, 0, 'b', 102)
```

does not imply anything about the order of the operations you want to perform. Even if the time interval is the same, once you reach the first `await` statement, everything after that can theoretically run before the await finishes, implicitly reordering your operations.

Your `while` loops do not do what you may expect. The last loop (that you said does not work)

```js
while(obj.lock && await obj.lock !== obj.v)
```

is missing the loop body, so `obj.v = (obj.v || 0) + 1` is implicitly inside the loop. Similar with your first loop. Your second loop

```js
while(obj.lock && obj.v !== await obj.lock){}
```

does not work because JavaScript evaluates expressions from left to right. Once `obj.v` is evaluated, its value in the expression is not going to change until the next loop iteration, but `await obj.lock` dispatch the control back to the event loop, so it is delayed by at least one tick.

Also, note that

```js
new Promise(async (resolve) => {
  await func()
  resolve(obj.v)
})
```

is not really something you want to use, because the Promise constructor expects a non-async function. If an error occurs, it would produce an unhandled rejection that you would not be able to catch in any way.

And `obj.v = (obj.v || 0) + 1` is also a very bad practice, because it creates a new property on an arbitrary object. Better use `WeakMap` instead.

Besides all that, while it may look obvious what you are trying to achieve, your approach is wrong. Correct usage would be something like this:

```js
class Semaphore{
  static mutex(){
    return new Semaphore(1);
  }

  constructor(s=1){
    this.s = s;
    this.blocked = [];
  }

  init(s){
    this.s = s;
  }

  wait(){
    if(this.s > 0){
      this.s--;
      return Promise.resolve();
    }

    return new Promise(res => {
      this.blocked.push(res);
    });
  }

  signal(){
    const {blocked} = this;

    if(blocked.length === 0){
      this.s++;
      return;
    }

    setTimeout(blocked.shift());
  }
}

const mutexMap = new WeakMap();
let data = {a: 1, b: 100};

const read = readUseTime => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve({...data});
    }, readUseTime);
  })
};

const write = (value, writeUseTime) => {
  return new Promise(resolve => {
    setTimeout(() => {
      data = value;
      resolve();
    }, writeUseTime);
  });
};

const synchronized = (obj, func) => {
  if(!mutexMap.has(obj))
    mutexMap.set(obj, Semaphore.mutex());

  const mutex = mutexMap.get(obj);

  mutex.wait().then(func).then(() => {
    mutex.signal();
  });
};

const readAndWrite3 = (key, value, readUseTime=0, writeUseTime=0) => {
  synchronized(readAndWrite3, async () => {
    const d = await read(readUseTime);
    d[key] = value;
    await write(d, writeUseTime);
  });
};

setTimeout(readAndWrite3, 0, 'a', 2);
setTimeout(readAndWrite3, 0, 'b', 101);
setTimeout(readAndWrite3, 0, 'a', 3);
setTimeout(readAndWrite3, 0, 'b', 102);

setTimeout(() => {
  console.log(data);
}, 1000);
```

**Comment by PoojaDurgad** [comment]
@lbj2014 - were you bale follow @Hakerh400 's suggestion? or is this  still outstanding?

**Comment by PoojaDurgad** [comment]
inactive. closing . feel free to reopen if that is not the case
