### ISSUE TITLE
requestAnimationFrame alternative in node.js 

### ISSUE THREAD

**Issue by extremety1989** [nodejs/help#2483]
v12.14.1
windows 10

`
function run(){
  socket.emit("postion",pos)
   setImmediate(run)`
}
run();

function run(){
  socket.emit("postion",pos)
}
setInterval(  run , 60)
socket.on("keyspressed",(key)=>{})`

i want to make a game loop!
i tried both methods above (taken from stackoverflow)

#1st one with setImmediate blocks  keyspressed event of socket
#2nd one consumes a lot of memmory 

is there anyway to create a loop like requestAnimationFrame (browser version like) but in nodejs ?

**Comment by Hakerh400** [comment]
Try this:

```js
const fps = 60;
const funcs = [];

const skip = Symbol('skip');
const start = Date.now();
let time = start;

const animFrame = () => {
  const fns = funcs.slice();
  funcs.length = 0;

  const t = Date.now();
  const dt = t - start;
  const t1 = 1e3 / fps;

  for(const f of fns)
    if(f !== skip) f(dt);

  while(time <= t + t1 / 4) time += t1;
  setTimeout(animFrame, time - t);
};

const requestAnimationFrame = func => {
  funcs.push(func);
  return funcs.length - 1;
};

const cancelAnimationFrame = id => {
  funcs[id] = skip;
};

animFrame();
```

You run the above code only once. Then use it like this:

```js
const f = dt => {
  console.log('Animation frame!');
  requestAnimationFrame(f);
};

requestAnimationFrame(f);
```

**Comment by extremety1989** [comment]
@Hakerh400 thank you ! it works

**Comment by namonaihito** [comment]
@extremety1989 
1) Remember that requestAnimationFrame is fired based on monitor HZ, so for 144Hz monitor is about 6+ ms.
2) I would use performance.now() for time which has more precision (6.67897ms)  instead of Date.now()  (7ms).
3) SetTimeout will fire, no sooner, then time which was passed as argument to setTimeout. So if you set 16ms it will fire after 16ms or 20ms or 1000ms if the main thread will be busy or there are more timers (events) in queue.
