### ISSUE TITLE
request block

### ISSUE THREAD

**Issue by waqasmughal** [nodejs/help#25]
how can i prevent my server from block if 40 lakh record takes 30 secs all request in queue would block for 30 sec 

```
var http = require("http");
var url = require("url");
var MongoClient = require('mongodb').MongoClient

http.createServer(function(request, response) {

if (url.parse(request.url).pathname == '/search')
{
    var collection = db.collection('documents');
   // suppose it takes 40lakh record in 30 secs all request block until response end
    collection.find({}).toArray(function(err, docs) {
  
      console.log("Found the following records");
      console.dir(docs);
      
      response.writeHead(200, {"Content-Type": "text/plain"});
      response.write(JSON.stringify(docs));
      response.end();

    });

    
}
else
{
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write(0 + '');
  response.end();
}
}).listen(8888);
```

**Comment by Trott** [comment]
My knowledge of the `mongodb` package is very limited, but I don't think your code would actually block. If you are having an issue, since this would probably have more to do with Mongo specifically and not Node so much, perhaps try asking on StackOverflow? Sorry for the not-very-informative answer but I also didn't want to leave your question unaddressed.

**Comment by waqasmughal** [comment]
@Trott yes code would not block but request would be
