### ISSUE TITLE
Are stream error events recoverable?

### ISSUE THREAD

**Issue by pushkin-** [nodejs/help#2548]
* **Node.js Version**: 12.13.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: Streams

My Node app spawns a C# process that sits around reading input from the Node app. I give it input via:

    myProc.stdin.write(data);

The C# process also sends data back, which I read via:

    myProc.stdout.on("data", (data) => { });

I have added "error" event handlers for both streams and have been assuming that if I get such an event, I can't reliably recover from it, so I restart the C# process and set up fresh streams again.

Is this accurate? If the `"error"` event fires on the streams, can I possibly know if a subsequent write/read will succeed, or do I not have any guarantee of that and have to treat this is as a fatal error?

The documentation is fairly sparse on what "error" indicates. From [here](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_event_error):

>The 'error' event is emitted if an error occurred while writing or piping data. The listener callback is passed a single Error argument when called.

>The stream is not closed when the 'error' event is emitted unless the autoDestroy option was set to true when creating the stream.

**Comment by gireeshpunathil** [comment]
@pushkin- - is this still an issue?

> can I possibly know if a subsequent write/read will succeed

hard to say. as `error` event encapsulates several erroneous conditions at various levels, the possibility of successful write depends on the actual error instance itself. For example if the root cause of the error is a broken n/w between the source and the sink of the stream data flow, it is evident that the subsequent write will fail.

So your approach of recycling and respiring the process upon an I/O error looks reasonable to me!

**Comment by pushkin-** [comment]
@gireeshpunathil  ok thanks for the feedback. It wasn't necessarily an issue, but just wanted some clarification.
