### ISSUE TITLE
Slower multithreaded calculation than single-threaded?

### ISSUE THREAD

**Issue by wilk** [nodejs/help#2562]
* **Node.js Version**: 13.11.0
* **OS**: Mac OS X Catalina
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I'm doing an exercise to better understand the pros of multithreading computation with Node.js.
I created a huge text file (3GB) filled with positive random numbers.
Then I wrote two programs: one using a single thread and the other using a thread for each core (8 in this case).
The program is simple: it searches for a number by scanning the whole file.
I used Node.js streams so the file got read by chunks of 64KB.
I simulated the worst scenario by looking for a negative number, a number that does not exist in that file.

**The text file looks like this: (data.txt)**

```
69253
51351
13698
44222
114971
127840
40517
67127
52522
86899
29478
96527
...
```

I used the following command to generate it:

```bash
$ shuf -i 0-134600 -n 3221225472 > data.txt
```

**The single thread program: (single.js)**

```js
const fs = require('fs');

let found = false;
const stream = fs.createReadStream('./data.txt');

stream.on('data', data => {
  const el = data.toString().split('\n').map(parseInt).find(num => num === -1);
  if (el) found = true;
});

stream.on('end', () => {
  if (found) console.log('found :D');
  else console.log('not found :(');
});
```

The multithread program is a little bit different.
It uses the main thread to read the file using a stream (exactly like the single thread does) and passes the chunks to a thread pool in a round-robin style.
The worker is just the function to search inside an array of numbers.

**Main thread: (multi.js)**
```js
const { Worker } = require('worker_threads');
const os = require('os');
const fs = require('fs');

const cpus = os.cpus().length;
let stream;
let finishedReading = false;
let found = false;
let onlineCount = 0;
let roundCount = 0;
let busyCount = 0;

const pool = Array.from({ length: cpus }).map(() => {
  const worker = new Worker('./search.js');
  // used to start the real program when all the threads are ready
  worker.on('online', () => {
    onlineCount++;
    if (onlineCount === cpus) start();
  });

  worker.on('message', async message => {
    if (message.type === 'result') {
      busyCount--;

      if (message.found) found = true;
      if (finishedReading && busyCount === 0) {
        if (found) console.log('found :D');
        else console.log('not found :(');
        await Promise.all(pool.map(w => w.terminate()));
      }
    }
  });

  return worker;
});

const start = () => {
  stream = fs.createReadStream('./data.txt');

  stream.on('data', data => {
    pool[roundCount % cpus].postMessage(data.toString());
    busyCount++;
    roundCount++;
  });

  stream.on('end', () => {
    finishedReading = true;
  });
};
```

**Worker thread: (search.js)**
```js
const { parentPort } = require('worker_threads');

parentPort.on('message', data => {
  const el = data.split('\n').map(parseInt).find(el => el === -1);
  parentPort.postMessage({ type: 'result', found: typeof el !== 'undefined' });
});
```

The purpose of this exercise is to pipe the content of a stream to a thread pool and parallelise all the work.
I was expecting to get a better result from the multithread version, in terms of time, but instead I got exactly the opposite.
That's weird:

<img width="616" alt="single-vs-multi" src="https://user-images.githubusercontent.com/647020/77896409-8ae31000-7278-11ea-8805-a521ccfccbd2.png">

I also tried to increase the `highWaterMark` option of the stream but it just got worst.
Why that?
Did I miss something?
Are my expectations correct?

Maybe it can be related to this issue: https://github.com/nodejs/help/issues/2315 ?

**Comment by Hakerh400** [comment]
First, this part

```js
stream.on('data', data => {
  const el = data.toString().split('\n').map(parseInt).find(num => num === -1);
  if (el) found = true;
});
```

is fundamentally incorrect. It does not do what you may expect. Data chunk can be split at any location, meaning that it can theoretically cut a number in half. For example, if you have this content in the text file:

```
123
456
789
```

and you are searching for number `45`, you may receive the chunk

```
3
45
```

and your program will incorrectly report that `45` is found. You need to manually parse line breaks and use some buffer to store data from previous chunk (or use readline interface). Similar in the multi-threaded version.

Also, this code:

```js
data.toString().split('\n').map(parseInt)
```

is probably not what you want. Function `parseInt` takes an optional second parameter, which is the number base. `Array.prototype.map` will call it with the index, which is `0`, `1`, `2`, etc. For example:

```js
'1\n2'.split('\n').map(parseInt); // [1, NaN]
```

---

Regarding the performance issue you are experiencing, it is probably due to the fact that sending a message to a worker is much more expensive than parsing a small chunk of data. I think it is expected.

**Comment by wilk** [comment]
@Hakerh400 Thanks for your reply.
In this case I'm not concerned about the feasibility of the exercise.
It works for the purpose and that's fine.
In fact, I'm searching for a negative number (that's hardcoded) inside a positive number set: no problem if some number gets truncated.
Also the default value of the second parameter of `parseInt` is 10 and also that is fine because the `data.txt` file has a final `\n`.

Said that, I'd like to have a confirm about the performance issue: it really builds up almost 10s delay out of a total of 50 for the solely serialise/deserialise part?

**Comment by wilk** [comment]
Just to be clear: I did this exercise to test if it makes sense piping a stream inside a worker pool and load balancing it between multiple threads to take full advantage of parallel computation.

**Comment by addaleax** [comment]
Fwiw, I can’t also reproduce the performance behaviour that you’re seeing (maybe it’s because `os.cpus().length` varies here). I generated an actual large file using `shuf -i 0-134600000 -n 3221225472`, and this was the result:

```
$ time node single.js 
not found :(

real	0m14,828s
user	0m14,136s
sys	0m1,227s
$ time node multi.js 
not found :(

real	0m5,541s
user	0m34,561s
sys	0m1,563s
```

This is what I would have expected – the total computation time goes up because of the overhead and the relatively small chunks, but the overall execution time goes down.

> Said that, I'd like to have a confirm about the performance issue: it really builds up almost 10s delay out of a total of 50 for the solely serialise/deserialise part?

Yes, although there are some surprising things going on here that might make sense to look at in more detail.

I tried both using 

```js
    pool[roundCount % cpus].postMessage(data, [data.buffer]);
```

and

```js
    pool[roundCount % cpus].postMessage(data);
```

and then converting the Buffer to a string in the worker thread, but surprisingly, this came with a significant negative change in performance. That’s probably worth being considered a bug in either Node.js or V8.

One thing that I’m confused by though is the fact that this doesn’t seem to actually be doing round-robin – shouldn’t `roundCount` be increased in the `stream.on('data')` handler? Otherwise data from chunks that are read after each other might just end up going to the same worker.

**Comment by wilk** [comment]
@addaleax Thanks for your detailed reply!

Well, it seems it is working as expected on your machine: is it possible to have different behaviours on different OSs?
Otherwise I cannot explain why I get a different (worst) result.

For the Node.js/V8 bug: so, did I just win the bugfix ticket? 😄

Nice catch!
It may happen for the first bunch of chunks: I'm gonna change the logic to make the round-robin behaviour effective.

**Comment by addaleax** [comment]
> @addaleax Thanks for your detailed reply!
> 
> Well, it seems it is working as expected on your machine: is it possible to have different behaviours on different OSs?
> Otherwise I cannot explain why I get a different (worst) result.

I think there may be some OS-dependency here, but it’s probably negligible. I have 8 CPU core, I think that might make a bigger difference.

> For the Node.js/V8 bug: so, did I just win the bugfix ticket? smile

Sorry, after looking into it, it was just my fault. Since `Buffer` are received as plain `Uint8Array`s on the receiving end of a `postMessage()`, `.toString()` does something pretty different. `Buffer.from(data.buffer).toString()` in `search.js` is the correct transformation and gives comparable performance.

> 
> Nice catch!
> It may happen for the first bunch of chunks: I'm gonna change the logic to make the round-robin behaviour effective.

Yeah, I think that might also play a big part here.

---

Overall, with the `roundCount` fixed, this program seems to do what it’s supposed to – the overhead of message passing seems relatively low, so using Worker threads should be improving performance here. They do for me, locally, at least.

**Comment by Hakerh400** [comment]
Tested on Windows and unable to reproduce performance regression:

```
single.js - 9.547s
multi.js  - 5.980s
```

> converting the Buffer to a string in the worker thread, but surprisingly, this came with a significant negative change in performance.

I'm unable to reproduce that either. It has minor performance regression (about half of a second in total). Are you sure you are properly stringifying it?

---

> Also the default value of the second parameter of parseInt is 10 and also that is fine because the data.txt file has a final \n.

I understand your intention is to show code that demonstrates performance issues and not ask how to find a number, but I must again say that it does not do what you want. If you want to find number `5` (assuming `-1` is not hardcoded), given the following `data.txt` file:

```
3
5
7
```

your code prints `not found :(`

**Comment by wilk** [comment]
@addaleax I think I made a huuuuuge mistake here: interpreting the output of `time` on Mac 😬 
I considered the `user` time as the `total` time but as you can see in the screenshot above, that's the real total time taken by the execution.
So.... that's really not an issue 🤦‍♂ 
It was already working as expected.

Sorry, my bad.
