### ISSUE TITLE
Node is taking up a lot of processor time

### ISSUE THREAD

**Issue by FrAgFo0d** [nodejs/help#2570]
* **Node.js Version**: 12.14.1 and 12.16.1
* **OS**: Mac OS Catalina (10.15.4) (with i7 processor)
* **Scope (install, code, runtime, meta, other?)**: Using with yarn and webpack in PHPStorm 
* **Module (and version) (if relevant)**: Yarn version 1.17.3, NPM Version: 6.13.4, Webpack 4.35.3

Use of webpack and its dev server.

When in use the processor percentage is at about 300% 
Fans are blowing all the time to cool it down. 

I also tried to use Node directly from the terminal, with all other screens closed. 
Then again the CPU time went up to 300%. 
With that I conclude that it is not the IDE which is causing this issue.

**Comment by addaleax** [comment]
> Use of webpack and its dev server.

That probably means that it’s more related to webpack than to Node.js itself.

Without a reproduction, it’s probably hard to tell what’s happening here.

**Comment by gireeshpunathil** [comment]
@FrAgFo0d - is this still an issue for you? if so, pls provide details as suggested.

In general, I have seen webpacking consumes CPU and time, and these are proportional to the volume of the project. So if you have a large project with you (mega bytes of source code) , I would deem this as expected (the packing essentially means parsing, compiling, and composing text). If it causes unbounded (hang) processing, then it is a bug, otherwise I suggest provide the details and then we can attempt to recreate and observe.

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
