### ISSUE TITLE
node.js not creating app in cmd

### ISSUE THREAD

**Issue by jsamuel29** [nodejs/help#2594]
* **Version**:
* **Platform**:
* **Subsystem**:

### Additional information

 when i type in the command terminal "create-react-app" and the name of the app it keeps giving me warning messages. After that when i navigate to the app and type npm start the command gives me a bunch of errors like for example " Failed at the ravenous@0.1.0 start script." and here are several more examples: "npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ravenous@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ravenous@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jonathan Samuel\AppData\Roaming\npm-cache\_logs\2020-04-09T16_06_48_764Z-debug.log
"

**Comment by PoojaDurgad** [comment]
@jsamuel29 - for me probably with your issue, the start script in your package.json is react-scripts start . so install 'npm install react-scripts' globally and try to run the command `react-scripts start` instead of npm start. this issue looks similar to 
https://github.com/facebook/create-react-app/issues/8221 hope it may help.

**Comment by PoojaDurgad** [comment]
inactive . closing!! please let me know if that is not the case.
