### ISSUE TITLE
Why is 'end' event not explicitly mentioned on instances of http.IncomingMessage on Node.js API docs?

### ISSUE THREAD

**Issue by segmentationfaulter** [nodejs/help#26]
There is only one event mentioned for the instances of http.IncomingMessage on [Node.js API docs](https://nodejs.org/api/http.html#http_http_incomingmessage) and that is 'close'. Why is 'data' and 'end' events are not mentioned there?

**Comment by martinheidegger** [comment]
@segmentationfaulter In the documentation `http.IncomingMessage` is mentions that it implements Readable stream. Readable stream requires a `data` and `end` event but regarding the close event is conditionally (not necessarily implemented) which is why it is mentioned in the `http.IncomingMessage`

> Not all streams will emit the 'close' event.

[here](https://nodejs.org/api/stream.html#stream_event_close)

**Comment by segmentationfaulter** [comment]
thank you @martinheidegger , it makes sense now.
