### ISSUE TITLE
What are the Authentication's are available  in NodeJS?

### ISSUE THREAD

**Issue by LaxmanL** [nodejs/help#261]
Hi all,
    I am very new to Nodejs,  we have a one nodejs web application,  we are planning to implement Authentication(Login) module in our application which one is better can you any one Help me out?

   while i am googling(R & D) i got two types of logins, that is JWT (json web token) and Passport authentication.
other then this Is it there any better module to authenticate. 

Thanks & Regards,
Laxman.

**Comment by danielkhan** [comment]
Hello Laxman - I think there is a little mixup.

jwt is *a way to authorize* a request.
Passport is a *module* that provides various ways of authentication through drivers.
You can use passport to implement a jwt based authentication.

But let's approach this a little more systematic:

1. Find out *against what* how you want to *authenticate* your users. Will the credentials be stored in a database or maybe you want them to log in using Facebook or even their active directory passwort?

2. Decide how you want to *authorize* requests. Will it be some session stored in a cookie because you are dealing with regular web requests or do you want to authenticate REST requests which could be done via JWT?

3. Get the passport driver for the authentication you chose and and implement the routes in your application.

**Comment by LaxmanL** [comment]
Hi Khan,

This very helpful for me,  Thanks you very much .

Thanks,
Laxman
