### ISSUE TITLE
Downloading file using Nodejs causing data loss in excel files

### ISSUE THREAD

**Issue by akulmehta** [nodejs/help#2615]
* **Version**: v12.13.1
* **Platform**: Windows 10 (64-bit)
* **Subsystem**: fs / File System

### What steps will reproduce the bug?

I am trying to create a script in node.js which will download an excel file. My code is built upon first making an `http.get` request to the URL and then write to a file using `response.pipe` and `createWriteStream`. My code is as follows:

```
const fs = require("fs");
const http = require("http");

let url = "http://www.functionalglycomics.org:80/glycomics/HFileServlet?operation=downloadRawFile&fileType=DAT&sideMenu=no&objId=1002183";

http.get(url, response => {
  let file = fs.createWriteStream('file.xls');
  let stream = response.pipe(file);
})

```

If you download the following file using Firefox the file downloads appropriately and if you open the file it works fine and excel does not give any errors.
http://www.functionalglycomics.org:80/glycomics/HFileServlet?operation=downloadRawFile&fileType=DAT&sideMenu=no&objId=1002183

Note- the download link above will not work with Chrome due to [this][1] issue with the filename containing `,` in filename. Therefore I cannot use puppeteer for this.

However if I use my script above and download the file and try to open it in excel it gives me an error stating "data may have been lost" 5 times but then eventually still opens the file. 

[![File error: data may have been lost error][2]][2]

My question is therefore, what is causing this data loss when downloading using nodejs?

**Update**

Some data about versions:

 - Node:v12.13.1 
 - Excel: Office 2019 
 - OS: Windows 10 latest

  [1]: https://www.ryadel.com/en/err_response_headers_multiple_content_disposition-error-google-chrome-fix/
  [2]: https://i.stack.imgur.com/jMzBt.png

### How often does it reproduce? Is there a required condition?
Everytime

### What is the expected behavior?
expect it to download the file like firefox and not corrupt any data in the file.

### What do you see instead?
See error in excel indicating data loss.

**Comment by Hakerh400** [comment]
> Note- the download link above will not work with Chrome due to this issue with the filename containing , in filename. Therefore I cannot use puppeteer for this.

It is not a Chrome issue. Chrome properly follows the specification. The response is indeed invalid. It is more a Firefox issue which allows you to download the file. The server responds with the following headers:

```
HTTP/1.1 200 OK
Date: Sat, 18 Apr 2020 01:20:39 GMT
X-Powered-By: Servlet 2.5; JBoss-5.0/JBossWeb-2.1
Content-Disposition: inline; filename=BCIA-10,000x­_7162_V3.1_DATA.xls
Content-Type: application/vnd.ms-excel
Connection: close
Transfer-Encoding: chunked
```

According to the [specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2):

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.

So, yes, the server is the one who violates the specification.

> My question is therefore, what is causing this data loss when downloading using nodejs?

I cannot reproduce. It may be your Excell that is complaining about something. Firefox on windows adds some extra file headers after downloading a file. Can you compute SHA512 of the downloaded file and ensure it is consistent with Firefox? I get the following SHA512 both when downloading using Firefox and Node.js and I do not get any warnings when opening files:

```
d091c777639b774891e2e1d3dc846832fb492404a44f148dbc398314876de6f8005b5d2359bc95e38d85627e191139d2c9347e0ed225b18c8bd349d48726033b
```

**Comment by akulmehta** [comment]
Yes I did not say it was a Chrome issue, I said it was "this" issue and the issue mentioned on that page does state it clearly that the issue is due to improperly specifying headers by the server. That being said, I cannot control that particular website's backend to change it. 

If I may ask which version of Excel are you using and which OS?

I am getting the same hash from node:
`d091c777639b774891e2e1d3dc846832fb492404a44f148dbc398314876de6f8005b5d2359bc95e38d85627e191139d2c9347e0ed225b18c8bd349d48726033b`

and from firefox:
`d091c777639b774891e2e1d3dc846832fb492404a44f148dbc398314876de6f8005b5d2359bc95e38d85627e191139d2c9347e0ed225b18c8bd349d48726033b`

**Comment by Hakerh400** [comment]
> If I may ask which version of Excel are you using and which OS?

I am using LibreOfficeCalc on Ubuntu, which can properly open all .xls files.

Regarding the *"data may have been lost"* error in Excel: I did some more digging. There is something on Windows NTFS file systems called alternate data streams (ADS). They are hidden file content and can be accessed by appending colon character `:` after file name. There are tools for listing and inspecting ADS.

When you download a file, browser uses ADS to store information that the file is downloaded from the internet and to tell the operating system that it may contain harmful data (because the file is not created offline). Firefox stores that information in an ADS called `Zone.Identifier`.

Microsoft Excel has a registry of all files that you created offline. When you try to open a file that is downloaded from the internet, Excel checks the `Zone.Identifier` stream and if it exists, Excel adds the file to the registry and starts to track it. If the stream is not present in the file, Excel expects it to already be in the registry. However, Node.js does not add any ADS, so Excel thinks that the registry is corrupted and reports an error, despite the file being perfectly valid.

You can confirm that yourself. Try to run the following code:

```js
console.log(fs.existsSync('node.xls:Zone.Identifier'));
console.log(fs.existsSync('firefox.xls:Zone.Identifier'));
console.log(fs.readFileSync('firefox.xls:Zone.Identifier', 'utf8'));
```

where `node.xls` is downloaded using Node.js and `firefox.xls` is downloaded using Firefox. You will get the following output:

```
false
true
[ZoneTransfer]
ZoneId=3
```

**How to solve it**

You can either ignore the error or artificially add the stream yourself (not tested):

```js
fs.writeFileSync(
  'node.xls:Zone.Identifier',
  '[ZoneTransfer]\r\nZoneId=3\r\n',
);
```

It may be the case that there are other hidden streams that affect the Excel's behavior. Try to inspect all streams and find the one that works.

**Comment by akulmehta** [comment]
Thanks for taking such a deep interest in this issue. I suppose I will have to live with the errors. But I will try out your suggestion to add the stream as well tomorrow.

**Comment by akulmehta** [comment]
@Hakerh400 the workaround suggested above to add the Zone.Identifier ADS solved the problem and does not produce the error anymore on reading the file in "Protected View" (the security warning which shows up at the top when you download an office file from the internet). However, on trying to "Enable Editing", excel still produces those errors 5 times. 
I am ok with this solution as it does not seem to be causing any real data compromise and we can still read the files if need be.

The final code which I used to do this:
```
http.get(url, response => {
  let file = fs.createWriteStream('file.xls');
  let stream = response.pipe(file);
  fs.writeFileSync(
    'file.xls:Zone.Identifier',
    `[ZoneTransfer]\r\nZoneId=3\r\nHostUrl=${url}`,
  );
})
```
