### ISSUE TITLE
Cannot Find Modules

### ISSUE THREAD

**Issue by DNR07** [nodejs/help#2619]
* Node.js Version: v12.16.2
* OS: Microsoft Windows [Version 10.0.18363.720]
* **Scope (install, code, runtime, meta, other?)**: Runtime

I'm getting a "Cannot find module" error. 
PFA files to understand the issue.
![Screenshot (72)](https://user-images.githubusercontent.com/56871181/79682758-6e684100-8242-11ea-844c-7fffd84b3aa6.png)
![Screenshot (73)](https://user-images.githubusercontent.com/56871181/79682759-70320480-8242-11ea-8f2f-ef7d9f75f8f8.png)
![Screenshot (76)](https://user-images.githubusercontent.com/56871181/79682760-70ca9b00-8242-11ea-85b0-9b076ea9ad70.png)

**Comment by Hakerh400** [comment]
You need to add quotes:

```
node "Test-7(obj prototype).js"
```

**Comment by DNR07** [comment]
> You need to add quotes:
> 
> ```
> node "Test-7(obj prototype).js"
> ```

Woah, thanks a lot man.. It worked but can you please explain why the quotes had to be put?

**Comment by Hakerh400** [comment]
> why the quotes had to be put

Because there is a space character in the script name. Command line arguments are separated by spaces, unless they are surrounded by double quote characters.

When you type `node Test-7(obj prototype).js`, Node.js thinks that you are trying to
call script `Test-7(obj` with script argument `prototype).js` (everything after script name are script arguments).

If you indeed create file `Test-7(obj.js` and put `console.log(process.argv)`, and
then run `node Test-7(obj prototype).js`, you will get the following output:

```js
[
  'C:\\Program Files\\nodejs\\node.exe',
  'F:\\Node.JS\\Per\\Test-7(obj',
  'prototype).js'
]
```

**Comment by DNR07** [comment]
> > why the quotes had to be put
> 
> Because there is a space character in the script name. Command line arguments are separated by spaces, unless they are surrounded by double quote characters.
> 
> When you type `node Test-7(obj prototype).js`, Node.js thinks that you are trying to
> call script `Test-7(obj` with script argument `prototype).js` (everything after script name are script arguments).
> 
> If you indeed create file `Test-7(obj.js` and put `console.log(process.argv)`, and
> then run `node Test-7(obj prototype).js`, you will get the following output:
> 
> ```js
> [
>   'C:\\Program Files\\nodejs\\node.exe',
>   'F:\\Node.JS\\Per\\Test-7(obj',
>   'prototype).js'
> ]
> ```

Ah alright, thanks for your time!
