### ISSUE TITLE
Will node GC the memory that not sliced on a buffer?

### ISSUE THREAD

**Issue by LongTengDao** [nodejs/help#2627]
* **Node.js Version**: 12
* **OS**:
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: buffer

```js
let whole = Buffer.alloc(2000);
const reserved = whole.slice(1000);
whole = null; // Will the first 1000 bytes be GC?
```

If yes, how does engine know that, while the buffer is in node pre-allocated pool?
If no, because buffer.buffer refers to the whole buffer, then how to GC the first 1000 bytes?

**Comment by Hakerh400** [comment]
`slice` does not copy data, it just creates another view on the underlying `buffer`. To actually copy data, use either `Buffer.from(whole.slice(1000))` or `Uint8Array.prototype.slice`.

**Comment by LongTengDao** [comment]
Thank you, but I don't want to copy data, I just want to reserve part of the original buffer, and drop the rest. But since the buffer refers the original buffer via .buffer property, it seems that the whole buffer won't be release until any part of the buffer reference disappear.

**Comment by addaleax** [comment]
Generally, there is no way to de-allocated only parts of an `ArrayBuffer`, by design, in JS. If you need that option, the best approach is probably to maintain a list of Buffers instead of a single Buffer, so that some of them can be GC’ed when they are no longer being used.

> But since the buffer refers the original buffer via .buffer property, it seems that the whole buffer won't be release until any part of the buffer reference disappear.

That’s correct :+1: Is there anything else to be answered here?
