### ISSUE TITLE
max concurrency on one thread

### ISSUE THREAD

**Issue by nsiitk** [nodejs/help#263]
I am trying to benchmark the nodejs hello world program in one thread.
http.createServer(function (req, res) {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.write('request successfully proxied: ' + req.url +'\n' + JSON.stringify(req.headers, true, 2));
  res.end();
}).listen(8081);
Nodejs version: v6.4.0
OS: CentOS Linux release 7.0.1406
 I see 100% cpu usage on concurrency of 1500. 

cpu profiling shows

[Bottom up (heavy) profile]:
  Note: percentage shows a share of a particular caller in the total
  amount of its parent calls.
  Callers occupying less than 2.0% are not shown.

   ticks parent  name
  10187   14.0%  /usr/lib64/libpthread-2.17.so
   3619   35.5%    LazyCompile: *Socket._writeGeneric net.js:654:42
   1545   42.7%      LazyCompile: *clearBuffer _stream_writable.js:376:21
   1380   89.3%        LazyCompile: *_flushOutput _http_outgoing.js:652:63
   1380  100.0%          LazyCompile: *OutgoingMessage._writeRaw _http_outgoing.js:145:47
   1380  100.0%            LazyCompile: *OutgoingMessage._send _http_outgoing.js:122:43
     83    5.4%        Handler: host {194}
     83  100.0%          LazyCompile: *OutgoingMessage._writeRaw _http_outgoing.js:145:47
     83  100.0%            LazyCompile: *OutgoingMessage._send _http_outgoing.js:122:43
     82    5.3%        LazyCompile: *Writable.uncork _stream_writable.js:232:37
     82  100.0%          LazyCompile: ~_flushOutput _http_outgoing.js:652:63
     82  100.0%            LazyCompile: *OutgoingMessage._writeRaw _http_outgoing.js:145:47
   1120   30.9%      LazyCompile: ~<anonymous> net.js:661:34
   1120  100.0%        LazyCompile: ~g events.js:282:13
   1120  100.0%          LazyCompile: *emit events.js:136:44
   1120  100.0%            LazyCompile: *afterConnect net.js:1045:22
    954   26.4%      LazyCompile: *writeOrBuffer _stream_writable.js:269:23
    954  100.0%        LazyCompile: *OutgoingMessage._writeRaw _http_outgoing.js:145:47
    954  100.0%          LazyCompile: *OutgoingMessage._send _http_outgoing.js:122:43
    861   90.3%            LazyCompile: *OutgoingMessage.write _http_outgoing.js:425:43
     93    9.7%            LazyCompile: ~OutgoingMessage.write _http_outgoing.js:425:43
   2958   29.0%    LazyCompile: *Socket._destroy net.js:458:37
   1827   61.8%      LazyCompile: *responseKeepAlive _http_client.js:484:27
   1827  100.0%        LazyCompile: *responseOnEnd _http_client.js:508:23
   1827  100.0%          LazyCompile: *emit events.js:136:44
   1827  100.0%            LazyCompile: *endReadableNT _stream_readable.js:970:23
   1131   38.2%      Handler: host {6}
   1131  100.0%        LazyCompile: ~resOnFinish _http_server.js:496:25
   1131  100.0%          LazyCompile: *emit events.js:136:44
   1131  100.0%            LazyCompile: ~finish _http_outgoing.js:580:18
   2657   26.1%    LazyCompile: *connect net.js:810:17

What is the maximum concurrency that can be achieved by nodejs http server. How can I increase the concurrency without 100%cpu.

**Comment by Trott** [comment]
I'm not 100% sure I understand the question, although a part of me wants to just say "cluster module". No guarantees that anyone is going to jump in and answer, but let's see if some benchmarking people have anything to say. @nodejs/benchmarking

**Comment by gareth-ellis** [comment]
Hi @nsiitk ,

I've just had a go at recreating. I don't have a Centos system available, so this is run on Ubuntu. I used wrk to benchmark - which tool did you use?

The results from asking for 800 connections and 30 threads.

> wrk -c 800 -t 30 -d 60 http://localhost:8081
Running 1m test @ http://localhost:8081
30 threads and 800 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    47.66ms    4.09ms 206.57ms   87.88%
Req/Sec   545.81     48.44   787.00     83.95%
976700 requests in 1.00m, 192.94MB read
Requests/sec:  16258.26
Transfer/sec:      3.21MB

So from that we seem to be able to achieve 16000 requests per second. I can increase the number of connections (in wrk you increase the number for -c), however we see the latency increase without much change in the requests/second. This is because there is no resource left available to node to deal with more requests, so they just have to wait for node to get round to dealing with the request.

Is this the number where you're seeing 1500? 

Or do you mean where you're specifying the number 1500 instead of 800 and seeing 100% cpu usage? 

I'd say from a single instance not being able to maintain 1500 simultaneous connections is probably acceptable. However as @Trott mentioned, using cluster to fork more child processes would be the way to go if you need to be able to handle more concurrent connections. 

Setting up something like this:
https://gist.github.com/gareth-ellis/fe80d98286914db2e40486100d6f32c9

Lets me run much more, though we are perhaps reaching the limit here. Notice the slightly higher latency, as well as a pretty nasty max of almost a second:

> wrk -c 3200 -t 30 -d 60 http://localhost:8081
Running 1m test @ http://localhost:8081
  30 threads and 3200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    51.67ms   14.53ms 931.27ms   99.63%
    Req/Sec     2.00k   226.73     2.61k    85.41%
  3583666 requests in 1.00m, 708.00MB read
Requests/sec:  59630.81
Transfer/sec:     11.78MB

**Comment by nsiitk** [comment]
I have tested it using spirent avalanche where I was increasing the connection/sec load till node process cpu reaches 100%. I have used cluster mode on 8 core machine and reached 8200 c/s on 7 workers. latency remain under 10ms  till cpu reaches 100% .  I was testing on single thread to evaluate the capacity of node http server per core.
