### ISSUE TITLE
Node Issue on AIX 7.2 TL 4

### ISSUE THREAD

**Issue by chaithuprsnl** [nodejs/help#2630]
* **Node.js Version**: node-v4.2.3-linux-x64 
* **OS**: AIX 7.2 TL 4
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

We have the following versions installed on AIX 7.2 TL 4.

GCC 8.3.0
node-v4.2.3-linux-x64

PATH, LIBPATH, LD_LIBRARY_PATH are set as follows

export PATH=<Path>:/appsrc/node-v4.2.3-linux-x64/bin
export LD_LIBRARY_PATH=/opt/freeware/lib64
export LIBPATH=/opt/freeware/lib/gcc/PowerPC-ibm-aix7.2.0.0/8.3.0/ppc64

When I run node or node -v commands, I am getting the following error

**exec(): 0509-036 Cannot load program node because of the following errors:
rtld: 0712-001 Symbol _ZNKSt9type_infoeqERKS_ was referenced from module node(), 
but a runtime definition of the symbol was not found.
rtld: 0712-002 fatal error: exiting.**

When I comment the below in .profile
#export LD_LIBRARY_PATH=/opt/freeware/lib64
#export LIBPATH=/opt/freeware/lib/gcc/PowerPC-ibm-aix7.2.0.0/8.3.0/ppc64

I got different error when I run 'node' or 'node -v' command
exec(): 0509-036 Cannot load program node because of the following errors:
                0509-150   Dependent module libstdc++.a(libstdc++.so.6) could not be loaded.
                0509-022 Cannot load module libstdc++.a(libstdc++.so.6).
                0509-026 System error: A file or directory in the path name does not exist.

Am getting this issue with NodeJS-v13.13.0 as well. But I need to run node-v4.2.3-linux-x64 for our application.

Could you please suggest what is going wrong, I am stuck with this issue.

**Comment by bnoordhuis** [comment]
Going by the error messages, you either don't have libstdc++ in a location where the dynamic linker can find it or it's an incompatible version.

That missing symbol `ZNKSt9type_infoeqERKS` is [`std::type_info`](https://en.cppreference.com/w/cpp/types/type_info) and, as the `std` prefix suggests, lives in the C++ standard library.

cc @nodejs/platform-aix

**Comment by shellberg** [comment]
GCC and its compatible C++ library do need to be 'installed' together as a package.  You need to ensure that these were successfully added to the AIX 7.2 system first, and then you likely need to expose(override) those in the context of the package that demands it, e.g. Node.js v13.  You might want to review some of the advice, such as posted at the Bull Freeware, on the subject of adding higher-than-default compilers to AIX: http://www.bullfreeware.com/howto
(NOTE: You are adding the compiler and its level of C++ in addition to the platform default ; don't try and substitute or remove the default C++ library of AIX 7.2 - a world of pain will ensue!)

However, the basic C++ support needed for Node.js v4 is already covered in the AIX 7.2 platform's default C++ library - that would be sufficient.  There wasn't a community AIX release at Node.js v4 ; IBM was producing its AIX port at that time (IBM SDK for Node.js), and still in the contribution process.  So, you would need to chose your 'linux' level carefully, because you need a big-endian PowerPC based image...  Although you are reporting runtime linkage errors, so you must have got a good enough executable - did you compile it yourself?  If so, you should be able to execute it on the platform you compiled it on, but you might be faced with issues having tried to distribute that image thereafter to another server?

**Comment by gireeshpunathil** [comment]
@sumitradawn - do you have a similar environment? if so, we could try reproduce this

**Comment by gireeshpunathil** [comment]
@chaithuprsnl - is this still an issue?

**Comment by mhdawson** [comment]
There has been no response from the OP for quite some time, even after @gireeshpunathil asked. I'm going to close the issue. Please let us know if that was not the right thing to do.
