### ISSUE TITLE
bad code examples in stream.html?

### ISSUE THREAD

**Issue by pps83** [nodejs/help#268]
There are multiple places where examples do not make sense IMO.
For example, in [using the Simplified Constructor approach](https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options) there is this sample code:
```
const myWritable = new Writable({
  write(chunk, encoding, callback) {
    // ...
  },
  writev(chunks, callback) {
    // ...
  }
});
```
these are function calls and not function declarations there. It has to be:
```
const myWritable = new Writable({
  write: function(chunk, encoding, callback) {
    // ...
  },
  writev: function(chunks, callback) {
    // ...
  }
});
```
Same error is in other locations there. For example in [Errors While Writing](https://nodejs.org/api/stream.html#stream_errors_while_writing) sample code.

Is that an error there, or it's some different js syntax?

**Comment by addaleax** [comment]
Something like

```js
({
  a() {
    return 42;
  }
}).a();
```

is perfectly valid ES6 syntax and supported by all Node versions >= 2.0, including the version for which you are viewing the docs, namely v6.x.

You can find the current versions of the Node documentation at:
- https://nodejs.org/api/ – Latest (currently v6.x)
- https://nodejs.org/dist/latest-v6.x/docs/api/ – v6.x
- https://nodejs.org/dist/latest-v4.x/docs/api/ – v4.x

If you try the above code with something older than that, e.g. Node v0.10 or Node v0.12, it won’t work (you should also definitely upgrade to at least v4.x in that case, because these versions will soon reach their end of life). You need to view the docs for those versions if you want appropriate JS syntax and Node.js features.

Maybe I’m misunderstanding your point… if so, please clarify that :)
