### ISSUE TITLE
Decreasing CPU performance over time. 

### ISSUE THREAD

**Issue by przemkow** [nodejs/help#2721]
* **Node.js Version**: 12.16 (similar behaviour on 10.16)
* **OS**: Linux (docker image of node:12.16-alpine)
* **Scope**: CPU performance runtime problem

Hi all, I create this issue to ask you for some help/suggestion how could I detect CPU performance issue of our node.js instance. 

We have Nuxt.js (`"nuxt": "^2.11.0"`) applications running in a docker container on amazon ECS.

The problem we currently have is related to slowly decreasing performance of node.js instance. 

Here are some charts from new relic:
Web transaction time/number of request on that specific machine:

<img width="1178" alt="Screenshot 2020-05-22 at 14 50 21" src="https://user-images.githubusercontent.com/10272880/82673398-1ad28400-9c42-11ea-97a8-56a8c97a79c3.png">

Lifetime chart of the instance:

<img width="1178" alt="Screenshot 2020-05-22 at 14 50 21" src="https://user-images.githubusercontent.com/10272880/82673513-47869b80-9c42-11ea-83fa-c77dce91b6e4.png">

As you can see during the first few hours everything seems to work fine but after some time our instance goes to an unstable state with a very high response time. When we arrive at the critical value load balancer is spawning a new server and turns off the one with the poor performance.  
Ex here is the average web transaction time drop after restarting the server:
<img width="598" alt="Screenshot 2020-05-22 at 14 33 00" src="https://user-images.githubusercontent.com/10272880/82674472-a4368600-9c43-11ea-8ed3-52c426c1ad1c.png">
 

we run Node.js instance using :
`node --max_old_space_size=460 node_modules/.bin/nuxt start`  
on the machine which has ~512mb of memory. 

We tried also `--optimize_for_size` or `--gc_interval=100` commands as we thought that it might be related with GC performance but the final result was always the same, the machine was turned off after few hours by the load balancer. 

I tried to run this docker instance locally and reproduce this issue using `clinicjs`, `autocannon / artillery` but I couldn't find anything, also profiling CPU with chrome dev tools did not show anything suspicious. 

Do you have any suggestions on how could we debug this issue when it appears on the server instance? is there any way to get a memory snapshot / run CPU profiler on the server and send those metrics to external service (like new relic)? I would be really grateful for any suggestion. 
Thanks a lot!

**Comment by squarewav** [comment]
I'm not speaking from experience because I don't have any node apps in production under load but based on my decades of experience as a programmer, my guess would be that you have an error (or multiple errors) in your code and you're leaking resources like not waiting for a drain event on a stream or something like that.

To figure it out, I would probably create a very light weight "resource metrics" log file and sprinkle the code with log statements that write comma separated lists of info to the log. Have each module of code maintain an object that is just a map of counters indicating the number of outstanding requests or streams or file handles or whatever. During idle periods these numbers should generally be either 0 or limited. Import the log into a spreadsheet and sort and filter to see if you can see an issue.

Then I would create a "torture test" that exercises whatever you can programmatically using a pool of HTTP clients. Run it and study said resource metrics log.

**Comment by franciscotln** [comment]
First think I would try is to increase max-semi-space-size to 128 since your charts show an increase in the rate of scavenge garbage collections. it could mean that your new-space is too small and GC scavenge has to work very frequently, compromising your allocated CPU capacity

**Comment by przemkow** [comment]
This issue has been caused by Axios, an external library used for HTTP requests. 

I found an issue addressing this problem in their repository: 
https://github.com/axios/axios/issues/3217

To resolve this memory leak we temporarily removed the usage of Axios interceptors.
