### ISSUE TITLE
How to connect Node service with Office 365 Mail Box

### ISSUE THREAD

**Issue by ShankerBhandari** [nodejs/help#2749]
I'm facing issues while trying to read mail from Office 365 account.
Below is the code I'm using:

const EWS = require('node-ews');
 
// exchange server connection info
const ewsConfig = {
  username: 'myuser@myDomain.com',
  password: 'mypassword',
  host: 'https://outlook.office365.com/owa/myDomain.com/',
  auth: 'basic'
};
 
// initialize node-ews
const ews = new EWS(ewsConfig);
 
// define ews api function
const ewsFunction = 'ExpandDL';
 
// define ews api function args
const ewsArgs = {
  'Mailbox': {
    'EmailAddress':'publiclist@domain.com'
  }
};
 
// query EWS and print resulting JSON to console
ews.run(ewsFunction, ewsArgs)
  .then(result => {
    console.log(JSON.stringify(result));
  })
  .catch(err => {
    console.log(err.message);
  });

**Comment by lundibundi** [comment]
Could you clarify what is the error exactly?

Are you sure `host: 'https://outlook.office365.com/owa/myDomain.com/',` this is a correct host for Office EWS?

Perhaps this Microsoft tutorial may help https://docs.microsoft.com/en-us/samples/officedev/outlook-add-in-javascript-makeewsrequest/outlook-add-in-make-an-exchange-web-service-request-from-outlook/?

Anyway, I don't think you will find much help here since this repo is dedicated to helping with Node.js itself and its core modules, and since your main issue is with the npm package I think it would be better to ask in their issue tracker https://github.com/CumberlandGroup/node-ews/issues.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if this is still outstanding.
