### ISSUE TITLE
How do you manually test changes made in nodejs code?

### ISSUE THREAD

**Issue by cschli** [nodejs/help#2761]
* **Node.js Version**: Any
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: Other
* **Module (and version) (if relevant)**: N/A

Hello,

I am very new to this community, and feel like I'm missing a very simple step to being able to contribute. If I make changes on a local branch, how do I get my local instance of node to point at this changed code so I can run node to check how my code change affected things? 

I may still not be wording my question correctly, so please be patient with me if I follow up your answer(s) with more questions.

Thank you.

**Comment by addaleax** [comment]
https://github.com/nodejs/node/blob/master/BUILDING.md contains the instructions for how to build Node.js from the source code (tl;dr: run `vcbuild` on Windows, or `./configure && make -j4` on other OSes).

After that, you will have a `./node` binary in your local checkout on UNIX (`.\Release\node.exe` on Windows), which you can run instead of the `node` binary installed on your system. Using `./node -v` should indicate a pre-release version if everything worked out.

I hope this helps!

**Comment by cschli** [comment]
Thank you, I had previously tried looking through BUILDING.md, but between not entirely sure it was the right file and the sheer length of it, I just got lost in the instruction.
