### ISSUE TITLE
HTTP request object sometimes has no headers

### ISSUE THREAD

**Issue by prettydiff** [nodejs/help#2786]
* **Node.js Version**: 13.2.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

In an application I am writing occasionally an HTTP request will have no headers.  If I attempt to access headers directly as *request.headers* it will be an empty object.  If I attempt to access headers as *request.rawHeaders* it will be an empty array.

I don't know why this is occurring, what to look for in troubleshooting, and it appears to occur randomly about 1 out of 200 times with no sign of rhythm.  Sometimes it will occur after hundreds of HTTP requests and sometimes it will occur after only 2 requests.  I am just using the regular Node HTTP library and nothing from NPM.

What can I do to investigate why this is happening?  It seems like a defect and I assume the defect is is something with my application, though I have no evidence of what is causing the behavior.

**Comment by addaleax** [comment]
Since Node.js 13.x is no longer supported – what happens on the latest versions of v14.x or v12.x?

Are you using some kind of `http.Agent` to schedule multiple requests? At what point are you inspecting `request.headers` or `request.rawHeaders` (i.e. is it immediately after sending the request headers, after `.end()`ing the request, or at some other point in the request’s lifetime)?

**Comment by prettydiff** [comment]
I upgraded to node 14.4.0 and cannot reproduce the problem yet.  If I can reproduce I will reopen this issue with additional details.

I suspect, and this is just guessing, that I have open HTTP connections that are not being closed and they could be contributing to this.
