### ISSUE TITLE
HTTP Client request getting lost for long running API

### ISSUE THREAD

**Issue by Chintanvpatel** [nodejs/help#2827]
* **Version**: v10.16.0
* **Platform**: x86_64 GNU/Linux

### What steps will reproduce the bug?

I'm calling one API endpoint which takes about 15 mins for the response. Here is a sample code, https://gist.github.com/Chintanvpatel/468798f6c321d81cbe4e8cea55aaf394

### How often does it reproduce? Is there a required condition?

Whenever Server takes more than 12 mins to response, at that time I'm not getting any response in NodeJS script.

### What is the expected behavior?

HTTP Request should be resolved and It should execute [next line](https://gist.github.com/Chintanvpatel/468798f6c321d81cbe4e8cea55aaf394#file-gistfile1-txt-L10). 

### What do you see instead?

HTTP Request never finished ( I guess promise is getting lost ) and next line never execute.

**Comment by Chintanvpatel** [comment]
Hi @bnoordhuis , Here is my endpoint for test, http://54.221.26.246:3000/hello15
It show response after 15 mins If you hit this URL in browser. It means, It terminates the response properly. I didn't get you second part about "Content-length".

Anyway I have prepared one example for test, https://repl.it/repls/RustySecondhandLogins#index.js In this You can run it and you can see It never call 'end' event.

Thanks for your help!

**Comment by bnoordhuis** [comment]
> I didn't get you second part about "Content-length".

For example, a server can set `Content-Length: 3` but only send `ok` (2 bytes) as the response body. In that case you'll never see the `'end'` event because node will wait for that promised third byte.

I used Content-Length as an example but there are more ways to create a never-terminating response, e.g., by using `Transfer-Encoding: chunked` and never sending the terminating chunk.

Aside: your test case potentially contains a bug. It appends a `Buffer` to a string but that won't work correctly for multi-byte character sequences (e.g., characters > U+007F in UTF-8.)

**Comment by PoojaDurgad** [comment]
@Chintanvpatel - is this still outstanding?

**Comment by Chintanvpatel** [comment]
@PoojaDurgad Didn't get chance to check.

**Comment by PoojaDurgad** [comment]
closing . please feel free to re-open the issue if its still an issue
