### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Qaiser-313** [nodejs/help#2832]
![Node](https://user-images.githubusercontent.com/50129504/87028599-46143100-c1f8-11ea-98fb-1d5056d1bbc4.PNG)
 **I have too much space  to install but every time I try to install it shows  error**

**Comment by gireeshpunathil** [comment]
@Qaiser-313 - is this still an issue?

This is most likely not directly originating from Node code, but the underlying system. Which OS version you are attempting to do the installation? based on that, see if information provided in this link gives you any guidance.

**Comment by PoojaDurgad** [comment]
@Qaiser-313 - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding

**Comment by sodhairkhan** [comment]
From 3 days i m facing this issue.
![IMG-20210701-WA0013](https://user-images.githubusercontent.com/78597941/124076624-f5789200-da5f-11eb-9e6f-a10632837a11.jpeg)
![Uploading IMG-20210701-WA0010.jpeg…]()

**Comment by sodhairkhan** [comment]
I have a lot of space but  computer didn't know about it .
What should i do

**Comment by gireeshpunathil** [comment]
> but computer didn't know about it .

@sodhairkhan - can you elaborate on this statement? is there any program complaning about not having enough disk space? are you trying to install Node.js?

**Comment by sodhairkhan** [comment]
I TRYING TO RUN  CODE  ON VISUAL STUDIO CODE .
THEY GIVE ERROR  AND TELL THAT INSTALL LATEST VERSION OF POWER SHELL.
I TRYING MANY TIME TO INSTALL POWER SHELL BUT THEY GIVE ME ERROR THAT U HAVE NOT ENOUGH SPACE.
ALTHOUGH I HAVE A LOT OF SPACE IN DISK

**Comment by gireeshpunathil** [comment]
@sodhairkhan - If you have a question specific to Node.js or its associated components you may ask here, this issue is definitely outside the scope of this repository.

( I don't know how powershell installer works, but generally installers unpacks `stuff` in the temporary folder, and if the disc partition that contain temporary folder is small, we can expect similar error. not sure if that is happening here, and not sure if that applies for windows, and even not sure how to check the temporary folder in windows)

**Comment by sodhairkhan** [comment]
OKAY THANX.
