### ISSUE TITLE
node gives me an error saying "prompt not defined". However my Javascript works well as part of an html

### ISSUE THREAD

**Issue by nieve07** [nodejs/help#2839]
* **Node.js Version:12.18.2-x64
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**:

node gives me an error saying "prompt not defined". However my Javascript works well as part of an html

```js
// let str = prompt("What...............","");
```
-->

**Comment by addaleax** [comment]
That’s because [`prompt`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) is part of HTML, not part of JavaScript – Node.js only supports a few Web APIs, like `URL` and `performance`, but not all of them.

The closest thing that Node.js has is probably [`readline.question`](https://nodejs.org/api/readline.html#readline_rl_question_query_callback), but it’s going to read from the command line, not a graphical pop-up like `prompt()` does.

**Comment by nieve07** [comment]
However, I include a statement about prompt in Javascript - maybe it's just that Node.js doesn't support it:

"Javascript | Window prompt() Method. The prompt() method is used to display a dialog with an optional message prompting the user to input some text. It is often used if the user wants to input a value before entering a page. It returns a string containing the text entered by the user, or null."

**Comment by nieve07** [comment]
I didn't mean to close thread ....

**Comment by addaleax** [comment]
@nieve07 If something claims that `prompt()` is part of JavaScript, then that’s not accurate. However, writing code for the Web is still the most common use of JavaScript, so it’s easy to see how that misconception might come up.

Node.js doesn’t have the `window` object either, so that’s why `window.prompt()` is missing (in browsers, `window` is the global object, so `prompt()` is shorthand for `window.prompt()`).

**Comment by nieve07** [comment]
Thank you addaleax .... Is Prompt valid in Java ?

**Comment by addaleax** [comment]
@nieve07 Java is a fully different language, and I don’t know of any packages that implement a browser to the degree that it would support `Window` or `window.prompt()`. I might be wrong about that, though. (It’s definitely not part of the language itself there either.)

**Comment by nieve07** [comment]
Thanks again addaleax. Have a nice weekend.

**Comment by PoojaDurgad** [comment]
closing as answered.
