### ISSUE TITLE
NodeJs v12.18.3 not supported by bundled npm  v5.5.1 on Ubuntu 20

### ISSUE THREAD

**Issue by abhishekmadhu** [nodejs/help#2871]
I installed **node.js LTS (v12)** using instructions [here](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions)

Upon installation, I see proper results with `node -v` (v12.18.3) and `npm -v` (v5.5.1)

**But trying to use npm throws an error:**
```
*** $ npm i underscore
npm WARN npm npm does not support Node.js v12.18.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/*****/.npm/_logs/2020-07-22T22_56_12_979Z-debug.log
```

**My OS information is here:**
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
UBUNTU_CODENAME=focal
```

**Comment by addaleax** [comment]
Hey, and thanks for the report!

I’m moving this over to nodejs/help, because this isn’t really actionable for us as a bug report. It’s primarily a problem with npm, and Node.js only tries to guarantee that the version of npm that we ship with it works, not older npm versions (which sometimes rely on Node.js internals to a degree that we cannot control and that is not reasonable to expect from us to maintain, which includes this particular error).

It’s also not something that npm can do anything about, because they are not in control of the version that Ubuntu ships, and cannot modify outdated already-published versions (the most recent `npm@5` release was `5.10.0`, not `5.5.1`).

I’d suggest that you reach out to the Ubuntu maintainers team in order to have this addressed.

**Comment by abhishekmadhu** [comment]
Hey @addaleax 
Thanks for the quick response. I did some research on this (I am new to Node.js) and your suggestion really helped. 
I could set this up properly with my other computers (Windows) with no additional issues. 

I will raise a bug with the Ubuntu maintainers when I have time. 
Thanks again!
