### ISSUE TITLE
Sending or Attempting to send 1 million Request in Under 1 Second.

### ISSUE THREAD

**Issue by NotMoni** [nodejs/help#2889]
* **Node.js Version**: 14.5.0
* **OS**: macOS Cataline
* **Scope (install, code, runtime, meta, other?)**: Code
* **Module (and version) (if relevant)**:None

So, I read this article a few weeks ago.

https://www.freecodecamp.org/news/million-requests-per-second-with-python-95c137af319/

I want to ask how I can send a lot of requests like he manages to do. This is just for learning. Let's say I have an array with request options. 
How can i send all the requests in parallel at the same time? 
Is this even possible with NodeJS? 
Should I use worker_threads or clusters? 
Should I use the inbuild HTTPS modules or some other module like Axios or node-fetch? 
How would my sample code look like?
Would I use async/await? 
How can i get the `res` object to analyze the requests? 
Should I use the cloud (AWS) to run this or would this be possible on my local PC? 
How can this be done? 
How can this is possible with NodeJS? 
Should I use another language or stick with NodeJS?

I have tried `Promise.all` but its not as fast as I would like it to be. 

Thanks in advance. I just want to know how stuff like this can be done in NodeJS? :D

**Comment by NotMoni** [comment]
cc @addaleax

**Comment by PoojaDurgad** [comment]
@NotMoni - In my opinion I think if the goal is to just process millions of requests as fast as possible, then you want to do the following:
1. Start up enough parallel node.js processes so that you are using all the CPU you have available for processing the request responses.
2. make sure to have much network bandwidth capability to so that you can do networking as good as possible
3. Use asynchronous I/O processing for all I/O bcz, nodejs uses a thread pool for all node implementation.
4. Open  as many simultaneous requests per node.js process (likely somewhere between 2 and 20) depends upon how much of the total time to process a request is networking vs. CPU
5. Create a coordination mechanism among your multiple node.js processes and collect results (something like a work queue)
6. If your requests are all to the same remote server then you will have to figure out how it behaves with multiple requests.

The basic idea is to maximize your use of the CPU so each CPU is always doing as much as it can. Since node.js code is single threaded, you need one node.js process per core in order to maximize your use of the CPU cycles available. Having lot of requests in one short time in queue will cause the memory issue and also affects the performance

and one thing I need to add is, in my perspective ,actually making millions of parallel requests at the same time will not help you get the job done any quicker and it will likely exhaust many system resources (memory, sockets, bandwidth, etc...).
Hope it helps.

**Comment by NotMoni** [comment]
@PoojaDurgad Thanks you for the insight.

**Comment by DishantPal** [comment]
https://stackoverflow.com/questions/38268371/how-to-make-millions-of-parallel-http-requests-from-nodejs-app
