### ISSUE TITLE
Node version question

### ISSUE THREAD

**Issue by Govindaraju** [nodejs/help#2952]
* **Node 6.x**:
We are currently using node version 6.x which needs to be upgraded. My question is can you please let me know in general what potential issues we may face if we keep running node 6 for significant amount of time in the future? Can you please point me to the links which describe the reason for an upgrade?
We are in a situation that upgrade is not straightforward and needs almost a re-write.
Your help on this is much appreciated.

**Comment by addaleax** [comment]
You can find the Node.js security release announcements on https://nodejs.org/en/blog/, and check what impact the security vulnerabilities have on you

**Comment by bnoordhuis** [comment]
> We are in a situation that upgrade is not straightforward and needs almost a re-write.

Can you go into more detail? People might be able to make better recommendations that way.

**Comment by Govindaraju** [comment]
Hi
Thank you both for your response. We are using loopback 2.x on top of node version 6 for our development. If we intend to upgrade to node 12 or beyond we have to move to loopback 4.x which in itself is a re-write which means applications written using loopback 2.x are not directly upgradable to loopback 4.x and hence they need a re-write to a larger extent as loopback 4.x is all done using typescript. Long story short, upgrading node version 6 to node version 14 warrants an upgrade from loopback 2.x to loopback 4.x which needs a re-write. Hope this gives you the background. I m afraid I wont be able to go to the specifics beyond this.

**Comment by AqilCont** [comment]
I think the main things you might miss out on are modern JS features and some performance here and there. Web standards also get new features and stuff, and node is usually up to date on those too in the newer releases. Otherwise, if you can handle most of these changes, you're mostly fine. As the people who commented before sent, it should be a priority to do some research on what security vulnerabilities have been discovered in 6.x before proceeding to any further development.
