### ISSUE TITLE
Potential issue with classes?

### ISSUE THREAD

**Issue by miniDeathStriker** [nodejs/help#2954]
* **Version**: 14.9.0
* **Platform**: win10 64 bit ver 1903
* **Subsystem**: N.A

### What steps will reproduce the bug?

```js
function bugTest(){
    return {test:"bug"}
}
class Test extends bugTest {
    constructor(){
         super()
    }
    someMethod(){return "testing"}
}

let test = new Test()
test.someMethod() //test.someMethod is not a function
```
As you can tell from the example, extending a function will somehow make you unable to use any methods declared within the class.

### How often does it reproduce? Is there a required condition?
Appears to always be present.

### What is the expected behavior?
Being able to access the method.

### What do you see instead?
typeError: #method is not a function

### Additional information
I'm unsure if this is an actual issue, it seems like one for sure.

**Comment by addaleax** [comment]
That’s because `return <value>` will make it so that the result of the `new ...` call will be `<value>`.

You can “““fix””” this by adding `Object.setPrototypeOf(test, Test.prototype);` after the `new Test()` line (or, a bit more generically, `Object.setPrototypeOf(this, new.target.prototype);` after the `super()` line), but whether that’s really what you want here is a different question.

**Comment by RaisinTen** [comment]
Closing as this is answered already.
