### ISSUE TITLE
Kerberos authentication support

### ISSUE THREAD

**Issue by sathyarajagopal** [nodejs/help#2960]
**Problem statement**
At my workplace there are APIs maintained by external teams and are protected through JWT which is generated using a centralized Kerberos service. So in-order to make a call to that protected API from my Node JS service, I am trying to generate kerberos keytab and using that I am trying to hit that centralized service to get the JWT which I can use to hit the external protected APIs. It looks like there is no node modules to achieve this.

**Solution**
Create a module which can be used to do "kinit" and then "curl" into a URL using negotiate to get the JWT.

**Alternative**
I can achieve this today by running "kinit" through child process from my Node JS code.

**Comment by sathyarajagopal** [comment]
I went through almost all of the libraries. Only this (https://github.com/caspian311/kerb_request/blob/master/lib/kerb_request.js) fits the purpose. And that is what I am doing today. I just want to avoid using sub processes.

**Comment by fholzer** [comment]
I am using https://www.npmjs.com/package/kerberos which works fine on a single connection, though the main problem I have with this is that I want to use an http(s) agent, though the way Kerberos (or NTLM, for that matter) work is that they identify a session as TCP connection, and authentication flow is consists of multiple requests and responses which shouldn't be interleaved with unrelated requests. This means once the server requests the client to authenticate, the subsequent requests/responses must not be interleaved with other requests an agent might have queued. Or put differently, the client upon seeing the server response asking for authentication, the client would need a way to reuse that same connection instead of making it available for other requests. I spent some time looking at the http agent and client documentation and code and I don't see any way of accomplishing this. Unless this can be done, the node built-in agents are not generally compatible with Kerberos/NTLM (unless used in very specific, controlled circumstances)

**Comment by sathyarajagopal** [comment]
I am able to get this completed using "Kerberos". Please close this issue.

**Comment by Sindiya90** [comment]
Hi Sathyarajagopal ,i have the same issue  could you please share your code here please .I am also facing same kind of API integrated  with keberos i am trying to use same kerberos library but that doesnt work ,can you help me here
@sathyarajagopal
