### ISSUE TITLE
Creating an Array from a Set containing '0' value returns an empty Array

### ISSUE THREAD

**Issue by SebastienAuvray** [nodejs/help#2968]
* **Version**: 12.16.3
* **Platform**: Linux 5.5.7-200.fc31.x86_64 nodejs/node#1 SMP Fri Feb 28 17:18:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**: 

When creating an Array from a Set containing only zero (0), the array is empty. 
If another value is added to the set (say 1) then another Array is correctly created.

> *>* s=new Set()
Set {}
> *>*  s.add(0)
Set { 0 }
> *>*  new Array(...s)
[] // **[0] was expected**
>  *>* s.add(1)
Set { 0, 1 }
>  *>* new Array(...s)
[ 0, 1 ] // **now the array is correct**

**Comment by addaleax** [comment]
I think you want `[...s]` instead of `new Array(...s)`.

The problem with the latter is that `new Array()` takes *either* a single `length` argument that specifies the length of the new array, *or* its contents as a list of arguments passed directly to it. `new Array(...s)` expands to `new Array(0)`, so it creates an empty Array, because the first and only argument is a number.

**Comment by SebastienAuvray** [comment]
I mixed the two constructors :
 - new Array(arrayLength)
 - new Array(val1, val2) // With one value only

Thnak you !
