### ISSUE TITLE
can't run npm scripts

### ISSUE THREAD

**Issue by AdriBusse** [nodejs/help#2979]
Hello

if I run my npm-script I get a error message that node cannot be found or have a wrong spelling.

the npm script just contain: " node index".

If I hit node index into the Terminal everything work fine. 

I got the same problem with all npm scripts which I used in previous projects.

I think something is wrong with the environment variables maybe. I have the PATH : "C:\Program Files\nodejs\". Do I need something else?

Thank you if you can help me with my problem.

**Comment by Alon2303** [comment]
Hi, @AdriBusse 

try reading this:
[https://docs.npmjs.com/misc/scripts](url)

A couple of questions to get clear:
1. what happens when you type in terminal node -v | npm -v
2. are the scripts in the in the scripts property of your package.json?

you may try:
`node run myScript`
if the script is not built in
