### ISSUE TITLE
Unable to import users with SHA512 passwords

### ISSUE THREAD

**Issue by AdamBCo** [nodejs/help#3024]
- Operating System version: OSX 10.15.5 (19F101)
- Module: crypto
- Node.js version: 12.18.3.
- NPM version: 6.14.6

At the moment, I'm running into issues [migrating my users from one database to a third-party auth platform](https://github.com/firebase/firebase-admin-node/issues/1059). The code below shows exactly how I am creating the salt and hash, which is evidenced in the following [documentation](https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback). According to another engineer, I am doing this incorrectly. Can someone please tell me what is wrong with the code below? Is it worth updating the documentation on crypto to account for this?

```js
const salt = crypto.randomBytes(16).toString('hex');  
const user = {  
   uid: "tbSL53PN7zVTMsWc9up24hev4CN2",  
   email: "test@test.com",  
   hash: crypto.pbkdf2Sync("test123", salt, 100, 64, 'sha512').toString('hex'),  
   salt  
}  
```

**Comment by addaleax** [comment]
As mentioned in the other issue, the problem seems to be that your platform does not use `pbkdf` and instead uses repeatedly applying SHA-512 to the password directly – those are expected to give different results, so I’m not sure what we can do for you here. You’re not doing something inherently wrong, you’re just doing something differently than your third-party auth platform expects.

**Comment by AdamBCo** [comment]
@addaleax Thanks for the feedback. I appreciate the help.
