### ISSUE TITLE
Do I need to install node modules for each node process seperately?

### ISSUE THREAD

**Issue by GitterHubber** [nodejs/help#307]
Version: v0.12.12
Platform: Linux ubuntu 4.7.0-x86_64
Subsystem: node-sqlite3, mysql

I have multiple node processes running and each is running in its own folder.

Eg. np1 in folder1 , np2 in folder2 ...

All process need access to SQLite and MySQL for np1 I have already done

```
npm install sqlite3
npm install mysql
```

after doing this there was a node_modules folder in folder1.
and I could run np1 successfully.

Now np2, np3 ... also need access to SQLite and MySQL.
So would I need to repeat the same procedure in folder2, folder3 ... etc.

With Regards

**Comment by addaleax** [comment]
> Version: v0.12.12

I would definitely recommend you to upgrade to v6.x or at least v4.x; support for v0.12 will run out in December 2016. See https://github.com/nodejs/LTS for a schedule.

> So would I need to repeat the same procedure in folder2, folder3 ... etc.

Maybe. Assuming the folders are `/foo/bar/folder1`, `/foo/bar/folder2`, etc. and that all `node_modules` folders, you could have a common `/foo/bar/node_modules` directory; that should work.

A slightly more elegant solution would be to symlink `/foo/bar/folder1/node_modules`, `/foo/bar/folder2/node_modules`, etc. all to the same directory, so that installing any package makes it available everywhere. (Again, assuming you *want* those directories to be shared).

**Comment by GitterHubber** [comment]
@addaleax 
I had asked a similar question on nodejs googlegroups the link is [here](https://groups.google.com/d/topic/nodejs/AEchaC3hdjM/discussion)

And and user ryandesign had said this

> Be in the root directory of your project when you run the "npm install sqlite3" command, so that it gets installed in the correct directory. 
> 
> You are meant to install separate copies of things for each project. You're not meant to link things. 

Do you foresee any problems with multiple processes accessing the same node module at the same time?
I mean if the author of  the module has not designed it as for a multi process use case?
