### ISSUE TITLE
where to find internalBinding file in nodejs source code?

### ISSUE THREAD

**Issue by anlexN** [nodejs/help#3079]
* **Node.js Version**: all
* **OS**: all
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: all

in the nodejs source code, there is so many internalBinding statements. for example, where to find **constants** file?
![image](https://user-images.githubusercontent.com/8686739/99140336-f4832380-267b-11eb-9131-f87a14dc2653.png)

**Comment by RaisinTen** [comment]
Hey @anlexN. :)

[Here](https://github.com/nodejs/node/blob/b589128f6f4c3c6f636bfb0146957847ef0a8d53/lib/internal/bootstrap/loaders.js#L21-L24) is the description of `internalBinding`:
```cpp
// - internalBinding(): the private internal C++ binding loader, inaccessible
//   from user land unless through `require('internal/test/binding')`.
//   These C++ bindings are created using NODE_MODULE_CONTEXT_AWARE_INTERNAL()
//   and have their nm_flags set to NM_F_INTERNAL.
```

So, to look for `"constants"`, you might have to peep into the `src` folder where the C++ code lives:
* https://github.com/nodejs/node/blob/master/src/node_constants.h
* https://github.com/nodejs/node/blob/master/src/node_constants.cc

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.

**Comment by anonyco** [comment]
```js
require("v8").setFlagsFromString('--expose-internals');

const { internalBinding, primordials } = 
    require("vm").runInNewContext("require('internal/test/binding')");
```

Alternatively, if this stops working, then you must manually pass `--expose-internals` and use `const { internalBinding, primordials } = require('internal/test/binding'):` 

Join me in meditative prayer 🙏🏻 that this amazing black magic never gets removed/deprecated due to being "unsafe"/"unstable".

Yea!, we’re not stupid and are only using it if we have to. For example, I absolutely NEED `internalBinding('v8')` in order to get byte-accurate v8 heap stats as the object returned from ‘getHeapSpaceStatistics’ allocates at least a kilobyte of internal class data and v8 shape space (or whatever is going on), which muddles up all the heap stats to the whims of the GC.
