### ISSUE TITLE
Problem uploading converted image file(.dng) into dropbox

### ISSUE THREAD

**Issue by JagsDew** [nodejs/help#3098]
* **Node.js Version - v15.0.1**:
* **OS - windows10**:
* **Scope (install, code, runtime, meta, other?) - runtime**:
* **Module (and version) (if relevant)**:

I have an application in node js in which I am uploading the image to the node server after that  I compress the file to reduce the size. After that, I upload it to dropbox but the uploaded file has a 0-byte size. I don't understand the problem. Below is the code that I used.

```js
var namefile= path.basename("C:\\Users\\uploads\\converted\\"+foldername+"\\"+req.file.originalname,".ARW" );

var image =namefile+".dng";
fs.readFile("C:\\Users\\uploads\\converted\\"+foldername+"\\"+image, function(err, data) {
    
    var dbx = new Dropbox({ accessToken: 'XXXX' });
    dbx.filesUpload({path: '/'+link+'/'+image, contents: data})
        .then(function(response) {
        console.log(response);
    })
    .catch(function(error) {
        console.error(error);
    });
});
```
Appreciate your help.

**Comment by marsonya** [comment]
Hi @JagsDew  - Apologies for the late reply. As the code you share is not complete (the compression part seems to be missing), I can suggest checking the `data` after reading the file using `fs`
> fs.readFile("C:\\Users\\uploads\\converted\\"+foldername+"\\"+image, function(err, data) {
This should help you make sure that the file you are uploading is OK.

In case `data` is not what it should be, there is a problem in the compression or someplace before reading the image to upload it.
Else, if `data` is fine, there might be a problem with the Dropbox JS SDK, since you were able to read the file properly and the very next step after that is uploading the image using the SDK. I would recommend getting in touch with Dropbox either through technical support or on Github through issue.

Since this issue is 5 months old so I am assuming you have found a solution for it. So, I am going to close this issue. But incase you are still facing issue, do reopen this issue and we will help you resolve it.
