### ISSUE TITLE
Cannot communicate to web app powered by Node 4.6 from Windows Server 2003 using HTTPS

### ISSUE THREAD

**Issue by asuchac** [nodejs/help#311]
I have web client running on Windows Server 2003 communicating with web app powered by NodeJS. The protocol is HTTPS. The web client uses Microsoft's SSL components. 

When I updated the Node from ver 4.4.0 to 4.6.0, I couldn't connect to the web app anymore. This applies only to the web clients and browsers using Microsoft's SSL components, e.g. Internet Explorer. 

When I tried to reach the web app from Firefox, all was good. Also, there was no problem to connect to my web app from more recent Windows, e.g. Win 8.

I have workaround solution put in place, I just wanted to alert NodeJS team of this issue. Can't say if it's Node issue or Windows Server 2003 issue - probably the later.

**Comment by bnoordhuis** [comment]
That is probably because we updated openssl (the crypto library) to 1.0.2j or possibly because we made the hostname check for certificates more strict.  Am I right that v4.5.0 still works?

You can file an issue over at https://github.com/nodejs/node/issues if you want.  If we can track down the root cause, we can investigate a fix or a workaround.

**Comment by asuchac** [comment]
Yes, the older version - particularly 4.4.0 - still works. OK, I am going to fill the issue.

**Comment by bnoordhuis** [comment]
For future reference: continues in https://github.com/nodejs/node/issues/8944.
