### ISSUE TITLE
event loop: which eventloop is used by nodejs? eventloop of v8 or eventloop of libuv?

### ISSUE THREAD

**Issue by Divine1** [nodejs/help#3124]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/10482177/102022012-f985e080-3da9-11eb-97cf-9f3f2ab02159.png">

**Below is my understanding on the eventloop**
1. nodejs uses the embeddable v8 runtime + libuv.
2. `v8 runtime` has a default implementation of eventloop
3. `libuv` also has the implementation of eventloop
4. nodejs extends the eventloop of v8Runtime and adds additional functionality to it.

This is my understanding so far.

**Here is my question,**
Where does eventloop of `libuv` come into picture in nodejs? 
(on looking at point4 mentioned above) does `nodejs` adds the additional functionality into eventloop of v8Runtime by including the eventloop features of `libuv` ?
```
nodejs extends V8_Eventloop {

  // additional functionality is added into V8_Eventloop by including LIBUV_eventloop features ?
}
```

**Please clarify**

**Comment by addaleax** [comment]
> `v8 runtime` has a default implementation of eventloop

V8 does not provide an event loop. Can you clarify what gives you the impression that it does? I think that might be helpful here.

**Comment by Divine1** [comment]
@addaleax  Thank you for the quick response. 

So, only libuv provides the eventloop features in nodejs?
and incase of browser environment (chrome for example), what provides the eventloop features to the browser?

Below 3 answers gave me the impression that `v8 has the default implementation of an eventloop`. 


**[Article1 Link](https://stackoverflow.com/a/55083999)**
![image](https://user-images.githubusercontent.com/10482177/102022418-b4af7900-3dac-11eb-901c-2286bc376f51.png)

**[Article2 Link](https://stackoverflow.com/a/49823266)**

![image](https://user-images.githubusercontent.com/10482177/102022382-85990780-3dac-11eb-9516-9f70cd60deff.png)

[Article3 Link](https://chaudharypulkit93.medium.com/how-does-nodejs-work-beginner-to-advanced-event-loop-v8-engine-libuv-threadpool-bbe9b41b5bdd)
![image](https://user-images.githubusercontent.com/10482177/102022567-bded1580-3dad-11eb-8361-f983e3324449.png)

**Comment by addaleax** [comment]
> So, only libuv provides the eventloop features in nodejs?

Yes, the only exception being the microtask queue, i.e. what Promises, which *is* provided by V8, but I think it would be odd to consider that an event loop or part of an event loop (in particular, because it doesn’t actually involve events of any kind, it’s just a queue of code that should be run in the future).

> And incase of browser environment (chrome for example), what provides the eventloop features to the browser?

Some parts of the browser code, I assume. I think this is going to differ between browsers a lot.

> Below 4 answers gave me the impression that v8 has the default implementation of an eventloop.

I think all of these could be called inaccurate. :)

The V8 platform implementation is, for the most part, concerned with scheduling asynchronous tasks, but those are **not** for running asynchronous code (i.e. Article 3 is incorrect there), but instead for scheduling work like garbage collection and optimizing code compilation, e.g. in parallel on other threads or in the future.

This does, in the Node.js case and presumably also in the browser, integrate with the event loop to some degree, and V8 provides a default implementation, but I think calling it an event loop by itself does go too far (V8 calls it “message loop” in its external API, which seems reasonable to me).

**Comment by Divine1** [comment]
@addaleax thank you for the details. i was stuck on this for a while, its kind of clear to me now :)
 

i looked up few materials based on the details you have shared, these were helpful.
[link1](https://blog.insiderattack.net/javascript-event-loop-vs-node-js-event-loop-aea2b1b85f5c)
[link2](https://www.reddit.com/r/node/comments/cluorc/what_are_the_differences_between_nodes_event_loop/)

**Comment by goncharov-vlad** [comment]
Since “the event loop” is nothing but a programming pattern, V8 allows the ability to plug-in an external event loop implementation to work with its JavaScript runtime. Using this flexibility, the Chrome browser uses libevent as its event loop implementation, and NodeJS uses libuv to implement the event loop
