### ISSUE TITLE
Manually advance Cipher offset/counter without writing data

### ISSUE THREAD

**Issue by justablob** [nodejs/help#3149]
* **Node.js Version**: v15.5.0
* **OS**: Ubuntu Server 18.04 / Windows 10 Pro
* **Scope (install, code, runtime, meta, other?)**: code

Ciphers like ChaCha20 run on a counter, so I was wondering if it's possible to advance that counter on `crypto.Cipher` or  `crypto.Decipher` object to for example read from an offset. Imagine you had a file encrypted with ChaCha20 and wanted to read a part of it starting from somewhere in the middle. With the current implementation, I can't find anything that would allow me to do that. I've played with prepending and appending a 4-byte counter to the IV but that did nothing, so it's probably more complicated, or maybe it's impossible.

**Comment by addaleax** [comment]
@nodejs/crypto

**Comment by mildsunrise** [comment]
Hi! These sort of questions usually depend on OpenSSL rather than Node. According to the [docs on chacha20](https://www.openssl.org/docs/man1.1.1/man3/EVP_chacha20.html), the IV is 128-bit and is made up of a 32-bit counter plus a 96-bit nonce. The counter is little endian, maybe you were trying in big endian? (Or maybe I'm missing something important, could happen too ^^')

**Comment by justablob** [comment]
Hey, thanks for the answer, I had totally messed this up. First reason was, like you said, BE vs. LE. My second issue was that for some reason, I thought ChaCha20 internally uses a 16-byte state, which is obviously wrong, it's 64...  So I was incrementing the counter by 1 for every 16 bytes, while it should've been 64. I changed those two things and now it's working, so thanks!
