### ISSUE TITLE
Can't Resoluve 'async_hooks'

### ISSUE THREAD

**Issue by jchavezberkeley** [nodejs/help#3161]
* **Node.js Version**: v10.15.0
* **OS**: Mac OS Big Sur
Nativescript 7 / Angular 11
Bluebird 3.7.2

I trying to run my Nativescript project but I keep getting the following error regarding 'async_hooks' in bluebird (^v3.7.2). I have no idea what to do to start resolving this issue. I'm a little new and unsure as to whether or not I need to install 'async-hooks'? Any help would be much appreciated. 
```
ERROR in ../node_modules/bluebird/js/release/promise.js
Module not found: Error: Can't resolve 'async_hooks' in '/Users/.../node_modules/bluebird/js/release'
 @ ../node_modules/bluebird/js/release/promise.js 34:4-26
 @ ../node_modules/bluebird/js/release/bluebird.js
 @ ./app/components/pages/session/session.service.ts
 @ ./app/components/pages/session/session.component.ts
 @ ./app/components/pages/index.ts
 @ ./app/components/components.module.ts
 @ ./app/app.module.ts
 @ ./main.ts
```

Both the session.component.ts and the session.service.ts use an async and await call. Specificaly, there is one method that is labeled async with an await inside of it.

**Comment by addaleax** [comment]
I think you’re using webpack, or a similar bundler, guessing from the stack trace? You may need to tweak your build config so that the bundler doesn’t try to resolve `async_hooks`, and leaves the raw require call in. For webpack, that feature is called “Externals”.

> Both the session.component.ts and the session.service.ts use an async and await call.

That’s not related, `async_hooks` are for monitoring asynchronous operations but are not part of them directly. (`async`/`await` is also a language feature and `async_hooks` is Node.js-specific).

**Comment by jchavezberkeley** [comment]
I changed my bluebird version to 3.5.5 and it worked! I just followed the recommendation provided here https://github.com/petkaantonov/bluebird/issues/1617
