### ISSUE TITLE
The "emitter" argument must be an instance of EventEmitter

### ISSUE THREAD

**Issue by nnewc** [nodejs/help#3184]
* **Node.js Version**:
* **OS**: 14.15.4
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: stream

I'm trying to write a custom parser for node-seriaport. When I pipe my serialPort stream to it, I get:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "emitter" argument must be an instance of EventEmitter. Received type string ('unpipe')
```

```js
var stream = require('stream')

class Parser extends stream.Transform {
  constructor() {
    super()
    this.incomingData = Buffer.alloc(0)
  }

  _transform(chunk, encoding, cb) {
    // chunk is the incoming buffer here
    this.incomingData = Buffer.concat([this.incomingData, chunk])
    const packet = this.parseBuffer()
    this.emit('data', packet)
    cb()
  }

  _flush(cb) {
    this.parseBuffer()
    this.incomingData = Buffer.alloc(0)
    cb()
  }
...
}
```
-->

**Comment by uzluisf** [comment]
This is among the few search results that mention this issue:

```
node:events:994
    throw new ERR_INVALID_ARG_TYPE('emitter', 'EventEmitter', emitter);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "emitter" argument must be an instance of EventEmitter. Received type string ('unpipe')
```

however it's unclear how OP solved/fixed it.

For context, I was playing around with this example:

<details>
<summary>Example (click to open)</summary>

```javascript
const stream = require('stream');
const fs = require('fs');

class JsonLineReader extends stream.Transform {
    constructor(options) {
        super(options);
    }

    _transform(chunk, enc, cb) {
        try {
            console.log(chunk.toString('utf8'));
            cb();
        }
        catch (err) {
            cb(err);
        }
    }
}

const filename = './data.ndjson';
const readStream = fs.createReadStream(filename, { encoding: 'utf8' });
readStream.pipe(JsonLineReader); // <= HERE
```
</details>

The issue lies on the fact I didn't instantiate the class `JsonLineReader`, thus I was passing the class itself and not an instance of the class as expected. After all `JsonLineReader` inherits from `Transform` which inherits from `EventEmitter`, however it's an instance of `JsonLineReader` that is an instance of `EventEmitter`, not the class `JsonLineReader` itself. A minor but important distinction. This solved the issue:

```javascript
readStream.pipe(new JsonLineReader());
````
