### ISSUE TITLE
New version of node not reflecting while trying to create a project build

### ISSUE THREAD

**Issue by lanuradha** [nodejs/help#3210]
* **Node.js 14**:
* **OS**: Windows
* **Scope (install)**:
* **Module (and version) (if relevant)**:

Newer version of Node is installed. But when I try to create a build for my web application, it is referring to older version. 
Is system reboot mandatory after node js installation. Is there an alternative?
Error:
Node.js version v8.9.4 detected.
The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.
Please update your Node.js version or visit https://nodejs.org/ for additional instructions.

**Comment by PoojaDurgad** [comment]
@lanuradha - I think there is no need to restart your system after the installation of node. because , after installing the node on your system it will directly adds itself to path and you can check the version of node in new command prompt . so  check your path and make sure you don't have any previous installed node copy in the path , if yes remove the path and uninstall the previous one.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
