### ISSUE TITLE
creating bool value via n-api

### ISSUE THREAD

**Issue by MattsNorrbohm** [nodejs/help#3225]
* **Node.js Version**: >=10
* **OS**: Debian9 64bit AMD, Windows64.
* **Scope (install, code, runtime, meta, other?)**:n-api
* **Module (and version) (if relevant)**:

Missing a function in the n-api to create a bool value working in the same fashion like the napi_create_int32(), like a napi_create_bool().

**Comment by NickNaso** [comment]
Hi @MattsNorrbohm,
I think that the function that you need is `napi_get_boolean` see: https://nodejs.org/dist/latest-v14.x/docs/api/n-api.html#n_api_napi_get_boolean

**Comment by MattsNorrbohm** [comment]
Hi @ NickNaso,
will this really work when I want to create a boolean property of an object with true/false value. If so, that would be great and the function to use. But I'm a bit confused over the wording in the help regarding the napi_get_boolean function that to me returns the "global boolean" object... What I want to do is from C create a NodeJS object with a property that is of boolean type.

**Comment by mhdawson** [comment]
So I agree it is potentially a bit confusing but I'd think about it this way:

- a property on a JavaScript object (NodeJS object as you say above) does not have a type so itself. It can hold boolean values, integer values etc.
- given that the property itself does not have a type, what you need to do on the C side is create boolean values "true/false". Since there are only 2 values it makes sense to pre-create values that represent `true` or `false` versus creating a new one each time and that has already been done and they are accessible from the global object.
- napi_get_boolean returns the pre-created values for `true` and `false`.
- so what you can do is (error handling omitted of  course)
  ```
  bool myBoolean; // set however is appropriate
  napi_value boolValue;
  napi_get_boolean(env, myBoolean, &boolValue);
  napi_set_property(env, object, "my_property_name", boolValue);
  ```

Just like with napi_create_uint32(),  napi_get_boolean gives you a napi_value which you can to to use set a property value with.

**Comment by MattsNorrbohm** [comment]
Now I see. Makes sense now.. I'll just close the issue.
