### ISSUE TITLE
Library used on Linux image not found on M1 ARM64 image

### ISSUE THREAD

**Issue by juliencharrel** [nodejs/help#3239]
## Environment

* **Platform**: Mac M1 ARM
* **Docker Version**: 20.10.3, build 48d30b5
* **Node.js Version**: v15.5.1
* **Image Tag**: FROM node:15 (not usre exactly which image is then pulled on Docker preview M1)

## Expected Behavior

I am using a built with dependencies Rust binary that works perfectly on images on x86 architecture with the exact same parameters. When launching that binary on the same node:15 image but for Macbook M1, I should get it to work the same way.

## Current Behavior

When trying to run my binary in my docker node:15 image on MacbookM1, I get the following error:

qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

## Possible Solution

I have no idea, but the lib in question clearly is not here on node:15 ARM64, but is present on a x86_64 node:15 image

**Comment by yosifkit** [comment]
The Rust binary you have was compiled for an amd64 (x86_64) architecture and needs the linked library. The image you are running on the Mac M1 ARM is likely the arm64v8 image and so doesn't have libraries for amd64. Since Docker for Mac sets up qemu emulation, you can likely use the amd64 image by adding the `--platform` flag on `docker pull` and `docker run`.

**Comment by juliencharrel** [comment]
Worked like a charm, thanks!

**Comment by jaydrue** [comment]
> The Rust binary you have was compiled for an amd64 (x86_64) architecture and needs the linked library. The image you are running on the Mac M1 ARM is likely the arm64v8 image and so doesn't have libraries for amd64. Since Docker for Mac sets up qemu emulation, you can likely use the amd64 image by adding the `--platform` flag on `docker pull` and `docker run`.

I'm running automatic built in Visual Studio via .yml file. How and where do I include the --platform flag for Mac M1 ARM specifically?

**Comment by juliencharrel** [comment]
In your Dockerfile, right after the image name, for example: 
FROM node:14 - - platform=linux/amd64 
(without the space between - -)

**Comment by nigamzoman** [comment]
Thanks for the solution!
Looked up docker reference here https://docs.docker.com/engine/reference/builder/. 
The correct to specify the platform flag is  `FROM --platform=linux/amd64 node:14`

**Comment by xboxmachine** [comment]
> The Rust binary you have was compiled for an amd64 (x86_64) architecture and needs the linked library. The image you are running on the Mac M1 ARM is likely the arm64v8 image and so doesn't have libraries for amd64. Since Docker for Mac sets up qemu emulation, you can likely use the amd64 image by adding the `--platform` flag on `docker pull` and `docker run`.

Hi, can you give a example? in the file..

**Comment by zisko** [comment]
Here's mine for a solana dapp:

This was super helpful thanks all!.

```
FROM --platform=linux/amd64 ubuntu:latest


RUN apt-get update
RUN apt-get update && apt-get upgrade && apt-get install -y pkg-config build-essential libudev-dev
RUN apt-get -y install curl gnupg
RUN apt-get -y install nodejs
RUN npm install -g yarn
RUN npm i -g @project-serum/anchor-cli

CMD ["solana-install", "anchor-cli", "pkg-config"] 
```

**Comment by gubatron** [comment]
2 days wasted until I found this thread, this was super helpful for me too, thank you!

```FROM --platform=linux/amd64 ubuntu:18.04```

Cheers from the [jlibtorrent project](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/Dockerfile), millions of Android and Linux users thank you.

**Comment by vysecurity** [comment]
`--plathform=linux/amd64` doesn't appear to work here on a M1 MacBook. Any idea?

**Comment by anna-hope** [comment]
@vysecurity >`--plathform=linux/amd64`
 you made a typo in `--platform`, could that be why?

**Comment by stav-hacohen** [comment]
docker-compose doesn't support --platform flag.
I've tried to add it to my docker-compose.yaml but still got the error. 
Any ideas?

docker-compose.yaml -
service_x:
    platform: linux/amd64

**Comment by trozdol** [comment]
I don't know if this will help anyone but if I believe I've had the issue where docker will prefer an image that exists locally over a specific `platform` that does not exist on your system. I've found it helpful to prune images from my system first then bring up a docker compose project and see if that makes a difference. It should have to download all of the images from the registry and will try to find the specific platform if it exists.

**Comment by stav-hacohen** [comment]
Hi,

Thanks for this info. Adding "platform: linux/amd64" to docker-compose.yaml
did the trick.

Best regards,
Stav.

**Comment by olzhasar** [comment]
In case you are using docker-compose, you can specify the platform like this:
```
services:  
  frontend:  
    platform: linux/amd64
    build: frontend  
    ports:
      - 80:80  
    depends_on:
      - backend  
  backend:  
    platform: linux/amd64
    build: backend  
```

**Comment by tegge** [comment]
So. How do we do an arm image then? I consider the platform flag set to x86_64 a workaround.

**Comment by goelinsights** [comment]
For those of you like me, looking at this who want to use the ARM64 architecture rather than falling back to emulating, I ran into two things:
1) Have to install the gcompat library `apk add --no-cache gcompat`. I have a multi-stage build, so it went into the final.
2) Switch to gravitron/ ARM64 containers. In AWS fargate, which I'm using, you have to add (below CPU and memory in JSON view):
`"runtimePlatform": {
        "operatingSystemFamily": "LINUX",
        "cpuArchitecture": "ARM64"
  },` (see docs https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-arm64.html)

**Comment by sebastiendan** [comment]
I understand that thanks to qemu macs with Apple Silicon chips can run `amd64` images successfully. But shouldn't there be another approach where one can actually build `arm64` images that do work? It seems everyone is fine with working with emulation, but I've read here and there that this can become a problem in some situations (also, running my docker-compose stack locally on an M1 mac, I get warnings I would ideally like to see gone).

**Comment by yosifkit** [comment]
> I understand that thanks to qemu macs with Apple Silicon chips can run `amd64` images successfully. But shouldn't there be another approach where one can actually build `arm64` images that do work? It seems everyone is fine with working with emulation, but I've read here and there that this can become a problem in some situations (also, running my docker-compose stack locally on an M1 mac, I get warnings I would ideally like to see gone).

As long as the tag of each image (like [`node:20-bullseye`](https://hub.docker.com/layers/library/node/20-bullseye/images/sha256-c6b8ae21142621595ae24ca50eeda1299a33bba46cfcc9f64f7ce62bc50cd56c?context=explore)) that you are using are an [image index](https://github.com/opencontainers/image-spec/blob/9615142d016838b5dfe7453f80af0be74feb5c7c/image-index.md#oci-image-index-specification) that has `amd64` and `arm64` versions, then `--platform` and emulation should be unnecessary. Problems arise when using pre-compiled binaries (copied in or downloaded during build) that are architecture specific (like the initial issue here). The multiarchitecture awareness needs to be addressed in the Dockerfile, like downloading a binary for the userspace architecture; see one of the [`golang`](https://github.com/docker-library/golang/blob/29b2d53bcf3365a9fe72612ae24b884546185be6/1.20/bullseye/Dockerfile) Dockerfiles as an example.

As far as building your own multiplatform images (i.e. multiple platform specific images under a single tag via an image index), there are resources like https://docs.docker.com/build/building/multi-platform/ that can be helpful. I try to build each architecture on a native CPU rather than relying on emulation for both speed and reliability.
