### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by spacemanspace2003** [nodejs/help#3254]
* **Version**:
* **Platform**:
* **Subsystem**:

### Additional information

/-----------------------------------------------------------
AppData\Local\Temp\chocolatey\Visual Studio Installer\16.8.6.0\vs_BuildTools.exe" --quiet --update] was not successful. Exit code was '5008'. See log for possible error messages.
The upgrade of visualstudio2019buildtools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.
 See log for details.

visualstudio2019-workload-vctools v1.0.0 [Approved]
visualstudio2019-workload-vctools package files upgrade completed. Performing other installation steps.
 The upgrade of visualstudio2019-workload-vctools was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey upgraded 16/17 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
/----------------------------------------------------------
The visualstudio2019 are new install. Is there something with the installer.

Greatings

**Comment by marsonya** [comment]
@spacemanspace2003, did you find a solution for your issue?

**Comment by Shivamsen12579** [comment]
> It says that it had error while running '\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1' which is a powershell script, so maybe installing pwsh 7 should fix it.
> Just give it a try

hii sir i need your help.i was installing node js in my laptop and suddenly stuck due to net ..now console of backend node is not runningplease help me out sir I am in great trouble. Due to this issue i am not keep forwarding my web development course. 
And during installation so many miny files been installed and during uninstall I have deleted only some of them.

**Comment by Shivamsen12579** [comment]
> Try reinstalling chocolatey to it's latest version, as well as retrying the installation of Visual Studio Build tools.
> 
> Let me know if any of these solves your problem! @spacemanspace2003

hii sir i need your help.i was installing node js in my laptop and suddenly stuck due to net ..now console of backend node is not runningplease help me out sir I am in great trouble. Due to this issue i am not keep forwarding my web development course. 
And during installation so many miny files been installed and during uninstall I have deleted only some of them.

**Comment by Shivamsen12579** [comment]
> It says that it had error while running '\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1' which is a powershell script, so maybe installing pwsh 7 should fix it.
> Just give it a try

hii sir i need your help.i was installing node js in my laptop and suddenly stuck due to net ..now console of backend node is not runningplease help me out sir I am in great trouble. Due to this issue i am not keep forwarding my web development course. 
And during installation so many miny files been installed and during uninstall I have deleted only some of them.

**Comment by Shivamsen12579** [comment]
> Try reinstalling chocolatey to it's latest version, as well as retrying the installation of Visual Studio Build tools.
> 
> Let me know if any of these solves your problem! @spacemanspace2003

hii sir i need your help.i was installing node js in my laptop and suddenly stuck due to net ..now console of backend node is not runningplease help me out sir I am in great trouble. Due to this issue i am not keep forwarding my web development course. 
And during installation so many miny files been installed and during uninstall I have deleted only some of them.

**Comment by RedYetiDev** [comment]
> > Try reinstalling chocolatey to it's latest version, as well as retrying the installation of Visual Studio Build tools.
> 
> > 
> 
> > Let me know if any of these solves your problem! @spacemanspace2003
> 
> 
> 
> hii sir i need your help.i was installing node js in my laptop and suddenly stuck due to net ..now console of backend node is not runningplease help me out sir I am in great trouble. Due to this issue i am not keep forwarding my web development course. 
> 
> And during installation so many miny files been installed and during uninstall I have deleted only some of them.
> 
> 

Please open a new issue if you still experiencing this


I've closed this issue, as there has been little action in years, and the author never replied to this thread
