### ISSUE TITLE
problem with "node ." command

### ISSUE THREAD

**Issue by acgr70** [nodejs/help#3263]
* **Node.js Version**: 15.11.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**:

hi, I am new to coding and I am trying to create a discord bot. I am using visual studio code and I have a problem getting the bot online. When I write in the commands prompt "node ." or "node main.js" the bot is turning online. I suppose I have a problem with the node.js command because the coding is right. Any idea on what should I do?

**Comment by KlanterV** [comment]
Can you explain a little more about your mistake

**Comment by MrPerunaMies** [comment]
Are you watching codelyons tutorial if so i had the same problem i had typed
const client = new discord.client();      instead of 
const client = new Discord.Client();
Difference being thag Discord.Client(); has the capital letters

And be sure to save the main.js file before running rhe node . Or node main.js command

**Comment by marsonya** [comment]
@acgr70 - Kindly share the code snippet you are working with.

**Comment by RedYetiDev** [comment]
*(no response from author)*
