### ISSUE TITLE
Memory leak on persistent handles with weak callbacks during environment shutdown

### ISSUE THREAD

**Issue by implausible** [nodejs/help#3297]
* **Version**: 12.22.0, 14.16.0
* **Platform**: All platforms
* **Subsystem**: environment

### What steps will reproduce the bug?
You can use this repo to view the memory leak. https://github.com/implausible/native-node-worker-no-gc

### How often does it reproduce? Is there a required condition?
Every time. Memory is leaked when closing context.

### What is the expected behavior?
Garbage collector cleans up any persistent objects with weak callbacks and calls the weak callback on environment teardown.

### What do you see instead?
Weak callback is never called, memory is never released.

**Comment by addaleax** [comment]
> This does not seem to be the case when leveraging napi. Cleanup is correctly handled there.

Yes :+1:

> So any non-napi module that wants to leverage persistent references likely also needs to handle that.

That's what [`AddEnvironmentCleanupHook`](https://github.com/nodejs/node/blob/5dae7d67589c908a1fe672b084838c1397d00e54/src/node.h#L908-L919) is there for, yes. It's effectively what N-API uses for this as well.

> Is there just no way to guarantee weak callbacks are performed on persistent references at close of context time?

Persistent references are managed by V8, Node.js does not know about them. Since V8 does not clean them up on exit, Node.js has no way to do so either. N-API is different, because in that case, the abstraction layer allows Node.js to know which references are in existence during environment cleanup.
