### ISSUE TITLE
[ESM] Way to import package with path

### ISSUE THREAD

**Issue by julien-f** [nodejs/help#3380]
* **Node.js Version**: 14.17.0 and 16.2.0
* **OS**: Fedora 33
* **Scope (install, code, runtime, meta, other?)**: code

**Context:** I'm using packages as plugins for my app, plugins are looked up in specific dirs and then imported in the main process, it worked well with `require` but no longer with `import`.

**Problem:** `import` only knows how to import packages with bare specifiers, not with paths.

**Actual:**

```js
import "./my-package/"
```

```
> node index.mjs
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/tmp/my-package/' is not supported resolving ES modules imported from /tmp/index.mjs
Did you mean to import ../my-package/index.mjs?
    at finalizeResolution (internal/modules/esm/resolve.js:272:17)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///tmp/tmp.hV25xBwag4/tmp/my-package/'
}
```

**Workaround:**

```js
import { createRequire } from "module";

const require = createRequire(import.meta.url);

await import(require.resolve("./my-package"));
```

But it's a bit cumbersome and I fear it will no longer work in the future.

**Comment by aduh95** [comment]
I don't think there's any plan for deprecating `createRequire` anytime soon, it's OK to rely on it. If you want your code to also work on Windows, you should use `pathToFileURL`:

```js
import { createRequire } from "module";
import { pathToFileURL } from "url";

const require = createRequire(import.meta.url);

await import(pathToFileURL(require.resolve("./my-package")));
```

A big issue with using `require.resolve` is it would not pick up `"exports"` field from the `package.json`; if `my-package` is a dual package providing both ESM and CJS, `require.resolve` would likely resolve to the CJS file rather than the ESM one. Depending on your use-case, you may find [loader hooks](https://nodejs.org/api/esm.html#esm_hooks) useful, although the API is being rewritten.

**Comment by axkibe** [comment]
Works fine, but unfortunally require() forces sync call, which in ESM world should IMO be possible with promises.
