### ISSUE TITLE
I TRYING TO RUN  CODE  ON VISUAL STUDIO CODE .

### ISSUE THREAD

**Issue by sodhairkhan** [nodejs/help#3434]
I TRYING TO RUN  CODE  ON VISUAL STUDIO CODE .
THEY GIVE ERROR  AND TELL THAT INSTALL LATEST VERSION OF POWER SHELL.
I TRYING MANY TIME TO INSTALL POWER SHELL BUT THEY GIVE ME ERROR THAT U HAVE NOT ENOUGH SPACE.
ALTHOUGH I HAVE A LOT OF SPACE IN DISK
PROGRAMMING  C++

_Originally posted by @sodhairkhan in https://github.com/nodejs/help/issues/2832#issuecomment-872243173_

**Comment by gireeshpunathil** [comment]
@sodhairkhan - If you have a question specific to Node.js or its associated components you may ask here, this issue is definitely outside the scope of this repository.

( I don't know how powershell installer works, but generally installers unpacks `stuff` in the temporary folder, and if the disc partition that contain temporary folder is small, we can expect similar error. not sure if that is happening here, and not sure if that applies for windows, and even not sure how to check the temporary folder in windows)

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
