### ISSUE TITLE
Cannot import or use require (node/react)

### ISSUE THREAD

**Issue by charlietlamb** [nodejs/help#3444]
* **Node.js Version**: 14.17.0
* **OS**: Big Sur 11.4
* **Scope (install, code, runtime, meta, other?)**: import

I am having an error when importing in node/react.

This is the error that I get.
```
SyntaxError: Cannot use import statement outside a module
```

Then I looked online and added the following to package.json
```
"type":"module"
```
I now get this error.
```
const express = require('express')
                ^

ReferenceError: require is not defined
```
Any help?

**Comment by sharmankita** [comment]
By adding` "type": "module"` in package.json you have converted ur app into ES Modules. So instead of require u can use Import. And if you want to use both like require in some files and import statement in some files then instead of adding `type : module` 

you can save the file with .mjs extension in which u want to use import statement.

you cannot use both import and require in same file.

Thought I will not recommend to use different coding style in different file use which suits u and ur requirement. Hope this resolves ur query :)

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
