### ISSUE TITLE
How does NodeJS listen for string concatenation?

### ISSUE THREAD

**Issue by zhu956645239** [nodejs/help#3459]
Hello great developer, I want to ask you a question about how NodeJS listens for string methods so that they can be used for function hooks. For example, when my project had an SQL injection vulnerability, my idea was to listen for "+", concat, split, etc., methods of the String class, but now I have used many methods like shimmer, SQL parsing, etc., but this is not feasible. Do you have any good ideas, thank you!

**Comment by zhu956645239** [comment]
???

**Comment by Ayase-252** [comment]
You will not be able to listen `+` since there is no operator overloading in JavaScript.

You may be able to monkey-patching `String.prototype.concat` or `String.prototype.split` before user code is executed. But it is bad programming practice.

If possible, you could write a wrapped function then change all usages of `concat` and `split` to your wrapper. You could do check in your wrapped function.

**Comment by zhu956645239** [comment]
thank you

**Comment by Ayase-252** [comment]
Closing as presumably resolved. If it is not the case, please feel free to reopen it.
