### ISSUE TITLE
long-term support for certain require() pattern

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#354]
I filed this issue with NPM first, but makes sense to file it here instead

Just curious if Node core knows if it will support this pattern of requiring modules

`const colors = require('colors/safe');`

I looked at the colors project to see how that works. Basically the directory structure looks like:

https://github.com/Marak/colors.js

```
root
    --/lib
       --index.js
--safe.js
```

I am sure deep in the docs for require it says that when requiring a directory with a package.json file, it will return the module.exports value of the module that the main property points to, yet at the same time it will somehow reference the root directory (where package.json is), so that when you do require('x/y'), if y is in the root directory you will only load that file. It's a bit confusing at the least.

wondering 

(a) what the explanation is for this, and
(b) if you will be able to require a module in this way with ES6 import syntax?
Will there be long-term support for this?

**Comment by Qard** [comment]
It's a fairly common pattern in userland modules, so that functionality will not be getting removed from `require()` any time soon. As for import behaviour, I don't have the answer to that. A lot of semantics change and I haven't been following the import discussion too closely lately to know exactly where things are at on that currently.

**Comment by ORESoftware** [comment]
Yeah that's what i am really wondering - will this pattern by supported by
import syntax

**Comment by Qard** [comment]
@bmeck might have more insight.

**Comment by bmeck** [comment]
> (a) what the explanation is for this

For people that need to access a subset of a module like `lodash/array`. This allows better optimization rather than trying to load a whole module if you are only using a minute subset.

> (b) if you will be able to require a module in this way with ES6 import syntax?

Yes, deep linking inside of packages will be supported in ESM and long term in require.

ESM does not mandate anything about the file, import specifier, or resolution of modules.

**Comment by ORESoftware** [comment]
@bmeck thanks I understand the rationale, just not really understanding the logic of the require function necessarily, but we can forget that for now.

But more importantly, I cannot seem to parse any definitive info from your statement as to whether import statements support this? I could go try it, but curious if there is long-term support.

**Comment by bmeck** [comment]
@ORESoftware `import` specifiers are opaque and left up to a host environment to parse/resolve/etc. as they see fit; the language grammar/types are unrelated/do not declare how to actually load code given a string specifier. Node as a host environment will have the proper behavior.

**Comment by ORESoftware** [comment]
alright I think I know what you mean

**Comment by SamMorrowDrums** [comment]
I'd also assume that many authors would move to support the syntax `import {safe} from "colors";` part of the joy of the Module Loader Spec is it can facilitate static analysis, and so it can reduce your imported package size down even with a single entrypoint, via selective imports as above.

I cannot say for sure that things will go like that, but it's very plausible.

**Comment by lordKnighton** [comment]
Closing for now, feel free to reopen.
