### ISSUE TITLE
Node.Js deployment on IBM Websphere

### ISSUE THREAD

**Issue by RaniaShady** [nodejs/help#3541]
* **Node.js Version**: 14
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: deployment
* **Module (and version) (if relevant)**:

I need support for deploying my application to websphere as per as customer requirements.

My application has angular 8 as front end, and node.js as back-end (api)

I can’t find a similar example on the internet.

Appreciate your support.

**Comment by shellberg** [comment]
Which version of WebSphere?  Traditional (tWAS) or a Liberty deployment?
As you likely appreciate, the WebSphere SDK runtime is primarily Java, so its not going to natively execute your Angular application at the server.  However, some Liberty environments do include a Node.js runtime, so perhaps that is what your customer is expecting?  Otherwise, are you perhaps only expecting to statically serve the front-end JS files for local execution at your customer's clients?

**Comment by RaniaShady** [comment]
Hi Shellberg,
Actually I am not expert in websphere. However, we don't need to serve the frontend statically .
If you can describe both ways (traditional and liberty) it will be appreciated
Thank you

**Comment by shellberg** [comment]
Well... I sort of tried to indicate your problem in my first response.

The 'Traditional' WAS is Java-based, not JavaScript.  Even with the Java runtime running JS code in emulation - not as performant as Node.js - you are not executing a Node.js workload, whether that is Angular-based or not.
As for Liberty, it similarly has its roots in execution with a Java runtime.  However, your customer might be in a (Liberty-based) situation where a Node.js runtime exists alongside the Java stack, and is conducting some processing (related to WAS)... I do not know if the terms of use include execution of additional user workloads by that Node.js runtime (in the Liberty context).  Assuming it could accommodate, I'm not sure that I see how that constitutes 'deploying your [Angular] application to WebSphere' in order to meet your customer requirements!
(The one way I might have understood your requirements was if you were using WAS as your server to host files statically to distribute your client-side JS code, but you dismissed that.)

**Comment by mhdawson** [comment]
@RaniaShady if you work for IBM or Red Hat I suggest you reach out to me internally so we can have a higher bandwidth discussion (You should be able to find me in either internal directory)

**Comment by preveen-stack** [comment]
@RaniaShady were able to get a solution to your issue
