### ISSUE TITLE
Dynamic importing stops node

### ISSUE THREAD

**Issue by TheBotlyNoob** [nodejs/help#3600]
### Details

When I dynamically import a file, it just stops node with no error.

### Node.js version

v16.9.1

### Example code

Don't know of a minimum reproducible example, but the github repo is [here](https://github.com/TheBotlyNoob/principal-discord-bot)

### Operating system

Windows 11

### Scope

runtime

### Module and version

don't know what you mean by `module`, but I am using ESM

**Comment by VoltrexMaster** [comment]
In which part of the repo you provided does the dynamic import stop the process?

**Comment by TheBotlyNoob** [comment]
here: https://github.com/TheBotlyNoob/principal-discord-bot/blob/main/main.ts#L18-L24

**Comment by VoltrexMaster** [comment]
> here: https://github.com/TheBotlyNoob/principal-discord-bot/blob/main/main.ts#L18-L24

This happens when you're trying to import something that causes a circular dependency, one or more of your files are importing a file that also imports the file that is being imported from.

You can get an idea of how to fix that from [here](https://stackoverflow.com/questions/10869276/how-to-deal-with-cyclic-dependencies-in-node-js).
