### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by 996Jack** [nodejs/help#3699]
### Version

16.13.2 LTS

### Platform

Windows

### What steps will reproduce the bug?

1. Have an old node.js version that's broken. (CAN'T INSTALL NPM FILES AND DOESN'T HAVE C:/USERS/USER/PACKAGE.JSON)
2. Install it.
3. Get a dam error.

### How often does it reproduce? Is there a required condition?

CAN'T INSTALL NPM FILES AND DOESN'T HAVE C:/USERS/USER/PACKAGE.JSON

### What is the expected behavior?

Error 2:
![image](https://user-images.githubusercontent.com/73414034/150673042-c9ff6dae-9d96-42fe-be67-0f299c557007.png)

Error 1:
![image](https://user-images.githubusercontent.com/73414034/150673070-3c9a4704-a4a3-4ccf-b200-24b273258ce1.png)

### What do you see instead?

Errors.

### Additional information

Running Windows 11, January 2022 update.
Installing from https://nodejs.org/en/

**Comment by benjamingr** [comment]
What happens if you try to install using nvs? https://github.com/jasongin/nvs

**Comment by 996Jack** [comment]
> What happens if you try to install using nvs? https://github.com/jasongin/nvs

Is NVS Node.js?

**Comment by benjamingr** [comment]
@996Jack nvs is a tool that allows installing multiple versions of Node.js on your computer - it may be useful in your case since you likely have a permission problem that will be hard to debug. nvs (and similar tools) work around that by installing Node versions in their own directories and pointing the "global node" to them.

If it won't succeed - it will at least give you a more detailed error in the cli (you can also try installing Node from chocolatey or winget directly - there are instructions on nodejs.org)

**Comment by 996Jack** [comment]
@benjamingr I can't figure out how to install with this. I'm getting a new laptop to code anyways. I will reopen this issue if I need help. Thank you.
