### ISSUE TITLE
issue with npm install 

### ISSUE THREAD

**Issue by chkashif167** [nodejs/help#372]
Version:
    $ node -v
    v6.9.1
    $ npm -v
    4.0.2

    Platform: windows 10

    Subsystem: gitbash

I have issue with npm start please have look at screenshot
http://prntscr.com/d9ono9

Regards

----
 `post from other issue`

I am facing these issue any idea why?

http://prntscr.com/da2v7s
http://prntscr.com/da2sda
Regards

**Comment by Fishrock123** [comment]
@chkashif167 Did you run `npm i`? If so, maybe this is a problem with the package you are trying to use.

https://www.npmjs.com/package/angular2-quickstart appears to be a test project and has no repo associated so I think it may just be broken.

**Comment by lordKnighton** [comment]
Let's see your start script in `package.json file`

**Comment by chkashif167** [comment]
[package.zip](https://github.com/nodejs/help/files/604035/package.zip)

here is package.json

**Comment by chkashif167** [comment]
even I have this issue with my every project
http://prntscr.com/da0yhy

$ npm install
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kashif\\AppData\\Roaming\\npm\\node                                                  
_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2

**Comment by lordKnighton** [comment]
https://github.com/nodejs/help/issues/374 -   I've closed your other issue, because of the same content. If any more issue arrive containing npm issues, note them here while this issue is open. If this is issue is close and you have any issue pop up then open a new issue. Thanks for understanding  

⚠️  Let's continue 

--

Let's see if this help:  [link](http://stackoverflow.com/questions/34335340/angular2-quickstart-npm-start-is-not-working-correctly)

![screen shot 2016-11-21 at 4 09 15 pm](https://cloud.githubusercontent.com/assets/1773260/20505911/0a2a7f2c-b005-11e6-8e9b-ba8ae754d440.png)


Don't worry we will continue trying to help you with your other npm issues

**Comment by lordKnighton** [comment]
For the screenshot shared 8 hours ago: you need to go to npm like your error suggests you to & open an issue there.  Check out this link-  https://github.com/npm/npm/issues/10065

---------
For your gulp Typings error-  

Look @ this Readme - https://github.com/typings/typings

because `gulp installTypings` is just erroneous. 
evidence-  gulp has `2743 plugins` & InstallTypings isn't one of them. 

-----

I'm gonna close this issue for now, If your still having issues after trying the suggested methods above, comeback & open this. And we will go from there 

😸  Happy coding
