### ISSUE TITLE
Promise fires both "catch" and "then" callbacks !

### ISSUE THREAD

**Issue by Disco1267** [nodejs/help#3779]
### Version

v14.19.0

### Platform

Linux base0 5.4.0-104-generic nodejs/node#118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Subsystem

core

### What steps will reproduce the bug?

Only Depending on the order of attaching .the and .catch callbacks they both get fired.
Here is simple code to reproduce that:

``` js
function foo(ok, msg) {
  return new Promise((res, rej) => {
    if (ok)
      res(msg)
    else
      rej(msg);
  })
}

//The bad case
foo(false, 'Test 2')
  .catch((error) => console.log('Error-2:', error)) // This is fired as expected
  .then((result) => console.log('Answer-2:', result)) // this fires too, and result is undefined
```

Result:

```console
Error-2: Test 2
Answer-2: undefined
```

### How often does it reproduce? Is there a required condition?

It depends on the order of `.then` and `.catch` calls
This errors:

``` js
//The bad case
foo(false, 'Test 2')
  .catch((error) => console.log('Error-2:', error)) // This is fired as expected
  .then((result) => console.log('Answer-2:', result)) // this fires too, and result is undefined
```

This works:

``` js
foo(false, 'Test 4')
  .then((result) => console.log('Answer-4:', result))
  .catch((error) => console.log('Error-4:', error))
```

### What is the expected behavior?

Result:

```console
Error-2: Test 2
```

### What do you see instead?

Result:

```console
Error-2: Test 2
Answer-2: undefined
```

### Additional information

You will also see this if you try this version of foo:
It uses `async foo()` instead of returning a `new Promise(...)`

``` js
async function foo(ok, msg) {

  if (ok)
    return (msg)
  else
    throw (msg);
}
```

**Comment by Disco1267** [comment]
@devsnek : Do you really think that a Promise which emits BOTH a reject and a response AT THE SAME TIME isn't  a serious problem ????

**Comment by addaleax** [comment]
@Disco1267 It’s not the same `Promise`, though, and they don’t happen at the same time either.

```js
foo()
  .catch(() => { ... catch block ... })
  .then({ ... then block ... })
```

is equivalent in async/await to 

```
try {
  await foo();
} catch {
  ... catch block ...
}
... then block ...
```

and is, in particular, **not** equivalent to

```js
const promise = foo();
promise.catch(() => ... catch block ...);
promise.then(() => ... then block ...);
```

because `foo()` and `foo().catch(...)` are very different promises.

**Comment by Disco1267** [comment]
Yet again, they do fire BOTH. 
Did you try my code snippet ?

**Comment by user7230724** [comment]
@Disco1267 That's how promises work. Consider the following simplified cases:

**Case 1**

```js
const p = Promise.reject('x')
p.then(console.log)
p.catch(console.error)
```

![](https://user-images.githubusercontent.com/95079291/158001033-89626361-bc22-432b-95d0-6d81cf46cb2a.png)

**Case 2**

```js
const p = Promise.reject('x')
p.then(console.log).catch(console.error)
```

![](https://user-images.githubusercontent.com/95079291/158001041-4cf894f9-53ad-41a5-af48-65ea32c4433f.png)

**Case 3**

```js
const p = Promise.reject('x')
p.catch(console.error).then(console.log)
```

![](https://user-images.githubusercontent.com/95079291/158001044-0861bdc8-d411-4ca8-b247-e16f114dc187.png)

---

Can you guess what each of these snippets output? Were you correct?

Now let's analyze each case. In the first case, we have a rejecting promise `p` and we attach both `then` and `catch` handlers to that promise. The promise follows both paths. Since it is a rejecting promise, it triggers the `catch` handler. The `catch` handler "eats" the rejection, so after the `console.error` prints `x`, the promise returned is rejection-free and since there are no further paths after the `console.error`, it decays. However, the first path also gets triggered. Since `p` is a rejecting promise, it does not trigger the `then` handler. It simply skips the `then` handler and continues further. The promise is still rejecting. However, there are no paths after the `then` handler, so Node.js reports an unhandled rejection warning/error. Despite the promise being handled in one of the paths, the rejection survived in the other path, so it is considered unhandled.

In the second case, we first attach `then` handler and then we attach `catch` handler to the resulting promise. The promise starts following the path. The first handler it sees is the `then` handler, but since `p` is a rejecting promise, it skips the `then` handler. Next, it sees the `catch` handler and triggers it. `console.error` outputs `x` and "eats" the rejection. The rejection-free promise continues further. Since there are no more paths after `catch`, the chain ends.

In the third case, The promise `p` first sees the `catch` handler. Since `p` is a rejecting promise, it triggers the `catch` handler. `console.error` prints `x` and "eats" the rejection. A new rejection-free promise continues further. It then sees the `then` handler. Since the promise is now rejection-free, it also triggers the `then` handler. The promise monad contains `undefined`, because that's the return value of `console.error`. That's why `undefined` is printed after the `x`.

---

Your example is basically Case 3. Do you understand now why it prints undefined?

**Comment by Disco1267** [comment]
Thank you for this very detailed explanation. I really appreciate your effort.

And I understand now, that the following construction doesn't lead to the desired result, since catch() and then() deliver a modified Promise so only chaining is an option.
``` js
// never do that
const p = Promise.reject('x')
p.then(console.log)
p.catch(console.error)
```

So far so good.
But about case 3: Even though you explained what is going on here, the behaviour doesn't make any sense.
What I see is: 
- A rejection is handled,
- It propagates further down the chain, but marked as handled.
- A handled rejection hits a then() handler and instead of being ignored, the then() gets triggered.

Conclusion: Handled Rejections end up in the resolve() path and call the wrong function without data.
What a fat bug!
And if the specs state that it should work that way, I would call that "broken by design".

**Comment by addaleax** [comment]
> It propagates further down the chain, but marked as handled.

It doesn’t propagate further down the chain – a `.catch()` handler really is like a JS `catch { ... }` block (hence the name). If you want the rejection to be propagated further, you need to re-throw it.

**Comment by addaleax** [comment]
> How can the poor then() handling function tell why it was triggered ?

It can’t know why – that’s just not information that exists in a running program. It can only know the return value of the `Promise` that it is attached to.

**Comment by texonidas** [comment]
To explain slightly further for anyone else who lands here:
```ts
foo(false, 'Test 2')
  .catch((error) => console.log('Error-2:', error))
  .then((result) => console.log('Answer-2:', result))
```
is equivalent to:
```ts
const p = foo(false, 'Test 2')
  .catch((error) => Promise.resolve(console.log(error)));
// conversion to a resolved promise happens implicitly unless you Promise.reject

p.then((result) => console.log('Answer-2:', result))
```
