### ISSUE TITLE
Installs instructions - ubuntu

### ISSUE THREAD

**Issue by tribycol** [nodejs/help#3782]
### Details

Hi,
I could not find how install nodejs. I downloaded the file. now, what is the next step?
if i use sudo apt install nodejs. it does not install npm

### Node.js version

16x or 17x

### Operating system

ubuntu 20.04

### Scope

install nodejs and use in the OS and also in VS code. 

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
> if i use sudo apt install nodejs. it does not install npm

As you're using Aptitude (also known as APT | `apt`), not all repositories provide the same binaries to install, some repositories bundle Node.js with NPM and some doesn't (which seems to be your case).

You hsould try installing NPM separately using:

```shell
$ sudo apt install npm
```

Although these repositories tend to provide old binraries, so I recommend using something like [Volta](https://volta.sh/) and running:

```shell
$ sudo volta install node
```

To install the latest LTS release of the Node.js runtime bundled with NPM, you can also choose to install the latest version instead of the latest LTS version.

**Comment by gireeshpunathil** [comment]
@tribycol -  is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive
