### ISSUE TITLE
Unable to update my version of Node

### ISSUE THREAD

**Issue by jonathan-whitmire** [nodejs/help#3816]
### Details

I have gone through the process 3 times of trying to upgrade to the newest version of Node. I follow the wizard's instructions, but then when I check in my terminal it still shows v14.17.0. I have restarted my computer after the 3rd attempt and it still shows v.14. Any help is greatly appreciated! 

### Node.js version

I'm currently using v14.17.0, but I'm trying to update to the v16.14.2

### Operating system

macOS Monterey Version 12.2.1
MacBook Air (M1, 2020)

### Scope

Installation problems. I can't upload the newest version of Node. 

### Module and version

I'm unable to upgrade to v16.14.2 from v 14.17.0

**Comment by MonaTyagi** [comment]
Hi, I was having similar problem. After trying a lot of things, I used 

nvm install node v16.15.0

using command line
Then it installed node v18.1.0 (npm v8.8.0). I was not sure if it is the latest one , so I tried

nvm install node v16.15.0 LTS 

Then I got the message

v18.1.0 is already installed.
Now using node v18.1.0 (npm v8.8.0)

So hopefully I am using the correct version(latest one), by 1) using the command line instead of wizard; and 2)using nvm command instead of npm command

I hope it helps

**Comment by MonaTyagi** [comment]
> ### Details
> I have gone through the process 3 times of trying to upgrade to the newest version of Node. I follow the wizard's instructions, but then when I check in my terminal it still shows v14.17.0. I have restarted my computer after the 3rd attempt and it still shows v.14. Any help is greatly appreciated!
> 
> ### Node.js version
> I'm currently using v14.17.0, but I'm trying to update to the v16.14.2
> 
> ### Example code
> _No response_
> 
> ### Operating system
> macOS Monterey Version 12.2.1 MacBook Air (M1, 2020)
> 
> ### Scope
> Installation problems. I can't upload the newest version of Node.
> 
> ### Module and version
> I'm unable to upgrade to v16.14.2 from v 14.17.0
