### ISSUE TITLE
I need a mentor

### ISSUE THREAD

**Issue by hemos007** [nodejs/help#3841]
### Details

could someone be my mentor, I'm currently studying NodeJS from " NodeJS masterclass " because I need something that gets me close to where I can understand NodeJS itself, I hate using libraries.

### Node.js version

v16.14.2

### Operating system

Windows

### Scope

code

### Module and version

Not applicable.

**Comment by anonyco** [comment]
My No. 1 advice is upgrading from Windows to some Linux distro and committing to only using Linux as your daily driver for everything you do throughout the day. This will start you on the road to recovery from all your years of using Windows and help you retrain your mind to think more like a developer. Not to mention the fact that Linux the most awesome developer toolkit and playpen paradise imaginable. It's unrealistic to expect going from novice to expert in a week. Rather, over the course of months, things will start becoming more and more intuitive (like a "this is the way it was meant to be" kind of feeling). Intuition is a very critical component of becoming a developer because it's impossible for a human to memorize a million random APIs and their random usages and random quirks. Instead, you accumulate a pattern of sorts whereby the APIs neatly fit into slots and it makes semi-intuitive sense about how everything works together. This, in turn, forms the foundation of the mental toolbox you use to structure and implement solutions to problems.

**Comment by hemos007** [comment]
thank you so much for your reply, i think it's almost all about understanding the objects very well, so that whenever I read the object tree of any API I can easily understand how it's written & works, therefore I can use it like a pro, I just wanna do that for me, I know the market relies on Lips and if I only learn Lips I won't become a pro developer

**Comment by anonyco** [comment]
> I know the market relies on Lips and if I only learn Lips I won't become a pro developer

I see and understand Windows to a tremendously greater depth of detail after 3 years of using Linux exclusively than I did with 10 years of working exclusively on Windows. It's not a matter of learning Windows or learning Linux, rather it's a matter of fact that its simply not possible to really immerse yourself in computer science in Windows.

Also, two things:

1. If you only learn Lisp, you will become a pro developer much faster because mastering the syntax of one language allows you to focus on learning the concepts of CS, and these concepts are universal across all programming languages.
2. Also, I've yet to use a single piece of software written in Lisp, so I'm pretty certain that market doesn't rely on Lisp.

**Comment by hemos007** [comment]
thank you so much I'll follow your advice

**Comment by anonyco** [comment]
Good deal. I promise you won't regret it. Also, important note: if you choose to dual boot, then I highly recommend disabling bitlocker in Windows beforehand. I've seen some people have success with dual booting bitlockered Windows and Linux but I've also experienced first-hand a lot that can go wrong.

**Comment by hemos007** [comment]
thank you very much @anonyco
