### ISSUE TITLE
url.pathToFileURL is not a function : how to convert a file path to an URL in node.js?

### ISSUE THREAD

**Issue by raphael10-collab** [nodejs/help#3846]
I want to convert a file path to an URL.

I tried to follow the indications found in the official docs: https://nodejs.org/dist/latest-v16.x/docs/api/url.html#urlpathtofileurlpath

```js
import { pathToFileURL } from 'url'

let filepathurl = pathToFileURL(file.path)
```

But I get this error: 

```console
Uncaught TypeError: (0 , _url.pathToFileURL) is not a function
```

Or : 

```js
import url from 'url'
let filepathurl = url.pathToFileURL(file.path)
```

 Error message:

```console
_url.default.pathToFileURL is not a function
```

Other info: 

```txt
node: v16.13.0
O.S. : Ubuntu 20.04 Desktop
```

What am I doing wrongly? How to solve the problem?

At the moment, I solved the problem using https://www.npmjs.com/package/file-url combined with this helpful suggestion for webpack configuration: https://github.com/facebook/create-react-app/pull/11764#issuecomment-1104019653

But I would like to know if and how to correctly use the features of the node.js library

**Comment by VoltrexMaster** [comment]
I can't reproduce this, the code snippet looks correct. You're probably using either an "incomplete" version of the Node.js binary which can cause the error although I'm unsure how you've got an incomplete version, and the errors don't seem like errors from Node.js itself since Node.js won't point out the name of the module you imported the function from, nor would it prepend a `_` (`_url`) to the front of the module name.

I would recommend uninstalling Node.js and reinstalling it.

**Comment by RedYetiDev** [comment]
*(Closing stale issue)*
