### ISSUE TITLE
Problem with version available for Windows 7

### ISSUE THREAD

**Issue by otacilioricardo** [nodejs/help#3855]
### Details

I can't use the latest versions of Node on Windows 7. This has become a problem. Windows 8.1 crashes a lot. Node version 12 doesn't allow me to use some React Native features.

### Node.js version

All above version 12.

### Operating system

Windows 7.

### Scope

Instalation.

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
Windows 7 has reached it's EoL (End-of-Life) phase as described [here](https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information).

We no longer support operating systems/platforms that has reached their EoL phases as described [here](https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
> Node.js does not support a platform version if a vendor has expired support for it. In other words, Node.js does not support running on End-of-Life (EoL) platforms.

Now all you can do is to upgrade to a higher Windows major release if possible (I recommend getting the latest major release as of now which is [Windows 11](https://www.microsoft.com/software-download/windows11)).

If upgrading is not possible due to incompatibility, I'd recommend either switching to a different operating system such as distributions of the Linux kernel (such as [Ubuntu](https://ubuntu.com/), [Fedora](https://getfedora.org/), [Linux Mint](https://www.linuxmint.com/), or more advanced ones such as [Arch Linux](https://archlinux.org/), there are many Linux distributions you can choose from) or getting a new device/machine/PC (or whatever you want to call it) and upgrade to the latest major operating system releases and use the latest versions of the Node.js runtime which you can download from [here](https://nodejs.org/).
