### ISSUE TITLE
exec in child_porcess does not recognise pnpm as a comand

### ISSUE THREAD

**Issue by PetkoPetkov03** [nodejs/help#3872]
### Version

v18.2.0

### Platform

Linux ARCHPETKO 5.17.9-arch1-1 nodejs/node#1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

 make an exec function that specified the folder that has pnpm-lock.yaml and run pnpm install

```js
exec(`cd ${motherFolder}/${fullFolderName}${relPath} && pnpm install`, (error, stdout, stderr) => {
            if (error) {
                console.log(`error: ${error.message}`);
                return;
            }
            if (stderr) {
                console.log(`stderr: ${stderr}`);
                return;
            }
            console.log(stdout);

        });
```

When you replace it with npm it works flawlessly

### How often does it reproduce? Is there a required condition?

It exits with error every time

### What is the expected behavior?

installing the node_modules from package.json or pnpm-lock.yaml

### What do you see instead?

error: Command failed: cd ../../gen/testuser@gmail.com/video-serv && pnpm install

**Comment by VoltrexMaster** [comment]
The error you seem to be getting can occur from multiple things.

First case is that the `cd` command failed to change the directory to the specified directory because it probably doesn't exist, can be caused if the path specified is incorrect. Double check the path and see if it actually exists.

Second case is that the `pnpm` program is not globally available in your machine as a command, possibly because it's not set to the `PATH`.

PNPM should already be set to `PATH` and should be available globally if you've installed it correctly or at least from the correct source. I would recommend uninstalling the current installation of PNPM and following the [instructions from the official website of PNPM](https://pnpm.io/installation) to install it.

If that doesn't work then you can see how to add a program to `PATH` [here](https://medium.com/codex/adding-executable-program-commands-to-the-path-variable-5e45f1bdf6ce), so you can set the PNPM program globally.

For example, you need to edit the `.bashrc` file (or the `.zshrc` file if you're using Zsh instead of Bash):

After you've opened the aforementioned file for your respective shell, add the following line to the file:

```shell
export PATH=$PATH:<path to the pnpm program>
```

Remember to replace the `<path to the pnpm program>` with the path to where the PNPM (`pnpm`) program is located.

**Comment by PetkoPetkov03** [comment]
@VoltrexMaster Found the problem it was a mistake  from my part. The reason npm worked but pnpm didn't is because of how my program was decoding and writing the yaml file. When decoding and writing to the file it would insert an unwanted symbol that would force pnpm into an error.
