### ISSUE TITLE
Jest detected open handle on Fetch

### ISSUE THREAD

**Issue by murraymichal** [nodejs/help#3903]
### Version

18.3.0

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?

Same issue as with node-fetch: https://github.com/node-fetch/node-fetch/issues/1479#issuecomment-1099134082
Although fetch terminated, the jest couldn't exit. 

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:
●  TLSWRAP

    > 52 |         const resp = await fetch(reqUrl, {
         |                            ^
```

### What do you see instead?

jest doesn't exit after fetch terminated

**Comment by murraymichal** [comment]
> Thanks for the report. `node-fetch` is not handled here though and there is little that can be done by Node.js itself.

It's not `node-fetch`, but node 18.3.0 global fetch.

**Comment by Amine27** [comment]
I have the same issue, any news on this?

**Comment by LudoVio** [comment]
same issue, node v18.13.0, global fetch

**Comment by RaisinTen** [comment]
If you're facing this issue with global fetch, does https://github.com/nodejs/undici/issues/1614 look relevant? If so, I'd suggest continuing the conversation there because the implementation of Node.js' global fetch is maintained in undici. For node-fetch, please continue the discussion in https://github.com/node-fetch/node-fetch/issues.
