### ISSUE TITLE
Process Sudden Stop 

### ISSUE THREAD

**Issue by abdooo9** [nodejs/help#3916]
### Details

Hello, I have had a problem since changing my computer, I downloaded node version v16.15.1, when I run a process like a web server, it suddenly stops after several minutes of running.

### Node.js version

v16.15.1

### Operating system

Windows 10 21H2

### Scope

runtime

### Module and version

I use [express](https://www.npmjs.com/package/express) web server

**Comment by VoltrexMaster** [comment]
There could be several reasons as to why the process would suddenly stop, can you tell us how exactly does it stop in this case?

The process can stop when: an unhandled error is thrown, the process runs out of memory, your program isn't starting up properly due to a bug in your code, and many other reasons.
