### ISSUE TITLE
Don't have the autorisation to edit the np.cmd file

### ISSUE THREAD

**Issue by Molpo456** [nodejs/help#3933]
### Details

I have to change the prefix -g to prefix --location=global in the npm file. But when I want to change the editing it tell me that I don't have the permission to open the file and I have to contact the admin to obtain it.
Please I would appreciate any help thank you.

### Node.js version

v16.16.0

### Operating system

Windows 10

### Scope

To obtain the authorisation to edit the npm.cmd file.

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
> I have to change the prefix -g to prefix --location=global in the npm file.

Unsure why you would want to do that, if it's because of the `--global` (`-g` for short) CLI flag being deprecated in npm v8.11.x, then the deprecation was lifted on the newer versions, so you don't have to change it unless it's for something else.

> But when I want to change the editing it tell me that I don't have the permission to open the file and I have to contact the admin to obtain it.
Please I would appreciate any help thank you.

There isn't much we can do to help you in this case, you'd have to either gain administrator permissions and run the editor as administrator to edit the file, or contact the administrator of the machine to edit it for you.

If you're the administrator of the machine, just open the file editor as administrator by right-clicking on the file editor and clicking the "Run as Administrator" button. You can have a look at a guide on running programs as administrator [here](https://www.minitool.com/news/run-as-administrator-windows-11.html).
