### ISSUE TITLE
SSL decryption failed or bad record MAC 

### ISSUE THREAD

**Issue by alicja-r** [nodejs/help#3953]
### Details

Hi, I'm getting this error installing anything using internet from my phone hotspot (Xiaomi 8). Problem is disappearing using WiFi. Once I was able to install with hotspot but then I made some changes in my computer and I reinstall my OS windows 8.1. I tried npm cache clear -f, setting SSL to false and checked settings of firewall
Any ideas what can I do? 
Thank you for answering! 

### Node.js version

16

### Operating system

Windows 8.1

### Scope

Installation 

### Module and version

Not applicable.

**Comment by vivganes** [comment]
I am doing an educated guess here. 

It is possible that your windows PC sees your phone hotspot as a public network and uses more security settings when you connect to the phone hotspot.  At some point in the past, probably the first time you connected to your phone wifi, windows should have asked you if it is a public or a private network.  I guess you have chosen public.

One possible fix (I guess) could be to rename your wifi's SSID and try to connect and choose it as a trusted network, when the Windows 'Choose your network type' popup appears.  Also, allowing node.js to run through Windows Defender Firewall

I am suspecting this to be the reason because there is a similar issue recorded in the past -- https://github.com/nodejs/help/issues/3815

**Comment by Bajarangj** [comment]
> I am doing an educated guess here.
> 
> It is possible that your windows PC sees your phone hotspot as a public network and uses more security settings when you connect to the phone hotspot. At some point in the past, probably the first time you connected to your phone wifi, windows should have asked you if it is a public or a private network. I guess you have chosen public.
> 
> One possible fix (I guess) could be to rename your wifi's SSID and try to connect and choose it as a trusted network, when the Windows 'Choose your network type' popup appears. Also, allowing node.js to run through Windows Defender Firewall
> 
> I am suspecting this to be the reason because there is a similar issue recorded in the past -- #3815

Thank you. it worked for me.

**Comment by preveen-stack** [comment]
@alicja-r is the above suggestion solved your problem
