### ISSUE TITLE
How does node.js code interact with libUV?

### ISSUE THREAD

**Issue by dSalieri** [nodejs/help#3988]
I've tried to find something about that how node.js interact with libUV. But I didn't find anything good for explanation.

Well, if we take for example node.js' stream and destroy it intentionally by `stream.destroy()` (`destroy` is a method of node.js library that belong to streams). So that method must destroy our stream, but it doesn't, take a look at the [source of destroy's code](https://github.com/nodejs/node/blob/2b32985c626b57d7ea3e68d6ce088ea3183e3a58/lib/internal/streams/destroy.js). There is no something that could be destroy our stream. So how does node.js interconnect with libUV

@addaleax do you know something about that?

**Comment by ErickWendel** [comment]
I made a video showing in practice how Node.js work with V8, Libuv, and C++. [Take a look later](https://www.youtube.com/watch?v=ynNDmp7hBdo)

Libuv handles all pending events in Node.js. When you destroy a stream it [emits an event](https://github.com/nodejs/node/blob/2b32985c626b57d7ea3e68d6ce088ea3183e3a58/lib/internal/streams/destroy.js#L132) and all events are handled by libuv so that's how libuv knows when to stop processing
