### ISSUE TITLE
Rest operator with await inside ternary

### ISSUE THREAD

**Issue by nairihar** [nodejs/help#3989]
### Details

Hey, could you help me to understand why the first example works well but the second one returns a syntax error?

The third one is clear why can return a syntax error.

<img width="621" alt="Screen Shot 2022-10-07 at 2 10 47 PM" src="https://user-images.githubusercontent.com/15065065/194540106-cfa8cd4c-29e4-43bd-8be6-08f6215ebb9f.png">

### Node.js version

v16.14.2

### Operating system

Mac OS 12.5.1

### Scope

repl

### Module and version

No module

**Comment by ErickWendel** [comment]
Well, there're a few things there. I'm not sure if doing a ternary inside an Array would be a good practice. 

This is not related to await but the way javascript interprets your code

This error occurs with objects as well.
```js
a = {1 ? ...{one: 1, two: 2, three: 3} : {} } 
```
The problem is that on a ternary JS cannot tell what is the target. It doesn't know whether it's an object or an Array.
But if you enclose them into it's right datatype it'll work

```js
1 ? [... await [ 1, 2, 3]] : [] 
```
