### ISSUE TITLE
Node isn't functioning properly

### ISSUE THREAD

**Issue by scarnation** [nodejs/help#3990]
### Details

Anytime I run an npm command on cmd , vs code or node command prompt, node automatically pops up a new gnode.exe window for me without executing or giving me feedback on my command. I use v16.17.0 on a windows 10 . Sometimes it pops up the new window randomly on my system even when I don't run any node command multiple times. I only get feedback on my terminal when I run -v  and still get numerous pops ups 

### Node.js version

v16.17.0

### Operating system

Windows 10

### Scope

Runtime

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
This could be due to a faulty installation of the Node.js runtime.

I recommend uninstalling the current installation of the runtime and installing it from the [official Node.js website](https://nodejs.org/).

If that doesn't work for you then it's a fault on your end, possibly due to custom configurations that prevents such runtimes from running properly, it can also be caused due to a faulty Windows installation.
