### ISSUE TITLE
Stuck on Step 2 - Permission Denied in Linux Mint

### ISSUE THREAD

**Issue by fruitlets** [nodejs/help#4002]
### Details

I'm very new to this (just installed Linux Mint 21 today and trying to get BetterDiscord working, which needs the nodejs install), and I can't seem to find a solution in here or with general google searching. Also possible I saw a solution and didn't understand it when I was looking at it, so forgive me if it's obvious.

When setting the environment variable with the following:
`~/.profile export PATH=/usr/local/lib/nodejs/node=v16.18.0-linux-64/bin:$PATH`

I get this error:
`bash: /home/gidget/.profile: Permission denied`

I've tried using sudo, but then it just tells me the command isn't available for this. Any guidance is appreciated!

### Node.js version

v16.18.0-linux64

### Operating system

Linux Mint 21 (Cinnamon)

### Scope

Installation

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
`~/.profile` is a directory not a command, and since you seem to be trying to add Node.js to `$PATH`, you shouldn't need to do that manually.

You can use a Node.js version manager (such as [nvm](https://nvm.sh/)) to not only install Node.js easily and also add it to `$PATH` automatically, but also manage different versions of Node.js, so I would recommend giving it a try.

> trying to get BetterDiscord working

Using BetterDiscord is against [Discord's Terms of Service](https://discord.com/terms) declared under [this section](https://discord.com/terms#6):

> You may not copy, modify, create derivative works based upon, distribute, sell, lease, or sublicense any of our software or services. You also may not reverse engineer or decompile our software or services, attempt to do so, or assist anyone in doing so, unless you have our written consent or applicable law permits it.

So I would oppose against using it, if you do then beware of the risks.
