### ISSUE TITLE
What to do with CVE-2022-3786 and CVE-2022-3602 on node 16.18.1?

### ISSUE THREAD

**Issue by iocmet** [nodejs/help#4027]
### Node.js version

16.18.1

### Example code

No code?

### Operating system

Ubuntu 20.04

### Scope

Other

### Module and version

Not applicable.

**Comment by bmuenzenmeyer** [comment]
Only the 18 and 19 release lines were affected because prior to that, the included version of Open SSL was not vulnerable

From https://nodejs.org/en/blog/vulnerability/november-2022-security-releases/

[CVE 2022-3602](https://nodejs.org/en/blog/vulnerability/november-2022-security-releases/#x-509-email-address-4-byte-buffer-overflow-high-cve-2022-3602)

> Impacts:

> All versions of the v18.x and v19.x releases lines.

[CVE 2022-3786](https://nodejs.org/en/blog/vulnerability/november-2022-security-releases/#x-509-email-address-variable-length-buffer-overflow-high-cve-2022-3786)

> Impacts:

> All versions of the v18.x and v19.x releases lines.
