### ISSUE TITLE
add feature to node for printing property name while each lookups

### ISSUE THREAD

**Issue by jackfromeast** [nodejs/help#4038]
### Details

Hi, 

I am trying to find every *undefined* property in my codebase. I thought it would be most straightforward to add a few lines in the get object property part in Node.js. After a day of hard work, I finally make a progress: I added the following code to the `Runtime::GetObjectProperty` function in `./deps/v8/src/runtime/runtime-object.cc`.

```cpp
if(result.ToHandleChecked()->IsUndefined(isolate)){
    printf("[!] Found undefined property: ");
    lookup_key.GetName()->NameShortPrint();
    printf("\n");
  }
```

However, it doesn't print the stuff I want. When I try it with a simple case, it outputs something shown below:

```js
a = {
    "nohello": 1
}
console.log(a.hello);
```

Output by the revised Node.js
```console
[!] Found undefined property: <kHandle>
[!] Found undefined property: <kHandle>
[!] Found undefined property: <kHandle>
[!] Found undefined property: /home/x/tmp/test.js 
[!] Found undefined property: MODULE
[!] Found undefined property: /home/x/tmp/test.js
undefined
[!] Found undefined property: beforeExit
```

Expected output
```console
[!] Found undefined property: <a:hello>
```

Is there anyone who can help me to achieve this feature?
Happy Thanksgiving:>

### Node.js version

v20.0.0-pre

### Operating system

Linux version 5.15.49-linuxkit (root@buildkitsandbox) (gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, GNU ld (GNU Binutils) 2.35.2)

### Scope

code

### Module and version

Not applicable.

**Comment by bmuenzenmeyer** [comment]
I don't think this repo is actively monitored by core team members or used to discuss node internals or feature development. Since what you are trying to do touches node's functionality, you might have more luck within https://github.com/nodejs/node/issues

the process for contribution there, IIRC, is that an issue would be opened first to discuss with maintainers whether or not this would be acceptable as a feature
