### ISSUE TITLE
receive 'spawn EPERM' error when call child_process.execFile

### ISSUE THREAD

**Issue by wubeans** [nodejs/help#4051]
### Details

Hi, I'd like to ask:
1. When will occur this problem?
2. How to catch it?
Please take a look, thanks!

### Node.js version

16.17.0

### Example code

We can see the source code on line 184 at file index.js on wmic project, wmic version is 1.1.1.
the code: 
`var wm = execFile('wmic', splitter(cmd), opts);`

### Operating system

Windows 10.0.18363

### Scope

runtime

### Module and version

child_process

**Comment by VoltrexKeyva** [comment]
The `spawn EPERM` error occurs when the Node.js process doesn't have the permission to spawn the child process with the provided command, file, or whatever you're trying to spawn.

You can handle the error in multiple ways:

Since the [`child_process.execFile()`](https://nodejs.org/docs/latest-v18.x/api/child_process.html#child_processexecfilefile-args-options-callback) method returns a [`ChildProcess`](https://nodejs.org/docs/latest-v18.x/api/child_process.html#class-childprocess) class instance, you can listen to it's [`error`](https://nodejs.org/docs/latest-v18.x/api/child_process.html#event-error) event and see if it threw such an error.

Or if you want to use the `execFile()` method's callback parameter, the callback's first argument is the error if any was thrown.

---

If you don't want to catch the error by listening to an event or by the callback, you can also use the [`child_process.execFileSync()`](https://nodejs.org/docs/latest-v18.x/api/child_process.html#child_processexecfilesyncfile-args-options) method, which synchronously spawns the child process and executes the file rather than doing it asynchronously, and you can catch it's error using a [`try...catch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) block.

**Comment by wubeans** [comment]
Hi @VoltrexKeyva , thank you! but from codes, there is already error handling like child_process.on('error',()) and child_process.stderr.on('data',()), but we still find this error was throw to console(didn't be catched), it's the whole codes:
![image](https://user-images.githubusercontent.com/37647271/208329743-6df74021-b28e-4a8c-9e3b-f538a2081974.png)
is there other error handling should add to? or the error handling is not correct, like `stderr.push(e);` may throw the error directly(not sure)?
