### ISSUE TITLE
uncaughtException not handling synchronous error thrown in imported file

### ISSUE THREAD

**Issue by NazCodeland** [nodejs/help#4070]
### Details

It seems like `process.on("uncaughtException")` does not handle errors thrown from an imported file if the error comes from synchronous code. However, It handles the same error if it's thrown asynchronously, why is that? How can I make `process.on("uncaughtException")` handle errors thrown from an imported file if the error was caused by synchronous code?

Thanks in advance.

### Node.js version

v19.1.0

### Example code

```javascript
//fileB.js
console.log(x); // error thrown from synchronous code - will not be handled by `uncaughtException` in fileA.js

setTimeout(() => {
	console.log(x); // error thrown from asynchronous code - will be handled by `uncaughtException` in fileA.js
});


// fileA.js
import  "./fileB.js";

process.on("uncaughtException", (error) => {
		console.log("--------------------");
		console.log("within uncaughtException");
		console.log(error);
		process.exit(1);
	});
```

### Operating system

Microsoft Windows NT 10.0.22621.0 x64

### Scope

code

### Module and version

Not applicable.

**Comment by preveen-stack** [comment]
cc @nodejs/loaders PTAL

**Comment by JakobJingleheimer** [comment]
I don't see anything throwing in your example

**Comment by aduh95** [comment]
It throws `ReferenceError: x is not defined`  for me.

What's happening is you're adding the `'uncaughtException'` event handler after the exception occurs. Let's try the other way around:

```js
process.on("uncaughtException", (error) => {
		console.log("--------------------");
		console.log("within uncaughtException");
		console.log(error);
		process.exit(1);
	});

await import('./fileB.js');
```

Now you should see `within uncaughtException` logged out.
BTW I'm using dynamic import and not static import because static import are hoisted and the dependency they are pointing to will always be evaluated first.
