### ISSUE TITLE
Receive pid that signal was sent from

### ISSUE THREAD

**Issue by mehulkar** [nodejs/help#4075]
### Details

In the code:

```js
process.on('SIGUSR1', () => {})
```

I would like to receive information about where the signal came from. Currently, the callback only receives the string `SIGUSR1` and an int `30`. How do I do this?

### Node.js version

Not applicable.

### Operating system

macOS

### Scope

signal handling

### Module and version

Not applicable.

**Comment by mehulkar** [comment]
It seems this is where the signal handler is setup here: https://github.com/nodejs/node/blob/66b1356ebcf55e477639a52baba3067afd9ea7a0/deps/uv/src/unix/signal.c#L224-L242

and according to the [`sigaction` docs](https://man7.org/linux/man-pages/man2/sigaction.2.html), it needs to set `sa_sigaction` and a `SA_SIGINFO` flag. 

```diff
-  sa.sa_handler = uv__signal_handler;
-  sa.sa_flags = SA_RESTART;
+  sa.sa_sigaction = uv__signal_handler;
+  sa.sa_flags = SA_SIGINFO;
```

I have no real understanding of how this works, this is all based on a couple hours of research that [I wrote down here](https://www.mehulkar.com/blog/2023/01/investigating-signal-handling-in-node.js/). I'm looking for some guidance about:

1. Whether this is possible to do already, and I'm looking in the wrong place
2. If it did require a patch to "make it work", where else would I also have to patch such that the `process.on` callback actually gets the information? (I tried building node with the patch above and it didn't Just Work™)
3. Is it desirable to add this information into signal handling _always_ or with an option? Changing the callback signature is a breaking change, so I imagine it would need an option.
4. If I'm right about how this works, is there some history here about why it works this way, or is it entirely dependent on `libuv` (and should I ask someone there?)

Thank you!

**Comment by gireeshpunathil** [comment]
thanks @mehulkar - this is very detailed research work indeed! I will attempt to answer some:
 - 1. no, this is not already possible.
 - 2. the PR you referred (https://github.com/nodejs/node/pull/34648) is potentially abandoned because of portability issues - Node.js is supported in many platforms, and some platforms implement signal handling minimally
 - 3. this is definitely a useful info, and desirable to add it always. However, point 2 poses challenge IMO. Please feel free to resurrect 34648 and see if you can progress.
 - 4. no idea.
 - /cc @richardlau , who may be able to provide additional insight as well as guidance.

Again, this is a great ground work, and wishing you good luck with working in Node.js!

**Comment by richardlau** [comment]
> * 2. the PR you referred ([src: set SA_SIGINFO flag when using sa_sigaction node#34648](https://github.com/nodejs/node/pull/34648)) is potentially abandoned because of portability issues - Node.js is supported in many platforms, and some platforms implement signal handling minimally

I have suspicions that the AIX behaviour is faulty and that there is an AIX bug there but I was unable to find the right person/group within IBM to pursue any further and now I'm outside of IBM. The behaviour on AIX was an outlier -- all other platforms I tested returned the signal information to the handler (see https://github.com/richardlau/signals).

**Comment by preveen-stack** [comment]
cc @nodejs/platform-macos PTAL
