### ISSUE TITLE
Build nodejs 18 with openssl 1.x

### ISSUE THREAD

**Issue by kumarrishav** [nodejs/help#4086]
### Details

is it possible to build nodejs 18 binary with openssl 1.x?

node 18 is breaking my app with following error

`Error: error:0A00018E:SSL routines::ca md too weak`

I tried setting the DEFAULT:@SECLEVEL=0 but still got the error.
```
...
key: config.credentials.key,
cert: config.credentials.cert,
ca: config.credentials.ca,
ciphers: "DEFAULT:@SECLEVEL=0",
....
```

### Node.js version

18

### Operating system

Ubuntu 20

### Scope

code

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
Are you sure the OpenSSL version is the cause of this problem?  As far as I know Node does not externally expose its OpenSSL to the shell, but git does and that version of OpenSSL is less than 1.0.

**Comment by kumarrishav** [comment]
yes. As node.js v18 comes with OpenSSL v3, lots of certs and current implementation is breaking. It was working fine till node 16. 

can/should we build nodejs v18 with openssl v1

**Comment by prettydiff** [comment]
I am currently on Node 20 and was trying to figure out PKI for the first time last month.  I was running into a variety of similar problems as well and even opened a ticket here about it.

https://github.com/nodejs/help/issues/4211

I eventually gave up on PKI and instead went with a shared secret based upon SHA3-512 hash sequences.  This was a better idea for me anyways, because large public keys take an incredible amount of computation effort for security that isn't as strong.

**Comment by preveen-stack** [comment]
cc @nodejs/crypto can you comment

**Comment by tniessen** [comment]
@kumarrishav I believe you should be able to solve most issues with SECLEVEL through a custom OpenSSL configuration file and/or the legacy provider in OpenSSL 3. However, you should probably upgrade your keys and certificates to not use weak keys and ciphers.

That being said, you should also be able to dynamically link against OpenSSL 1.1.1 while building Node.js from source.

**Comment by tniessen** [comment]
Also, OpenSSL 1.1.1 reaches end-of-life status in two weeks. It's important to migrate to OpenSSL 3 because starting in a few weeks, security patches won't be provided for OpenSSL 1.1.1 anymore, and any vulnerabilities will remain unpatched.
