### ISSUE TITLE
npm installation 

### ISSUE THREAD

**Issue by MadanLad** [nodejs/help#4088]
### Details

while installing the npm I am getting following error 

```console
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2032:
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

can any one suggest why I am facing this issue

### Node.js version

Not applicable.6.11

### Operating system

windows 10

### Scope

npm installation

### Module and version

Not applicable.

**Comment by VoltrexKeyva** [comment]
> ```console
> npm ERR! node v6.11.0
> npm ERR! npm  v3.10.10
> ```

You're using a very old version of Node.js and npm, uninstall your current version and install either the latest LTS (recommended) or the latest non-LTS from the [official Node.js website](https://nodejs.org/).

**Comment by prettydiff** [comment]
What was the exact command line instruction you used to cause that error?  Also, have you tried installing Node/NPM via NVM.  I can see you are installing a super old version Node that has fallen out of support.  NVM makes it easy to install old versions and toggle between versions of Node/NPM.

This one is a bit more mature for Windows - https://github.com/coreybutler/nvm-windows

This one is otherwise more popular and commonly used - https://github.com/nvm-sh/nvm

**Comment by brestmoor** [comment]
We are trying to solve the same issue in our company, and the strange this is, it is working with old NPM and node on many computers, but on a newer laptop we get that ssl3_get_key_exchange:bad signature. Do you have any idea why this may be computer dependent?

**Comment by prettydiff** [comment]
@brestmoor What version is your node/npm?  Have you tried updating them to later versions to see if that resolves this issue?

**Comment by khashayar9387** [comment]
error An unexpected error occurred: "https://registry.npmjs.org/axios: write EPROTO 101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\\ssl\\s3_clnt.c:2032:\n".
