### ISSUE TITLE
tcp nodejs grpc client TLS not working

### ISSUE THREAD

**Issue by urko-b** [nodejs/help#4096]
### Version

18.12.1

### Platform

Manjaro Linux x86_64 5.15.81-1-MANJARO arch linux

### What steps will reproduce the bug?

Hi, I've created a nodejs `grpc` client and I'm not able to connect with a go `grpc` server deployed already on a VPS through TCP connection. 

To test if the problem with the code I decided to create a go `grpc` client I check connection to same server. I reached connection and I could do all requests to my server successfully. 

I've come from this other issue on `grpc-node` [**repo**](https://github.com/grpc/grpc-node/issues/1974) and another man had got same problem as me.

So please take a look to this [issue](https://github.com/grpc/grpc/issues/32312) I've created and this other [one](https://github.com/grpc/grpc-node/issues/1974). If need more details please ask and I'll give further instructions.

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

It should be able to connect by **TCP** to this `grpc` server.

### What do you see instead?

I cannot connect to server.

**Comment by prettydiff** [comment]
Questions:

* Is that server on localhost?
* Are you processing your connection either with certificates or with option `rejectUnauthorized: false`?

I have created a TLS peer to peer file sharing utility and I solved for this concern in my utility using both rejectUnauthorized option and with certificates.  First of all I want to be very clear that under normal conditions in production software you should **never** use option rejectUnauthorized.  In my case I only use rejectUnauthorized option because I handle authentication elsewhere because everything is a dedicated socket, there is no anonymity, and I intentionally do not validate certificates.

Trusted certificates are extremely painful to figure out cross OS.  Windows was the easiest and Linux proved to be a challenge.  In order for that to work the certificates must reside on the server and be trusted by the client.  On windows you can install your own certificates into a trust store without elevation, depending upon the security settings.  On Linux you have to use Sudo to install the certificates into a trust store of the OS and each browser.  Also, when creating the certificates you need to use an options file with OpenSSL and that is another challenge to get correct.

When all the certificates are install properly the browser will trust them but Node will not because I did not install them into a trust store cross-OS specific to Node, which is why I use rejectUnauthorized.  So in my case certificates are necessary only because TLS will not try without them and then browser will not try without them, but otherwise are completely superficial.  Since I am managing identity validation elsewhere the client will not issue the connection without passing validation and the server will drop the connection if it cannot validate the client provided hash.  On the web certificates are necessary because clients are always anonymous and the server is always untrusted.

**Comment by urko-b** [comment]
@prettydiff 
My grpc server is deployed on a VPS, it is not localhost. I can access it through domain name + port like : `domainname.com:443` 
I created my own CA then I created client certificate. I'm using same certificates to connect a `grpc` go client on my local to this go `grpc` server on my VPS.

I'm not using that configuration you mentioned `rejectUnauthorized`

**Comment by GabrielLeonte** [comment]
Suggestion: Try to listen the grpc server with the external ip of your server and the 443 port. 

Although I wouldn’t recommend using grpc with Node, the compatibility is poor, it really stands out that grpc is better suited for golang

**Comment by urko-b** [comment]
@GabrielLeonte I decied to rebuild the whole project in `go`
