### ISSUE TITLE
Description for default threads per one nodejs process

### ISSUE THREAD

**Issue by ChrisCho-H** [nodejs/help#4101]
### Details

I'm just wondering whether my understanding is right regarding the default number of thread in nodejs.

### 1. Without Network I/O

7 threads default per process.

- 4 threads for LIBUV(fs, zlib, crypto) -> either to execute cpu intensive job(crypto) or File I/O job(because underlying OS does not support async for it)
- 1 thread for javascript execution
- 1 thread for garbage collector
- 1 thread for event loop -> which is mainly used, so nodejs is usually regarded as 1 thread(event loop) per 1 process runtime.

### 2. With Network I/O

11 threads default per process

- 7 threads same with above
- 4 threads for DNS lookup -> which used to share above LIBUV thread pool but separated to solve [this issue](https://github.com/nodejs/node/issues/8436)

Is my understanding right? Any help to correct or elaborate on is welcome!

### Node.js version

Latest

### Operating system

MacOS

### Scope

runtime

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
No.  JavaScript is single threaded and runs (V8) in the same thread as Node.js thereby allowing access to the Node APIs directly to the language without anything crazy.  So, there is only one thread.

Asynchronous programming occurs in Node using JavaScript's event model.  The event model provides multiple call stacks to this one thread.  You have to understand that asynchronous programming is always dramatically slower than synchronous programming (single call stack).  The advantage provided by multiple call stacks is that with a single call stack any call to an API for something outside the JavaScript language will freeze the application until that external task completes.

Arguably multiple call stack programming is less powerful than true multi-threading.  While tasks outside the actual language may execute and complete in parallel the messaging back to the language must occur in sequence of looping through the event model.  With multi-threaded application everything is truly parallel all the way down and messaging occurs between threads to keep each thread apprised to status changes.  Multi-threading, though, requires much greater hardware resources to achieve superior performance though, which is why this matter is arguable.

Node does provide an extended capability for multiple threads though: https://nodejs.org/dist/latest-v19.x/docs/api/cluster.html

**Comment by Hyunhum** [comment]
Thanks for elegant explanation for gc and event loop!
However, if you check the process of node, you can find out there's a 7 to 12 threads running per 1 node process. I'm just wondering if node is a single thread, what are those other threads running on node?
With this curiosity, I ended up with the conclusion above, single thread for event loop and other complementary threads(not used in most cases).
As I researched, LIBUV has a multi-thread(default size 4) which is [clearly declared in its repo](https://github.com/libuv/libuv/blob/acfe668ecbb008755ded4c2a7b2639e6b17a6f11/docs/src/threadpool.rst)!
Description for other threads, here is a [reference](https://stackoverflow.com/questions/61550822/why-node-js-spins-7-threads-per-process).
You mean that other threads(i.e. run by LIBUV) are just independent helper for node, so not account as node's thread?

**Comment by spaceyTracey50** [comment]
I have not one clue of what you just said, lol  NO IDEA.... lol

Tracey

**Comment by prettydiff** [comment]
@Hyunhum When I open Windows Task Manager on Windows 10 after starting my Node application I see one entry for *Node.js JavaScript Runtime*.  That process has no child processes associated with it.  If were to use the child process library then I would expect to see a sub-process executing with Node as the parent process.  Perhaps OS resources are consumed and listed different than what the Task Manager displays and/or other OSs associate low level OS resources in a way that looks like additional processes.

**Comment by ivan-kleshnin** [comment]
> No. JavaScript is single threaded and runs (V8) in the same thread as Node.js thereby allowing access to the Node APIs directly to the language without anything crazy. **So, there is only one thread.**

Maybe the last claim is wrong. Macos Activity Monitor also counts 11 or 7 nodejs threads:

![Screenshot 2023-09-21 at 09 10 00](https://github.com/nodejs/help/assets/2128182/afaf94db-f861-4174-a168-d7955d44004c)

For this script:

```js
setTimeout(() => {
  console.log("bye")
}, 60000)
```

**Comment by BoburF** [comment]
actually there is one thread for v8 and it's call stack with garbage collector(in my opinion), one thread for event loop and there is thread pool with it's default 4 threads.
question: is there 6 threads in nodejs if you use all 4 threads in thread pool?

**Comment by RealYukiSan** [comment]
> @Hyunhum When I open Windows Task Manager on Windows 10 after starting my Node application I see one entry for _Node.js JavaScript Runtime_. That process has no child processes associated with it. If were to use the child process library then I would expect to see a sub-process executing with Node as the parent process. Perhaps OS resources are consumed and listed different than what the Task Manager displays and/or other OSs associate low level OS resources in a way that looks like additional processes.

my mine also not show only 1 thread, here's the output on the linux machine:

```bash
$ node -e 'console.log(require("fs").readFileSync(`/proc/${process.pid}/status`).toString().match(/Threads\W+([0-9]+)/)?.[1])'
7
$ node
Welcome to Node.js v18.19.1.
Type ".help" for more information.
> require("fs").readFileSync(`/proc/${process.pid}/status`).toString().match(/Threads\W+([0-9]+)/)?.[1]
'12'
```

**Comment by RealYukiSan** [comment]
why people dislike the responses by @prettydiff ?
