### ISSUE TITLE
How do i install nodejs on Ubuntu 14.04 after downloading the package (.tar) from nodejs.org

### ISSUE THREAD

**Issue by zenismaharjan** [nodejs/help#418]

**Comment by gibfahn** [comment]
There is no "installation" per se, you just need to extract the tarball, and make sure the `node` and `npm` binaries in the `./bin` subdirectory are somewhere in your path.

I find [nvm](https://github.com/creationix/nvm#install-script) is useful for managing node installations (it will download, extract, and add to path for you). If you want to do things manually, you can do something like:

```bash
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
tar -xf node-v6.9.2-linux-x64.tar.gz --directory /usr/local --strip-components 1
```

This will put the `./bin` directory in `/usr/local/bin`, which should be in your `$PATH` already. You can verify that it worked with:

```bash
node --version
npm --version
```

**Comment by gibfahn** [comment]
I'm not a huge fan of this, as it makes it harder to know what to remove if you want to "uninstall" and use a new version of node. You can also untar to a different directory and symlink your node and npm binaries.

**Comment by Flet** [comment]
I like to use the Nodesource PPA when installing node on Ubuntu:
https://github.com/nodesource/distributions#installation-instructions

In a nutshell:
```bash
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by zenismaharjan** [comment]
@gibfahn Thank you very much, it worked perfectly!!! :D 

@Flet Thank you, but it tried it before, but couldn't get the latest versions.

**Comment by zipzit** [comment]
I'm way confused.  If using NVM or another package manager system is recommended for adding nodejs to a linux operating system, WHY are the binaries offered up at http://nodejs.org instead of a few lines of simple instructions to use a package manager?  And if the decision is made to keep the binary distribution, why is there not a simple instruction on how to download, extract and use the binaries?  (Hint: readme.md might be a handy place to add Linux specific comments and lines of code shown on this issue by gibfahn on 23 Dec 2016? ) 

Am I looking at this wrong? Why doesn't the documentation for http://nodejs.org/en match a user's needs here?  

Would it be helpful for me to pull a branch and submit that readme update?

**Comment by bnoordhuis** [comment]
@zipzit Package managers are not _the_ recommended way of installing, just _a_ way.  The officially endorsed way is the installer or tarball from https://nodejs.org/.

Pull requests are welcome if you think the documentation could be improved.  Copying @gibfahn's instructions verbatim isn't a good idea though because /usr/local won't be right for everyone.

**Comment by gibfahn** [comment]
@zipzit to add to what @bnoordhuis said, the basic issue is that there is no single "recommended" way to install things in Linux. We release (and thus support) the tarballs containing the binaries. 

The way to install node is to extract the tarball somewhere, and put the `bin/` subdirectory in your `$PATH`. 

However there are lots of different ways people do that. Some like to put node in `/usr/local/bin` (what I showed). Some like to use a set of shell scripts to manage the path, and install node into `$HOME` (nvm). If you distro has a package manager you might want to use that, although we don't maintain packages ourselves (`apt`, `yum`). You might want to build from source (`git clone https://github.com/nodejs/node.git && cd node; make -j4 install`).

Despite not being official ways, both `nvm` and `apt` [are documented on nodejs.org](https://nodejs.org/en/download/package-manager/). I agree that we should have some basic documentation for how you might want to install node from the tarball on Linux, it's on my list (assuming no-one else steps up to do it). If you'd like to submit a PR that'd be great!

Also docs for using downloads should be added to the list on https://nodejs.org/en/download/, the README on Github is for people building/contributing to node, not for users.

**Comment by codefusser** [comment]
@gibfahn There couldn't be any better solution than your explanation. You rock man!

**Comment by navaneethnavi** [comment]
@Flet  Thank you so much man, i wasted a day on this. I tried may commands none of them worked.  i was not able to install Checkinstall, that's why all my attempt failed

**Comment by rahulpatial98** [comment]
Thanks You :relaxed:

**Comment by ctp-placebo** [comment]
@gibfahn and everyone else too

Would it not then make even more sense to include the commands  
```
wget https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
tar -xf node-v6.9.2-linux-x64.tar.gz --directory /usr/local --strip-components 1
```
on the download page for Linux, thus negating that everyone has to grab a tar ball only to **not** find any install instructions inside, ie no `install.sh` or similar, like we are used to from other sources?  

Seems like whoever made that page didn't really think through _what users are actually trying to do_. WE don't care, we want a fast install so we can get on with whatever red text is stopping some cli command from succeeding due to an out of date/incompatible version.   

As for: "it's not the same for everyone on Linux" argument, with the install location being `/usr/local` or not, I think if you are specifying a non-standard location, you probably know to adapt that command. 

So maybe just provide simple instructions for the 99% ?

**Comment by gireeshpunathil** [comment]
FWIW, https://github.com/nodejs/help/wiki/Installation documents the installation instructions from tarballs, but if you think that location is not discoverable , feel free to suggest a better one!

**Comment by codefusser** [comment]
Since, node tar file runs without prior installation, after executing the _tar zxvf <node-filename>_, move/copy the directory to the usr/local/ directory and add that to the node.../bin/ directory to the PATH with the _export PATH:$PATH../<node/bin_dir>_....

**Comment by ChrisAchinga** [comment]
hello, I downloaded the zipped node js from the site, how do I install it, I use ubuntu

**Comment by Zankoku-Okuno** [comment]
@gireeshpunathil I "discovered" that location through google-fu and then reading the entirety of this issue, to say nothing of the dead-ends I ended up with. A more-discoverable location has already been suggested by @ctp-placebo "on the download page for Linux" (or presumably any other OS for which there is a binary release you can download). Some instructions (or a link to them) at that location would help those who just need node installed for something else, rather than those who have the time and inclination to explore at the source repository. I expect that's a fair number of people, not just the ones who have found their way here and spoken up.
