### ISSUE TITLE
vm Module Loader throws "request for 'net' is not in cache"

### ISSUE THREAD

**Issue by akwotom** [nodejs/help#4218]
### Details

I'm using the **vm** API in a project, where I need to provide virtual environments for code to run. However, during linking (`link()` method), I get the following error.
**Error: request for 'net' is not in cache
    at SourceTextModule.link (node:internal/vm/module:199:17)**

Please, what am I doing wrong? I deeply appreciate your help.

### Node.js version

20

### Operating system

Ubuntu 20 (Linux)

### Scope

Code

### Module and version

Not applicable.

**Comment by prettydiff** [comment]
Could you please provide a link to the code?

**Comment by preveen-stack** [comment]
Also, Can you share detailed log

**Comment by akwotom** [comment]
The code is part of a complex system, and wouldn't even make sense, if shared.
To reproduce this, just have a situation where two modules require each other, cyclically.

**Comment by prettydiff** [comment]
There must be more to the problem then that because the ECMA module syntax used in the language already accounts for this.  For example my browser network library and my browser web socket libraries import each other:

* https://github.com/prettydiff/share-file-systems/blob/master/lib/browser/utilities/network.ts
* https://github.com/prettydiff/share-file-systems/blob/master/lib/browser/utilities/webSocket.ts

**Comment by preveen-stack** [comment]
cc @nodejs/vm
