### ISSUE TITLE
https on application based on node.js

### ISSUE THREAD

**Issue by AsimPervez93** [nodejs/help#446]
* **Node.js Version**: 6.9.4
* **OS**: Ubuntu 16.04.1
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

I have installed timeoff-management, based on node.js.  I'm trying to secure it using https but am having a difficult time.  I had no idea how to secure node using https directly so I thought of the workaround of installing apache2, installing the https cert on there and then redirecting ports 80 and 443 to port 3000 (application).  This works for port 80 but I can't get it to work for port 443.

I'm new to node so would very much appreciate some support of if maybe there's a way to secure node with https directly instead of securing apache then redirecting traffic as that clearly isn't working for me.

**Comment by bnoordhuis** [comment]
The built-in HTTPS server support keys/certificates in PEM and PKCS#12 format.  If it isn't working for you, please post your code but make sure you've read the documentation for the https and tls modules first.

**Comment by stamster** [comment]
Serving HTTPS traffic from node.js is far from good idea. 
Best scenario one could achieve is to put nginx (apache2, really?!) as a front web server and to connect to the node.js (back-end) via UNIX socket pipe in order to avoid overhead as much as possible. 
That's how I do it with our team. 
Application server of any kind should not bother with purely technical protocols such as HTTP(S), and nothing does better job than nginx there.

This is how I deploy PHP apps and now Node.js apps. Application server is always in the background, and never fully exposed to the clients.
