### ISSUE TITLE
Is it necessary to listen for the "error" event in a http.request response?

### ISSUE THREAD

**Issue by zbjornson** [nodejs/help#507]
* **Node.js Version**: 6+
* **OS**: Any
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: http

In the [example given for `http.request` on the http doc page](https://nodejs.org/api/http.html#http_http_request_options_callback), there's no `error` event listener on the response. Is there any scenario in which an error would be emitted on the response?

```js
var req = http.request(options, (res) => {
  res.on('data', (chunk) => { /* ... */ });
  res.on('end', () => { /* ... */ });
  res.on('error', () => { /* Can this ever happen? */ });
});

req.on('error', /* (can definitely happen) */);
```

**Comment by bnoordhuis** [comment]
Related (but not the same): https://github.com/nodejs/node/issues/9592

I'm 98% sure no runtime errors are currently emitted on the response object.  Socket errors are all emitted on the request object.

You do get an 'error' event for a couple of logic error situations, like trying to write after the response has been finalized.

**Comment by zbjornson** [comment]
Thanks!

**Comment by KickButtowski80** [comment]
I wish there were more explanations so novice people like me could learn more about it

**Comment by borkaborka** [comment]
Although this is an old thread - I'd like to add a comment here to avoid others being confused same way as I was. As opposed to implicit conclusion coming from the above comments - `response.on('error')` does happen and a proper implementation must add a handle for it (in addition to `request.on('error')`). 

There's a real situation, and we see in our production systems - when target system aborts (closes the socket) during _response_ transmission (i.e. after response headers, but before response was fully completed) - a response.error event (which happens) is not propagated to the request object.

This is _somewhat_ mentioned in Node.js docs:
https://nodejs.org/api/http.html#http_http_request_url_options_callback

> In the case of a premature connection close after the response is received, the following events will be emitted in the following order:
> 
> 'socket'
> 'response'
> 'data' any number of times, on the res object
> (connection closed here)
> 'aborted' on the res object
> 'error' **on the res object** with an error with message 'Error: aborted' and code 'ECONNRESET'
> 'close'
> 'close' on the res object

My confusion was due to some other place in Node.js docs above - where they say:

> If **any error** is encountered during the request (be that with DNS resolution, TCP level errors, **or actual HTTP parse errors**) **an 'error' event is emitted on the returned request object**. As with all 'error' events, if no listeners are registered the error will be thrown.

I guess "during the request" here means only "request" phase of the whole `Http.request()` lifecycle. And "HTTP parse errors" are likely about input parameter errors, not HTTP response parsing errors.

So, the bottom line is - both `request.on('error')` and `response.on('error')` are needed in a solid, reliable implementation
