### ISSUE TITLE
object desctructuring not working in Node v6.9.5

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#518]
I'm on MacOS 10.12

I have this .js script:

```js
#!/usr/bin/env node

const suman = require('suman');
const Test = suman.init(module);

Test.create(function (assert, sumanUtils, it) {

  {
   checkForEquality,
    mapToTargetDir
  } = sumanUtils;           // this should be simple object destructuring

  it(checkForEquality.name, t => {

  });

  it(mapToTargetDir.name, t => {

  });

});

```

I am just trying to test some functions - sumanUtils is an object with all the functions as methods.
The name of each test case is just the name of the function.

No idea why object destructuring is not working here. I get this error:

```
$ node test/src/all.test.js 
/sumanjs/suman-utils/test/src/all.test.js:11
  } = sumanUtils;
    ^
SyntaxError: Unexpected token =
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by addaleax** [comment]
Try `const` before the `{` :)

**Comment by ORESoftware** [comment]
Ahhhh, yeah, I knew it was operator error but I could not figure out what it was.
IMO, that const declaration should not be necessary, maybe in future versions, but thanks!!

**Comment by bnoordhuis** [comment]
> that variable declaration should not be necessary, maybe in future versions

I'd say that's unlikely.  Without a const/let/var, the parser potentially needs to look ahead until the `=` to know whether it's a block statement or a destructuring assignment expression.  Ambiguity that needs unbounded lookahead to resolve is unlikely to be accepted by TC39.

Aside: `({ checkForEquality, mapToTargetDir } = sumanUtils)` resolves the ambiguity.  Note however that with your example it creates globals because it's non-strict code and `checkForEquality` and `mapToTargetDir` haven't been defined yet; it throws a ReferenceError in strict mode.

**Comment by ORESoftware** [comment]
@bnoordhuis  good points

**Comment by ORESoftware** [comment]
thanks
