### ISSUE TITLE
How to run Node.js program from HTML5 Page

### ISSUE THREAD

**Issue by vikrammohan7** [nodejs/help#528]
* **Node.js V6.9.4**:
* **Windows Server 2012 R2**:

I am trying to run a Node.js program from HTML5 page on a local server. But I am not sure how to call or execute the Node.js program I created on the local server in the HTML page.
Can you please help me with this or direct me with some samples?

**Comment by vdeturckheim** [comment]
Nodejs does not run in a HTML page but on a server.

**Comment by vladamx** [comment]
Hi @vikrammohan7 

Welcome to the Node.js platform!

Node has the same concerns as any other language used for a web development. 
Node just does things a little bit different. 

That's why it is so awesome!

If you are just interested to get things done, follow the steps bellow:  

1. [Fire up HTTP server](http://expressjs.com/en/starter/hello-world.html) 

2. [Serve HTML file](http://expressjs.com/en/starter/static-files.html)

**Comment by vsemozhetbyt** [comment]
BTW, there are ways to call Node.js from HTML:

https://github.com/electron/electron
https://github.com/nwjs/nw.js

However, they are for desktop applications mostly.
