### ISSUE TITLE
Online Compiler using Compilex

### ISSUE THREAD

**Issue by sajalarora11** [nodejs/help#543]
* **v6.9.2**:
* **macOS**:
* **code**:
* **Compilex**:

Hello there...
I have to build an app using Node.js on the back end and have to create an online compiler that can mainly compile C C++ and Java. Can anyone provide me the details how to make it using compilex package. I read the documentation of this module but i am probably confused.  

```js
// I am an example of JS code
// please remove me too
```
-->

**Comment by lordKnighton** [comment]
This is depreciated tech: You can't find any modern tech that does the same, with a decent upheld docs section? Anyway i don't know anything about this, so I'll try to bring in the fellow behind the tech you want @scriptnull 

Not to sure if that will work. You should read the CompileX readme, i thinks the brands he names should be you answer.

**Comment by scriptnull** [comment]
@sajalarora11 compilex is deprecated and I won't advice using it. You can read the deprecation notice from here ( https://github.com/scriptnull/compilex#deprecation-notice ). 

### Alternate solutions:
- If you want the programs to be compiled and executed on your machine, go with https://glot.io/ ( this solution saves you from the hassle of installing all the compilers on your machine by using a container technology called [docker](https://www.docker.com/). So it might be a good exploration exercise for learning docker, if you haven't already known about it)
- If you don't mind your programs to be uploaded to the internet, then you can easily achieve compilation through online compilation service APIs like https://www.hackerrank.com/api , https://www.hackerearth.com/docs/api/developers/code/legacy/

### Why Deprecated ? 
- well, we already have a production ready tech ( glot.io ).
- security issues - this can be overcome by running compilex inside docker containers. But again, it would take lot of time and energy to get things in place.

Let me describe a glimpse of security issue. Lets say user is trying to compile and run a malicious program ( example: program to shutdown a system ). If you run compilex on host machine rather than a container, then the whole machine would go down.

So, better stick with the alternate solutions for now !

**Comment by lordKnighton** [comment]
Thanks for coming here & giving us your time. @sajalarora11 I hope you can find some other suitable tech. Im gonna close for now, but if you want to continue this discussion, reopen & we will take it from there.
