### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by MKT123** [nodejs/help#546]
Hi.... I am working on node js app in bluemix...
I see 2 below observation with performance
1. The app takes quite sometime to get data from app.js to send it to html (app URL)
2. app seems getting crashed slowly and shows below error.
503 Service Unavailable: The server is not available now. Please try your request later.
here is my code..can someone tel me what could be the issue? 

Thanks.

**Comment by rnchamberlain** [comment]
hi @mahakT, do you see anything on the bluemix console log when it crashes?

**Comment by mahakT** [comment]
Hi Thanks for the response...

I see only below msg in bluemix console ... **home/vcap/app/.app-management/scripts/start: line 50: 149 Killed ${NODE_EXECUTABLE} ${NODE_OPTS} ${BOOT_SCRIPT} ${NODE_ARGS}**

Also... I did noticed about the Jsondata[], I removed them from global declaration and added inside methods.... Uploaded the code in GitHub link.. I still see that it take few secs to load the output.

https://gist.github.com/mahakT/817238ae7774120840aa96608b0038b2

output for review --> https://firstappthea.mybluemix.net/

**Comment by gireeshpunathil** [comment]
I see no issues with your website - tried many times and the page displays just fine! Probably slow network at your end?

```
#time curl https://firstappthea.mybluemix.net > 1 2>&1
real	0m1.391s
user	0m0.029s
sys	0m0.013s
```

**Comment by mahakT** [comment]
Hi...May be I should put it in more clear.

The app works fine... but if you notice... the link takes lil delay to get the data to the table that display in html.

and secondly, the app slowly getting crashed after sometime...which ends up displaying 

503 Service Unavailable: The server is not available now. Please try your request later.

That's why I shared my code to see if am missing something as app is working and am not able to get more logs in bluemix.

**Comment by gireeshpunathil** [comment]
> 503 Service Unavailable: The server is not available now. Please try your request later.

Can you clarify if it is still happening, after your code changes? If so, after how much time?

> this is node js app takes few sec to display the output

how many seconds precisely? Can you measure the timelines in the browser? (Chrome: view-> developer -> developer tools -> timelines, Safari:  Develop -> start timeline recording)

I get the page in less than 2 seconds, consistently. The timeline captured shows a bit more, due to the involvement of manual clicks.

<img width="313" alt="screen shot 2017-03-24 at 11 31 53 am" src="https://cloud.githubusercontent.com/assets/6447530/24282660/eed2484e-1086-11e7-8806-e8e9a3da9bc4.png">

**Comment by mahakT** [comment]
Hi Gireersh,

As you suggested the data accumulation was causing issue and app works fine now...Thanks a lot for that !!

About the second point, yes its consistent on manual clicks and  it takes 1-2 seconds to populate the data in the table right... do you think its bec of index.html takes that time to fetch the data from js? 

Thanks.

**Comment by gireeshpunathil** [comment]
@mahakT 

If you think the 2 seconds is un-acceptable, here is what you should do:

1. Isolate the delay between the app and the network: for that, modify the index.html to write just a 'helloworld' string to the client. Measure the time for the same either through timeline profiling, or the time command (`time curl https://firstappthea.mybluemix.net/`).

2. If this shows up similar time period, then it is a question of the network bandwidth.

3. If there is a considerable reduction with the helloworld page, then there is a scope for improvement in the code:

4. Isolate between the server logic and the client scripting logic (index.html).

However, from the above chart, I see the client scripting takes only 83 ms, which means it does not contribute anything significantly.

I will be able to make further assertions when I see your profiling data.

**Comment by mahakT** [comment]
Hi gireeshpunathil ,
Thanks for all your help !!

I see the app working constantly, should be good i guesss... Thanks again for all your inputs...

**Comment by gireeshpunathil** [comment]
Glad that your issue is resolved and the app running healthily in Bluemix, and I was of help. Feel free to close this issue at your comfort.
