### ISSUE TITLE
Native promises + node.js domains

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#555]
I like domains and use them for certain edge cases and libraries. Not for servers but for other things.

Has anyone in the Node.js community monkey-patched native promises to work with domains?

Is it possible? Looking for help with this. Thanks!

**Comment by ORESoftware** [comment]
I wrote this up now:

https://github.com/nodejs/node-v0.x-archive/issues/8648



Seems to work

**Comment by shellberg** [comment]
I think its well recognised that Domains serve a developer's needs, but it created a maintenance nightmare in the core code (the tentacles of Domains penetrated everywhere!).  Domains was an experiment; but [it officially remains 'Deprecated' functionality](https://nodejs.org/api/domain.html).  It persists, but with the hope that the usage exposure is only confined within the scope of well-maintained modules such that when its superceded the impact will be borne for the Node.js (end-)user community by only a few module maintainers.  Just fair warning, because its sounds like your intention is to use Domains in your application code rather than in the module context.

As for promises... you're on safer ground with the standardisation of ES6 promises - you at least know the expectations for behaviour and specifications of what constitutes them given the many options of implementations hitherto.

You'll certainly find Domains has been a subject of much discussion : you could probably do worse than googling for some of that activity (some [StackOverflow questions provide decent jumping off points](http://stackoverflow.com/questions/33986859/what-is-the-alternative-to-node-js-domain-module) ).
And, you should track progress on [AsyncWrap](https://github.com/nodejs/promises/issues/9) which is a potential Domains successor and probably exactly what you want/need!

**Comment by ORESoftware** [comment]
I have been on this thread awhile. My concern is that AsyncWrap or whatever it's called now does not solve the same problem that Domains solved.

If AsyncWrap can wrap an arbitrary amount of user code (or foreign code) and catch any and all errors that might get thrown, then - great - I don't need Domains any more. However I don't believe that's the case - TMK AsyncWrap is only as good as what you do with it. In other words, it will only be guaranteed to work for the code you control.

I have heard the core maintenance headache argument - it's legit but I am starting to believe that it's not as bad as originally estimated.

Again, Domains become very useful, even imperative, not for application code, but for library code.

**Comment by sam-github** [comment]
Domains couldn't be relied on either, not at first, they need cooperation from libs that did connection pooling.

Many libs slowly gained domain support, because domains were offiicial Node APIs. With time, asyncwrap support should also be adopted by the npm module ecosystem, but we aren't there yet, and I don't know if the APIs even exist (they were still under discussion at last NINA). Bluebird, for example, reasonably refused to add continuation-local-storage support, but when/if asyncwrap has APIs it can use, that might be more compelling.

I find it odd you say domains are imperative for library code, given the most common use was to wrap http request handlers, and libraries mostly just use domains when necessary to make sure callbacks occur in the correct domain, because error handling should be delegated to the user of a library. What do you find them so useful for in libraries?

**Comment by ORESoftware** [comment]
domains are imperative for *some* library code. Here's some knowledge for you. Lab (for HapiJS) and Suman are test frameworks that both use domains to trap errors thrown from user code.  This is a much better pattern that that used by Mocha.  On the other hand, AVA partially solves the same problem in a different way - AVA has its own assertion library which will trap errors. *But* if errors are thrown in AVA hooks that aren't thrown by its assertion library, than AVA is dead in the water. That's why Suman and Lab can have a better dev experience than AVA and Mocha. 

Software testing inverts the standard software model - errors are supposed to be thrown. Think about that for second. The library has to trap errors through from arbitrary code, we cannot expect the user to perfectly trap their own errors, the library is supposed to do much of that work.

To a certin extent testing software inverts the software development model  - errors are supposed to be thrown, and aren't just for flow of control. They are supposed to be trapped and that's it. But how do you trap errors in arbitrary user code? Domains.

**Comment by ORESoftware** [comment]
In other words, domains are the only solution to small but significant subset of design problems in Node.js software.

**Comment by ORESoftware** [comment]
@sam-github but you are right, it's possible for users to write libraries that don't propagate domains. It requires buy-in from both core and userland.

**Comment by ORESoftware** [comment]
@sam-github @shellberg  here is your test:

take this code

**Comment by sam-github** [comment]
asyncwrap is a WIP, I don't claim it can replace domains yet, I don't think anyone does, but that's where the effort is going.

Mostly I was surprised by the "domains ... imperative for libraries". As for imperative for test runners, even my favorite test runner is trying to use domains now, I agree about that.

I've no comment on patching promises, it sounds like you got it working, maybe someone else will weigh in on what they've done in this space.  @isaacs is using them in tap, for example.

**Comment by ORESoftware** [comment]
@sam-github thanks for the feedback - so you are saying TapJS will use domains in the library?

**Comment by ORESoftware** [comment]
I see this issue - https://github.com/nodejs/node/issues/10843
glad to see it
