### ISSUE TITLE
Published or Release Build Feature for Node.js Web application

### ISSUE THREAD

**Issue by matt212** [nodejs/help#576]
Are there any npm packages for converting node.js web app's source code with all its dependencies within node_modules folder to compiled/released/published build files like for example :

- .net has .dll file
- java has .jar file
- elixir has .beam file.

rather than any npm packages , any other alternatives to achieve the goal of published IL !

**Comment by matt212** [comment]
Why is it invalid question ?
could you please provide "Valid" justification for the same !

**Comment by bnoordhuis** [comment]
@matt212 This issue is still open in case you hadn't noticed...

**Comment by matt212** [comment]
Sure will stay frosty , thanks  !

**Comment by sam-github** [comment]
`npm pack` or `docker build`

**Comment by refack** [comment]
@matt212 the `invalid` was ment that it's not a bug in node (since then we changed the tagging of such issues to `wrong-repo`).
There has been a lot of discussion about the packing/obfuscation of complete node projects. At present it's not a project goal to enable this, but it _might_ be the future nodejs/node#11842.
There are userland tools that can do that. I personally don't have a favorite solution, but you can check out:
https://github.com/nexe/nexe
https://www.npmjs.com/package/pac
and the discution in:
http://stackoverflow.com/questions/8173232/how-to-make-exe-files-from-a-node-js-app
http://stackoverflow.com/questions/14314038/how-do-i-deploy-node-js-applications-as-a-single-executable-file
http://www.jedi.be/blog/2013/05/14/Compiling%20-%20packaging%20a%20nodejs%20project%20as%20a%20single%20binary/

**Comment by SimenB** [comment]
We have successfully used https://github.com/h2non/nar at work. You can download an archive created with that tool here: https://github.com/finn-no/cdn-uploader/releases
The only thing I don't like is that it has to unpack in order to be executed, but the big thing for us is that it's distributable and runnable without requiring node to be pre-installed

**Comment by refack** [comment]
@matt212 I felt your original post should be turned into a feature request. I edited it a little bit, feel free to re-edit me. nodejs/node#12386

**Comment by matt212** [comment]
@refack  Many Thanks applied your edited version. !

**Comment by harshalyeole-tudip** [comment]
I support this issue...

**Comment by gireeshpunathil** [comment]
anything outstanding on this?

**Comment by matt212** [comment]
yes , since enhancement for  release build of node.js is still not available !

**Comment by refack** [comment]
I'm actively working on a solution (Also WRT https://github.com/nodejs/node/pull/17320) but it will take time, and might not land.

**Comment by SimenB** [comment]
Another alternative is https://github.com/zeit/pkg (which we've migrated to, ref my post above)

**Comment by Trott** [comment]
It seems that the question has been answered. As far as the desired feature, there is a relevant feature request at https://github.com/nodejs/node/issues/11903.
