### ISSUE TITLE
meta: labels in nodejs/help

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/help#593]
What is the policy for labels in nodejs/help? Currently, we have a default set and it almost is not used. Some topics are pretty persistent (windows, install, npm, memory...). Maybe we can add some as we go? If so, should we inform about new tags somewhere? Maybe we could have a dedicated issue for this?

**Comment by bnoordhuis** [comment]
No strong opinion.  I think of nodejs/help more as a forum than a bug tracker that doesn't need the same structured approach as other repos.

**Comment by refack** [comment]
No strong opinion. +0.3 as doing analytics may lead us to good insights (like better docs, better error messages, etc.)

**Comment by refack** [comment]
See https://github.com/nodejs/CTC/issues/102#issuecomment-294580379

**Comment by evanlucas** [comment]
I agree with @refack. +1

**Comment by lordKnighton** [comment]
agree with @bnoordhuis. But then again, when i added the `discuss label`, i just added it. Because there are always some issues popping up, that you don't want to be rude & close a discussion because it may still be active. Either way, I think you should create a tag if its necessary & delete it if it not in use much. Basically just use your best judgement.
