### ISSUE TITLE
How to use internal module in C++ Addons?

### ISSUE THREAD

**Issue by moran32** [nodejs/help#599]
Example:
I want to use http or other internal module in C++ Addons
How to do?

**Comment by sam-github** [comment]
Something like this: https://github.com/nodejs/node/blob/bda34bde56f688d38a908cc851e892402bef6f23/src/node.cc#L2648-L2660

Though I have to say doing so would probably be a mistake. Your package should have js code that uses http or other js modules, and then put only the part of its code that needs to be C++ because it calls C++ APIs in the addon.
