### ISSUE TITLE
can i get res.body at server.on('request') event?

### ISSUE THREAD

**Issue by i5ting** [nodejs/help#600]
* **Version**:
* **Platform**:
* **Subsystem**:

can i get res.body at server.on('request') event

```js
const http = require('http');
const server = http.createServer((req, res) => {
  res.end("Hello world")
});

server.on('request', function (req, res) {
  console.log('response.body', res.body);
})

server.listen(8000);
```

**Comment by sam-github** [comment]
No, there is no such property on the response object, see docs: https://nodejs.org/api/http.html#http_class_http_serverresponse

**Comment by sam-github** [comment]
What are you trying to do? What do you think the .body property would be?

**Comment by i5ting** [comment]
```
server.on('request', function (req, res) {
  
})
```

it's Semantically incomplete!

the `request` event is trace a complete request && response, as you said, if it can't get res.body, it is strange!


now, we can make it work with a hack

```
    var body = "";

    res._originalWrite = res.write; // Store reference to the original write method
    res.write = function(chunk, encoding, callback) {
        body += chunk;

        res._originalWrite.call(res, chunk, encoding, callback);
    }

  res.on('finish', function () {
        this.body = body;
  })
```

**Comment by refack** [comment]
@i5ting it's not that simple, a `request` can be a very long process, even have back-and-forth with the client. That's way the request acts like a stream stream
What you call a "hack" is the intended behaviour, since only you know how the client and server should behave.

Also you could try frameworks like `express` that implement more functionality using the basic HTTP module.
