### ISSUE TITLE
install nodejs within Cygwin under win10

### ISSUE THREAD

**Issue by chen-fang-1992** [nodejs/help#606]
* **Node.js Version**: v6.10.2
* **OS**: win10
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

When I am installing node within Cygwin under win10, I receive this error
usr/bin/python_tools/gyp_node.py -f make
gyp: name 'MSVS_VERSION' is not defined while evaluating condition '(OS=="win" and MSVS_VERSION>="2012")' or ...
Actually, I have installed Microsoft Visual Studio 2017 community, how can I fix this problem?

**Comment by refack** [comment]
That version (`v6.10.2`) needs some tweaking in order to build on VS2017. You can try to follow the instructions in https://github.com/nodejs/node/blob/v6.10.2/CONTRIBUTING.md on how to build for Windows.

P.S. If you don't HAVE to use cygwin you can just download a prebuilt binary from https://nodejs.org/download/release/
