### ISSUE TITLE
formation of ReadStream for ftpd module to process

### ISSUE THREAD

**Issue by SameerTi** [nodejs/help#611]
* **4.1.1**:
* **Linux**:
* **n/a**:
* **FTPD (0.2.11)**:

I use "custom file system", stored in rfs variable, while constructing FtpServer

```js
var o_DownloadBufferSize=1024 * 1024; // 1MB Buffer
var o_DownloadBuffer=new Buffer(o_DownloadBufferSize);
o_DownloadBuffer.fill("0xFF");

var restrictedFs=function(conn) {
this.createReadStream=function(path){
   
}

...
..
..

var ftpServer=new ftpd.FtpServer(host,options);

ftpServer.on('client:connected',function(conn) {
	var rfs=new restrictedFs(conn);
        var username;
        conn.on('command:user',function(user,success,failure) {
		username=user;
		(user == appConfig.ftpUsername) ? success() : failure();
	});

	conn.on('command:pass',function(pass,success,failure) {
		// check the password 
		(pass == appConfig.ftpPassword) ? success(username,rfs) : failure();
	});

}
...
...
..
```
Above is code from my module... and as you can see, using "createReadStream" for FTP download test.
Under "createReadStream" i get path as "/download/120", this 120 is in MB
This createReadStream is called from "ftpd" module, as in following manner:
```
FtpConnection.prototype._RETR_usingCreateReadStream = function(commandArg, filename) {
...
..

  afterOk(function() {
    self._whenDataReady(function(pasvconn) {
      **var rs = self.fs.createReadStream(filename);**
      var readLength = 0;
...
..

```
My question is if you can provide me, sample code to be used under rfs.createReadStream, which is best in terms of performance, to send 120 MB in chunk as streams in parallel to process for ftpd module

Thanks in Advance.

**Comment by mk-pmb** [comment]
The API docs remind me that `new Buffer` is deprecated.

The problem with the for loop is what to do when the destination stream signals it doesn't want more data at the moment. Waiting would be futile, because as long as node is still busy with your function, it cannot deal with events on the destination stream, so it has no chance to ever notice when the stream is ready for more data.
To solve this, you'll have to go event-based.
The idea is to have a per-destination variable that counts how many more copies of your buffer shall be written, and event handler functions for when it's appropriate to write more data. Thankfully, npm has a module `from2` that abstracts the event plumbing away for us.

A rough idea for how it could work (not tested):

```javascript
'use strict';
var mtd, from2 = require('from2'), consts = {
  oneMegabyteOf_0xFF: Buffer.alloc(1024 * 1024, 0xFF),
  noMoreData: null
};

function makeCustomFs(ftpSession) {
  return Object.assign({ sess: ftpSession }, mtd);
}
mtd = makeCustomFs.methods = {};

mtd.createReadStream = function (fileName) {
  var readable, remainingCopies = 120;

  function readMoreData(sizeHint, then) {
    console.log('read stream suggested to read', sizeHint, 'bytes');
    if (remainingCopies > 0) {
      remainingCopies -= 1;
      return then(null, consts.oneMegabyteOf_0xFF);
    }
    return then(null, consts.noMoreData);
  }

  readable = from2(readMoreData);
  readable.fileName = fileName;
  return readable;
};



module.exports = makeCustomFs;
```
