### ISSUE TITLE
Date object

### ISSUE THREAD

**Issue by Gilli95** [nodejs/help#612]
* **Node.js Version**: v7.8.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**:code

I'm having issues with the Date object. The first example works fine. But when i try it with the month may in dutch (mei) i get NaN
```js
var date = new Date("woensdag 26 april 2017 13:40:47").getTime();
```
```js
var date = new Date("woensdag 3 mei 2017 13:40:47").getTime();
```

i've tested with other months and they all seem to be fine just the month "mei" is not. I worked around the issue but still wanted to let you know. 
Cheers

**Comment by refack** [comment]
@Gilli95 This is according to the [Standard](http://www.ecma-international.org/ecma-262/6.0/#sec-date-objects) or more easy to read [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date):

> dateString
String value representing a date. The string should be in a format recognized by the Date.parse() method (IETF-compliant RFC 2822 timestamps and also a version of ISO8601).
Note: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

I'm going to close this as "work according to standard"
