### ISSUE TITLE
Does NodeJS run in Windows CE x86?

### ISSUE THREAD

**Issue by binaryangel-noah** [nodejs/help#616]
Hello,
i am considiring to use nodejs in a project targeted to devices, since at this time windows is a possible target platform, i would like to know if nodejs runs on Windows Embedded 
Compact (Windows CE) x86, which is not based on the same Kernel like the rest of the Windows Embedded familly.

Any Insights on that ?

Thanks

**Comment by refack** [comment]
/cc @nodejs/platform-windows 

The official list of supported platforms is https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1
Binaries are at https://nodejs.org/download/release/

But if you have your CE set-up, you could try and build it yourself. `node` can be built with either `x86` or `arm` support.

P.S. I'm setting up a CE 2013 VM because I'm curious.

**Comment by benjamingr** [comment]
> i would like to know if nodejs runs on Windows Embedded

As Refack said, it's not supported, (I don't think ARM builds run on Windows). 

However you _might_ have some success getting https://github.com/nodejs/node-chakracore to run which has the same API but I think you'll need to do some work there too.

**Comment by gibfahn** [comment]
Maybe a question for @nodejs/chakracore

**Comment by binaryangel-noah** [comment]
@benjamingr  Thank you for you kind answer, but note, that it is not about CE on ARM, but on X86, which implements partially the windows 32Api. So basically that would be the regular Windows Build. My researches so far show that it "might or might not run or not stable" depending on what windows apis is uses.

@refack Thank you very much, i did not come far with setting up a VM with Windows Embedded Compact.

**Comment by refack** [comment]
> My researches so far show that it "might or might not run or not stable" depending on what windows apis is uses.

@binaryangel-noah running `vcbuild x86 test` will give you a good estimate on what works (our test suite is quite extensive). For extra context on compatibility with the ecosystem there's the [CITGM project](https://github.com/nodejs/citgm).

P.S. which version of `node` would you be interested in? Since the build requirements are different (e.g. `v7` can only be build with VS2015)

**Comment by binaryangel-noah** [comment]
@refack I am looking right now into the Version 6.10.3, the application would be running on industrial machines/devices, so LTS seems for me like the best choice. And our customer wants to stay "Platform Independent" as far posibble, it means right now Linux-Embedded or Windows Embedded Compact (as thats what their devices ship currently with)

**Comment by refack** [comment]
> Version 6.10.3

👍 It has a "soft" limit to VS2015.
Also I'm assuming you're targeting Windows CE 2013 (which is compatible with VS2015)

**Comment by refack** [comment]
> "Platform Independent" as far posibble, it means right now Linux-Embedded or

If you have the expertise, go with a linux solution, we build and test on "small" linuxes officially

|  System      | Support type | Version                          | Architectures        |
|--------------|--------------|----------------------------------|----------------------|
| GNU/Linux    | Tier 1       | kernel >= 2.6.18, glibc >= 2.5   | x86, x64, arm, arm64 |

**Comment by gireeshpunathil** [comment]
@binaryangel-noah - is this still an outstanding issue for you? please let me know

**Comment by binaryangel-noah** [comment]
Hi,
it resolved itself  as our customer decided to use linux after all. Thanks for everyones help.
