### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by eliasuardi** [nodejs/help#683]
* **OS**: Windows 10

Hello.
So I've created a simple app where a client and server establish communication over a websocket. In order to run the app I have to follow these steps:
1. execute ```npm run start``` in the command line to start the server.js script.
2. go to localhost:3000/ to access the client

What I'd like to do is to simply access the client and automatically run the server.js script without having to run any command in the command line. This is so that I can load the app on a host.
Is this possible? If so, how do I proceed?

Thanks.
Elia

**Comment by Kirmayrtomaz** [comment]
Try to use a package pm2, to deamon your application

**Comment by lordKnighton** [comment]
Say for instance that your deploying an app to heroku [Click me](https://www.heroku.com/) a `Cloud Application Platform` So they give you a script to insert in your code, so that it's continually. 
So this isn't something you have to bake up for yourself  But on your local System try to use nodemon #googleit so you don't have to keep stopping your server & restarting it. And if these answers aren't sufficient google host nodejs application, there are plenty of them & videos as well. 

--------

Closing issue for now, but if you still need help. No worries, just reopen issue & ping me @lordknighton
