### ISSUE TITLE
Push events listener to end or beginning of list

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#724]
I attach a `process.once('exit')` handler at the beginning of my program, but I actually want it to be the last handler to be invoked, not the first, is there some way to put this handler at and the end of the listeners list instead of the beginning?

**Comment by gireeshpunathil** [comment]
While the ability to achieve that in node is one thing, how do one use that capability? The same mechanism to place your listener at the end of the exit event queue (let us call it registerAtTail) can also be leveraged by other code sections at a later point in time to bring yours to the front?

So to me it looks like a language agnostic generic puzzle. Can I know your use case? I am not able to think of a task having a rule of being executed after everything else is over.

**Comment by the1mills** [comment]
It's library code. I am sure it's a common need to register a hook to run at the very end, but to register that hook first. I can see why it's not possible to do this, as is, however.

I unfortunately have a resorted to a callback in the global space that is fired by a different process.on('exit') handler, but frankly it's not very elegant.

**Comment by gireeshpunathil** [comment]
sorry, but I am trying to understand:

```
app -> lib1 -> lib2 -> lib3 -> ...
app <- lib1 <- lib2 <- lib3 <- ...
```
assuming this above consumption / invocation sequence, and assuming each of these entities are developed by different vendors independant of each other, and assuming that in the current model if the app registers an exit call back which is later superceded by a library in the sequence then this can happen.

But if the libraries are properly modularized having well-defined life-cyles, why would they register exit hooks? library code may not assume that they run until the end of the app right? Am I missing something?

**Comment by the1mills** [comment]
Let's talk about the simpler use case first. 1 library, 1 codebase. This is a command line app that is functional, no state, no db.

I register uncaughtException handlers in several places in the program. If the recency thing were true, the most recently registered uncaughtException handler would be invoked and that would be convenient, because I could tailor error messages. 

However, it is oldest uncaughtException handler that gets invoked first and that is inconvenient. It would be nice to be able to control (unshift or push) where a listener is placed in  observers list. Right now it's always a push, but us Node.js users should be able to decide where to push or unshift.

Which leads me to think I could manually unshift to the list.

process.listeners.unshift() or whatever.

**Comment by gireeshpunathil** [comment]
> I register uncaughtException handlers in several places in the program

But, why? By placing this at several places in the program implies an intention to catch the fault at program control points other than the entry point routine and subsequently to resume the app in some manner?

[doc](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_warning_using_uncaughtexception_correctly) is clear in terms of when and how to use this handler - as a last resort attempt to cleanup vital resources and shutdown, not to salvage the application. This implies only one such handler is needed.

**Comment by ORESoftware** [comment]
When your program has multiple entry points, that is easier said than done :)

**Comment by ORESoftware** [comment]
I was looking at the source-

https://github.com/nodejs/node/blob/master/lib/events.js

it looks like you can call Events.prototype.prependListener

and that can probably do what I want to do.
