### ISSUE TITLE
404  Not Found, nodejs_6.11.1-1nodesource1~xenial1_amd64.deb 

### ISSUE THREAD

**Issue by spencerthayer** [nodejs/help#729]
Err:1 https://deb.nodesource.com/node_6.x xenial/main amd64 nodejs amd64 6.11.1-1nodesource1~xenial1 404  Not Found
E: Failed to fetch https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.11.1-1nodesource1~xenial1_amd64.deb  404  Not Found

**Comment by gibfahn** [comment]
What command did you run? Was it `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -` from https://nodejs.org/en/download/package-manager/ ?

It looks like a network issue, have you tried it since?

If you get this repeatedly, you should raise an issue in https://github.com/nodesource/distributions (where those packages are maintained) with the command you ran and the full output.

**Comment by spencerthayer** [comment]
It's just an issue of a missing DEB file. Click the https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_6.11.1-1nodesource1~xenial1_amd64.deb and you'll see it's not there. Thanks for the tip. I informed distributions thanks.
