### ISSUE TITLE
How to generate RSA SHA256 signature by Javascript

### ISSUE THREAD

**Issue by nsvt100** [nodejs/help#730]
Hi,

I want to generate RSA SHA256 token based on jwt.io by javascript. Is there any source code or anything or available. 

Regards

**Comment by tniessen** [comment]
There is a library ([jsonwebtoken](https://npmjs.org/package/jsonwebtoken)) for JWT which internally uses the [jwa](https://npmjs.org/package/jwa) package. You can find relevant code in https://github.com/brianloveswords/node-jwa/blob/master/index.js.

**Comment by bt10** [comment]
I tried a lot but didn't get success to generate JWT Signature. I am not aware about more on NodeJS and what application i am using that will accept only nodeJS/Javascript code. So still i am struggling. Actually i am looking 1 single file to achieve my requirement. I tried by what you referring but there a lot to call 'REQUIRE' function due to i am unaware of NodeJS so that i am unable to get. I need 1 single source code.

**Comment by tniessen** [comment]
@bt10 We are here to help you understand node and to assist you if you have specific questions. If you need someone to write code for you, you might want to hire a software developer ("programmer").

**Comment by nsvt100** [comment]
@tniessen talk in manner, if you dont know anything first go and join school and dont wirte such nonsense things. Again if you are your any so called friend will reply then i will assume you are ...............

**Comment by bnoordhuis** [comment]
@nsvt100 What the heck is wrong with you?  You get a helpful answer from @tniessen and this is how you thank him?

**Comment by nsvt100** [comment]
my problem is still going on with RS256 Javascript/NodeJS JWT Signature, And i am doing and @tniessen  suggestion is not required

**Comment by bnoordhuis** [comment]
Suit yourself.  Closing.
