### ISSUE TITLE
NPM warning...

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#749]
Hi all, when I see this : "npm WARN crawler@1.0.2 No license field.|" can that cause problems for my program?

**Comment by bnoordhuis** [comment]
No.  It's MIT-licensed per https://www.npmjs.com/package/crawler but its package.json probably doesn't announce that fact.

**Comment by tniessen** [comment]
Which npm version are you using? crawler@1.0.2 [uses the `licenses` property](https://github.com/bda-research/node-crawler/blob/497b98225d0e608870619aae077fa3741c0b0e11/package.json#L48) instead of `license` which is now deprecated, see [here](https://docs.npmjs.com/files/package.json).

npm just warns you that a package you are using is missing metadata.

**Comment by WAINGOR** [comment]
Allright thanks you guys! @ tniessen I just installed the newest version
