### ISSUE TITLE
Contact with Latinamerica

### ISSUE THREAD

**Issue by ChrisADR** [nodejs/help#762]
Hi,

My name is Christopher Díaz Riveros, I'm a software development student
in Lima, Peru. For some time now I have been supporting my Linux
community, Gentoo Linux, and I have discovered a wide world of
possibilities in open source.

I tell you this because it has been so much benefit in my training as a
a developer that I am determined to start a new community in my country
to be able to make technology-related career students find an open
source community in which they can learn to work and get the same
positive effect that I have had on mine. I have already been talking to
some teachers, I am about to begin my final year of studies in the institute, and they agree to start the community with students of the
institution.

As one of the main problems when getting involved with a community here
is the barrier of english language, and few are able to have fluent
conversations in that language, as it is a bit intimidating for most to
approach an open source community. My community hopes to get in touch
with different open source projects throughout the world and seeks to
be a midpoint to interact with young developers and communities.

Having said all this I have only to offer to your community, the
availability of our community (we still do not have a definite name)
and see if anyone is interested in supporting this group of developers
here and with a bit of luck be able to turn it into a movement of all
Latin America.

Thanks and any kind of feedback is welcome :)
Christopher Diaz Riveros

**Comment by lordKnighton** [comment]
[Google-translate]

Admiro que eres pasión, porque parece que tu comunidad está empezando a establecerse. Una vez que su grupo se establece entonces creo que esto sería un coversation que se tenía. Pero su enfoque es un poco oscuro. No sé exactamente lo que quieres. ¿Desea que su grupo contribuya a la comunidad de Nodejs u otras tecnologías? Estoy diciendo que una vez que sepa exactamente lo que usted o su grupo quiere, entonces es más fácil para mí ayudarle. Odio ser desalentador. Pero lo que voy a decirte es Nodejs está feliz de tener nuevos recién llegados aquí una contribución. Así que sólo hacer algunas investigaciones y volver y háganoslo saber.


-------

I admire you're passion, because it sounds like your community is just starting to get established. Once your group is established then i think this would be a coversation to be had. But your approach is a little obscure. I don't know exactly what you want. Do you want your group to contribute to Nodejs community or other technologies. I'm saying once you know exactly what you or your group wants, then it's easier for me to help you. I hate to be discouraging. But what i will tell you is Nodejs is happy to have new comers come here an contribute. So just do some researching & come back and let us know.

**Comment by ChrisADR** [comment]
Hi @lordKnighton,

Thank you very much for your comments and please let me tell you a bit more about what I'm doing with the community.

First of all, now we have our website running

www.codelabora.com (I'm gonna have the English version in a couple of days)

I have three specific goals to achieve:

1. Fill the gap between our concept of technology (Latin America) and the rest of the world: We need to face the fact that technology in Latin America (at least in Perú) is very outdated compared to other countries from the world. That's the most important goal, to give students like me the opportunity to get involved with cutting edge technologies, something that they could not see by themselves here. In order to achieve this goal, we need to make the other two things from the list.

2. fill the programming gap from programming languages here and the open source projects. We need to teach our members the necessary concepts so that they could, first of all, understand how to code and how to read the code. I'm getting in touch with foundations like Python, PHP, js ( the answer is pending) and many others, so far the Python foundation is the only one that wants to help with workshops to teach the new members how to code in python.

3. Teach our members the workflow from open source projects, especially the tools that they use. That's why we are preparing a Spanish version from git, to make it easier for our future members to understand the tool and be able to use it.

The outcome from this 3 points is that the members could contribute to real projects, learn how they work, and how they code. With this skills, they could start to tinker their own projects on the same time that they contribute to their communities. Besides the benefits for the members, our countries could have more opportunities with new technologies.

CodeLabora is some sort of mid-point between open source and free software projects from all over the world and Latin America. So far I have contacted some other open source projects like LibreOffice, Drupal, KDE, MetaBrainz, Python, and we hope to help all of them while our members develop new skills as developers.  NodeJs  and Js are a must if we think in cutting edge open source projects.

And last but not least, why am I telling you all of these things if we don't have more than 10 members? The answer is quite simple, in order to be able to go to other universities and invite students, I need proofs that CodeLabora is actually helping real world projects, that's why I'm contacting so many projects and people. That's why I'm doing this at this very early stage of the community.

I hope that this is a bit less obscure now, but if something still unsolved, please let me know and I'll be more than happy to clarify it .

Regards,
