### ISSUE TITLE
crawler settings...

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#769]
Hi all,

I have made a crawler using the node crawler module that I intend to let keep track of about 10 specific pages on 1 website, during the whole day. I would like to let it make one request every minute per page. What would be good settings (maxConnections/requests per second) so my IP address wont get blocked by this specific website?

Greets

**Comment by tniessen** [comment]
I don't see how this question is specific to node?

**Comment by WAINGOR** [comment]
Well, it concerns the use of a node module, and I have tried posting at the issues of this specific module to no avail...

**Comment by tniessen** [comment]
> I have tried posting at the issues of this specific module to no avail...

For posterity: https://github.com/bda-research/node-crawler/issues/227.

> What would be good settings (maxConnections/requests per second) so my IP address wont get blocked by this specific website?

We cannot answer this question properly, and the maintainers of the `crawler` package most certainly won't be able to help you with that either. Depending on the website you are trying to crawl, there can be a wide range of protective measures, beginning with no protection at all up to intelligent request pattern recognition (which you won't be able to avoid with those two parameters).

If you want a definite answer, ask the webmaster of the website you are crawling. They might actually help you, assuming what you are doing is legal and does not violate their terms and conditions.
Apart from that, make sure that you don't put an unjustifiable load onto their servers as this might be considered a DoS. General rule of thumb: The less requests per second you make and the less bandwidth you use, the smaller is the probability of seeing countermeasures. Just try to stay close to "normal traffic" as if someone was viewing the page in a browser.

I am sorry, but this is completely off-topic. You could as well ask the same question in a Linux / Windows forum just because you are running your crawler on one of those operating systems. If anyone else feels like they can provide input to this, feel free to comment.

**Comment by WAINGOR** [comment]
Allright I am quite new to Github so will keep your words in mind :)
