### ISSUE TITLE
What modules/structure to use...

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#775]
Hi all, I have a fairly simple question. If I want to use Node JS for making a webpage that:

- contains HTML and CSS
- lets users input values which will manipulate the structure of a .JSON file 

now I know HTML and CSS fluently so writing good markup for this page won't be an issue. Does anybody know what the simplest way is to get Node working on HTML? I looked into express but it seems way to overqualified for the simple tasks at hand..

Greets

**Comment by tniessen** [comment]
You can serve static files with express, like this:

```js
const express = require('express');
const app = express();
app.use(express.static(__dirname + '/my_public_files'));
app.listen(80);
```

This should spin up a webserver, serving files from the directory `./my_public_files` (relative to the script) on port 80 (which will usually require root, go for ports above 1024 if you don't have / want to use root access).

For server logic, you can easily add some routes, e.g. like this:

```js
// Handle all post requests to this path, e.g. to handle form submission
app.post('/update_the_file', (req, res) => {
  // Parse the request message body, update the file etc
  res.end('All done!');
});
```

I usually keep my node applications behind an Apache webserver and configure Apache to redirect requests to my node application. This way I don't need to worry about permissions, SSL certificates, interface configuration etc within node.

I really like [pug](https://github.com/pugjs/pug) (formerly known as jade), and it is pretty simple to setup with [express](https://pugjs.org/api/express.html), you will find plenty of information online.

Another personal preference: I tend to use TypeScript both for server and client code, but that's just because I like strict type systems. Luckily, support for TypeScript has grown within the Node.js community, but there are still lots of modules which don't provide proper types.

**Comment by WAINGOR** [comment]
Hi tniessen, thanks for helping me with all this great advice. I have a few more question that I hope you can help me with...

In this context what does static mean? I only know the meaning of it when comparing 
- html that cant be adjusted/updates by users 
- html that **can** be manipulated by users through PHP

Also, is it safe to say that when I have node installed on my mac terminal that it is equal in functionality to a server that has Node installed on it? Meaning that there are no limitations or quirks to it? I ask this because I want to know if I can test the setup you mentioned on my mac only. 

And when serving these static files, I presume it will generate a HTML and CSS page, thats great! The only thing I still dont know is how to go from there... I mean, I can't just mix up HTML with Node JS code right?  Suppose I wanted to update/manipulate a .JSON file with user-generated content (I oversimplified my markup here, and used JQuery notation, pls dont take offense ^^ ) :

<button> </button>
<input> </input>

<script type = "text/javascript> 
var X = $("input).html();
if($(button).click) {
fs.writeFileSync('testwrite.json', JSON.stringify({contentUser: X}));
}
</script

I take it that this would not work? That is, presuming that one cannot just presume that any regular (none-node) javascript would be interpreted differently by the fact that Node is installed... 
Or would it? And if not, what is the missing step to get html-input transferred to my .JSON file?

**Comment by tniessen** [comment]
> In this context what does static mean? I only know the meaning of it when comparing

Static means that the files will not be modifed by the application when being served, so the client receives the file exactly as it is stored in that folder. PHP files are *not* static as their content is generated dynamically. For dynamic behavior with express, you will need to define custom routes.

> Also, is it safe to say that when I have node installed on my mac terminal that it is equal in functionality to a server that has Node installed on it? Meaning that there are no limitations or quirks to it?

Apart from hardware and OS limitations (you usually don't use macintosh for server setups), you can do the same stuff. Node.js provides the same functionality on both setups. For small private setups, you don't need any fancy firewalls, Apache etc.

> And when serving these static files, I presume it will generate a HTML and CSS page, thats great!

The server won't generate anything, it will just serve the HTML and CSS files as they are, and it is up to the client (usually a browser) to interpret those files.

> I mean, I can't just mix up HTML with Node JS code right?

Not really, no. Node.js code runs on the server and cannot be included in scripts served to the client. You can, however, use Node.js to generate dynamic pages, that's why I linked to pug in my previous message. The simplest approach is to use an HTML `<form>` which makes a `POST` request to a custom route of your application, the server can then [parse the request body](https://github.com/expressjs/body-parser), update the file (do not use `*Sync` functions in webservers, always use the asynchronous variants) and send a response to the client. (I like to send a redirect instead of a 200 response after receiving a `POST` request, though I won't go into detail here.)

**Comment by lordKnighton** [comment]
@WAINGOR Do you still need help?

**Comment by WAINGOR** [comment]
@lordKnighton @tniessen  I have received terrific help, so no my question is answered. Many thanks
