### ISSUE TITLE
how to run last release of web service that developed by express js  in ubuntu server

### ISSUE THREAD

**Issue by iarash84** [nodejs/help#781]
Hi guys 
I know that is dummy question, but i am newbie in Node.js and Express.js.
I developed a web service with Express.js and its work fine, now i want to immigrate to my ubuntu server.
that is enough to run 'node app.js' or i must doing somthing more ??

thanks for your answer
 best regards

**Comment by iarash84** [comment]
Should i use any web server like Apache , ... or nodejs is OK for release my app ??

**Comment by tniessen** [comment]
That depends on your server setup.

You can just run your app using `node app.js` but you should probably use tools such as `nohup` to ensure the process will keep running even if you log out of the system. There are some nice npm packages, e.g. `forever`, which will automatically take care of that, restart your app if it crashes etc.

If you are not using any other webserver software (e.g. Apache), you can listen on port 80 from within your node application. Note that you will need root permissions to listen on that port, which is one of the reasons I would not do that.

Personally, I use node applications next to an existing web server (Apache) on the same port. You will need to configure Apache to redirect requests to your application, e.g. using the `ProxyPass` directive. Assuming Apache listens on port 80, you should pick a port > 1024 for your own application and configure Apache to redirect requests to that port. This way, your application does not need root permissions. I usually use one subdomain per application which makes it really simple (the application becomes a virtual host within the Apache config). If you choose this approach, you might want to configure your firewall to disallow incoming traffic to the selected port in order to prevent abuse.

**Comment by iarash84** [comment]
Hi Tniessen
Thanks a lot
I got my answer completely

best regards
