### ISSUE TITLE
NodeJS String Encoding setting throughout application

### ISSUE THREAD

**Issue by xdvarpunen** [nodejs/help#790]
So far NodeJS application settings can be set through:
* CLI
  - https://nodejs.org/api/cli.html (CLI flags)
  - https://github.com/thlorenz/v8-flags/blob/master/flags-0.11.md (V8 unofficial flags)
* process.env.GLOBALS_HERE variables to define settings

Right now encoding to string needs to be set separately to `http`, `net`, `fs`, `buffer`, `stream` -modules through `setEncoding`-method or equivalent. Is there a way implemented into NodeJS to ensure each module uses the same encoding?

In Java/JVM equivalent would be through JVM environment variable.
> source: https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding

**Comment by addaleax** [comment]
That sounds like it could have really surprising side-effects, because it would change the default encoding for *any* of the Node code you are running.

Can you maybe give more information on your use case?

**Comment by jasnell** [comment]
Yeah, this would be super dangerous for a number of reasons. I definitely get why this would be an attractive idea, I just don't see it being feasible without breaking a *lot* of stuff.

**Comment by xdvarpunen** [comment]
@jasnell Could you elaborate why it would be dangerous please? 

@addaleax Playing with defaults is risky due to possible patch changes. In order to keep database content right (password etc.), ensuring in all parts of NodeJS having same encoding would save the time and work. The string encoding in database management, files and controllers would be ensured to be one type of encoding through global variable. It would make more sense knowing what is default throughout application and change when needed => makes managing application less workful (:

**Comment by addaleax** [comment]
@xdvarpunen If your code *relies* on using a specific encoding, I would *always* make that explicit (whether that encoding is UTF-8 or not). Making it more implicit and managing it globally is prone to creating pitfalls.

I have definitely have debugged situations in which a deep dependency made assumptions about encodings that changed over time, which then came with real security concerns.

**Comment by xdvarpunen** [comment]
@addaleax You are right, centralized encoding makes code less readable due to more to "things to keep in mind" and can hence make debugging harder. 

Am I still on track?
* NodeJS has no centralized way to set encoding throughout application
* Setting encoding explicitely ensures readability and smoothens debugging

What's NodeJS string default charset? What commands there are to check charset of string? I found this module: https://www.npmjs.com/package/detect-character-encoding to check the encoding, but there is probably built in one too?

**Comment by addaleax** [comment]
> NodeJS has no centralized way to set encoding throughout application

Yup :)

> What's NodeJS string default charset?

By now, the default is UTF-8 everywhere, which I also think is the most reasonable choice in 2017.

> What commands there are to check charset of string?

No, there’s no builtin one, partly because there is no way to detect a character encoding with certainty. What encodings you use is part of your application’s API, so ideally you know that in advance (and/or specify it). Also, the module you are linking here supports a lot *more* encodings than are built into Node core.

**Comment by xdvarpunen** [comment]
@addaleax It sounds like there is predefined common workflow with datamanagemetn with different encodings. Lets verify with two use cases.

Use case 1. "Take data from file, append, safe to database":
1. Read file
1.1 check file encoding
1.2 read file with encoding set
2. manage data in utf-8
2.1 append data
3. Save to database
3.1 check database encoding
3.2 save data with encoding set

Use case 2. "receive login username and password, verify, log into database":
1. receive login username and password
1.1 check page encoding
1.2 read login username and password with encoding set
2. verify login username and password
2.1 verify in utf-8
2.2 save datetime
3. log into database
3.1 check database encoding
3.2 save data with encoding set

In the nutshell in each point of the application:
1. check file/database/target/server where data will be sent/saved/received
2. set encoding and send/save/receive

Did I get it right?

**Comment by jasnell** [comment]
> What commands there are to check charset of string?

We should qualify this... In JavaScript, strings are *always* sequences of UTF-16 code points. For many operations internal to Node.js, we convert these to UTF-8 sequences by default. Where the encoding comes in to play is with things like `Buffer`, which are opaque sequences of bytes that may or may not represent text content. By default, when we interpret a `Buffer` as text, we *assume by default* that it is UTF-8, which as @addaleax says, is the most reasonable choice in 2017.

Every time that we change a default, or provide an option to change a default globally, there is the potential for breaking code because we are providing a way of undermining default assumptions that were in effect when existing code was written.

One example of this is when we change the default encoding crypto operations a while back from `binary` to `utf8`. The result is that hashes generated by certain crypto functions silently changed and code started breaking all over the place.

**Comment by xdvarpunen** [comment]
@jasnell Thanks, crypto example made it clear to keep encoding explicit.

So in the nutshell NodeJS handles strings internally and externally as UTF-8?

**Comment by addaleax** [comment]
> So in the nutshell NodeJS handles strings internally and externally as UTF-8?

It’s the default when converting the strings into buffers/anything that operates on lists of bytes rather than lists of characters.

There’s no way of telling how a string is handled “internally”. The JS engine can decide whether to represent a string as UTF-16 or UTF-8 or Latin-1 on its own, and there’s no way to tell which representation a string actually has. *But* that also shouldn’t matter, because it doesn’t make really sense to associate strings with a character encoding – it’s the Buffers corresponding to it that have the encoding. (For example, `abc` is a string – you can’t tell what kind of encoding your browser uses when it displays it to you – but `<Buffer 61 00 62 00 63 00>` would be an UTF-16-encoded and `<Buffer 61 62 63>` would be an UTF-8-encoded representation of it).

**Comment by xdvarpunen** [comment]
@addaleax Thanks for clarification (: I think I got it now. 

* Strings are treated as UTF-8 by default when strings are _converted_  into anything that operates on lists of bytes
* JS engine decides itself with what charset it represents the string
* NodeJS has no centralized way to set encoding throughout application
* Setting encoding explicitely ensures readability and smoothens debugging
* When working with incoming/outcoming data:
  1. Check file/database/target/server where data will be sent/saved/received
  2. Set encoding and send/save/receive

What do you think @addaleax @jasnell?

**Comment by addaleax** [comment]
Yup, all of that sounds accurate!
