### ISSUE TITLE
vm.runInNewContext() and node => Why do they share the same global "unhandledRejection" handler?

### ISSUE THREAD

**Issue by jdat82** [nodejs/help#942]
* **Node.js Version**: 8.4.0
* **OS**: macOS Sierra
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: vm

I'm currently using `vm.runInNewContext()` to execute code provided by the end-user.
My server has since the beginning a global `unhandledRejection` handler that shut down the server properly when invoked.

```js
process.on('unhandledRejection', function(err) {
    console.error('Unhandled rejected promise:', err);
    app.shutdown(2);
});
```

I'm doing that to be ready the day node effectively kill the process in case of unhandledRejection. That's what I understand from the warning logged by node in the console today.

Issues arise when executing code in a vm. According to my tests, the host and the vm share the same `unhandledRejection` handler. I don't understand why the vm which has its own V8 context share the same global error handlers.

It creates very big complications and don't allow proper isolation between contexts. For instance, if I create several contexts (vm), how do I make a difference between an asynchronous error from one context to another?

Plus with that constraint, you can't even return a rejected promise from your vm without invoking global error handlers like unhandledRejection. You are forced to catch the errror in the vm and either deal with it inside or pass the error instance via resolve.

```js
// Wrap user code to enable the await keyword out of the box.
async function wrapper() { 
    ${this.task.scenario}
}
wrapper();
```

In my case, if i don't destroy my global handler, it makes vm completely useless. 

Did I miss something? Any idea?

**Comment by bnoordhuis** [comment]
The short answer right now is "you can't," for two reasons:

1. `process.on('unhandledRejection', ...)` is a Node.js feature, it's not standard JavaScript.  Since you can only have one Node.js context (`vm.createContext()` creates standard JavaScript contexts), you can effectively have only one unhandledRejection handler.

2. The microtask queue (the promises pseudo-event loop) is a per-isolate property in V8, not per-context.  https://github.com/nodejs/node/issues/3020 is another example of where that is problematic, see the discussion in that issue.

**Comment by jdat82** [comment]
Thank you, glad to know. The other thread is really helpful (to better understand at least).
