### ISSUE TITLE
How to organize NodeJS Code + Learn workshop?

### ISSUE THREAD

**Issue by trivikr** [nodejs/help#959]
Hi,

I started contributing to node code last month, and it's a great experience ([PRs](https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Atrivikr+is%3Aclosed))

I noticed that NodeJS team organizes [Code + Learn workshops](https://nodejs.org/en/get-involved/code-and-learn/) which are pretty successful. For example, there were [250+](https://twitter.com/jasnell/status/916405968711303168) pull requests submitted during Code+Learn during NodeInteractive 2017

I have a team of 10+ developers who would like to contribute to node core, and to make it easy I've to organize a workshop for them.
Where can I learn how to organize NodeJS Code + Learn workshop so that it's easy for them to get up to speed and post their first PRs in node core?

Thanks,
Trivikram

**Comment by apapirovski** [comment]
Not sure re: organizing but I think in general a good idea is to find very simple tasks as opposed to writing full tests or similar. It's very likely participants won't be knowledgeable about Node's internals and also won't have enough to familiarize themselves enough during the duration of such a workshop.

I've previously mentioned a potential task: replacing `assert.throws(fn, common.expectsError(err));` with `common.expectsError(fn, err);`. There's an eslint rule I've created that can be used to find all the instances so that you can have a list of issues ready to go:

https://gist.github.com/apapirovski/b8d0803e6bd9938d29c207d50717eef3

**Comment by trivikr** [comment]
Thanks @apapirovski 
If nothing becomes available, we'll distribute tests among ourselves to replace `assert.throws(fn, common.expectsError(err));` with `common.expectsError(fn, err);`
Looking at the format, it shouldn't be difficult to write a script to do the replacement. I'll give it a try over the weekend.

**Comment by gireeshpunathil** [comment]
closing as answered / addressed. please re-open if it is still outstanding.
